### ISSUE TITLE
Refactor: Behaviour of `Partial` for objects with nullable types

### ISSUE THREAD

**Issue by peterschutt** [litestar-org/litestar#1179]
### Discussed in https://github.com/orgs/starlite-api/discussions/613

<div type='discussions-op-text'>

<sup>Originally posted by **peterschutt** October 18, 2022</sup>
`TypedDict` and `dataclass` have a slight difference in behavior when used with `Partial`. Omitted properties are excluded for `TypedDict`, while for `dataclass` they are set to `None`.

```python
"""Minimal Starlite application."""
from dataclasses import dataclass
from typing import TypedDict

from starlite import Starlite, post, Partial


@dataclass
class DC:
    a: str
    b: int
    c: float | None


class TD(TypedDict):
    a: str
    b: int
    c: float | None


@post("/dataclass")
def hello_dataclass(data: Partial[DC]) -> Partial[DC]:
    return data


@post("/typeddict")
def hello_typeddict(data: Partial[TD]) -> Partial[TD]:
    """Route Handler that outputs hello world."""
    return data
```

| endpoint | payload | response |
|---|---|---|
| /dataclass | `{}` | `{"a":null,"b":null,"c":null}` |
| /dataclass | `{"c": null}` | `{"a":null,"b":null,"c":null}` |
| /typeddict | `{}` | `{}` |
| /typeddict | `{"c": null}` | `{"c": null}` |

The `TypedDict` behavior is advantageous as can discern when a nullable property has been explicitly set to null or not. However, a dataclass instance cannot be constructed without values for all attributes, so maybe some sort of sentinel default value is necessary for that case.</div>

**Comment by peterschutt** [comment]
There is another side to the issue as well. As we make all the types `Optional` to get around the requirement for validation, but really we just need a requirement for optional presence in the payload. For example, the payload `{"a": null}` should be invalid for both the dataclass and typeddict endpoints in the example above, yet is accepted.

This is what I think we need for a proper `Partial` implementation:

1. A way to discern inside a handler if an objects value has been set by the request, or not.
2. Validation of data properties to be uninfluenced by the typing union with the sentinel value.
3. The default sentinel value would need to be ignored by openapi docs.

I think this can be solved by using a sentinel that is not a valid json type. It would be breaking, but I'm not sure how useful the current implementation is with these limitations anyway.

_Originally posted by @peterschutt in https://github.com/starlite-api/starlite/discussions/613#discussioncomment-3901269_

**Comment by peterschutt** [comment]
This needs to be looked at after DTO design is finalised in #1160

**Comment by bmle69** [comment]
Just found this framework about a week ago and came across this specific issue and realized the Partial class doesn't seem to do what I expect. 

If my model has nullable properties, any omitted property in the payload using the partial class results in those fields being set to null and potentially causing nulls to override valid properties.

**Comment by peterschutt** [comment]
Yes exactly @bmle69 - I think we can do something on top of the DTO refactoring that is going on in #1295 - along the lines of making every type a union of it's explicit type and `Empty` if config has `partial=True`.
