### ISSUE TITLE
Enhancement: nested exclude

### ISSUE THREAD

**Issue by peterschutt** [litestar-org/litestar#1197]
When defining mappings, new fields, and fields to omit from DTO models, it might be desirable to be able to use dot-notion to define behavior of nested models, for example `exclude={"a.b"}` would exclude field `"b"` from the nested model `"a"`.

**Comment by Goldziher** [comment]
you mean add this as an explicit kwarg?

**Comment by peterschutt** [comment]
Ah yeh, this is in context of the DTO branch, where I've pushed `exclude`, `field_mapping` etc into this method.

**Comment by Goldziher** [comment]
Sure, then update the protocols there @peterschutt ?

**Comment by peterschutt** [comment]
Yes, the protocol is updated in that branch.
