### ISSUE TITLE
Enhancement: Redis SSL & Sentinel integration

### ISSUE THREAD

**Issue by cofin** [litestar-org/litestar#1248]
**What's the feature you'd like to ask for.**
Extend the `RedisCacheBackend` to allow for SSL & Sentinel based Redis connections

<a href="https://polar.sh/litestar-org/litestar/issues/1248">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1248/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1248/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
> SSL should already be possible (you can simply pass in a `Redis` instance or pass an appropriate URL to `with_client`. Supporting sentinel clients should only be a matter of typing as far as I can tell.

Scratch that last part, I was thinking about something else.

@cofin I'm not sure if explicit support for Sentinel clients is actually needed, as we wouldn't want to do the setup within the storage backend anyway, and you would just pass a slave client to the storage, something like this:

```python
from redis.asyncio.sentinel import Sentinel
from starlite.storage.redis import RedisStorage

sentinel = Sentinel([('localhost', 26379)], socket_timeout=0.1)

storage = RedisStorage(redis=sentinel.slave_for('mymaster', socket_timeout=0.1))
```

**Comment by Goldziher** [comment]
@cofin can you take this one on?
