### ISSUE TITLE
CI: setup test environment for sqlalchemy 1.x code

### ISSUE THREAD

**Issue by peterschutt** [litestar-org/litestar#1253]
We've moved sqlalchemy 1.x code into a separate contrib from the new sqlalchemy stuff which will all be 2.x.

Our main test suite will run with 2.x installed, so we'll need a separate environment to exercise the 1.x stuff.

We should use `coverage combine` to roll the coverage reports for the two environments into 1 before sending off to sonar.

As an aside, we should consider also running coverage reporting on any version of python that has version specific runtime, e.g., if we have any `if PY_38: ...` blocks, then we should run coverage on py 3.8, and combine that report too.

**Comment by Goldziher** [comment]
I don't think we should go for 3.8 and combine it. It's basically identical to 3.11 except two skips due to pydantic and dataclasses issues.

**Comment by peterschutt** [comment]
we dropped sqla v1 support
