### ISSUE TITLE
Documentation: Missing Async version of code in SQLAlchemy Plugin

### ISSUE THREAD

**Issue by v3ss0n** [litestar-org/litestar#1259]
https://starliteproject.dev/lib/usage/plugins/sqlalchemy.html Is missing async version of code except Basic ones.

**Comment by peterschutt** [comment]
Pretty sure this is OK now in 2.0 docs: https://docs.litestar.dev/2/usage/contrib/sqlalchemy/plugins/index.html

Feel free to reopen if you feel otherwise @v3ss0n

**Comment by v3ss0n** [comment]
ALl good now , thanks a lot.
