### ISSUE TITLE
Enhancement: Validate annotations for reserved keyword handler arguments

### ISSUE THREAD

**Issue by provinzkraut** [litestar-org/litestar#1265]
**What's the feature you'd like to ask for.**
Reserved handler arguments like `state`, `body`, `cookies`, etc. should have their type annotation validated, such that a e.g. `state` could only be annotated with a subclass of `State` / `ImmutableState`.

This is a follow up to #1264.

<a href="https://polar.sh/litestar-org/litestar/issues/1265">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1265/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1265/pledge.svg">
</picture>
</a>

**Comment by JacobCoffee** [comment]
I am beginning work on this tonight.
