### ISSUE TITLE
Tests:  Investigate Xfail suspected fsspec windows issue

### ISSUE THREAD

**Issue by peterschutt** [litestar-org/litestar#1270]
Related to #1268 

We need to investigate why these tests do not pass in windows CI.

https://github.com/starlite-api/starlite/blob/06c50d7a85128e3a59bb13f6edb6da234219b624/tests/test_file_system.py#L52-L73

<a href="https://polar.sh/litestar-org/litestar/issues/1270">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1270/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1270/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
Why has this been closed?

**Comment by Goldziher** [comment]
> Why has this been closed?

It's stale. Issues are not meant to accrue, they are either handled or not.
