### ISSUE TITLE
Enhancement: Content negotiation and Accept header

### ISSUE THREAD

**Issue by NomAnor** [litestar-org/litestar#1299]
It would be nice to implement some kind of content negotiation based on the `Accept` header. 

I have an endpoint that should serve a graph in different formats. Depending on the requested mime type it can respond with an image, a PDF or the raw graph as a graphviz file. Currently I crudly parse the `Accept` header myself:

```python
def parse_accept(accept: str) -> List[str]:
    """
    Parse an Accept header string an return the list of accepted mime types.
    """
    mime_types = []
    for entry in accept.split(','):
        entry = entry.strip()
        type, _, extra = entry.partition(';')
        mime_types.append(type)
    return mime_types

def mime_type_matches(mime_type: str, pattern: str) -> bool:
    if pattern == '*/*':
        return True

    type, _, subtype = mime_type.partition('/')
    pattern_type, _, pattern_subtype = pattern.partition('/')

    return type == pattern_type and (subtype == pattern_subtype or pattern_subtype == '*')

def first_matching_mime_type(accept: str, available: List[str], default: Optional[str] = None) -> Optional[str]:
    accept_patterns = parse_accept(accept)
    for pattern in accept_patterns:
        for type in available:
            if mime_type_matches(type, pattern):
                return type
    return default

@get("/graph")
    async def graph(self, accept: str = Parameter(header="Accept")) -> Response[bytes]:
         mime_type = first_matching_mime_type(accept, ['image/png', 'application/pdf', 'text/vnd.graphviz'], default='image/png')
         with io.BytesIO() as f:
            if mime_type == 'image/png':
                render_graph_image(f)
            elif mime_type == 'application/pdf':
                render_graph_pdf(f)
            elif mime_type == 'application/pdf':
                raw_graph(f)
            return Response(content=f.getvalue(), media_type=mime_type)
```
I'm not sure what the best interface would be. Maybe just a special dependency that provides you with the requested type based on a list of available type. An integration into OpenAPI would also be nice, but I don't know if that is even possible.

The hard part is probably correctly parsing and matching the mime types, thats why i made this request. I haven't looked in the specs.

Django REST Framework has something [similar](https://www.django-rest-framework.org/api-guide/content-negotiation). But the render concept doesn't fit into starlite.

**Comment by Goldziher** [comment]
Hi,

So this could be a nice ready made dependency packages with Starlite. I don't see how we could implement the content negotiation - this is for the user to do. But we could parse the header and offer a ready made dependency.

Note- there is already a utility to parse content disposition / content type headers in place. 

Thoughts?

**Comment by NomAnor** [comment]
This is what I got now. I looked at [Quality Values](https://developer.mozilla.org/en-US/docs/Glossary/Quality_values) and [Accept Header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept) to parse and sort the media types. This needs more testing as I'm not sure if the matching works like I intended it.

The idea is that you provide a list of media types (also with wildcards) your handler can provide. And you get a concrete type back that is the best match for the request. You can then inspect that type and create the appropiate response.

If none of your provided types match you get the default type back. It seems to be best practice to return something instead of giving an error [406 Not Acceptable](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/406). But that could be implemented when no default is given.

```python
#!/usr/bin/env python

from typing import List, Optional, Tuple

from starlite import Starlite, Response, Provide, get
from starlite.params import Parameter
from starlite.multipart import parse_content_header



class MediaType:
    def __init__(self, type_str: str):
        full_type, self.params = parse_content_header(type_str)
        self.maintype, _, self.subtype = full_type.partition('/')

    def __str__(self) -> str:
        params = ''.join(f';{key}={value}' for key, value in self.params.items())
        return self.fulltype + params

    @property
    def fulltype(self) -> str:
        return f'{self.maintype}/{self.subtype}'

    @property
    def priority(self) -> Tuple[int, int]:
        # Use fixed point values with two decimals to avoid problems
        # when comparing float values
        quality = 100
        if 'q' in self.params:
            try:
                quality = int(100*float(self.params['q']))
            except ValueError:
                pass

        if self.maintype == '*':
            specificity = 0
        elif self.subtype == '*':
            specificity = 1
        elif not self.params or ('q' in self.params and len(self.params.keys()) == 1):
            # no params or 'q' is the only one which we ignore
            specificity = 2
        else:
            specificity = 3

        return quality, specificity

    def match(self, other: 'MediaType') -> bool:
        # Check parameters first, ignore the weight parameter 'q'.
        # Additional parameters on other are ignored.
        for key, value in self.params.items():
            if key != 'q' and value != other.params.get(key):
                return False

        # Then check if the subtypes match, ignoring the wildcard '*'
        if self.subtype != '*' and other.subtype != '*' and self.subtype != other.subtype:
            return False

        # Lastly check the main type, also ignoring the wildcard '*'
        if self.maintype != '*' and other.maintype != '*' and self.maintype != other.maintype:
            return False

        return True


class ContentNegotiation():
    def __init__(self, provided_types: List[str], default: str):
        assert provided_types, "List of provided types can't be empty"
        self.provided_types = [ MediaType(t) for t in provided_types ]
        self.default = MediaType(default)

    def __call__(self, accept: str = Parameter(header="Accept", default='*/*')) -> MediaType:
        accepted_types = [ MediaType(t) for t in accept.split(',') ]
        accepted_types.sort(key=lambda t: t.priority, reverse=True)

        for accepted in accepted_types:
            for provided in self.provided_types:
                if provided.match(accepted):
                    # Return the accepted type with wildcards replaced
                    # by concrete parts from the provided type
                    if accepted.subtype == '*':
                        accepted.subtype = provided.subtype
                    if accepted.maintype == '*':
                        accepted.maintype = provided.maintype
                    return accepted
        return self.default


@get("/", dependencies={
    "requested_type": Provide(ContentNegotiation(['text/plain', 'text/*', 'application/xml'], default='text/plain'))
})
def test_handler(requested_type: MediaType) -> Response[bytes]:
    print(str(requested_type))

    if requested_type.maintype == 'text':
        if requested_type.subtype == 'plain':
            content = b'Test'
        elif requested_type.subtype == 'html':
            content = b'<html><body><h1>Test</h1></body></html>'
        else:
            content = b'Default text response'
    elif requested_type.fulltype == 'application/xml':
        content = b'<xml><msg>Test</msg></xml>'

    return Response(
        content=content,
        media_type=str(requested_type)
    )


app = Starlite(
    route_handlers=[test_handler]
)


```
You can use curl to test it:
``` 
curl -v -H "Accept: application/xml" http://127.0.0.1:8000/
```

Specifying the dependency is a bit verbose for my taste, but I totally understand the reason behind explicit dependencies. 
A dependency is nice if you need the same negotiation in multiple handlers. When you only need it once, or different provided types in different handlers something similar to the `Parameter()` dependency might be easier to use:
```python
def test_handler(
    requested_type: MediaType = ContentNegotiation(['text/plain', 'text/*', 'application/xml'], default='text/plain')
) -> Response[bytes]:
```

**Comment by Goldziher** [comment]
This looks pretty good 👍😊

If you'd like to submit a PR - we can have a new dependencies module with some helpers like this, or maybe place it in another place. 

A few thoughts-
1. We will need to extend the MediaType enum
2. We currently do not support XML out if the box, which we probably should - but should be done separately
3. PR should include documentation too 

I'd like to have input from other @starlite-api/maintainers , and also - you're welcome to join in our discord and chat. 

P.S. regard dependencies - perhaps we should add a `provide` decorator, which would be an alternative way to define dependencies. I will make an issue for this.

**Comment by Goldziher** [comment]
> I like the general idea, but I'm not sure if a dependency is the best way to go about this. 
> 
> I personally like flask's implementation of this, which is to expose an `accept_mimetypes` property on `Request`, returning a [parsed `MIMEAccept` header](https://werkzeug.palletsprojects.com/en/2.2.x/datastructures/#werkzeug.datastructures.MIMEAccept), exposing the needed properties and methods. It feels like the more natural place, since we already have e.g a `content_type` property there, and it would be easier to then extend functionalities like this to other headers.

Interesting. Can you give some code snippets for Illustration? 

@NomAnor would you like to contribute?

**Comment by provinzkraut** [comment]
> Interesting. Can you give some code snippets for Illustration?

Well it would enable something like this:

```python
def handler(request: Request) -> str:
  if request.accept_mimetypes.accept_html:
      return '<html><body><h1>Test</h1></body></html>'
  if request.accept_mimetypes.accept_text:
      return 'Default text response'
  if request.accept_mimetypes.accept_xml:
      return '<xml><msg>Test</msg></xml>'
```

we could also add a more general API:

```python
def handler(request: Request) -> str:
    if request.accept_mimetypes.matches("text/html"):
        return '<html><body><h1>Test</h1></body></html>'
    if request.accept_mimetypes.matches("text"):
        return 'Default text response'
    if request.accept_mimetypes.matches("application/xml"):
        return '<xml><msg>Test</msg></xml>'
```

I believe the main value in adding this to `Request` is that it would be easy to streamline with other "accepts" properties like `accept_language`, `accept_encondings`, etc., and other header-based properties, e.g. `if_match` or  `if_range`. I made an overview of some of those in #966 a while ago.

I really like the Flask / werkzeug API for this, you can check it out [here](https://flask.palletsprojects.com/en/2.2.x/api/#flask.Request.headers), and I believe something similar would be a great addition.

**Comment by NomAnor** [comment]
After thinking about it, I also think it is better to put this functionallity with the request object. Using a dependency felt too convoluted for a local thing like this. Dependencies work better for (external) resources that are provided to the handler, than as a means to provide or transform data already present, like the headers in the request.

A quick glance at the [Accept API](https://werkzeug.palletsprojects.com/en/2.2.x/datastructures/#werkzeug.datastructures.Accept) and I also like it.

Some points I see are:
* You have access to the parsed and sorted Accept header values through a list interface (`accepted_types` in my code, `Accept`object in Werkzeug), this way you can implement your own logic
* Given a list of types the handler can provide, you get a best pick for the request. That's what my dependency class does. `best_match()` in Werkzeug.
* Some convenience properties, like `accept_html`. I'm not sure about these, see below.

Should the API expose plain datatypes (tuples, str) like Werkzeug or is it better to expose full types/dataclasses/namedtuple (MediaType, namedtuple for priority)? I'm a fan of more specialised types.

The convenience properties might lead new users to not optimal handling of the accept values. This
```
def handler(request: Request) -> str:
  if request.accept_mimetypes.accept_html:
      return '<html><body><h1>Test</h1></body></html>'
  if request.accept_mimetypes.accept_text:
      return 'Default text response'
  if request.accept_mimetypes.accept_xml:
      return '<xml><msg>Test</msg></xml>'
```
would boil down to
```
def handler(request: Request) -> str:
  if request.accept_mimetypes.best_match(['text/html']) == 'text/html':
      return '<html><body><h1>Test</h1></body></html>'
  if request.accept_mimetypes..best_match(['text/plain']) == 'text/plain':
      return 'Default text response'
  if request.accept_mimetypes..best_match(['application/xml']) == 'application/xml':
      return '<xml><msg>Test</msg></xml>'
```
Given the Accept header `text/html;q=0.7,application/xml`, this would return html content despite the client giving a preference for xml when the handler could also return xml.

You would only use this feature if your handler can return different content types. Testing for a single one at a time seems odd.

If I understand the header semantic correctly, the request provides a list of preferred media types, ordered by preference and the handler has a list of content types he can provide (without any preference). Someone (in this case the application) has to figure out which of the available content types best serves the request.

If there is an agreement on where to put the code, I can try to create a PR.

**Comment by provinzkraut** [comment]
Adding `best_match` is a good idea, but I think the API you proposed isn't ideal. I would expect `best_match` to be called with a list of mimetypes, of which it then returns the best matching one. This could then be used to determine the type of content to return.

Ideally something like:

```python
from starlite import get, Request
from starlite.enums import MediaType

def handler(request: Request) -> str:
  best_match = request.accept_mimetypes.best_match([MediaType.HTML, MediaType.TEXT, MediaType.XML]) 
  if best_match == MediaType.HTML:
      return '<html><body><h1>Test</h1></body></html>'
  if best_match ==  MediaType.XML:
      return '<xml><msg>Test</msg></xml>'
  if best_match ==  MediaType.TEXT:
      return 'Default text response'
```

**Comment by NomAnor** [comment]
That was my proposel, implement `best_match` but don't provide `accept_html` :D 

The code was to show that using the `accept_X` attributes that you used in your example would lead to non optimal responses. And not using a list of possible response types would be odd.

Another question, what should the attribute on the request object be called? `accept` or `accept_mimetypes`? Should all attributes be named after the header keyword? I would lean towards this so if a developer is looking to use a header value it is easier to find.

I'm a bit confused about the different names for the same thing, "mime type", "media type", "content type". "mime type" is the general name for the format. "media type" and "content type" seem to be more specific to http. The API should try to use the appropiate name for the context.

**Comment by provinzkraut** [comment]
> That was my proposel, implement `best_match` but don't provide `accept_html` :D 

I think they can coexist. They serve different purposes and both are useful to have. E.g. if all you care about is if HTML is accepted, `accepts_html` is more useful than `best_match`.

> Another question, what should the attribute on the request object be called? `accept` or `accept_mimetypes`? Should all attributes be named after the header keyword?

I would say yes. `request.accepts` should return a `Accepts` header, which in turn has the `best_match` method. This would be the schema to follow for all of these header types, e.g. `Range` or `Accept-Language`

**Comment by peterschutt** [comment]
The `AbstractDTOInterface.to_encodable_type()` method now receives the connection - so I can envisage something like:

```
class MyDTO(AbstractDTOInterface[MyModel]):
    ...
    def to_encodable_type(media_type: MediaType, connection: Request) -> bytes:
        return self.dto_backend.to_encodable_type(media_type=connection.accept or media_type)
```
Just guessing at the interface to demonstrate the point..
