### ISSUE TITLE
Enhancement: Add Secret 

### ISSUE THREAD

**Issue by JacobCoffee** [litestar-org/litestar#1312]
**What's the feature you'd like to ask for.**
Starlite-specific implementation of [Starlette's `datastructures.Secret`](https://github.com/encode/starlette/blob/ada845cc8ad0b531b16749b9bf3a57114c60c679/starlette/datastructures.py#L206-L223).

```py
#  Starlette's implementation of the `Secret`  class in `starlette.datastructures`
class Secret:
    """
    Holds a string value that should not be revealed in tracebacks etc.
    You should cast the value to `str` at the point it is required.
    """

    def __init__(self, value: str):
        self._value = value

    def __repr__(self) -> str:
        class_name = self.__class__.__name__
        return f"{class_name}('**********')"

    def __str__(self) -> str:
        return self._value

    def __bool__(self) -> bool:
        return bool(self._value)
```

**Additional context**

Additionally, with our recent  efforts to generalize away from Pydantic (#1306, etc.) we may want to implement Pydantics `SecretStr` and `SecretBytes` https://docs.pydantic.dev/usage/types/#secret-types

<a href="https://polar.sh/litestar-org/litestar/issues/1312">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1312/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1312/pledge.svg">
</picture>
</a>

**Comment by wassafshahzad** [comment]
@JacobCoffee  How would you recommend this be implemented ? 
Just a standard class as you have described or is there any context I may be missing ?

**Comment by JacobCoffee** [comment]
I think @cofin mentioned adding `secret` under `starlite.datastructures` but the pydantic ones I am not sure on. Probably the same but someone smarter should comment :D @starlite-api/maintainers

**Comment by JacobCoffee** [comment]
@wassafshahzad is this something you would like to take?

**Comment by wassafshahzad** [comment]
> @wassafshahzad is this something you would like to take?

Yeah, as soon as I have wrapped up provide decorator issue. Pun intended
