### ISSUE TITLE
Enhancement: Replace Headers with Dataclasses

### ISSUE THREAD

**Issue by Goldziher** [litestar-org/litestar#1386]
### Summary

Currently we have some left over pydantic models in the `datastructure.headers` namespace. These should be replaced with dataclasses.

<a href="https://polar.sh/litestar-org/litestar/issues/1386">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1386/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1386/pledge.svg">
</picture>
</a>

**Comment by wassafshahzad** [comment]
Can I take this on?
Also are there any reference PRs for thsi

**Comment by Goldziher** [comment]
> Can I take this on? Also are there any reference PRs for thsi

you're most welcome to. We replaced all the pydantic models with dataclasses, so there are a lot of dataclasses in the codebase (look for @dataclass decorators)

**Comment by wassafshahzad** [comment]
> > Can I take this on? Also are there any reference PRs for thsi
> 
> you're most welcome to. We replaced all the pydantic models with dataclasses, so there are a lot of dataclasses in the codebase (look for @dataclass decorators)

Thank you

**Comment by wassafshahzad** [comment]
@JacobCoffee  Should I update test cases as well, since a lot of Header classes are using dict method of Pydantic Base model which is not available in dataclasses

**Comment by JacobCoffee** [comment]
> @JacobCoffee  Should I update test cases as well, since a lot of Header classes are using dict method of Pydantic Base model which is not available in dataclasses

I am out for a bit dealing with a family issue - @Goldziher ?

**Comment by Goldziher** [comment]
> @JacobCoffee Should I update test cases as well, since a lot of Header classes are using dict method of Pydantic Base model which is not available in dataclasses

of course, we have done this everywhere

**Comment by wassafshahzad** [comment]
> > @JacobCoffee Should I update test cases as well, since a lot of Header classes are using dict method of Pydantic Base model which is not available in dataclasses
> 
> of course, we have done this everywhere
Would that not affect users calling dict on there headers ?

**Comment by Goldziher** [comment]
> > > @JacobCoffee Should I update test cases as well, since a lot of Header classes are using dict method of Pydantic Base model which is not available in dataclasses
> > 
> > of course, we have done this everywhere
> Would that not affect users calling dict on there headers ?

Good point. 

You can implement a dict method for Headers that proxies to our helper. I'll paste a link below.
