### ISSUE TITLE
Enhancement: Add support for OpenAPI objects like x-codeSamples

### ISSUE THREAD

**Issue by SanderWegter** [litestar-org/litestar#1396]
### Summary

Redocly has support for `x-codeSamples` as an OpenAPI object (or the `x-` vendor extensions entirely)

https://redocly.com/docs/api-reference-docs/specification-extensions/x-code-samples/#code-sample-object

This results in the docs in something like this:
![Screenshot 2023-03-27 at 12 47 19](https://user-images.githubusercontent.com/7465799/227920653-64e59722-229c-4572-912b-99ec20141542.png)

This would greatly help in (quickly) testing the API with examples to copy and paste. 

### Basic Example

One way to do it would be to implement it similar to FastAPI:

```python
@get(
  path="/example",
  openapi_extras={
    "x-codeSamples": [
      {"lang": "Python", "source": "import requests; requests.get('localhost/example')", "label": "Python"},
      {"lang": "cURL", "source": "curl -XGET localhost/example", "label": "curl"},
      {...}
    ]}
```

**Comment by peterschutt** [comment]
Certainly would be nice to be able to support that.

Is there anything that would go in these that couldn't be generated from the route handler info? Maybe we could build a plugin to generate them..

**Comment by SanderWegter** [comment]
Would be great to have them auto generated (perhaps with an override) based on the route/parameters. 

> Is there anything that would go in these that couldn't be generated from the route handler info?

What do you mean by 'these'? For the redocly vendor extensions the only ones which seemed relevant and are part of the operations section of the openapi spec are
- `x-codeSamples`: list
- `x-hideTryItPanel`: bool

**Comment by peterschutt** [comment]
By "these" I mean these:

```py
[{"lang": "Python", "source": "import requests; requests.get('localhost/example')", "label": "Python"},
      {"lang": "cURL", "source": "curl -XGET localhost/example", "label": "curl"}]
```
I feel like it should be trivial to generate them  based on the info we have attached to the handler.

**Comment by WilliamStam** [comment]
how would you actually set values once you have the class? 

```

from litestar.openapi.spec import Operation


@dataclass
class CustomOperation(Operation):
    x_scopes: Optional[List[str]] = field(default=None, metadata={"alias": "x-scopes"})
    x_requires_auth: Optional[bool] = field(default=False, metadata={"alias": "x-requires-authentication"})
    
    def __post_init__(self) -> None:
        self.x_scopes = []
```

this works fine and has the default values in it.. but for every route that includes the operation_class (`handle.operation_class = CustomOperation`) 

but then how do you actually set the value on those for a route? right up until the openapi schema is generated the operation_class is just a pointer to an uninitialized class. it only gets initialized in _openapi/path_item.py 

```
operation = route_handler.operation_class(
                operation_id=operation_id,
                tags=tags,
                summary=route_handler.summary or SEPARATORS_CLEANUP_PATTERN.sub("", route_handler.handler_name.title()),
                description=get_description_for_handler(route_handler, use_handler_docstrings),
                deprecated=route_handler.deprecated,
                responses=create_responses(
                    route_handler=route_handler,
                    raises_validation_error=raises_validation_error,
                    schema_creator=response_schema_creator,
                ),
                request_body=request_body,
                parameters=parameters,  # type: ignore[arg-type]
                security=security,
            )
```

and as far as i can tell isn't available to add values to the fields after that.
