### ISSUE TITLE
Question: Reporting issues for the V2 doc

### ISSUE THREAD

**Issue by hadware** [litestar-org/litestar#1408]
### Summary

I'm trying to use starlite v2.0.0alpha2 (for a personal project, i'm ok with the alpha status). I'm trying to migrate my v1 code to v2, but some stuff isn't properly documented yet in the V2 doc. What's the best way for me to report these problems, as to help you as much as possible in fixing them?

Should I create a single issue for each single tiny problem I encounter in the doc? Should I group them?

**Comment by provinzkraut** [comment]
> Should I create a single issue for each single tiny problem I encounter in the doc? Should I group them?

Well that depends. If they're completely unrelated it's probably best to open a separate issue, but if it's things within the same document / module, you can just open one issue for all of them.

You can of course also dump all your finding here and we'll sort out how best to track them :wink:
