### ISSUE TITLE
Docs: Add more detailed description of different signature modelling backends

### ISSUE THREAD

**Issue by provinzkraut** [litestar-org/litestar#1429]
### Summary

Attrs based signature modelling was introduced in #1382, but it's not comprehensively explained in the docs what this does and why one should use this over the Pydantic backend.

Points to cover should include:

- What is a signature model / what parts of an application are handled by it?
- What's the difference between Pydantic and attrs in this case?
- Why should a user select one over the other?

**Comment by peterschutt** [comment]
I think this can be closed as we aren't going to be exposing the signature backend choice up-front to users for v2 - at least not immediately.
