### ISSUE TITLE
Responses with a non `text/*` media type get rendered as JSON

### ISSUE THREAD

**Issue by NomAnor** [litestar-org/litestar#1446]
### Summary
I'm using v2 from main.

The rendering (everything not `bytes`) of a response only depends on the provided media type and is defaulted to JSON. The logic for rendering can be a bit surprising when you want to return text with a non `text/*` media type.

### Basic Example

```python
from starlite import Response, Starlite, get


@get("/resource")
def retrieve_resource() -> Response[str]:
    return Response(content="<xml><msg>Hello World!</msg></xml>", media_type="application/xml")

app = Starlite(route_handlers=[retrieve_resource])
```
This will return `"<xml><msg>Hello World!</msg></xml>"` because it is rendered as JSON.

### Drawbacks and Impact

The media type is defaulted to JSON in
https://github.com/starlite-api/starlite/blob/c8aa65d1419590d7ccb738911783857ca92ddcc1/starlite/response/base.py#L60
This is ok and stated in the documentation.

The render logic in
https://github.com/starlite-api/starlite/blob/c8aa65d1419590d7ccb738911783857ca92ddcc1/starlite/response/base.py#L233-L254
only checks for `text/*`. Obviously starlite can't know every media type in existance but I think the default handling of an unknown media type could be better.

Explicitly check for known (starlite has special handling for it) media types (MediaType.JSON, MediaType.MESSAGEPACK).  Existing code still returns JSON because that's the default.

Handle unknown media types by some documented heuristic. I would propose checking if the type is `str` and then do the text encoding, otherwise throw an exception. Returning text and having it properly encoded is common enough to warrant handling in the framework. If a user needs custom rendering of his data, he can always do it himself and return `bytes`.

**Comment by provinzkraut** [comment]
Have you tried:

```python
from starlite import Response, Starlite, get, MediaType

@get("/resource", media_type=MediaType.XML)
def retrieve_resource() -> str:
    return "<xml><msg>Hello World!</msg></xml>"

app = Starlite(route_handlers=[retrieve_resource])
```

You can do this as well for any media type you want:

```python
from starlite import Response, Starlite, get

@get("/resource", media_type="application/my-favourite-media-type")
def retrieve_resource() -> str:
    return "Hello World!</msg>"

app = Starlite(route_handlers=[retrieve_resource])
```

**Comment by NomAnor** [comment]
Both will also return the string rendered as JSON (with quotes). Isn't it internally converted to `Response[str]`?

Sorry that I missed it again. I'm using v2 from main.

**Comment by provinzkraut** [comment]
> Both will also return the string rendered as JSON (with quotes)

That would be a bug then.

**Comment by provinzkraut** [comment]
https://github.com/starlite-api/starlite/blob/c8aa65d1419590d7ccb738911783857ca92ddcc1/tests/response/test_serialization.py#L67-L70

We are missing the test case for XML and arbitrary types here.

**Comment by NomAnor** [comment]
> That would be a bug then. The example I provided is supposed to work. Would this behaviour (if working as intended) address your issue?

Yes that should do it. My expectation (guided by the documentation) is:

1. no `media_type` given or `media_type=MediaType.JSON`: render the stated return type as JSON.
2. `media_type=MediaType.MESSAGEPACK`: render the stated type as MESSAGEPACK.
3. `media_type=MediaType.TEXT`: render the encoded string.
4. `media_type=MediaType.HTML`: render the encoded string.

My expectation (not stated in the documentation):

5. `media_type=<anything>` and stated type `bytes`. Do nothing and just repond with the bytes.
6. `media_type=<anything else>` and stated type `str`. render the encoded string.
7. `media_type=<anything else>` and stated type `!= str` is ambigious (currently behaves like 1).

Regarding 7., for clarity I would like to get an exception. This would show me that starlite can't render the given type for the stated media_type (because it doesn't know what that media_type means) and that I should do it myself (return `bytes`, 5.).

Adding documentation for 5.-7. would help users that want to return more exotic reponses.

If you want to keep 7. as-is, maybe add a paragraph to the documentation stating that for media_types not in the [list](https://docs.starliteproject.dev/latest/usage/responses.html#media-type) the output will always be JSON and a user should use `bytes` to get the output he wants.

**Comment by provinzkraut** [comment]
> Regarding 7., for clarity I would like to get an exception. This would show me that starlite can't render the given type for the stated media_type (because it doesn't know what that media_type means) and that I should do it myself

That's a very reasonable approach I think. @starlite-api/maintainers?

Do you want to add a PR, since you've apparently given it a good of amount of consideration already?

**Comment by Goldziher** [comment]
im good with this, thanks @NomAnor for your efforts

**Comment by peterschutt** [comment]
All sounds good to me. I'm in favour of raising for 7 also, as long as the check is made during startup and we can have a nice exception message that details the error and the alternatives for the user.

> thanks @NomAnor for your efforts

Seconded!
