### ISSUE TITLE
Enhancement: support HTML media type in redirect

### ISSUE THREAD

**Issue by Goldziher** [litestar-org/litestar#1451]
### Summary

We  currently do not support MediaType.HTML in the Redirect class / response, and this value is ignored (we do TEXT always). We should add support for HTML redirects as well. 

### Drawbacks and Impact

None

**Comment by sonpro1296** [comment]
Hi, can I work on this?

**Comment by Goldziher** [comment]
> Hi, can I work on this?

Sure, I'll assign you

**Comment by sonpro1296** [comment]
PR for this is merged: https://github.com/litestar-org/litestar/pull/1474

**Comment by cofin** [comment]
closed by #1474 

Thanks for the work on this!
