### ISSUE TITLE
Add support for "Message Flashing"

### ISSUE THREAD

**Issue by 4n1qz5skwv** [litestar-org/litestar#1455]
### Discussed in https://github.com/orgs/litestar-org/discussions/1454

<div type='discussions-op-text'>

<sup>Originally posted by **4n1qz5skwv** April  6, 2023</sup>
https://flask.palletsprojects.com/en/2.2.x/patterns/flashing/

```python
flash('Invalid password provided', 'error')
```

How to do this **LiteStar**?</div>

<a href="https://polar.sh/litestar-org/litestar/issues/1455">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1455/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1455/pledge.svg">
</picture>
</a>

**Comment by v3ss0n** [comment]
I believe this framework is not designed for this . This is (mostly) API framework , why it needs a flashing facility ?

**Comment by Goldziher** [comment]
This is not going to be supported probably - what do you think @provinzkraut ?

**Comment by provinzkraut** [comment]
I think it could be fine in contrib if someone wants to add this, or we can create a "recipe" for it. It's easy enough to implement with request local state and a custom response class.

**Comment by provinzkraut** [comment]
Why has this been closed?

**Comment by Goldziher** [comment]
> Why has this been closed?

It's stale and no one showed interest
