### ISSUE TITLE
Docs: Rename broke old docs link

### ISSUE THREAD

**Issue by sabard** [litestar-org/litestar#1459]
### Summary

Congrats on taking the step of renaming!

What are the plans for the old docs link @ https://docs.starliteproject.dev/ ?

I found out about the rename this morning since the old link is still very SEO'd and was confused thinking the site was down. If you all still have control of this URL would it be possible to redirect to the new docs link or to a message about the rename?

**Comment by provinzkraut** [comment]
Hey @sabard, thanks for bringing this up! 

The old domains should redirect to the new page, but it's possible that the DNS changes haven't propagated fully yet. Unfortunately, since we're hosting these on GitHub pages, there's not really an easy way to make this process more seamless.
