### ISSUE TITLE
Enhancement: Allow customizing uploader. 

### ISSUE THREAD

**Issue by 4n1qz5skwv** [litestar-org/litestar#1465]
### Discussed in https://github.com/orgs/litestar-org/discussions/1463

<div type='discussions-op-text'>

<sup>Originally posted by **4n1qz5skwv** April  9, 2023</sup>
Currently, Uploaded files are stored in temporary location. In order to save it elsewhere, we have to rewrite or copy it. 

Is it possible to setup a custom handler?

Say, uploaded file will saved in my_dir/{uuid4}/filename.ext directly ?</div>

<a href="https://polar.sh/litestar-org/litestar/issues/1465">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1465/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1465/pledge.svg">
</picture>
</a>

**Comment by Goldziher** [comment]
Please specify exactly what you are requesting. Thanks
