### ISSUE TITLE
Docs: Build docs per commit/PR

### ISSUE THREAD

**Issue by JacobCoffee** [litestar-org/litestar#1485]
### Summary
Add a GitHub Action that comments on PRs with a link to previews of documentation builds.

---

Tiangolo has this really cool thing for FastAPI/Typer/etc. that builds docs per PR.
I think this is done via the [Comment Docs Preview in PR](https://github.com/tiangolo/fastapi/tree/master/.github/actions/comment-docs-preview-in-pr) GitHub Action.

It will be a little different, as we are on Sphinx, but mostly should be the same.

https://github.com/tiangolo/fastapi/pull/9383#issuecomment-1505146933

![image](https://user-images.githubusercontent.com/45884264/231479309-3c01776d-5841-460e-b595-d50470e80c51.png)

**Comment by provinzkraut** [comment]
Adding some info: We already build the docs as part of our CI on pull requests anyway to check for issues there. A possible implementation of this would then be as simple as:

1. Upload the built docs as an artifact from the workflow
2. Have a different workflow/action that takes this artifact and publishes it somewhere (GH-pages / netlify / vercel / etc.)
3. Use the GitHub API to post a comment linking the deployment

**Comment by VietThan** [comment]
Is this issue already addressed with #1697  ?

**Comment by provinzkraut** [comment]
It is, yeah. We forgot to link that!
