### ISSUE TITLE
Docs: Add `sphinx-click` to the documentation.

### ISSUE THREAD

**Issue by JacobCoffee** [litestar-org/litestar#1495]
### Summary

Sphinx has a contrib plugin for click. It would be nice to auto-doc it.
I have used it in my own app recently - example:
![image](https://user-images.githubusercontent.com/45884264/232075027-5cec60bf-2965-4f81-8239-ccf1059abb06.png)

https://sphinx-click.readthedocs.io/en/latest/ 

1. `poetry add -G docs sphinx-click`
2. Add `sphinx-click` to the `conf.py`
3. Use it to document our CLI automatically

### Reference:
https://discord.com/channels/919193495116337154/1061269663750836234/1095917360591949904

<a href="https://polar.sh/litestar-org/litestar/issues/1495">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1495/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1495/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
Would we still be able to easily document the env variable alternatives for the CLI flags with this?
