### ISSUE TITLE
Bug: Mounting a WSGI app fails to find endpoint, returns 404 error

### ISSUE THREAD

**Issue by ThinksFast** [litestar-org/litestar#1496]
### Description

I've been struggling with a memory leak for a while.  I'd like to try using PyLoot to analyze what's going on.

https://pypi.org/project/pyloot/

With @provinzkraut help, I was able to get the following MCVE.  But when I run the app `uvicorn main-pyloot:app --reload` and try to load the pyloot path, I get a 404 error.  The logs only show this.  

I'm not sure if the problem lies on `Litestar`, `a2wsgi` or `Pyloot` side of things.

```
GET /pyloot HTTP/1.1" 404 Not Found
pyloot.server - server - [_dispatch] path_info=/pyloot path=/pyloot
```

### MCVE

```python
from a2wsgi import WSGIMiddleware
from pyloot import PyLoot
from starlite import Starlite, asgi

loot = PyLoot()
loot.start()


def pyloot_wrapper(wsgi_environ, start_response):
    pyloot_environ = wsgi_environ.copy()
    pyloot_environ["wsgi.multiprocess"] = False
    wsgi = loot.get_wsgi()
    return wsgi(pyloot_environ, start_response)


pyloot_handler = asgi("/_pyloot")(WSGIMiddleware(pyloot_wrapper))

app = Starlite(
    [pyloot_handler],
    debug=True,
)
```
EDIT: I updated the MCVE to use the path shown in Pyloot docs (`/_pyloot`). This does not resolve the issue, but since it's the suggested path, better this way.

### Steps to reproduce

```bash
1. Run the mcve: `uvicorn main-pyloot:app --reload`
2. Open this in your browser: `http://localhost:8000/pyloot`
3. See error
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Logs

```bash
INFO:     127.0.0.1:64971 - "GET /pyloot HTTP/1.1" 404 Not Found
INFO - 2023-04-14 11:00:52,822 - pyloot.server - server - [_dispatch] path_info=/pyloot path=/pyloot
```

### Litestar Version

Python == 3.11.0
starlite == 1.51.10  
a2wsgi == 1.7.0 
pyloot == 0.1.0

### Platform

- [ ] Linux
- [X] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

<a href="https://polar.sh/litestar-org/litestar/issues/1496">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1496/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1496/pledge.svg">
</picture>
</a>

**Comment by Goldziher** [comment]
So, this functionality is not supported on our end - mounting wsgi. @provinzkraut - should we close this issue?

**Comment by provinzkraut** [comment]
@Goldziher Well it's not, but I think we should investigate if this is an issue on our end with how we handle mounting ASGI apps.
