### ISSUE TITLE
Enhancement: Add support for SuperTokens SDK

### ISSUE THREAD

**Issue by Spectryx** [litestar-org/litestar#1497]
### Summary

I would be nice if LiteStar was supported in the SuperTokens Python SDK, ref discussion https://github.com/orgs/litestar-org/discussions/1490
The SDK already supports Flask, Django and FastAPI and provides a pretty simple way to get started with authentication.

https://supertokens.com

<a href="https://polar.sh/litestar-org/litestar/issues/1497">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1497/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1497/pledge.svg">
</picture>
</a>

**Comment by Alc-Alc** [comment]
I think @Goldziher wanted to have discussion on their (SuperTokens) repo and not here?

**Comment by Spectryx** [comment]
> I think @Goldziher wanted to have an issue on their (SuperTokens) repo and not here?

Yeah, that arena more logical…🙈 ill fix it

**Comment by Goldziher** [comment]
I added a draft PR. I'm afraid I'm stuck - https://github.com/supertokens/supertokens-python/issues/310#issuecomment-1509833120
