### ISSUE TITLE
Docs: Fix typos in `Routing` docs

### ISSUE THREAD

**Issue by JacobCoffee** [litestar-org/litestar#1498]
### Summary

https://docs.litestar.dev/2/usage/routing.html#mounting-asgi-apps

![image](https://user-images.githubusercontent.com/45884264/232183931-df1d8f66-ef25-42b6-b922-1bcc150a94df.png)

```suggestion
for example, for 3rd party libraries.
```

**Comment by quantavoid11** [comment]
Hey @JacobCoffee, can I work on this issue?

**Comment by peterschutt** [comment]
All yours @quantavoid11

**Comment by quantavoid11** [comment]
Hey @peterschutt, I am getting some errors while building docs using make command. Can you please help me out?
![image](https://user-images.githubusercontent.com/97203165/233542259-2343d6d7-bc60-4af2-bf6a-6358d9d816af.png)

**Comment by peterschutt** [comment]
Do you have `curl` available?

```sh
(litestar-py3.8) peter@peter-Inspiron-15-5510:~/PycharmProjects/litestar$ curl
curl: try 'curl --help' or 'curl --manual' for more information
```

**Comment by quantavoid11** [comment]
Ohh!! My bad.I recently shifted from windows to ubuntu. I assumed it comes pre built with curl command.
