### ISSUE TITLE
Docs: Issue in "Stores/Deleting expired values" section

### ISSUE THREAD

**Issue by sonpro1296** [litestar-org/litestar#1499]
### Summary

Hi guys, I found this bit pretty confusing: 

![Crop It 2023-4-15 at 13 32 14](https://user-images.githubusercontent.com/17319142/232190964-82785c63-904f-4f73-86fa-a2523487cede.png)

As I understand, `after_response` function will be called after every awaited response , not "at most every 30 second"

**Comment by peterschutt** [comment]
Yes, the after response hook is called for each request, but the logic to delete expired items is guarded such that it will only execute at most once per 30 seconds.

**Comment by sonpro1296** [comment]
Got it, I pretty much misunderstood this sentence. Thanks a lot for lightspeed response :)

**Comment by peterschutt** [comment]
No probs! Feel free to make a PR to clarify the wording if you think it is required.
