### ISSUE TITLE
DTO Interface: consider removing support for declaring the DTO as data/return type

### ISSUE THREAD

**Issue by peterschutt** [litestar-org/litestar#1525]
This is mostly a feature hangover from when the DTO types _were_ pydantic models, and were relying on being in the signature model. 

Now that they are declarable at the layers, I'm not totally sure if having this support is necessary: less is more, can always be added later, want to hear actual use-cases for it, and all that.

**Comment by provinzkraut** [comment]
> I'm not totally sure if having this support is necessary: less is more

I also think that having one clear way to do this is best.
