### ISSUE TITLE
RFC: do we need to continue to support v1 serialization plugins?

### ISSUE THREAD

**Issue by peterschutt** [litestar-org/litestar#1528]
The alternate implementation in #1501 has approval and would be good to merge into the `dto-factory` branch, however, this will involve removing all of the existing v1 serialization plugin implementation.

We have an implementation of that in sqlalchemy v1 contrib, which would then also have to be removed (we could  still keep the init plugin though).

Alternatively, we keep supporting both, and put the DTO based serialization plugin under a different name.

**Comment by provinzkraut** [comment]
IMO we can drop it. No need to keep it around just for SQLA 2.

**Comment by Goldziher** [comment]
Let's make it simple and drop it. We can drop SQLA 1 as well IMO - we can spin it into a separate package if required

**Comment by peterschutt** [comment]
OK thanks, this is happening in #1501
