### ISSUE TITLE
Enhancement: Prometheus exporter for Litestar

### ISSUE THREAD

**Issue by harochau** [litestar-org/litestar#1558]
### Summary

It looks lite the existing solutions like https://github.com/stephenhillier/starlette_exporter and https://github.com/trallnag/prometheus-fastapi-instrumentator don't work with Litestar as they rely on Starlette`s add_middleware() method.
Litestar does have OpenTelemetry integration, but as I understand it is not compatible with Prometheus as it cannot expose /metrics endpoint.

<a href="https://polar.sh/litestar-org/litestar/issues/1558">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1558/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1558/pledge.svg">
</picture>
</a>

**Comment by Goldziher** [comment]
would be a nice addition to contrib for sure, PR is welcome!

**Comment by JacobCoffee** [comment]
Seconding this, if anyone wants to pick it it would be well appreciated 😄

**Comment by r4gesingh47** [comment]
Can I pick this up?, never worked around  Prometheus but confident enough that I could do it.

**Comment by Goldziher** [comment]
> Can I pick this up?, never worked around Prometheus but confident enough that I could do it.

sure

**Comment by r4gesingh47** [comment]
Hi @Goldziher .
1. I am thinking to implement mostly like https://github.com/stephenhillier/starlette_exporter did.

2. However as the Issue mentioned we have already open telemetry integrated there is package around that  https://pypi.org/project/opentelemetry-exporter-prometheus/ which translates the data into Prometheus format.

I think having a standalone integration will be best and not being dependent on open telemetry. So, should I start with approach 1.

**Comment by Goldziher** [comment]
thats fine @r4gesingh47

**Comment by r4gesingh47** [comment]
@Goldziher  can you suggest what metrics to add by default.
The starlette export had  requests_duration, total_requests, requests_in_progress.

**Comment by Goldziher** [comment]
> @Goldziher  can you suggest what metrics to add by default.
> The starlette export had  requests_duration, total_requests, requests_in_progress.

Sure, these are fine - google "the four golden signals" and "red signals".

**Comment by Goldziher** [comment]
> While built-in Prometheus metrics is being developed, it is possible to use `starlette-exporter` with Litestar:
> 
> ```python
> from starlite import (
>     DefineMiddleware,
>     MediaType,
>     Starlite,
>     Request,
>     get
> )
> from starlette_exporter import handle_metrics
> from starlette_exporter.middleware import PrometheusMiddleware
> 
> @get("/metrics", media_type=MediaType.TEXT)
> def get_metrics(request: Request) -> bytes:
>     """Endpoint for collecting Prometheus metrics."""
>     metrics = handle_metrics(request=request)  # type: ignore
>     return metrics.body
> 
> 
> app = Starlite(
>     route_handlers=[get_metrics],
>     middleware=[
>         DefineMiddleware(
>             PrometheusMiddleware,  # type: ignore
>             app_name="example",
>             prefix="starlite",
>         ),
>     ],
> )
> ```
> 
> Metrics:
> 
> ````
> # HELP starlite_requests_in_progress Total HTTP requests currently in progress
> # TYPE starlite_requests_in_progress gauge
> starlite_requests_in_progress{app_name="example",method="GET"} 1.0
> # HELP starlite_requests_total Total HTTP requests
> # TYPE starlite_requests_total counter
> starlite_requests_total{app_name="example",method="GET",path="/metrics",status_code="200"} 1.0
> # HELP starlite_requests_created Total HTTP requests
> # TYPE starlite_requests_created gauge
> starlite_requests_created{app_name="example",method="GET",path="/metrics",status_code="200"} 1.685710305568984e+09
> # HELP starlite_request_duration_seconds HTTP request duration, in seconds
> # TYPE starlite_request_duration_seconds histogram
> starlite_request_duration_seconds_bucket{app_name="example",le="0.005",method="GET",path="/metrics",status_code="200"} 1.0
> starlite_request_duration_seconds_bucket{app_name="example",le="0.01",method="GET",path="/metrics",status_code="200"} 1.0
> starlite_request_duration_seconds_bucket{app_name="example",le="0.025",method="GET",path="/metrics",status_code="200"} 1.0
> starlite_request_duration_seconds_bucket{app_name="example",le="0.05",method="GET",path="/metrics",status_code="200"} 1.0
> starlite_request_duration_seconds_bucket{app_name="example",le="0.075",method="GET",path="/metrics",status_code="200"} 1.0
> starlite_request_duration_seconds_bucket{app_name="example",le="0.1",method="GET",path="/metrics",status_code="200"} 1.0
> starlite_request_duration_seconds_bucket{app_name="example",le="0.25",method="GET",path="/metrics",status_code="200"} 1.0
> starlite_request_duration_seconds_bucket{app_name="example",le="0.5",method="GET",path="/metrics",status_code="200"} 1.0
> starlite_request_duration_seconds_bucket{app_name="example",le="0.75",method="GET",path="/metrics",status_code="200"} 1.0
> starlite_request_duration_seconds_bucket{app_name="example",le="1.0",method="GET",path="/metrics",status_code="200"} 1.0
> starlite_request_duration_seconds_bucket{app_name="example",le="2.5",method="GET",path="/metrics",status_code="200"} 1.0
> starlite_request_duration_seconds_bucket{app_name="example",le="5.0",method="GET",path="/metrics",status_code="200"} 1.0
> starlite_request_duration_seconds_bucket{app_name="example",le="7.5",method="GET",path="/metrics",status_code="200"} 1.0
> starlite_request_duration_seconds_bucket{app_name="example",le="10.0",method="GET",path="/metrics",status_code="200"} 1.0
> starlite_request_duration_seconds_bucket{app_name="example",le="+Inf",method="GET",path="/metrics",status_code="200"} 1.0
> starlite_request_duration_seconds_count{app_name="example",method="GET",path="/metrics",status_code="200"} 1.0
> starlite_request_duration_seconds_sum{app_name="example",method="GET",path="/metrics",status_code="200"} 0.0033044167794287205
> # HELP starlite_request_duration_seconds_created HTTP request duration, in seconds
> # TYPE starlite_request_duration_seconds_created gauge
> starlite_request_duration_seconds_created{app_name="example",method="GET",path="/metrics",status_code="200"} 1.685710305569102e+09
> ````

That's neat!

**Comment by r4gesingh47** [comment]
I am mostly done, few extra configuration settings are left which I need to test and also can we connect on discord for review.
