### ISSUE TITLE
Enhancement: DTO Calculated fields

### ISSUE THREAD

**Issue by peterschutt** [litestar-org/litestar#1563]
Allow the DTO to accept alternate fields to that which exist on the model, and a converter function that receives the values to populate the model value.

Rough idea for interface:

```py
@dataclass
class Model:
    a: int

def converter(b: int, c: int) -> int:
    return b + c

calculated_field = CalculatedField(
    fields=(
        FieldDefinition(name="b", parsed_type=ParsedType(int)), 
        FieldDefinition(name="c", parsed_type=ParsedType(int)),
    ),
    converter=converter
)
config = DTOConfig(calculated_fields={"a": calculated_field})

ModelDTO = DataclassDTO[Annotated[Model, config]]
```

<a href="https://polar.sh/litestar-org/litestar/issues/1563">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1563/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1563/pledge.svg">
</picture>
</a>

**Comment by Goldziher** [comment]
@gsakkis would you like to take this one?

**Comment by Jannchie** [comment]
Hello, I think this is a useful feature, but it is not planned… Are there any alternative solutions?

**Comment by provinzkraut** [comment]
Not really, other than to add a `@property` on the actual model.

**Comment by Jannchie** [comment]
Oh, thank you! The `@property` is what I actually want! I am still attempting to work around #4114.  I found that although I can parse normally, I can’t get the correct types in OpenAPI.

With knowledge of the property concept, I can now write code in this way to bid farewell to all those annoying hacks for configuration!


```py
@dataclass
class Post:
    _embedding: np.ndarray = field()

    @property
    def embedding(self) -> list[int]:
        return self._embedding.tolist()


class PostDTO(DataclassDTO[Post]):
    config = DTOConfig(rename_strategy="camel")


@get("/", dto=PostDTO, sync_to_thread=True)
def test() -> Post:
    return Post(_embedding=np.array([[1, 2, 3]], dtype=np.int8))
    

```
