### ISSUE TITLE
Enhancement: Support SSE

### ISSUE THREAD

**Issue by JacobCoffee** [litestar-org/litestar#1578]
### Summary

While we do have websockets, SSE looks nice to fill out our users choices.

https://github.com/sysid/sse-starlette

We will need to have our own implementation of this instead of depending upon Starlette.

<a href="https://polar.sh/litestar-org/litestar/issues/1578">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1578/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1578/pledge.svg">
</picture>
</a>

**Comment by v3ss0n** [comment]
SSE is a lot easier to implement on both side , and can use as the same pattern and normal HTML web developement pattern , without needed to switch to always connected Websocket pattern. Huge plus for me.

**Comment by Goldziher** [comment]
Would be great to have this in v2

**Comment by v3ss0n** [comment]
would like to help.

**Comment by JacobCoffee** [comment]
@v3ss0n what do you think of this?

I am thinking doing something like this, now that we have the [channels](https://docs.litestar.dev/dev/usage/channels.html) stuff in and use `@websocket("/ws")`

```py
from litestar import Litestar
from litestar.handlers import sse_listener

@sse_listener("/") # this would use text/event-stream
async def handler(data: str) -> str:
    return data

app = Litestar([handler])
```

**Comment by v3ss0n** [comment]
quite clean , that would nice.

**Comment by Goldziher** [comment]
@JacobCoffee eta?

**Comment by v3ss0n** [comment]
I could work on it if this is going into beta

**Comment by Goldziher** [comment]
it should go into it, yes

**Comment by Goldziher** [comment]
This is done

**Comment by v3ss0n** [comment]
awesome! felt guilty didn't managed to contribute. I am going to test it tomorrow.
