### ISSUE TITLE
RFC: Enhancement: DTO Partial Support

### ISSUE THREAD

**Issue by peterschutt** [litestar-org/litestar#1579]
### Summary

# v2  `Partial` support

Starlite `Partial` uses `__class_getitem__()` to create a new model of the generic argument type with all fields made optional, and returns that from `__class_getitem__()`. There's two facets of this I'd like to change:

1. returning a totally different type from `__class_getitem__()` isn't ideal as static type checkers will still think the thing is an instance of `Partial`.
2. `None` used as missing sentinel doesn't allow to discriminate where an optional field with no default value has been omitted from client data.

## Proposal

We have a new `Partial` type, that is still the interface for supporting routes that can accept partial representations of entities, but less magic.

### Proposed usage example

```py
model_instance = MyModel()

@patch(dto=MyDTO)
def patch_handler(data: Partial[MyModel]) -> MyModel:
    assert isinstance(data, Partial)  # we do inject an instance of partial
    validated_data: dict[str, Any] = data.as_builtins()  # validated but unstructured data available
    new_instance: MyModel = data.create_instance()  # utility that will create an instance of `MyModel` from the validated client data
    return data.update_instance(model_instance)  # utility to do a `setattr` of the inbound client data onto some `MyModel` instance
```

### Partial methods

- `create_instance()`/`update_instance()` methods are there because there is no guarantee that the underlying library that we are abstracting away will even allow to instantiate the model type without all required attributes (SQLAlchemy does allow this, but I imagine most won't), and no guarantee that the client has to send complete enough data to instantiate an instance on every request. So, a pattern where the instance needs to be queried first and subsequently updated from the raw data should be generally more useful. 
- `as_builtins()`: Making unstructured, but validated data available to the developer means that they can roll their own solution to how the partial updates should be handled.

### Partial and AbstractDTOFactory

When the DTO receives the handler `"data"` kwarg type on startup, it can  detect that it is representing a `Partial` type, and build the DTO backend to suit it. Every model field that is built by the backed will be a union of its type and `EmptyType` with a default value of `Empty`. Any `Empty` values encountered when accessing one of the `Partial` methods documented above, will be omitted.

### Partial and OpenAPI

The DTO that represents the partial type should be able to produce an openapi schema that removes any `EmptyType` unions.

**Comment by peterschutt** [comment]
> its a way to take a data container (read dataclass, typeddict, pydantic, msgspec, attrs etc.) instance and make all its proprties partial, thats it.

1. The way it makes all properties partial makes it impossible to know if a field typed `int | None` is explicitly set `None` or just `None` because the client sent no value.
2. What if I need a partial sqlalchemy model? Or any other model that I'm supporting by DTO and not default serialisable types?

**Comment by peterschutt** [comment]
Maybe the thing I'm talking about is a separate data structure to `Partial` then.

**Comment by Goldziher** [comment]
> Maybe the thing I'm talking about is a separate data structure to `Partial` then.

I think so

**Comment by provinzkraut** [comment]
> Maybe the thing I'm talking about is a separate data structure to Partial then.

I think yes and no. What you're describing @peterschutt is indeed something fundamentally different than what `Partial` currently is. But fwiw, I think it's what it should be. 

With this implementation, `Partial` is basically a kind of DTO. Which, looking at what it's supposed to do conceptually, it also should be. 

The idea of having a thing that simply "makes every field optional" is good in theory, but limited in practice, as shown by the cases you brought up where it doesn't work. It might work fine for the simple case of having a Pydantic model or a dataclass, but we shouldn't restrict it do that. The way I see it, it's an extension of the DTO pattern we established, and should follow those semantics and compatibility. 

As for the implementation, I can see how adding one extra layer of abstraction to this is not ideal. On the other hand, it does make things more transparent; Instead of having a new type that's modelled after the source but with only optional field, you now have a proxy that acts upon the source type. This in combination with solving the typing issues, having somewhat more involved interface is worth it IMO.

**Comment by Goldziher** [comment]
Partial is based on this https://www.typescriptlang.org/docs/handbook/utility-types.html#partialtype

It's not based on the DTO pattern, it's a typing utility helper. 

The above destroys this - which works, within the limitations of what python typing allows, and replaces it with another kind of DTO. 

I'm against this. But this takes something simple and both makes it unnecessarily complex while also coupling it to the DTO stuff.  

You can add a PartialDTO helper or something to do this stuff, but not at the cost of removing functionality.

**Comment by provinzkraut** [comment]
> It's not based on the DTO pattern, it's a typing utility helper.

But it's not just for typing. It's also used for data validation, which means it's just a DTO with a specific use case. It takes in a type and generates a new types with some transformation applied, which is then used for data validation. That's basically a subset of our DTO functionality.

**Comment by peterschutt** [comment]
I was only thinking of PATCH handling of DTO parsed data, but there might be other cases also where a user wants to access the unstructured, validated data. Consider this example, where it should be a client error for an `"id"` field to exist in the client payload for a POST request, so that field is excluded from the DTO model.

```py
from dataclasses import dataclass
from typing import Annotated

from litestar import post
from litestar.dto.factory import DTOConfig
from litestar.dto.factory.stdlib.dataclass import DataclassDTO

@dataclass
class Foo:
    id: int
    a: str

config = DTOConfig(exclude={"id"})
CreateDTO = DataclassDTO[Annotated[Foo, config]]

@post(dto=CreateDTO)
def post_handler(data: Foo) -> Foo:
    return Foo
```

This doesn't work as the dataclass cannot be instantiated without a value for `id` (NB: this is not a problem with sqlalchemy). I can think of a couple of options for handling something like this:

1. the dataclass `id` field can be given a sentinel default (like `-1`)
2. we could support a callback that receives the raw data after parsing it from the serialization model where sentinel values can be added before the model instance is instantiated.

However, for this, PATCH requests, and other scenarios that I can't imagine, it is fair that the user might want the validation of the inbound data to be performed according to the types specified on the model and the config declared on the DTO, but not want the data to be coerced into the model type before they use it for business logic.

So I'm thinking of a datatype like `DTOData[MyModel]` where the `DTOData` instance has those methods on it that I named in the OP. Then, a datatype called `Patch` could be a subclass of `DTOData` that signals to the DTO type that it needs to do all of the `EmptyType` union stuff to support missing data values.

E.g.,

```py
model_instance = MyModel()

@post(dto=MyDTO)
def post_handler(data: DTOData[MyModel]) -> MyModel:
    # gives dev a chance to augment data before creating the model instance
    return data.create_instance(id=get_id_sequence_value())  # kwargs are merged with the validated client payload before creating the model

@patch(dto=MyDTO)
def patch_handler(data: Patch[MyModel]) -> MyModel:
    # same as OP example but with different name
    ...
```
