### ISSUE TITLE
Enhancement: `contrib.respository.on_app_init()` handler

### ISSUE THREAD

**Issue by peterschutt** [litestar-org/litestar#1586]
### Summary

Callback to add to `on_app_init` that adds repository names to signature namespace.

### Basic Example

In `starlite-pg-redis-docker` I init the app with:

```py
        signature_namespace={
            "AsyncSession": AsyncSession,
            "FilterTypes": FilterTypes,
            "BeforeAfter": BeforeAfter,
            "CollectionFilter": CollectionFilter,
            "LimitOffset": LimitOffset,
            "UUID": UUID,
            "OrderBy": OrderBy,
            "SearchFilter": SearchFilter,
        },
```
These are names of things that would commonly be declared as handler or model parameter types when using the repository that are likely to get linted into an `if TYPE_CHECKING` block if using `__future__.annotations`.

E.g.,

```py
app = Litestar(..., on_app_init=[contrib.repository.on_app_init], ...)
```

### Drawbacks and Impact

It is opt in, so won't be any backward incompatible behavior.

A drawback is that it is a bit magical, but if we document it well, it might also be a good example of how to use the `signature_namespace` feature.

**Comment by peterschutt** [comment]
This could also be a method on the base repository which might make sense if we want to be able to customize behavior to each repository type. Would also probably make sense to make them an implementation of `InitPluginProtocol` in that case also. E.g., 

```py
app = Litestar(..., plugins=[contrib.sqlalchemy.repository.SQLAlchemyAsyncRepository.InitPlugin]
```

Weather the repository was actually also the plugin protocol or owns one is up for debate in this pattern I guess.

**Comment by Goldziher** [comment]
I think this is good, no issues from my end

**Comment by sonpro1296** [comment]
Hi guys, could I work on that?

I'm going to add extra repo names in `signature_namespace` function in each config (`SQLAlchemyAsyncConfig`, `SQLAlchemySyncConfig`), or implement the common ones in `GenericSQLAlchemyConfig`, any thoughts on that?

**Comment by peterschutt** [comment]
> Hi guys, could I work on that?
> 
> 
> 
> I'm going to add extra repo names in `signature_namespace` function in each config (`SQLAlchemyAsyncConfig`, `SQLAlchemySyncConfig`), or implement the common ones in `GenericSQLAlchemyConfig`, any thoughts on that?
> 
> 
> 
> 

More than welcome to work on it @sonpro1296! 

I'm not sure we want the repository names added via the sqlalchemy configs - my thinking here is that the sqlalchemy plug-in can be used independent of the repository pattern and I don't know that we want to unnecessarily populate the namespace in that case. Happy to discuss.

**Comment by sonpro1296** [comment]
That's make sense, but if that's the case, I think we will have to check if repository pattern is being used in order to add the namespace.  I'm not sure it's a good idea (because I don't know how xD), compare to adding via configs.

**Comment by peterschutt** [comment]
It should just be something that the user opts into IMO.

E.g., 

```py
from litestar.contrib import repository

app = Litestar(..., on_app_init=[repository.on_app_init])
```
