### ISSUE TITLE
Docs: Document signature namespace introduced in #1618

### ISSUE THREAD

**Issue by JacobCoffee** [litestar-org/litestar#1630]
### Summary

#1618 introduces x as requested in #1586.

As noted in #1586, we should enhance the docs to include detail on how to use this feature.

> A drawback is that it is a bit magical, but if we document it well, it might also be a good example of how to use the `signature_namespace` feature.

<a href="https://polar.sh/litestar-org/litestar/issues/1630">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1630/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1630/pledge.svg">
</picture>
</a>

**Comment by Alc-Alc** [comment]
Looks like this is already there? https://docs.litestar.dev/latest/usage/routing/handlers.html#signature-namespace
