### ISSUE TITLE
DTO: Implement DTO factory for Response[type]

### ISSUE THREAD

**Issue by abdulhaq-e** [litestar-org/litestar#1631]
### Summary

Sometimes, a concrete `Response` needs to be returned by a handler. For example, to add dynamic headers. The body of the `Response` should be something that can potentially be handled by `return_dto` of the handler.

### Basic Example

```python
from litestar import post

from .models import User, UserDTO

@get(user_id: str, return_dto=UserDTO)
def fetch_user() -> Response[User]:
    return  Response(
        User.get(user_id),
        headers={"Random-Header": str(randint(1, 100))},
    )
```

**Comment by abdulhaq-e** [comment]
@peterschutt What do you think?

**Comment by peterschutt** [comment]
Yes, this needs to be handled. Also, `OffsetPaginated[list[User]]` and any other generic return types similar.
