### ISSUE TITLE
Enhancement: Unify ASGI and application hooks

### ISSUE THREAD

**Issue by provinzkraut** [litestar-org/litestar#1634]
Currently there's two different sets of "lifespan" callables:

1. `before_shutdown` / `after_shutdown` and `before_startup` / `after_startup`
2.  `on_shutdown` and `on_startup`

The `on_` all receive the application as a positional arguments, while the `before_` / `after_` hooks optionally receive the application state. There is no actual need for this distinction, and the `before_` / `after_` hooks should also just receive the application instance.

**Comment by Goldziher** [comment]
Whats preventing us from removing the `on_` events?

**Comment by provinzkraut** [comment]
#1635

**Comment by provinzkraut** [comment]
Closed in #1663
