### ISSUE TITLE
Enhancement: Custom Return Codes

### ISSUE THREAD

**Issue by JacobCoffee** [litestar-org/litestar#1642]
### Summary

Allow for creation of custom return codes that can automatically be documented by the OpenAPI response section.
Currently if you do this, the custom response returns a `ValueError: 420 is not a valid HTTPStatus`

### Basic Example

```py
class HouseNotFoundError(HTTPException):
    status_code: int = 420
    detail: str = "House not found."

    ...
        
@get(path="foo", raises=[HouseNotFoundError])
   ...
```

### Unresolved questions

It would be nice if these could be applied controller wide. 

<a href="https://polar.sh/litestar-org/litestar/issues/1642">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1642/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1642/pledge.svg">
</picture>
</a>

**Comment by JacobCoffee** [comment]
@Alc-Alc was able to come up with `responses={420: ResponseSpec(data_container=list[str], description="Store not found")}` but it feels hacky. Maybe this is the way we want to do it? @provinzkraut

**Comment by JacobCoffee** [comment]
Seeing that it was brought up / done for #1292

**Comment by Goldziher** [comment]
well thats a bug

**Comment by Goldziher** [comment]
Overriding openapi response descriptions is fine, but creating non-standard response codes is not IMO. The status codes are standardized for a reason and have a semantic meaning. This is not meant to be used arbitrarily.

Can we close this issue? If need be, open a different issue with a better description.
