### ISSUE TITLE
Bug: Annotated Types not being rendered in OpenAPI schema

### ISSUE THREAD

**Issue by st1nc1ty** [litestar-org/litestar#1653]
### Description

I've got a `msgspec.Struct` request object that uses an `typing.Annotated` type as one of it's field types.

When viewing routes request object, I'm only seeing a str or null allowed but no mention of the max length piece.  This also happens when I exclude the `| None` from the type declaration as well.

### MCVE

```python
from typing import Annotated
import msgspec

IDType = Annotated[str, msgspec.Meta(max_length=16)]

class Lookup(msgspec.Struct):
    id:  IDType | None
```

### Steps to reproduce

```bash
1. Create route with the above request object.
2. View the route in the /schema endpoint.
```

### Litestar Version

2.0.0a5

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

**Comment by Goldziher** [comment]
Yes, im not sure we currently parse the msgspec meta data.

**Comment by peterschutt** [comment]
There is also an issue with `Optional[...]` that @v3ss0n has encountered where type of those fields is displaying as `"Unknown type: null"` in api docs.

I'd like us to get to handling these msgspec `Annotated` constraints as I intend to improve on the SQLAlchemy and other ORM DTOs to generate them when possible, e.g., `VARCHAR(16)` would generate `Annotated[str, msgspec.Meta(max_length=16)]` on the transfer model.

**Comment by Goldziher** [comment]
Aight, if no one picks it I'll take it depending on my capacity

**Comment by v3ss0n** [comment]
> There is also an issue with `Optional[...]` that @v3ss0n has encountered where type of those fields is displaying as `"Unknown type: null"` in api docs (not saying related, just that there is seemingly work to be done on this in general).
> 
> I'd like us to get to handling these msgspec `Annotated` constraints as I intend to improve on the SQLAlchemy and other ORM DTOs to generate them when possible, e.g., `VARCHAR(16)` would generate `Annotated[str, msgspec.Meta(max_length=16)]` on the transfer model.

I was about to open an issue on it , so this one should cover right?

**Comment by Goldziher** [comment]
@v3ss0n - can you give me an MCVE of the Optional issue you encountered?

**Comment by v3ss0n** [comment]
I will try with the latest and see if it still happening.
