### ISSUE TITLE
Bug: OpenAPI schema incorrectly documents `None` or `Optional` types

### ISSUE THREAD

**Issue by v3ss0n** [litestar-org/litestar#1673]
### Description

If `Mapped[Optional[...]` or `Mapped[ ... | None]` is used , OpenAPI fails to detect fields from DTO and returns  `Unknown Type: null"` as value.

MVCE Included.

### MCVE

```python
from datetime import datetime

from sqlalchemy.orm import Mapped

from litestar import Litestar, post
from litestar.contrib.sqlalchemy.dto import SQLAlchemyDTO

from .my_lib import Base


class User(Base):
    name: Mapped[str | None]
    password: Mapped[str]
    created_at: Mapped[datetime]


UserDTO = SQLAlchemyDTO[User]


@post("/users", dto=UserDTO)
def create_user(data: User) -> User:
    return data


app = Litestar(route_handlers=[create_user])
```

### Steps to reproduce

```bash
1. Go to "http://localhost:8000/schema/swagger"
2. DTO Fields with Optional[] type annotated have `"name": "Unknown Type: null"`

[
...
    "name": "Unknown Type: null", //<-- here
...  }
]

```

### Litestar Version
`litestar = { version = "==2.0.0a7" , extras = ["redis", "cli"] }`

### Platform

- [X] Linux
- [X] Mac
- [X] Windows
- [ ] Other (Please specify in the description above)

**Comment by JacobCoffee** [comment]
Is this also related to what I am seeing?

`age: Annotated[str | None, Field(..., title="Age", description="The age of the cheese.")]`

Will display in the API UIs as
![image](https://github.com/litestar-org/litestar/assets/45884264/fd990dfa-d25d-491d-86ea-06bb3ae043bb)
![image](https://github.com/litestar-org/litestar/assets/45884264/115ce262-2a02-4622-be8b-a898fffa3141)

I think I recall there being a known issue around swagger specifically not handling null well.

It would be nice if we showed the appropriate value

**Comment by v3ss0n** [comment]
> Is this also related to what I am seeing in the response examples?
> 
> `age: Annotated[str | None, Field(..., title="Age", description="The age of the cheese.")]`
> 
> Will display in the API UIs as ![image](https://user-images.githubusercontent.com/45884264/238440211-fd990dfa-d25d-491d-86ea-06bb3ae043bb.png) ![image](https://user-images.githubusercontent.com/45884264/238440397-115ce262-2a02-4622-be8b-a898fffa3141.png)
> 
Yes , that is exactly what happens when Optional is Annotated .

**Comment by v3ss0n** [comment]
Shortened MVCE.

**Comment by JacobCoffee** [comment]
Hi I am finally starting to be freed up - I will work on this in the morning

**Comment by v3ss0n** [comment]
Redoc seems to understand fine :

![image](https://github.com/litestar-org/litestar/assets/419606/8553a18e-4275-4883-afe0-9dd7ddbe190a)

**Comment by v3ss0n** [comment]
I tried upgrading to alpha version but not enough i guess , 
```
        schema = self.get_schema_from_request(request)

        # Note: Fix for Swagger rejection OpenAPI >=3.1
        if not self._dumped_modified_schema:
            schema_copy = copy(schema)
            schema_copy.openapi = "3.0.3"
  ```
  
  This forced openapi ver ?

**Comment by Goldziher** [comment]
Ok, this is an Open API 3.0.3 compat issue. We won't fix it.

**Comment by v3ss0n** [comment]
ok redoc looks fine anyway.
