### ISSUE TITLE
Bug: ImmutableState deep-copies state, disallowing Cython objects in state

### ISSUE THREAD

**Issue by LeckerenSirupwaffeln** [litestar-org/litestar#1674]
### Description

First, in the before startup handler, I define a aiomysql connection pool in the state:
`app_instance.state.pool = await aiomysql.create_pool(...)`

Then I try to use an ImmutableState in a route handler:
`@get("/get_hello_world")
async def get_hello_world(state: ImmutableState) -> dict[str, str]:
  return {"Hello": "World"}`

This sends my browser an error:
> {"status_code":400,"detail":"Validation failed for GET http://127.0.0.1:8000/event_data","extra":[{"key":"state","message":"no default __reduce__ due to non-trivial __cinit__"}]}

This error may imply that we are trying to Pickle a Cython object. Looking through litestar's code I can indeed see that an ImmutableState attempts to deep_copy, which does Pickle. However, looking through the source code of aiomysql I cannot find any hint of Cython code.

I can indeed confirm that the issue is caused by the deep-copy as this code throws the same error as well:
`@get("/get_hello_world")
async def get_hello_world(state: State) -> dict[str, str]:
  state = State(state, deep_copy=True)
  return {"Hello": "World"}`

The mutable` State` works without an issue.

### MCVE

```python
N/A, you would need to connect to a MySQL server with aiomysql.
```

### Steps to reproduce

```bash
1. Create a connecting pool to a MySQL server using aiomysql
2. Put this connection pool in the before startup handler: app_instance.state.pool = ...
3a. Attempt to use ImmutableState as an argument in any route handler
3b. OR attempt to copy the State with deep_copy=True
4. See error
```

### Logs

```bash
2023-05-15 11:11:59 INFO - 2023-05-15 09:11:59,229 - app - app - An exception of type 'no default __reduce__ due to non-trivial __cinit__' has occurred for requested path '/event_data'.
2023-05-15 11:11:59 INFO:     172.25.0.1:60912 - "GET /event_data HTTP/1.1" 500 Internal Server Error
```

### Litestar Version

2.0.0alpha3

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

**Comment by peterschutt** [comment]
Have a look at https://github.com/litestar-org/litestar/pull/1678

In the case of the MVC above, you'd provide a state instance with `deep_copy=False` on app construction and any subsequent copies will honor it.

```py
app = Litestar(route_handlers=[hello_world], on_startup=[set_state], on_shutdown=[close_pool], state=State(deep_copy=False))
```

**Comment by LeckerenSirupwaffeln** [comment]
So issue was asyncio objects could not be pickled, thus were not compatible with deep_copy? 
And now passing deep_copy=False on app construction will prevent the deep-copying, thus preventing the limitation of the Pickling?

And since you guys used deep_copy in the first place, will circumventing it not make the state mutable again?

**Comment by peterschutt** [comment]
> So issue was asyncio objects could not be pickled, thus were not compatible with deep_copy? 

The issue is that _any_ non-picklable object cannot be deep copied - file objects, modules, thread locks, futures etc.

> 
> And now passing deep_copy=False on app construction will prevent the deep-copying, thus preventing the limitation of the Pickling?
> 
> 

Yes

> 
> And since you guys used deep_copy in the first place, will circumventing it not make the state mutable again?

Making something immutable in python is hard. We can make the state mapping _appear_ immutable - but objects within the state mapping cannot be made immutable. I believe the deep copy was in order to defend against this, so that if something within it _is_ modified, it is only modified within the scope of a single request. However, as you've seen, this prevented certain objects from being stored/accessed in state, so we added the `deep_copy` flag as a work around. The state object will still appear immutable, however if you modify the db pool within the state object, those modifications will persist across requests.

Can't have your cake and eat it too I suppose 🤷‍♂️

**Comment by LeckerenSirupwaffeln** [comment]
Understood. I will likely just switch to using State all the time to be extra explicit. Thank you for taking a look, I was more so curious why it was happening than actually having an immutable state
