### ISSUE TITLE
Bug: `URL_ENCODED` route handlers trim trailing zeroes from numerical values even when declared as string

### ISSUE THREAD

**Issue by LonelyVikingMichael** [litestar-org/litestar#1675]
### Description

Route handlers with their media type set to `RequestEncodingType.URL_ENCODED` will trim trailing zeroes from float-like numbers, even if the field is declared as `str`

### MCVE

```python
from dataclasses import dataclass

from starlite import Body, RequestEncodingType, Starlite, post
from starlite.testing import TestClient


@dataclass
class URLEncodedExample:
    amount_as_str: str
    amount_as_float: float


@post()
async def test_handler(data: URLEncodedExample = Body(media_type=RequestEncodingType.URL_ENCODED)) -> dict:
    return data


app = Starlite(route_handlers=[test_handler])

with TestClient(app=app) as client:
    response = client.post(
        "/",
        data="amount_as_str=2.50&amount_as_float=-3.50",
        headers={"Content-Type": "application/x-www-form-urlencoded"},
    )
    assert response.json() == {"amount_as_str": "2.50", "amount_as_float": -3.5}
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Litestar Version

1.51.12

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

**Comment by Goldziher** [comment]
the reason for this is that we are doing the parsing in rust - without actually knowing the expected types at all. we are then modifing the result as required in python. Im afraid there is not way for us to do this at present otherwise.
