### ISSUE TITLE
Bug: Enabling gzip only sends large streaming responses

### ISSUE THREAD

**Issue by LeckerenSirupwaffeln** [litestar-org/litestar#1681]
### Description

Enabling gzip compression causes small streaming responses to be completely ignored and never sent to the client browser.
I have verified that the request headers to specify at the very least:
`Accept-Encoding: gzip`
As can be seen in the logs.

### URL to code causing the issue

https://github.com/LeckerenSirupwaffeln/Litestar_StreamingResponseGzip_Bug

### MCVE

```python
https://github.com/LeckerenSirupwaffeln/Litestar_StreamingResponseGzip_Bug
```

### Steps to reproduce

```bash
1. git clone https://github.com/LeckerenSirupwaffeln/Litestar_StreamingResponseGzip_Bug
2. cd Litestar_StreamingResponseGzip_Bug
3. docker compose up
4. Open your browser
5. Navigate to http://127.0.0.1:8000/event
6. Open developer tools, go to Console
7. Click "Start retrieving data"
8. Observe that only the large arrays of data get received by the client browser. These arrays should have a size of 1000000, while arrays that have a size of 500 do not get printed to the console, and thus do not get received.

Alternatively:
Disable gzip compression in app construction and observe that arrays of size of 500 do get printed to the console as do the arrays of size of 10000000.
```

### Logs

```bash
Request headers:

POST /event HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,nl-NL;q=0.8,nl;q=0.7
Connection: keep-alive
Content-Length: 2
Content-Type: application/json
DNT: 1
Host: 127.0.0.1:8000
Origin: http://127.0.0.1:8000
Referer: http://127.0.0.1:8000/event
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36
sec-ch-ua: "Google Chrome";v="113", "Chromium";v="113", "Not-A.Brand";v="24"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
```

### Litestar Version

2.0.0alpha3

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

**Comment by peterschutt** [comment]
Thanks for the report @LeckerenSirupwaffeln 

When I run `docker compose up` on your example repo I get:

```
failed to solve: process "/bin/sh -c apt-get update && apt-get upgrade && apt-get install -y --no-install-recommends sudo && apt-get install -y --no-install-recommends bash && apt-get install -y --no-install-recommends git && apt-get install -y --no-install-recommends vim && apt-get purge -y --auto-remove && rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 1
```

**Comment by LeckerenSirupwaffeln** [comment]
Hi, peterschutt
1) It is possible that it prompted you on apt-get update && apt-get upgrade, so I made a small commit to include the -y flag this time. Please try again with the new commit.
2) You could have CRLF line-endings due to git. Verify that the line-endings in the file are all LF. 
3) Further I am not sure why this error would occur, I do not have it on my system.

**Comment by provinzkraut** [comment]
@LeckerenSirupwaffeln do you think it would be possible to create a self contained MCVE that does not require docker etc.?

That would make testing on our end a lot easier.

**Comment by provinzkraut** [comment]
I cannot reproduce this with:


```python
from litestar import get, Litestar
from litestar.config.compression import CompressionConfig
from litestar.testing import TestClient


@get(path="/", sync_to_thread=False)
def handler() -> str:
    return "foo"


app = Litestar(
    route_handlers=[handler],
    compression_config=CompressionConfig(
        backend="gzip",
        minimum_size=1,
    ),
)

with TestClient(app=app) as client:
    res = client.get("/")
    assert res.headers.get("content-encoding") == "gzip"

```

Are you sure you have set `minimum_size` to something other than the default value?

**Comment by LeckerenSirupwaffeln** [comment]
Hi provinzkraut, 

1) I have indeed tried to set a different minimum_size, I also do not think the default should cause this bug.
2) Sorry for the non-working Docker, here is the MCVE, took me a while to make because I could not replicate the bug exactly either, but I eventually did:

```
from litestar import Litestar, MediaType, post
from litestar.config.compression import CompressionConfig
from litestar.response_containers import Stream
from litestar.serialization import encode_json

from asyncio import sleep
from pathlib import Path


GLOBAL_SMALL_DICT = {}
for i in range(500):
  GLOBAL_SMALL_DICT[str(i)] = i
  
GLOBAL_LARGE_DICT = {}
for i in range(1000000):
  GLOBAL_LARGE_DICT[str(i)] = i

class SmallDataStreamer:
  def __aiter__(self) -> "DataStreamer":
    return self
  
  async def __anext__(self) -> bytes:
    await sleep(1)
    return encode_json(GLOBAL_SMALL_DICT)
  
class LargeDataStreamer:
  def __aiter__(self) -> "DataStreamer":
    return self
  
  async def __anext__(self) -> bytes:
    await sleep(1)
    return encode_json(GLOBAL_LARGE_DICT)

@post("/raw_small_example", media_type=MediaType.JSON) # Always works.
async def raw_small_example(data: dict[str, str]) -> dict[str, str]:
  return GLOBAL_SMALL_DICT

@post("/raw_large_example", media_type=MediaType.JSON) # Always works.
async def raw_large_example(data: dict[str, str]) -> dict[str, str]:
  return GLOBAL_LARGE_DICT

@post("/stream_small_example", media_type=MediaType.JSON) # Only works when gzip is disabled.
async def stream_small_example(data: dict[str, str]) -> Stream:
  small_data_streamer = SmallDataStreamer()
  return Stream(iterator=small_data_streamer)

@post("/stream_large_example", media_type=MediaType.JSON) # Always works.
async def stream_large_example(data: dict[str, str]) -> Stream:
  large_data_streamer = LargeDataStreamer()
  return Stream(iterator=large_data_streamer)

app = Litestar(
  route_handlers=[raw_small_example, raw_large_example, stream_small_example, stream_large_example],
  compression_config=CompressionConfig(backend="gzip", gzip_compress_level=9),
)
```

How to use this MCVE:

1. Set it up to be running locally.
2. `curl -X POST -H 'Accept-encoding: gzip' --data '{\"data\": \"\"}' 127.0.0.1:8000/raw_large_example --compressed`
3. `curl -X POST -H 'Accept-encoding: gzip' --data '{\"data\": \"\"}' 127.0.0.1:8000/stream_large_example --compressed`
4. After getting the data once: CTRL+C
5. `curl -X POST -H 'Accept-encoding: gzip' --data '{\"data\": \"\"}' 127.0.0.1:8000/raw_small_example --compressed`
6. `curl -X POST -H 'Accept-encoding: gzip' --data '{\"data\": \"\"}' 127.0.0.1:8000/stream_small_example --compressed`
7. Notice you never get the data within a reasonable time.
8. Now comment-out gzip compression and repeat steps 1 to 7, now you always get the data within a reasonable time after `POST` to `127.0.0.1:8000/stream_small_example`.

**Comment by peterschutt** [comment]
Can you try installing from https://github.com/litestar-org/litestar/tree/1681-gzip-small-responses and see if that has solved the issue for you @LeckerenSirupwaffeln

**Comment by peterschutt** [comment]
@all-contributors add @LeckerenSirupwaffeln for bug

**Comment by LeckerenSirupwaffeln** [comment]
Hi, thank you all for your hard and swift work. I can verify indeed that the curl now works correctly. I can also verify the browser correctly gets the small stream of data as expected. All of this after building from main, which was version:
 ```Successfully installed litestar-2.0.0a7 ```
