### ISSUE TITLE
Docs: Update sphinx-mermaid config for theming 

### ISSUE THREAD

**Issue by JacobCoffee** [litestar-org/litestar#1687]
### Summary

Currently some mermaid diagrams generated by `sphinx-mermaid` are hard to read/see.

You can configure this though -> https://github.com/mgaitan/sphinxcontrib-mermaid#config-values

We need to set something like

```py
mermaid_params = ["--theme", "neutral", "--backgroundColor", "transparent"] # or backgroundColor White if themeing doesnt fix?
mermaid_output_format = "svg" # or png, or keep raw
```

<a href="https://polar.sh/litestar-org/litestar/issues/1687">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1687/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1687/pledge.svg">
</picture>
</a>

**Comment by JacobCoffee** [comment]
https://github.com/mermaid-js/mermaid-cli would be required in the build process and I'm not sure that's something we want to do, but 
![image](https://github.com/litestar-org/litestar/assets/45884264/9cb871f7-7e0f-4693-afec-2d8cfbdce2a2)
 is a pretty bad UX

**Comment by JacobCoffee** [comment]
@provinzkraut what do you think the best approach here is?

**Comment by JacobCoffee** [comment]
In testing, I haven't found a way to do this customization without mcli. 😞 Open for ideas

**Comment by therealzanfar** [comment]
The following CSS rule seems to work well as a "hack":

```
html[data-theme=dark] .mermaid svg {
    background-color: white;
    padding: 1em;
}
```

**Comment by JacobCoffee** [comment]
We should be able to add this to https://github.com/litestar-org/litestar/blob/main/docs/_static/style.css @therealzanfar, if you want to open a PR?

**Comment by Goldziher** [comment]
> The following CSS rule seems to work well as a "hack":
> 
> ```
> html[data-theme=dark] .mermaid svg {
>     background-color: white;
>     padding: 1em;
> }
> ```

Yes, this is the way to go. It's good that sphinx follows standard practices. 

I'd think you should do it in the litestar sphinx theme repo.
