### ISSUE TITLE
Update Channels documentation with tutorial

### ISSUE THREAD

**Issue by keinagae** [litestar-org/litestar#1692]
### Summary

I am working on channels but atm unable to understand a few things like once have connected to to ws how can i make users join a channels and can they be private and if they private how can i send message from out side 

<a href="https://polar.sh/litestar-org/litestar/issues/1692">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1692/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1692/pledge.svg">
</picture>
</a>

**Comment by JacobCoffee** [comment]
I believe we can create a nice tutorial for this and put it in this section: https://docs.litestar.dev/dev/tutorials/index.html
