### ISSUE TITLE
Docs: template autoescaping behavior

### ISSUE THREAD

**Issue by zerosym** [litestar-org/litestar#1699]
### Summary

I appreciate this framework having a built-in choice between Jinja and Mako.  The documentation however makes no mention of a significant difference in the Litestar behavior between the two -- that using the Jinja engine will autoescape for you, whereas Mako will not.

**Comment by zerosym** [comment]
Or just make the functionality match and autoescape Mako by default, which is the expected behavior.

The instantiation here:
https://github.com/litestar-org/litestar/blob/4c1c9c486d4f50027faadec35728e5c51edf1808/litestar/contrib/mako.py#L73

Adding the following kwarg:
```python
 default_filters=['h']
```

Relevant Mako docs:
https://docs.makotemplates.org/en/latest/filtering.html#filtering-default-filters

**Comment by peterschutt** [comment]
Is #1699 what you are after @zerosym?

**Comment by zerosym** [comment]
Yes, thanks.
