### ISSUE TITLE
Enhancement: Support Pydantic v2

### ISSUE THREAD

**Issue by JacobCoffee** [litestar-org/litestar#1708]
### Summary

**Update**: Pydantic v2.0 is available, and Polyfactory has been adjusted to reflect that. We can move ahead with this repos updates.

---

Pydantic v2 alphas are available. I think it would be best to begin this work now and collaborate with @samuelcolvin and his team about potential issues, enhancements, etc. while they are in alpha.

[2.0a4](https://github.com/pydantic/pydantic/releases/tag/v2.0a4) is the latest.

### Unresolved questions

1. Should this be done during the Litestar v2 milestone, or as a future release? 
2. Polyfactory needs to be updated as the test suite has it as a dependency, but there are some blockers

### Other

[Migration Guide](https://docs.pydantic.dev/dev-v2/migration/)
[Blog Post](https://docs.pydantic.dev/latest/blog/pydantic-v2-alpha/)

may also be helpful for reference:

- Sebastián with FastAPI https://github.com/tiangolo/fastapi/pull/9500/
- Vitaliy with Django Ninja https://github.com/vitalik/django-ninja/issues/733
- Migration tool https://github.com/pydantic/pydantic/issues/5013

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/1708">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1708/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1708/pledge.svg">
</picture>
</a>

**Comment by JacobCoffee** [comment]
Should this be done during the Litestar v2 milestone, or as a future release?

**Comment by peterschutt** [comment]
Absolutely, have you tried? How much compatibility is there b/w 1 and 2 anyway?

**Comment by JacobCoffee** [comment]
I have started a little branch to test things; I believe the root `tests/` and other places that use [polyfactory](https://polyfactory.litestar.dev/) will need to be updated first or in tandem.

**Comment by JacobCoffee** [comment]
Just an update for anyone watching, the required Polyfactory changes were done in https://github.com/litestar-org/polyfactory/releases/tag/v2.3.0. I believe we can now move forward with the Litestar repo changes.

**Comment by JacobCoffee** [comment]
It looks like the migration tool is available :)

https://github.com/pydantic/bump-pydantic

**Comment by Goldziher** [comment]
> It looks like the migration tool is available :)
> 
> https://github.com/pydantic/bump-pydantic

this can be used for our examples and maybe tests too.

**Comment by JacobCoffee** [comment]
I feel like i may be hitting a bug on the `bump-pydantic` side, or I am doing something wrong, but it refuses to run in some dirs under `test/`.

```py
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/user/.pyenv/versions/3.11.3/lib/python3.11/site-packages/bump_pydantic/main.py:75 in    │
│ main                                                                                             │
│                                                                                                  │
│    72 │   │   │   │   for key, value in local_scratch.items():                                   │
│    73 │   │   │   │   │   scratch.setdefault(key, value).update(value)                           │
│    74 │                                                                                          │
│ ❱  75 │   find_base_model(scratch)                                                               │
│    76 │                                                                                          │
│    77 │   start_time = time.time()                                                               │
│    78                                                                                            │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │                 console = <console width=123 ColorSystem.TRUECOLOR>                          │ │
│ │                    diff = False                                                              │ │
│ │                 disable = []                                                                 │ │
│ │                   files = []                                                                 │ │
│ │               files_str = []                                                                 │ │
│ │                log_file = None                                                               │ │
│ │        metadata_manager = <libcst.metadata.full_repo_manager.FullRepoManager object at       │ │
│ │                           0x7faebe48e0d0>                                                    │ │
│ │                 package = PosixPath('tests/logging_config')                                  │ │
│ │ partial_visit_class_def = functools.partial(<function visit_class_def at 0x7faebde46ca0>,    │ │
│ │                           <libcst.metadata.full_repo_manager.FullRepoManager object at       │ │
│ │                           0x7faebe48e0d0>, PosixPath('tests/logging_config'))                │ │
│ │                    pool = <multiprocessing.pool.Pool state=TERMINATE pool_size=24>           │ │
│ │                progress = <rich.progress.Progress object at 0x7faebd9c9950>                  │ │
│ │               providers = {                                                                  │ │
│ │                           │   <class 'libcst.metadata.scope_provider.ScopeProvider'>,        │ │
│ │                           │   <class                                                         │ │
│ │                           'libcst.metadata.name_provider.FullyQualifiedNameProvider'>        │ │
│ │                           }                                                                  │ │
│ │                 scratch = {}                                                                 │ │
│ │                    task = 0                                                                  │ │
│ │                 version = None                                                               │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /home/user/.pyenv/versions/3.11.3/lib/python3.11/site-packages/bump_pydantic/markers/find_bas │
│ e_model.py:22 in find_base_model                                                                 │
│                                                                                                  │
│   19                                                                                             │
│   20                                                                                             │
│   21 def find_base_model(scratch: dict[str, Any]) -> None:                                       │
│ ❱ 22 │   classes = scratch[ClassDefVisitor.CONTEXT_KEY]                                          │
│   23 │   revert_classes = revert_dictionary(classes)                                             │
│   24 │   base_model_set: set[str] = set()                                                        │
│   25                                                                                             │
│                                                                                                  │
│ ╭─── locals ───╮                                                                                 │
│ │ scratch = {} │                                                                                 │
│ ╰──────────────╯                                                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
KeyError: 'class_def_visitor'
```

**Comment by JacobCoffee** [comment]
Without someone else confirming, though, I am too nervous to bug any of the Pydantic guys just yet.

**Comment by JacobCoffee** [comment]
In testing - specifically when i go dir-by-dir, i hit issues in the following places:

- `tests/logging_config/`
- `tests/conftest.py`
- `tests/unit/` (Gives me a very long multi-thousand line error, the bottom of which is here: https://paste.pythondiscord.com/ubezoralew)
These dirs worked just fine:

- `tests/examples/`
- `tests/e2e/`

**Comment by samuelcolvin** [comment]
Cc @Kludex.

**Comment by Kludex** [comment]
> I feel like i may be hitting a bug on the `bump-pydantic` side, or I am doing something wrong, but it refuses to run in some dirs under `test/`.
> 
> ```py
> ╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
> │ /home/user/.pyenv/versions/3.11.3/lib/python3.11/site-packages/bump_pydantic/main.py:75 in    │
> │ main                                                                                             │
> │                                                                                                  │
> │    72 │   │   │   │   for key, value in local_scratch.items():                                   │
> │    73 │   │   │   │   │   scratch.setdefault(key, value).update(value)                           │
> │    74 │                                                                                          │
> │ ❱  75 │   find_base_model(scratch)                                                               │
> │    76 │                                                                                          │
> │    77 │   start_time = time.time()                                                               │
> │    78                                                                                            │
> │                                                                                                  │
> │ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
> │ │                 console = <console width=123 ColorSystem.TRUECOLOR>                          │ │
> │ │                    diff = False                                                              │ │
> │ │                 disable = []                                                                 │ │
> │ │                   files = []                                                                 │ │
> │ │               files_str = []                                                                 │ │
> │ │                log_file = None                                                               │ │
> │ │        metadata_manager = <libcst.metadata.full_repo_manager.FullRepoManager object at       │ │
> │ │                           0x7faebe48e0d0>                                                    │ │
> │ │                 package = PosixPath('tests/logging_config')                                  │ │
> │ │ partial_visit_class_def = functools.partial(<function visit_class_def at 0x7faebde46ca0>,    │ │
> │ │                           <libcst.metadata.full_repo_manager.FullRepoManager object at       │ │
> │ │                           0x7faebe48e0d0>, PosixPath('tests/logging_config'))                │ │
> │ │                    pool = <multiprocessing.pool.Pool state=TERMINATE pool_size=24>           │ │
> │ │                progress = <rich.progress.Progress object at 0x7faebd9c9950>                  │ │
> │ │               providers = {                                                                  │ │
> │ │                           │   <class 'libcst.metadata.scope_provider.ScopeProvider'>,        │ │
> │ │                           │   <class                                                         │ │
> │ │                           'libcst.metadata.name_provider.FullyQualifiedNameProvider'>        │ │
> │ │                           }                                                                  │ │
> │ │                 scratch = {}                                                                 │ │
> │ │                    task = 0                                                                  │ │
> │ │                 version = None                                                               │ │
> │ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
> │                                                                                                  │
> │ /home/user/.pyenv/versions/3.11.3/lib/python3.11/site-packages/bump_pydantic/markers/find_bas │
> │ e_model.py:22 in find_base_model                                                                 │
> │                                                                                                  │
> │   19                                                                                             │
> │   20                                                                                             │
> │   21 def find_base_model(scratch: dict[str, Any]) -> None:                                       │
> │ ❱ 22 │   classes = scratch[ClassDefVisitor.CONTEXT_KEY]                                          │
> │   23 │   revert_classes = revert_dictionary(classes)                                             │
> │   24 │   base_model_set: set[str] = set()                                                        │
> │   25                                                                                             │
> │                                                                                                  │
> │ ╭─── locals ───╮                                                                                 │
> │ │ scratch = {} │                                                                                 │
> │ ╰──────────────╯                                                                                 │
> ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
> KeyError: 'class_def_visitor'
> ```

How did you run bump-pydantic?

**Comment by JacobCoffee** [comment]
Hi @Kludex 😃 

I did this by
```py
pip install bump-pydantic
bump-pydantic litestar/
bump-pydantic tests/ (or any of the combinations listed above e.g. `bump-pydantic tests/examples/`)
```

**Comment by Kludex** [comment]
I'm going to check. Thanks 👍

**Comment by Kludex** [comment]
It looks like LibCST cannot handle the `test_converter.py` file... I'm not sure what is wrong with that file, but it fails with any visitor.

I'm modifying the `bump-pydantic` in a way that it doesn't stop execution on those cases.

**Comment by provinzkraut** [comment]
@Kludex 

> I'm not sure what is wrong with that file, but it fails with any visitor.

I have actually seen this one before. It's an issue with string literal concatenation. An otherwise empty file with ~300 lines of implicitly concatenated strings will also cause the crash.

**Comment by Kludex** [comment]
Ah, is this one: https://github.com/Instagram/LibCST/issues/409

**Comment by provinzkraut** [comment]
Yeah, that one. I looked into it about a year ago but then decided it was easier to just work around it because the issue seems to be buried quite deep inside libcst :grimacing: 

@JacobCoffee We should be able to work around it by either making it two strings that are explicitly concatenated, or simply moving that stuff to a file (which would be preferable IMO).

**Comment by Goldziher** [comment]
This is finished on main
