### ISSUE TITLE
Bug: Models created from UUIDBase cause invalid migrations

### ISSUE THREAD

**Issue by patrickarmengol** [litestar-org/litestar#1714]
### Description

From what I can tell, the recent change from the sqlalchemy `Base` to the new `UUIDBase` is causing issues with my generated alembic migration scripts, specifically with the `id` columns. 

The old models would define the column as follows:

```python
sa.Column("id", litestar.contrib.sqlalchemy.types.GUID(), nullable=False),
```

Now, with `UUIDBase`, I'm getting the following:

```python
sa.Column('id', litestar.contrib.sqlalchemy.types.GUID(length=16), nullable=False),
```

This errors out on runtime as `length` is not a valid param for `GUID`. 

### MCVE

```python
from litestar.contrib.sqlalchemy.base import UUIDBase

class Whatever(UUIDBase):
    name: Mapped[str] = mapped_column(String(), unique=True)
```

### Steps to reproduce

```bash
1. Define a sqlalchemy model that extends `UUIDBase`
2. Setup Alembic migrations (also add `import litestar.contrib.sqlalchemy.types` to `script.py.mako`)
3. Autogenerate a revision for the whatever table: `alembic revision -m "create whatever table" --autogenerate`
4. Check the id column of the whatever table in the generated migration script.
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Litestar Version

2.0.0a7

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

**Comment by cofin** [comment]
Hey, @patrickarmengol, 

To use the new UUID columns with alembic, you'll need to make sure that your migrations are aware of the new type.

Here is what my `script.py.mako` template looks like in a project that I'm currently using the UUID models on:
```python
"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

"""
import sqlalchemy as sa
from alembic import op

from litestar.contrib.sqlalchemy.types import GUID

${imports if imports else ""}

sa.GUID = GUID 

# revision identifiers, used by Alembic.
revision = ${repr(up_revision)}
down_revision = ${repr(down_revision)}
branch_labels = ${repr(branch_labels)}
depends_on = ${repr(depends_on)}


def upgrade():
    ${upgrades if upgrades else "pass"}


def downgrade():
    ${downgrades if downgrades else "pass"}

```

**Comment by cofin** [comment]
Could you also mention which database backend you are using?

**Comment by patrickarmengol** [comment]
Thanks for the quick reply. I followed your guidance for `script.py.mako`, but the `id` column is still being generated as:

```python
sa.Column('id', litestar.contrib.sqlalchemy.types.GUID(length=16), nullable=False),
```

instead of:

```python
sa.Column('id', sa.GUID(), nullable=False),
```

like in your example at https://github.com/cofin/litestar-fullstack/blob/81d33439a87d44ab1dcd93b8d824f83ef37f0658/src/app/lib/db/migrations/versions/2023-05-02_user_teams_8e1731f221c4.py#L33

Perhaps I'm missing a preliminary step? or maybe we are on different versions of sqla?

I'm using postgres+asyncpg, with sqlalchemy v2.0.11 and litestar v2.0.0a7.

**Comment by patrickarmengol** [comment]
I'm working out of my personal project atm, so let me make a public MCVE project for testing.

**Comment by patrickarmengol** [comment]
Here is a simple example project: https://github.com/patrickarmengol/guidstuff

**Comment by cofin** [comment]
Thanks for the example project.  I was able to reproduce it with this repo.  

I think this is due to the enhancement that was put in last week to support binary GUIDs and Oracle databases, and it's just not made it into an official alpha release yet. 

If you look at the `litestar/contrib/sqlalchemy/types.py` that is installed into the `.venv`, you'll notice that it's different than what's in `main`.  I'm not familiar enough with hatch to tell you what to update, but in `poetry`, if you set your `litestar` dependency to this, it'll install from main instead of the last packaged alpha.
```toml
litestar = {git = "https://github.com/litestar-org/litestar.git", branch = "main", extras = ["jwt", 'cli', 'redis', 'jinja2', 'sqlalchemy', 'structlog']}
```

**Comment by patrickarmengol** [comment]
> @patrickarmengol Here is the PR that actually modified the `__init__` method last week. [ #1676 ](https://github.com/litestar-org/litestar/pull/1676)

Oh! It's already fixed. I should've looked more thoroughly before opening this ticket. I'll close this issue out then. Thanks for your help and patience.

**Comment by patrickarmengol** [comment]
Ok, so I did some testing with the main branch of litestar. The generated line is identical to what I have been getting. See https://github.com/patrickarmengol/guidstuff/blob/master/migrations/versions/3e4cd18cb2a2_create_whatever_table.py

```
sa.Column('id', litestar.contrib.sqlalchemy.types.GUID(length=16), nullable=False),
```

Ignoring the length bit, I think perhaps my actual issue might be more surface level. Like a misconfiguration or missed step. @cofin how are your migration files generated with `sa.GUID()` instead of the full `litestar.contrib.sqlalchemy.types.GUID()` in those columns? I've been looking through the fullstack example project, but can't find anything explicitly affecting it.

**Comment by cofin** [comment]
@patrickarmengol, I had a bit to look into this today.  Here's what I've come up with.  Can you test this to see if it works for you?

In your `env.py` for alembic, can you make the `do_run_migrations` function look like this?:
```python
def do_run_migrations(connection: Connection) -> None:
    context.configure(connection=connection, target_metadata=target_metadata, compare_type=True, user_module_prefix="sa.")

    with context.begin_transaction():
        context.run_migrations()
```

I made this one change, deleted your existing migration file and regenerated.  It had the `sa.` prefix added in the migrations once I made these changes.

```python

from litestar.contrib.sqlalchemy.types import GUID
...

sa.GUID = GUID
 

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatever',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.GUID(length=16), nullable=False),
    ...
    )
   ```

**Comment by cofin** [comment]
Also, I forgot to mention, the `length` attribute you see should be fine in this case.  I was able to apply these migrations without any problem.

**Comment by patrickarmengol** [comment]
I tested it out and it generated the same script. It ran fine (though pyright yells at me about "unknown member of module" and I'm not entirely sure why it doesn't fail at runtime with the length arg) and the table in the db looks fine. 

I'll roll with this for now. Thanks a bunch.
