### ISSUE TITLE
Enhancement: Make litestar CLI debuggable

### ISSUE THREAD

**Issue by MoBoo** [litestar-org/litestar#1715]
### Summary

Currently the way to debug a litestar app is to include
```
if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app)
```
in your `app.py` file and then debug this `app.py` file.
**Debugging the litestar app using the litestar cli (`litestar run`) does not work.** (See example below)

Atleast updating the docs to include a section on debugging (e.g. like [FastAPI](https://fastapi.tiangolo.com/tutorial/debugging/)) would be beneficial.

### Basic Example

Trying to debug an litestar app using the litestar CLI by running `litestar run` does not work. Breakpoints are ignored.

Example using PyCharm:

[Example using PyCharm](https://github.com/litestar-org/litestar/assets/28530702/077a8039-b2cf-499c-9816-d9eff1cf4123)

**Comment by zerosym** [comment]
No idea if this will help you but I had success with VSCode using `debugpy` inside a startup hook.  This was part of a docker compose setup, exposing port 5678 for the debugger to attach to.

For example:
```python
def setup_debugger(app: Litestar) -> None:
    if DEBUG:
        import debugpy
        debugpy.listen(("0.0.0.0", 5678))

app = Litestar(on_startup=[setup_debugger], ...)
```

There may be caveats to this approach (such as with Django, where you need a conditional to check for hot reloads), but I did not end up spending that much time playing with it.
