### ISSUE TITLE
Enhancement: DataDTO.create_instance() accept kwargs for initializing nested fields

### ISSUE THREAD

**Issue by MoBoo** [litestar-org/litestar#1727]
### Summary

Allow [DataDTO](https://docs.litestar.dev/dev/reference/dto/factory/index.html#litestar.dto.factory.DTOData) (`create_instance` and `update_instance`) to receive data for nested fields/models.

A possible notation could use `__` (double underscores) to define a nested attribute: `.create_instance(id=uuid.uuid4(), address__id=uuid.uuid4())` where `address__id` would refer to the `id` attribute of the nested model `address`. (see MCVE below)
This is in line with the Django ORM notation (https://docs.djangoproject.com/en/4.2/topics/db/queries/#lookups-that-span-relationships)

See also: https://discord.com/channels/919193495116337154/1110854577575698463
Related: https://github.com/litestar-org/litestar/issues/1726

### Basic Example

```
from dataclasses import dataclass
import uuid

from litestar import Litestar, post
from litestar.dto.factory import DTOConfig, DTOData
from litestar.dto.factory.stdlib import DataclassDTO

@dataclass
class Address:
    id: uuid.UUID
    street: str
    city: str

@dataclass
class Person:
    id: uuid.UUID
    name: str
    email: str
    address: Address

class WriteDTO(DataclassDTO[Person]):
    config = DTOConfig(exclude={"id", "address.id"})

@post("/person", dto=WriteDTO, return_dto=None, sync_to_thread=False)
def create_person(data: DTOData[Person]) -> str:
    inst = data.create_instance(id=uuid.uuid4(), address__id=uuid.uuid4())
    return "Success"

app = Litestar([create_person])
```

**Comment by peterschutt** [comment]
> A possible notation could use `__` (double underscores) to define a nested attribute: `.create_instance(id=uuid.uuid4(), address__id=uuid.uuid4())` where `address__id` would refer to the `id` attribute of the nested model `address`. (see MCVE below)
> This is in line with the Django ORM notation (https://docs.djangoproject.com/en/4.2/topics/db/queries/#lookups-that-span-relationships)

Makes sense to use a notation that many will already be familiar with - wonder if any other @litestar-org/maintainers have any opinion on this?
