### ISSUE TITLE
Enhancement: Terminal Output Debug Mode

### ISSUE THREAD

**Issue by flyboy1565** [litestar-org/litestar#1735]
### Summary

If we're in debug mode, show the traceback, else just exit with the return code from the subprocess?
Also should add a notification that when not in debug mode to tell the user to turn on debug for subprocess message. 

### Basic Example

Using Litestar app from app:app
┌──────────────────┬──────────────────────┐
│ Litestar version │ 2.0.0                │
│ Debug mode       │ Disabled             │
│ CORS             │ Disabled             │
│ CSRF             │ Disabled             │
│ OpenAPI          │ Enabled path=/schema │
│ Compression      │ Disabled             │
└──────────────────┴──────────────────────┘
Starting server process ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
INFO:     Started server process [48532]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 98] error while attempting to bind on address ('127.0.0.1', 8000): address already in use
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.

<a href="https://polar.sh/litestar-org/litestar/issues/1735">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1735/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1735/pledge.svg">
</picture>
</a>

**Comment by peterschutt** [comment]
To clarify, you are asking for the full tb only to be displayed if in debug mode, otherwise just the single line server error log message?

>  Also should add a notification that when not in debug mode to tell the user to turn on debug for subprocess message.

So in the example given, there would be another line `WARNING: Not in debug mode. ...`

**Comment by JacobCoffee** [comment]
Relevant discord discussion: https://discord.com/channels/919193495116337154/919193495690936353/1111354239336337438
