### ISSUE TITLE
Enhancement: Make Pydantic exception keys more verbose

### ISSUE THREAD

**Issue by rseeley** [litestar-org/litestar#1736]
### Summary

To add clarity and avoid confusion when there are validation errors when using nested Pydantic models for input, it would be helpful to include the full `loc` path instead of just the child's key.

### Basic Example

```python
from litestar import Controller
from pydantic import BaseModel, ValidationError


class Child(BaseModel):
    my_value: str


class Parent(BaseModel):
    child: Child


class SomeController(Controller):
    @post('/some-route')
    def some_route(self, data: Parent) -> Parent:
        return data
```

The following request:

```bash
http POST localhost:8000/some-route child:='{}'
```
results in the following response:
```json
{
  "status_code": 400,
  "detail": "Validation failed for POST http://localhost:8000/some-route",
  "extra": [
    {
      "key": "my_value",
      "message": "field required"
    }
  ]
}
```

This is a bit confusing because it makes it seem like `my_value` is a `Parent`-level value, not a `Child`-level value. It may be helpful if the key were `child.my_value` (or some other similar solution), like:

```json
{
  "status_code": 400,
  "detail": "Validation failed for POST http://localhost:8000/some-route",
  "extra": [
    {
      "key": "child.my_value",
      "message": "field required"
    }
  ]
}
```

<a href="https://polar.sh/litestar-org/litestar/issues/1736">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1736/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1736/pledge.svg">
</picture>
</a>

**Comment by rseeley** [comment]
I'd be happy to take this on if it's something the team finds valuable.

**Comment by peterschutt** [comment]
Hey, cheers for issue and offer to assist!

I did start looking before I read your latest message - so I have some work which I've pushed up to [a branch](https://github.com/litestar-org/litestar/tree/1736-client-error-key). You can cherry pick from that, or PR into it or whatever you'd prefer if you'd like to take it from here.

When writing the test - I noticed that it doesn't look like we are actually testing against the attrs sig model when the test parametrization suggests we should. So the first commit I've made also adds checking for that. I'm not sure what is going on though ([example](https://github.com/litestar-org/litestar/actions/runs/5085277889/jobs/9138569058?pr=1738#step:9:746)).

That aside, I believe the effort is to keep the error messages as consistent as we can between signature model backend types, but I don't think we should sacrifice specificity in the pydantic backend case if we are unable to replicate it with the attrs backend for whatever reason.

**Comment by Goldziher** [comment]
> Hey, cheers for issue and offer to assist!
> 
> I did start looking before I read your latest message - so I have some work which I've pushed up to [a branch](https://github.com/litestar-org/litestar/tree/1736-client-error-key). You can cherry pick from that, or PR into it or whatever you'd prefer if you'd like to take it from here.
> 
> When writing the test - I noticed that it doesn't look like we are actually testing against the attrs sig model when the test parametrization suggests we should. So the first commit I've made also adds checking for that. I'm not sure what is going on though ([example](https://github.com/litestar-org/litestar/actions/runs/5085432308/jobs/9138890751?pr=1738#step:9:685)).
> 
> That aside, I believe the effort is to keep the error messages as consistent as we can between signature model backend types, but I don't think we should sacrifice specificity in the pydantic backend case if we are unable to replicate it with the attrs backend for whatever reason.

We need to keep it consistent. The point is to not expose the underlying implementation.
