### ISSUE TITLE
Docs: Oxford comma

### ISSUE THREAD

**Issue by patrickarmengol** [litestar-org/litestar#1737]
### Summary

Hello! I know this can be a contentious issue, but as a member of the **grammar police**, I'd like to propose the standardization of use of the glorious Oxford comma (serial comma) in the docs. 

Reading through the docs can be quite jarring when you find inconsistencies in comma usage, like the first two lines of features in https://docs.litestar.dev/dev/usage/contrib/sqlalchemy.html#features

We could sweep through the docs to include the commas where they should be. We should also add some guidance in the contribution guidelines. 

### Tracking
- [x] add commas to docs
- [ ] add commas to docstrings

<a href="https://polar.sh/litestar-org/litestar/issues/1737">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1737/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1737/pledge.svg">
</picture>
</a>

**Comment by peterschutt** [comment]
Any consistency improvements for the docs would be warmly welcomed from me.

**Comment by provinzkraut** [comment]
Completed in #1766
