### ISSUE TITLE
Bug: OpenApi generation for `Dict[str, X]`

### ISSUE THREAD

**Issue by gsakkis** [litestar-org/litestar#1795]
### Description

The generated OpenApi schema for `Dict[str, X]` ignores `X`: for example `Dict[str, int]` generates just 
`{"type": "object"}` 
instead of 
`{"type": "object", "additionalProperties": { "type": "integer" }}`. 

In comparison `List[X]` generates the correct schema 
`{"items": {"type": "integer"}, "type": "array"}` \
instead of just 
`{"type": "array"}`

### Litestar Version

Main branch

### Platform

- [ ] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

**Comment by peterschutt** [comment]
Thanks for the report!

The behavior can be observed in our [hello-world](https://github.com/litestar-org/litestar-hello-world) app too:

![image](https://github.com/litestar-org/litestar/assets/20659309/c15cdf96-5789-448e-b416-9265ff50b7c4)

PRs welcome!
