### ISSUE TITLE
Enhancement: Ability to reuse DTOConfig(s) in other DTOConfigs

### ISSUE THREAD

**Issue by floxay** [litestar-org/litestar#1796]
### Summary

It would be nice if there was a way to reuse one or more `DTOConfig`(s) when creating new `DTOConfig` instances.

### Basic Example
The base for this example is from: https://docs.litestar.dev/dev/tutorials/dto-tutorial/03-nested-collection-exclude.html
```py
@dataclass
class Coordinate:
    long: float
    lat: float
    secret_field: str

@dataclass
class Address:
    street: str
    city: str
    country: str
    coords: Coordinate

@dataclass
class Person:
    name: str
    age: int
    email: str
    address: Address
    children: list[Person]
    current_coords: Coordinate

coord_config = DTOConfig(exclude={"secret_field"})
person_config = DTOConfig(exclude={"email", "address.street", "children.0.email", "children.0.address"}, config_map={"current_coords": coord_config})
```
Here `person_config.exclude` would become `{"email", "address.street", "children.0.email", "children.0.address", "current_coords.secret_field"}`

It would also be nice if `config_map` would accept a type as key and apply the specified config for all nested fields with that type, recursively.

### Drawbacks and Impact

Since this complicates the way excluded fields are created unsure how this and https://github.com/litestar-org/litestar/issues/1588 should behave as `include` might further complicate this process.

<a href="https://polar.sh/litestar-org/litestar/issues/1796">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1796/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1796/pledge.svg">
</picture>
</a>

**Comment by Goldziher** [comment]
This issue seems redundant to me and it just adds complexity and makes the API cumbursum. 

A user can easily share fields by declaring sets and sharing them between configs etc. An even better pattern is to create factory functions. And if all of this is not sufficent - a user can subclass the configs and create their own variation. I do not see this feature as something we should add. 

Can we close this?
