### ISSUE TITLE
Enhancement: DTO Support for Pagination and more collection types such as OffsetPagination

### ISSUE THREAD

**Issue by v3ss0n** [litestar-org/litestar#1798]
#### Background and Motivations :
During the development of my project, https://github.com/v3ss0n/scrumlog, I have been exclusively using available features from DTOs, repositories, and services, avoiding hand-written schemas. This approach has allowed me to test and push the capabilities of DTOs in real-world use cases.

However, I have faced a few limitations when trying to support **paginations** using DTOs. The main problems are that DTOs only allow simple collections of model types, and they cannot use paginators like OffsetPagination.

To address these limitations, I propose to support more complex collections such as `OffsetPagination`.

Here's a basic example of how this approach might work:
```py
async def filter_by_project_type(self, project_type: str, page: int, offset: int) -> OffsetPagination[ReadDTO]:
    result, count = await self.list_and_count(CollectionFilter(field_name="project_type", values=[project_type]))
    return OffsetPagination(
        items=cast(list[ReadDTO], result),
        limit=20,
        offset=offset,
        total=count,
    )
 ```
By supporting returns such as `OffsetPagination` : we can support paginators, making DTO more powerful.

```
### Drawbacks and Impact

_No response_

### Unresolved questions

_No response_

**Comment by peterschutt** [comment]
I assume that is is a route handler in your example? I think the pattern we'd be trying to support would be along the lines of this:

```py
@get(return_dto=ReturnDTO)
async def filter_by_project_type(self, project_type: str, page: int, offset: int) -> OffsetPagination[DataType]:
    result, count = await self.list_and_count(CollectionFilter(field_name="project_type", values=[project_type]))
    return OffsetPagination(
        items=cast(list[DataType], result),
        limit=20,
        offset=offset,
        total=count,
    )
```

The difference being that it wouldn't be the DTO that is returned from the handler, it would just be a list of your data model type, and the DTO would interact with the `OffsetPagination` type behind the scenes.

**Comment by v3ss0n** [comment]
Awesome!
