### ISSUE TITLE
DTO: OpenAPI redundant duplicate schemas

### ISSUE THREAD

**Issue by peterschutt** [litestar-org/litestar#1800]
Code such as:

```py
from dataclasses import dataclass
from litestar import Litestar, post
from litestar.dto.factory.stdlib import DataclassDTO

@dataclass
class Person:
    name: str
    age: int

class PersonDTO(DataclassDTO[Person]):
    pass

@post("/person", dto=PersonDTO)
def create_person(data: Person) -> Person:
    return data

app = Litestar([create_person])
```

Generates

![image](https://github.com/litestar-org/litestar/assets/20659309/b69b3f30-63dc-44a3-a7fa-cf3618e1250d)

In general, if there would be no difference between the Structs generated for multiple applications of a DTO type, then we should try to cache and reuse them. There would be no difference between the generated structs when all of the `TransferFieldDefinition`s generated were equal between the two.

<a href="https://polar.sh/litestar-org/litestar/issues/1800">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1800/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1800/pledge.svg">
</picture>
</a>

**Comment by Goldziher** [comment]
This is handled - 

Scheme names are now normalized and will not include random hex numbers unless a collision is impossible to avoid in more readable ways (read - you will need to define a handler with the same name at least 3 times, and use identical models + dtos on it).
