### ISSUE TITLE
Bug: Controller inheritance

### ISSUE THREAD

**Issue by gsakkis** [litestar-org/litestar#1808]
### Description

Inheriting route handlers from a base Controller doesn't work as expected, looks like the latest registered controller overwrites the previous ones.

### MCVE

```python
from litestar import Controller, Litestar, get


class BaseController(Controller):
    @get("/{id:int}")
    async def test_get(self, id: int) -> str:
        return f"{self.__class__.__name__} {id}"


class FooController(BaseController):
    path = "/foo"


class BarController(BaseController):
    path = "/bar"


app = Litestar(route_handlers=[FooController, BarController])
```

### Steps to reproduce

```bash
$ curl localhost:8000/bar/42
BarController 42

$ curl localhost:8000/foo/42
BarController 42
```
```


### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Litestar Version

Main branch

### Platform

- [ ] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

<a href="https://polar.sh/litestar-org/litestar/issues/1808">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1808/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1808/pledge.svg">
</picture>
</a>

**Comment by peterschutt** [comment]
Thanks for the report. I also confirmed that it occurs without the path parameter.

Another interesting thing is that even inheriting from `BarController` changes the behavior or `FooController`, e.g.,:

```py
class BazController(BarController):
    path = "/baz"
```
![image](https://github.com/litestar-org/litestar/assets/20659309/48e7d89e-8962-4455-8c84-6d835c4ce52c)

**Comment by provinzkraut** [comment]
I don't think controllers were even designed with this sort of inheritance in mind?

**Comment by Goldziher** [comment]
this is not a bug in inheritance, apparently. its an issue somewhere else in the process of route registration or path resolution. im tracing this through the hay stack.

**Comment by JacobCoffee** [comment]
@Goldziher interested to know your process there

**Comment by Goldziher** [comment]
> @Goldziher interested to know your process there to add wrinkles to my brain

Started TDD and tracing this with a debugger
