### ISSUE TITLE
Bug: OpenAPI schema with Pydantic field aliases

### ISSUE THREAD

**Issue by gsakkis** [litestar-org/litestar#1809]
### Description

The current situation with respect to Pydantic field aliases is the following:
1. Request data validation uses the alias names
2. Response data use the field (non-alias) names
3. OpenAPI spec documents both request and response with the aliased names

Whether (2) should change to be consistent with (1) (or at least be easier to override than suggested [here](https://github.com/orgs/litestar-org/discussions/1458#discussioncomment-5555105)) is debatable. (3) however is clearly wrong.

### MCVE

```python
from litestar import Controller, Litestar, post
from pydantic import BaseModel, Field


class UserOrder(BaseModel):
    id: int = Field(alias="_id")
    name: str


class UserController(Controller):
    @post()
    async def create(self, data: UserOrder) -> UserOrder:
        return data


app = Litestar(route_handlers=[UserController])
```

### Steps to reproduce

```bash
curl localhost:8000/ -d '{"id":1, "name": "foo"}'
{"status_code":400,"detail":"Validation failed for POST http://localhost:8000/","extra":[{"key":"_id","message":"field required"}]}

curl localhost:8000/ -d '{"_id":1, "name": "foo"}'
{"id":1,"name":"foo"}
```

### Screenshots

<img width="674" alt="Screenshot 2023-06-11 at 2 29 42 PM" src="https://github.com/litestar-org/litestar/assets/291289/1eff83ea-3db4-4194-a68f-3212006e2aac">

### Litestar Version

Main branch

**Comment by cofin** [comment]
@gsakkis, by default, serializer does not export Pydantic BaseModels by their alias.  However, this behavior can easily be changed by overriding the `type_encoder` behavior:

```python
def _base_model_encoder(value: BaseModel) -> dict[str, Any]:
    return value.dict(by_alias=True)

app = Litestar(
        ...,
        type_encoders={BaseModel: _base_model_encoder},
        ...
    )

```

**Comment by gsakkis** [comment]
@cofin:

1) I am aware of `type_encoder`, I actually linked to your [past comment](https://github.com/orgs/litestar-org/discussions/1458#discussioncomment-5555105) where you included the exact same code, not sure why you pasted it here again.
2) This issue is mainly about an OpenAPI schema generation bug, it's not (just) a documentation issue.

**Comment by provinzkraut** [comment]
@gsakkis The bug you're describing can be solved by using the `allow_population_by_field_name` configuration option on your Pydantic model, and is in fact not a bug in Litestar.

```python
from pydantic import BaseModel, Field


class UserOrder(BaseModel):
    id: int = Field(alias="_id")

UserOrder(id=1)  # this fails
``` 


If you change your code to this, it works as expected:

```python
from litestar import Controller, Litestar, post
from pydantic import BaseModel, Field
from litestar.testing import TestClient


class UserOrder(BaseModel):
    class Config:
        allow_population_by_field_name = False

    id: int = Field(alias="_id")
    name: str


class UserController(Controller):
    @post()
    async def create(self, data: UserOrder) -> UserOrder:
        return data


app = Litestar(route_handlers=[UserController])


with TestClient(app) as client:
    print(client.post("/", json={"id": 1, "name": "foo"}).json())
```

The OpenAPI schema you've shown is therefore correct, as this is how you have configured your model.

<hr>

Regarding the points 1 and 2 you brought up:

We previously had a few discussions about how to handle this. See #1078 for example.

The issue with aligning the OpenAPI behaviour with the Pydantic behaviour is that the Pydantic behaviour is controlled via the `type_encoders`, so it's opaque to the rest of the application. To be able to propagate these changes to OpenAPI, we'd have to add an explicitly layered parameter just for the Pydantic models, and for attrs and potentially msgspec. 

As for Pydantic in particulat, I don't know if OpenAPI allows aliasing like Pydantic does (i.e. having two names for the same field that are both valid (which is what `allow_population_by_field_name` does), so I'm not sure if we could even represent this correctly.

**Comment by gsakkis** [comment]
@provinzkraut I just tested your example and `allow_population_by_field_name` has no effect on the OpenAPI schema; the generated name is always the aliased one (`_id` in the example). I understand that what the **request** name should be is debatable (at least when `allow_population_by_field_name = True`) but the **response** isn't: it should be the non-aliased name, `id` in this case.

**Comment by provinzkraut** [comment]
>  I just tested your example and `allow_population_by_field_name` has no effect on the OpenAPI schema; the generated name is always the aliased one (`_id` in the example)

For all intents and purposes, this schema is correct, as this is how Pydantic represents those fields. As I said, in your first example, this is not a bug but simply the intended behaviour of Pydantic. It gives you an option to *also* populate by the field name, but never exclusively so. I don't know if this is intended to change in Pydantic v2, but if you want a different behaviour there, you should open an issue on the Pydantic repo.

In any case, the chosen field name is ambiguous when `allow_population_by_field_name=True` is chosen, so Litestar will select the one that's guaranteed to be valid; The alias.

<hr>

For the response, I'm actually not sure what the sane default behaviour should be here. I think it makes sense to not diverge from the request behavior, and use the alias when it's given. 

As I explain in my previous answer, it's quite complicated to come up with a sensible solution for this that covers all bases and doesn't introduce a huge amount of additional complexity.

<hr>

In general, this use case is somewhat debatable I think. Why would you want to define an alias and then not use it? The whole point of defining an alias like this to be able to have the incoming data differ from what's used in the model. But what you want is actually just ignoring the alias. Can you explain what the use of that would be? Because, as far as I can tell, you could achieve anything you want by just omitting the alias.

**Comment by gsakkis** [comment]
Let's limit the discussion to the response only: the discrepancy between the OpenAPI spec and the actual response is an unambiguous bug; one of the two has to change. This actually came to my attention by a consumer of my api that noticed "docs say X, api returns Y so which one is it?". It's not a theoretical issue.

As for what the fix should be (e.g. whether to always use the alias if given) I don't have a strong opinion as long as the behavior is consistent with the documentation.

**Comment by provinzkraut** [comment]
The fix is, as @cofin pointed out, to serialise your Pydantic models using `by_alias=True`. Then the response and the OpenAPI documentation will be the same.

**Comment by provinzkraut** [comment]
I want to reiterate this again: *Pydantic* does not have a consistent behaviour here, so Litestar cannot offer consistency either. 

If there was a config option on the Pydantic models that said "I want to export by alias", then we could reference it, and construct the OpenAPI model accordingly, but this does not exist. The current behaviour simply replicates Pydantic's. That is, using the alias for parsing only, and not during serialisation. 

If you modify this in any way, Litestar cannot infer what to do, and you'll have to adjust your application accordingly, for example by manually serialising the models with `by_alias=True`.

**Comment by gsakkis** [comment]
> The fix is, as @cofin pointed out, to serialise your Pydantic models using by_alias=True. 

To me this seems more like a workaround than a fix. The current behavior is broken by default, one shouldn't need 3 extra non-obvious lines to have docs agree with the api.

> The current behaviour simply replicates Pydantic's. That is, using the alias for parsing only, and not during serialisation.

That alone would be perfectly fine. What is not fine is the discrepancy with the generated OpenApi spec for the response. Unless I am mistaken, OpenAPI generation is Litestar's responsibility, not Pydantic's.
