### ISSUE TITLE
Bug: route with path parameters matches longer paths

### ISSUE THREAD

**Issue by gsakkis** [litestar-org/litestar#1830]
### Description

A route registered for `/{param:str}`, in addition to matching `/foo` matches also `/foo/bar` (but not `/foo/bar/baz`).

### MCVE

```python
from litestar import Litestar, get


@get("/{name:str}")
async def hello_world(name: str) -> str:
    return f"Hello, {name}!"


app = Litestar([hello_world])
```

### Steps to reproduce

```bash
✗ http -b 'localhost:8000/jon'
Hello, jon!


✗ http -b 'localhost:8000/jon/bon'
Hello, jon!


✗ http -b 'localhost:8000/jon/bon/jovi'
{
    "detail": "Not Found",
    "status_code": 404
}
```
```


### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Litestar Version

Main branch

### Platform

- [ ] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/1830">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1830/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1830/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
This seems to be a regression. @Goldziher?

**Comment by Goldziher** [comment]
I'll handle it this weekend

**Comment by Goldziher** [comment]
can you tak this one on @gsakkis ? the fix should be in `traversal.py`
