### ISSUE TITLE
Bug: `Parameter.pattern` doesn't validate request parameters [v2.0.0beta1]

### ISSUE THREAD

**Issue by Okabintaro** [litestar-org/litestar#1860]
### Description

I am migrating a simple starlite application to litestar and noticed that the pattern/regex field of the parameter doesn't get validated anymore. I used this [this guide](https://docs.litestar.dev/2/usage/parameters.html#extra-validation-and-documentation-for-path-params) and updated my code accordingly.

The now called field/argument `Parameter.pattern` doesn't seem to be validate the request parameter anymore, while the old `Paramter.regex` worked fine.

Maybe I can dig into into the code and fix it myself later this week.

### MCVE

```python
from typing import Annotated

from litestar import MediaType, get
from litestar.params import Parameter
from litestar.status_codes import HTTP_200_OK, HTTP_400_BAD_REQUEST
from litestar.testing.helpers import create_test_client


@get(path="/val_regex", media_type=MediaType.TEXT)
async def regex_val(text: Annotated[str, Parameter(title="a or b", pattern="[a|b]")]) -> str:
    return f"str: {text}"


def test_broken_validation():
    with create_test_client(route_handlers=[regex_val]) as client:
        for letter in ("a", "b"):
            response = client.get(f"/val_regex?text={letter}")
            assert response.status_code == HTTP_200_OK
            assert response.text == f"str: {letter}"

        response = client.get("/val_regex?text=c")
        assert response.status_code == HTTP_400_BAD_REQUEST

if __name__ == "__main__":
    import pytest
    pytest.main([__file__])
```

### Steps to reproduce

```bash
1. Use the controller from above in a litestar applicaiton.
2. Call/Request `http://localhost:8000/ex/regex_val?text=c`
3. Expect a validation error, but text just gets printed/forwarded
```

### Litestar Version

v2.0.0beta1

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

<a href="https://polar.sh/litestar-org/litestar/issues/1860">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1860/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1860/pledge.svg">
</picture>
</a>

**Comment by Okabintaro** [comment]
I narrowed down the problem being this commit: https://github.com/litestar-org/litestar/commit/53aa6c3567f56f03dbe88efa68fd527d49f66fe3
What was done there is renaming the regex field of things to pattern to match the upcomming pydantic v2 release.
Since litestar still depends on pydantic v1 the field won't get filled properly anymore [here](https://github.com/litestar-org/litestar/blob/main/litestar/_signature/models/pydantic_signature_model.py#L146-L150).

Now my question is, should I upgrade to the pydantic v2 prerelease or is this considered a bug?
The mentioned commit seems to consider the regex field in some cases but not for the method/handler signatures it seems.

**Comment by Okabintaro** [comment]
Changing the validation backend to also resolves my issue, which might be the default/preferred thing in the future afaik.
For the test/example above:
```diff
- with create_test_client(route_handlers=[regex_val]) as client:
+ with create_test_client(route_handlers=[regex_val], _preferred_validation_backend="attrs") as client:
```

**Comment by Goldziher** [comment]
lemme see about fixing this. thanks for reporting.

**Comment by Okabintaro** [comment]
Thanks for the quick fix!
