### ISSUE TITLE
Enhancement: Python 3.12

### ISSUE THREAD

**Issue by JacobCoffee** [litestar-org/litestar#1862]
### Summary

3.12.0b4 is underway and the release date for 3.12 quickly approaches.

Release Schedule: https://peps.python.org/pep-0693/
Available Betas/RCs: https://www.python.org/ftp/python/3.12.0/

Tooling is beginning to support this (https://github.com/astral-sh/ruff/commit/8bc7378002d080094d572e83f3a3a69df1023030), I imagine we will have a waiting game for some things.. but it would be nice to get a head start on this once 2.0 is released.

Support 3.12, adding it to our CI matrix version, testing, docs, etc.

## Pre-3.12 Release Pending Upstream Packages

- [x] `greenlet`
  - [x] https://github.com/python-greenlet/greenlet/pull/327
  - [x] Greenlet 3.0 release
- [x] `grpcio`
	- [x] https://github.com/grpc/grpc/issues/33063
- [x] `orjson >= 3.8.10`
    - [x] https://github.com/ijl/orjson/releases/tag/3.8.10

## Post-3.12 Release Pending Upstream Packages

- [x] https://github.com/MagicStack/uvloop/issues/567

 
--- 

<a href="https://polar.sh/litestar-org/litestar/issues/1862">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1862/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1862/pledge.svg">
</picture>
</a>

**Comment by JacobCoffee** [comment]
added greenlet, grpcio, and orjson deps.

**Comment by provinzkraut** [comment]
Why orjson?

**Comment by JacobCoffee** [comment]
piccolo

**Comment by JacobCoffee** [comment]
Added pending upstream for `uvloop`
