### ISSUE TITLE
Enhancement: Add a MongoDB Motor Repository or Plugin

### ISSUE THREAD

**Issue by Goldziher** [litestar-org/litestar#1874]
### Discussed in https://github.com/orgs/litestar-org/discussions/1559

<div type='discussions-op-text'>

<sup>Originally posted by **Goldziher** April 20, 2023</sup>
I'd suggest we add a MongoDB repository to work directly with the Motor async driver. The issue with the driver is that it has no official types, just an unofficial (but very solid) stubs library. 

There are of course multiple ODMs such as beanie, Odmantic, Mongox that build on Motor + pydantic to create a smoother experience. I do think though that these have some inherent problems -

1. None of them uses the proper mongo query and aggregation syntax. They try to make it more `pythonic`, but i don't personally like that. 

2. They are not performant or performance orientated. 

3. They don't integrate as smoothly with us as a proper repository or plugin will. 

Thoughts and suggestions?</div>

<a href="https://polar.sh/litestar-org/litestar/issues/1874">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1874/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1874/pledge.svg">
</picture>
</a>

**Comment by gsakkis** [comment]
> None of them uses the proper mongo query and aggregation syntax. They try to make it more pythonic, but i don't personally like that.

FWIW I do like it, but personal preferences aside what's the point of an ODM if it doesn't hide/abstract the mongo-specific syntax and quirks? Why not just use Motor?

Btw I'd also add:

4. They're all but unmaintained at this point (infrequent commits, accumulating issues/PRs, bus factor of 1).

I started off with Odmantic, switched to Beanie but would consider switching again to a well-maintained alternative even if I don't particularly like all the design decisions.

**Comment by Goldziher** [comment]
> > None of them uses the proper mongo query and aggregation syntax. They try to make it more pythonic, but i don't personally like that.
> 
> FWIW I do like it, but personal preferences aside what's the point of an ODM if it doesn't hide/abstract the mongo-specific syntax and quirks? Why not just use Motor?

That's a fair point. But the issue really is that mongo does offer a strong query language, and these tools font use it. 


> Btw I'd also add:
> 
> 4. They're all but unmaintained at this point (infrequent commits, accumulating issues/PRs, bus factor of 1).
> 
> I started off with Odmantic, switched to Beanie but would consider switching again to a well-maintained alternative even if I don't particularly like all the design decisions.

Well, in this case how about adding a PR? We have a bus factor > 1

**Comment by provinzkraut** [comment]
Closing this as it is not planned. This might be implemented in a separate package in the future.
