### ISSUE TITLE
RFC: Enforce Conventional Commits

### ISSUE THREAD

**Issue by JacobCoffee** [litestar-org/litestar#1878]
### Summary

Enforce conventional commits for all commits to ease the generation of changelogs, then use this newly standardized stream of commits with another tool to generate beautiful changelogs for releases.

### Basic Example

Enforce via adding this to the pre-commit hooks and CI:

* https://github.com/compilerla/conventional-pre-commit
```yaml
- repo: https://github.com/compilerla/conventional-pre-commit
    rev: 2.3.0
    hooks:
      - id: conventional-pre-commit
```

### Drawbacks and Impact

1. It might annoy people with yet-another-pre-commit-hook.
2. We have to ensure commits are done in the correct way (e.g. `docs:` are only for documentation-based changes, etc.) 

### Unresolved questions

What changelog tool would we use?

Some options:

* https://git-cliff.org/
* https://pypi.org/project/git-changelog/
* https://github.com/KeNaCo/auto-changelog
* https://github.com/release-it/release-it

<a href="https://polar.sh/litestar-org/litestar/issues/1878">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1878/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1878/pledge.svg">
</picture>
</a>

**Comment by Goldziher** [comment]
I don't think this is the way forward. 

We squash merge in GitHub. That's where we should enforce the conventional commit message. Individual commits shouldn't matter. 

As for actual tools - commitizen and commit-lint are pretty standard
