### ISSUE TITLE
Docs: Document the new Prometheus exporter in "What New in v2"

### ISSUE THREAD

**Issue by JacobCoffee** [litestar-org/litestar#1882]
### Summary

https://docs.litestar.dev/2/release-notes/whats-new-2.html need to have the new Prometheus exporter added to it.
It should link to https://docs.litestar.dev/2/usage/contrib/prometheus.html, and can mostly just something akin to the [HTMX](https://docs.litestar.dev/2/release-notes/whats-new-2.html#htmx) section where it gives a brief intro to the new feature and then sends users to the usage docs and api ref. docs for more info.

<a href="https://polar.sh/litestar-org/litestar/issues/1882">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1882/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1882/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
Closing this as we chose to document changes and not entirely new features there.
