### ISSUE TITLE
Docs(Bug): Building raises warning for SQLAlchemy

### ISSUE THREAD

**Issue by JacobCoffee** [litestar-org/litestar#1910]
### Summary

`make docs-serve` on `main`:

```py
AWarning: Unmanaged access of declarative attribute id from non-mapped class BigIntAuditBase
  return getattr(obj, name, *defargs)
/home/user/git/python/litestar-org/litestar/.venv/lib/python3.11/site-packages/sphinx/util/inspect.py:376: SAWarning: Unmanaged access of declarative attribute id from non-mapped class BigIntBase
  return getattr(obj, name, *defargs)
/home/user/git/python/litestar-org/litestar/.venv/lib/python3.11/site-packages/sphinx/util/inspect.py:376: SAWarning: Unmanaged access of declarative attribute id from non-mapped class BigIntPrimaryKey
  return getattr(obj, name, *defargs)
/home/user/git/python/litestar-org/litestar/.venv/lib/python3.11/site-packages/sphinx/util/inspect.py:376: SAWarning: Unmanaged access of declarative attribute id from non-mapped class BigIntPrimaryKey
  return getattr(obj, name, *defargs)
/home/user/git/python/litestar-org/litestar/.venv/lib/python3.11/site-packages/sphinx/util/inspect.py:376: SAWarning: Unmanaged access of declarative attribute _sentinel from non-mapped class UUIDAuditBase
  return getattr(obj, name, *defargs)
/home/user/git/python/litestar-org/litestar/.venv/lib/python3.11/site-packages/sphinx/util/inspect.py:376: SAWarning: Unmanaged access of declarative attribute _sentinel from non-mapped class UUIDBase
  return getattr(obj, name, *defargs)
/home/user/git/python/litestar-org/litestar/.venv/lib/python3.11/site-packages/sphinx/util/inspect.py:376: SAWarning: Unmanaged access of declarative attribute _sentinel from non-mapped class UUIDPrimaryKey
  return getattr(obj, name, *defargs)
  ```

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/1910">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1910/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1910/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
Oh, I remember this. @cofin, did you have the time to look into this yet?

**Comment by cofin** [comment]
I'm taking a look now.

**Comment by provinzkraut** [comment]
@cofin any progress on this?

**Comment by cofin** [comment]
I'm struggling with this one.  I've added `-vvvv` to the sphinx build, and I'm still not seeing anything that points to where this is coming in at.  It looks like it's part of the autodoc piece that's causing it, but I've not gotten much further.

**Comment by Goldziher** [comment]
you should check where in sqla this is raised `SAWarning: Unmanaged access of declarative attribute id from non-mapped class BigIntBase`
