### ISSUE TITLE
List to changelog in website, broken

### ISSUE THREAD

**Issue by jruere** [litestar-org/litestar#1921]
### Summary

The link to the changelog (`https://docs.starliteproject.dev/1/release-notes/changelog.html`) in the website (`https://docs.litestar.dev/`) is broken. It results in a 404.

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/1921">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1921/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1921/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
This has been fixed.
