### ISSUE TITLE
Bug: CSRF tokens input tag rendered as string

### ISSUE THREAD

**Issue by LTsCreed** [litestar-org/litestar#1922]
### Description

When utilizing the Jinja Template Engine, the CSRF input tag is rendered as a string rather than a DOM element

### MCVE

```python
class FrontEndController(Controller):
    path = "/"

    @get(exclude_from_auth=True)
    async def index(self) -> Template:
        return Template(template_name="index.html.jinja2")
```

```html
    <form id="login-form" class="py-4" novalidate>
        {{ csrf_input }}
        <h3 class="mb-3">Please sign in</h3>
    </form>
```

### Screenshots

![Example](https://img001.prntscr.com/file/img001/FvbjodEITkqwJkt0Om6ZZg.png)

### Litestar Version
litestar==2.0.0b2

### Platform

- [ ] Linux
- [ ] Mac
- [X] Windows
- [ ] Other (Please specify in the description above)

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/1922">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1922/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1922/pledge.svg">
</picture>
</a>

**Comment by LTsCreed** [comment]
Jinja has autoescaping enabled by default. To load CSRF token a safe filter is required {{ csrf_input|safe }}

**Comment by eisenhaus335** [comment]
https://docs.litestar.dev/latest/usage/templating.html#adding-csrf-inputs
Update detail for templating autoescape for csrf
