### ISSUE TITLE
Bug: Using a bound generic type with msgspec DTO fails to decode

### ISSUE THREAD

**Issue by abdulhaq-e** [litestar-org/litestar#1929]
### Description

Please see the MCVE and note the two possible ways to circumvent this. I'm not sure if this is expected behaviour. Regardless, the test failure happens at the assertion. The actual logic doesn't throw and silently returns: `b'{"age":10,"data":{}}` which it shouldn't do silently imo.

### MCVE

```python
def test_dto_with_msgspec_and_generic_inherited_models(create_module: Callable[[str], ModuleType]) -> None:
    module = create_module(
        """
from typing import Dict, Generic, TypeVar
from typing_extensions import Annotated

from litestar import Litestar, post
from litestar.dto.factory import DTOConfig
from litestar.contrib.msgspec import MsgspecDTO

from msgspec import Struct

T = TypeVar("T", bound=Struct) # removing the bound argument solves the issue

class ClassicNameStyle(Struct):
    first_name: str
    surname: str

class User(Struct, Generic[T]):
    age: int
    data: T

class Superuser(User[ClassicNameStyle]):
    # uncommenting the line below also solves the issue (while keeping bound)
    # data: ClassicNameStyle 
    pass

class SuperUserDTO(MsgspecDTO[Superuser]):
    pass

@post(dto=SuperUserDTO)
def handler(data: Superuser) -> Superuser:
    return data

app = Litestar(route_handlers=[handler])
"""
    )
    with TestClient(app=module.app) as client:
        data = module.Superuser(data=module.ClassicNameStyle(first_name="A", surname="B"), age=10)
        headers = dict()
        headers["Content-Type"] = "application/json; charset=utf-8"
        received = client.post(
            "/",
            content=msgspec.json.encode(data),
            headers=headers,
        )
        print(received.content)
        assert msgspec.json.decode(received.content, type=module.Superuser) == data
```

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Litestar Version

latest

### Platform

- [ ] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/1929">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1929/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1929/pledge.svg">
</picture>
</a>

**Comment by Goldziher** [comment]
There is a branch called `msgspec-signature-model`. Can you add a PR with failing tests branched from and pointing at that branch?

**Comment by Goldziher** [comment]
this the draft PR of the above mentioned branch. Please add a PR with failing tests - we should make sure sure that msgspec requrest bodies are properly supported

**Comment by Goldziher** [comment]
https://github.com/litestar-org/litestar/pull/1854

**Comment by Goldziher** [comment]
thanks!

**Comment by abdulhaq-e** [comment]
So previously I mentioned that removing `bound=Struct` solves the issue. It actually doesn't (completely), in the example posted in the test, the `Superuser` will be decoded as: 

```python
Superuser(age=10, data={'first_name': 'A', 'surname': 'B'})
```

Notice the `data` field, it has been decoded as `dict` rather than the original type `ClassicNameStyle`

Therefore, as of now, the only solution is to re-declare the generic field:

```python
class Superuser(User[ClassicNameStyle]):
    data/: ClassicNameStyle 
```

**Comment by provinzkraut** [comment]
Okay, so here is a simplified version of the test reproducing the behaviour:

```python
from typing import Generic, TypeVar

import msgspec
from msgspec import Struct

from litestar import Litestar, post
from litestar.contrib.msgspec import MsgspecDTO
from litestar.testing import TestClient

T = TypeVar("T", bound=Struct)  # removing the bound argument solves the issue


class ClassicNameStyle(Struct):
    first_name: str
    surname: str


class User(Struct, Generic[T]):
    age: int
    data: T


class Superuser(User[ClassicNameStyle]):
    # uncommenting the line below also solves the issue (while keeping bound)
    # data: ClassicNameStyle
    pass


class SuperUserDTO(MsgspecDTO[Superuser]):
    pass


@post(dto=SuperUserDTO, sync_to_thread=False)
def handler(data: Superuser) -> Superuser:
    return data


app = Litestar(route_handlers=[handler])

with TestClient(app) as client:
    request_data = Superuser(data=ClassicNameStyle(first_name="A", surname="B"), age=10)
    received = client.post("/", json=msgspec.to_builtins(request_data))
    assert received.content == {"age": 10, "data": {"first_name": "A", "surname": "B"}}
```

<hr>

Inserting a breakpoint into the `handler` reveals that `data` is `Superuser(age=10, data=Struct())`, which suggests to me that the DTO *does* know about the generic type, but only seems to take into account its upper bound, and not the actual bound value.

I'm not yet sure if this is a bug or rather a missing feature.

@peterschutt Do you perhaps have any insights? (=

**Comment by peterschutt** [comment]
> @peterschutt Do you perhaps have any insights? (=

Thanks for the ping, I missed this one - will take a look tomorrow 👍

**Comment by Goldziher** [comment]
Please don't work on this. I'm reworking DTOs. Let's address this once I'm done

**Comment by abdulhaq-e** [comment]
> On a side note: This work just fine if you simply leave out the DTO. Msgspec is fully supported since `beta3`, so you can simply type your handler as
> 
> ```python
> @post(sync_to_thread=False)
> def handler(data: Superuser) -> Superuser:
>     return data
> ```

@abdulhaq-e Thanks. yh I'm aware of the change but this won't enable me to use cool things like exclude/renaming fields etc.

Also note my comment about removing `bound` decodes the data as a dict. Not sure if this is one issue or multiple. Lets address it when @Goldziher finishes the DTO rework.

**Comment by provinzkraut** [comment]
> Also note my comment about removing bound decodes the data as a dict. Not sure if this is one issue or multiple

That would be expected, or at least I'd argue that it makes sense, given the current behaviour. The DTO doesn't respect the type the `TypeVar` gets bound to, but only its upper bound, so naturally, if you don't provide that upper bound, it doesn't have any type information at all.

**Comment by Goldziher** [comment]
done
