### ISSUE TITLE
Bug: Prometheus client causes immediate websocket disconnect 

### ISSUE THREAD

**Issue by erik-hasse** [litestar-org/litestar#1934]
### Description

When using the Prometheus integration, websockets always disconnect immediately after opening the connection.

I've done a bit of digging, and the error arises in `PrometheusMiddleware._get_default_labels` [here](https://github.com/litestar-org/litestar/blob/main/litestar/contrib/prometheus/middleware.py#L107-L122), where `request.method` raises an attribute error for websockets. One possible fix that I've tested locally is to change it to:
```python
"method": (
    request.method
    if request.scope["type"] == "http"
    else request.scope["type"]
),
```

I'd be happy to open a PR for this change or some other fix if someone has a better idea.

### MCVE

```python
from litestar import Litestar, websocket_listener
from litestar.testing import TestClient
from litestar.contrib.prometheus import PrometheusConfig, PrometheusController

config = PrometheusConfig()

@websocket_listener("/")
def websocket_handler(data: str):
    return f"Hello, {data}!"

app_with_prometheus = Litestar(
    route_handlers=[websocket_handler, PrometheusController],
    middleware=[config.middleware]
)

app_without_prometheus = Litestar(route_handlers=[websocket_handler])

def test_app(app_to_test):
    with TestClient(app=app_to_test) as test_client:
        with test_client.websocket_connect("/") as socket:
            socket.send("World")
            response = socket.receive()
            print(response)

test_app(app_without_prometheus)
test_app(app_with_prometheus)
```

### Steps to reproduce

```bash
1. Run the MCVE
2. Observe the traceback
```

### Logs

```bash
Traceback (most recent call last):
  File "/Users/erik/test.py", line 27, in <module>
    test_app(app_with_prometheus)
  File "/Users/erik/test.py", line 20, in test_app
    with test_client.websocket_connect("/") as socket:
  File "/Users/erik/Library/Caches/pypoetry/virtualenvs/*****-ocilal_E-py3.11/lib/python3.11/site-packages/litestar/testing/websocket_test_session.py", line 52, in __enter__
    message = self.receive(timeout=self.client.timeout.read)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/erik/Library/Caches/pypoetry/virtualenvs/*****-ocilal_E-py3.11/lib/python3.11/site-packages/litestar/testing/websocket_test_session.py", line 195, in receive
    raise WebSocketDisconnect(
litestar.exceptions.websocket_exceptions.WebSocketDisconnect: KeyError('method')
```

### Litestar Version

2.0.0b2

### Platform

- [ ] Linux
- [X] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/1934">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1934/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1934/pledge.svg">
</picture>
</a>

**Comment by Goldziher** [comment]
@JacobCoffee can you try to reproduce this?

**Comment by JacobCoffee** [comment]
`"method": request.method if request.scope["type"] == "http" else request.scope["type"],` does indeed solve this but I am not certain it is the right place to fix. Investigating...

**Comment by JacobCoffee** [comment]
@erik-hasse would you like to open a PR with your fix? 

```py
    def _get_default_labels(self, request: Request[Any, Any, Any]) -> dict[str, str | int | float]:
        """Get default label values from the request.

        Args:
            request: The request object.

        Returns:
            A dictionary of default labels.
        """

        return {
            "method": request.method if request.scope["type"] == "http" else None,
            "type": request.scope["type"],
            "path": request.url.path,
            "status_code": 200,
            "app_name": self._config.app_name,
        }
```
