### ISSUE TITLE
Local run of `mypy` produces unexpected results

### ISSUE THREAD

**Issue by sobolevn** [litestar-org/litestar#1960]
### Description

Mypy produces unexpected failures locally, but the CI job passes: https://github.com/litestar-org/litestar/actions/runs/5561581892/jobs/10159348023?pr=1959

I think that this happens because `.pre-commit-config` and local mypy settings are not in sync.
I will fix that.

### Steps to reproduce

```bash
1. `poetry install --with lint -E full`
2. `poetry run mypy litestar`
```

### Logs

```bash
» mypy litestar      
litestar/contrib/jwt/jwt_token.py:115: error: Redundant cast to "str"  [redundant-cast]
litestar/_signature/models/attrs_signature_model.py:43: error: Skipping analyzing "pytimeparse.timeparse": module is installed, but missing library stubs or py.typed marker  [import]
litestar/_signature/models/attrs_signature_model.py:43: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
litestar/middleware/compression.py:29: error: Skipping analyzing "brotli": module is installed, but missing library stubs or py.typed marker  [import]
litestar/contrib/mako.py:19: error: Skipping analyzing "mako": module is installed, but missing library stubs or py.typed marker  [import]
litestar/contrib/mako.py:24: error: Skipping analyzing "mako.exceptions": module is installed, but missing library stubs or py.typed marker  [import]
litestar/contrib/mako.py:25: error: Skipping analyzing "mako.lookup": module is installed, but missing library stubs or py.typed marker  [import]
litestar/contrib/mako.py:28: error: Skipping analyzing "mako.template": module is installed, but missing library stubs or py.typed marker  [import]
litestar/cli/commands/schema.py:5: error: Skipping analyzing "jsbeautifier": module is installed, but missing library stubs or py.typed marker  [import]
Found 8 errors in 5 files (checked 303 source files)
```

### Litestar Version

`main`

### Platform

- [ ] Linux
- [X] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/1960">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1960/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1960/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
Hm. This is a bit odd since e.g. `jsbeautifier` is part of the dev dependencies and should therefore be installed:

https://github.com/litestar-org/litestar/blob/b32088f6618dd6b2fa8202da9883d5225b83bffe/pyproject.toml#L131

(same goes for the other dependencies)

**Comment by sobolevn** [comment]
If only this is easy :)

Please, let me explain. When `mypy` tries to build a graph to analyze it, it looks into several possible places for a package `xyz`:
1. `xyz` itself, if this package has `py.typed` file
2. `xyz-stubs` package, if the `1.` is missing (for example, package `types-python-jose` installs `jose-stubs`, so now stubs can be found)
3. (there are some other hacks like `MYPYPATH` that I don't want to bring up right now :) )

But, when all possible ways to find types fail, mypy raises an error when `ignore_missing_imports` is set to `False`. (I have no idea why this does not happen in `pre-commit`)

Let's see what's inside in `jsbeautifier`:

```
» ls .venv/lib/python3.11/site-packages/jsbeautifier                      
cli/  core/  javascript/  tests/  unpackers/  __init__.py  __version__.py                             
```

As you can see, it does not have `py.typed` and there are no stubs for this package.
This is why we have `litestar/cli/commands/schema.py:5: error: Skipping analyzing "jsbeautifier": module is installed, but missing library stubs or py.typed marker  [import]`

I hope it all makes sense :)

**Comment by provinzkraut** [comment]
> I hope it all makes sense :)

It does. I was simply not aware that `jsbeautifier` et al. are untyped. 

> (I have no idea why this does not happen in pre-commit)

The pre-commit hook (for some reason) passes `--ignore-missing-imports` by default. No idea why :shrug:
