### ISSUE TITLE
Move `mypy.ini` to `pyproject.toml`

### ISSUE THREAD

**Issue by sobolevn** [litestar-org/litestar#1974]
### Description

Mypy supports `pyproject.toml` for a long time now.
There's no need to have special `mypy.ini`, considering that all config is stored in `pyproject.toml`

### Litestar Version

`main`

### Platform

- [ ] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/1974">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1974/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1974/pledge.svg">
</picture>
</a>

**Comment by sobolevn** [comment]
pydantic also supports `pyproject.toml`: https://docs.pydantic.dev/latest/integrations/mypy/

**Comment by JacobCoffee** [comment]
I believe this will impact vscode users

**Comment by provinzkraut** [comment]
How so? Does it not pick up the config within `pyproject.toml`?

**Comment by JacobCoffee** [comment]
I am just recalling something one of our users had - https://discord.com/channels/919193495116337154/919193688775749662/1093564708256219219

I haven't used vscode in quite a while though... so I'm not sure past this

**Comment by JacobCoffee** [comment]
```md
## Coffee — 04/04/2023 7:35 PM
can we move mypy.ini into pyproject.toml? I can do the work if its okay to do

## chris — 04/06/2023 10:55 AM
Some MyPy IDE extensions don't like this -- just something to be aware of

## provinzkraut — 04/06/2023 10:56 AM
I think they meant extensions for the IDE, not extensions of mypy?

## chris — 04/06/2023 10:57 AM
Correct provinzkraut. Sorry that was unclear
But VSCode's MyPy extension doesn't. Funny enough I had a user interview with them where I asked them to start supporting it. They said they were working on it along with better poetry support.
But I know you guys pretty much all use pycharm. So perhaps not an issue. VSCode users can of course just run from the command line
```

**Comment by sobolevn** [comment]
Hm, interesting 🤔 
I've never heard of any problems before, thanks for letting me know!

Related https://github.com/microsoft/vscode-mypy/issues/37

**Comment by provinzkraut** [comment]
So we can either move all the mypy config into `mypy.ini` until the extension properly supports `pyproject.toml` or just tell VS Code users that they'll need to run mypy via the command line?

**Comment by JacobCoffee** [comment]
For me option 2 would be my suggestion, but thats due to my journey to eradicate 47 files in the root directory 😅
