### ISSUE TITLE
Bug: reload stalls after a 500 NoRouteMatchFoundException

### ISSUE THREAD

**Issue by euri10** [litestar-org/litestar#1984]
### Description

I made a Minimal reproducible example of the issue (url below), big picture it boils down to the following:

1. you run a litestar app with `uvicorn bug_reload_litestar.main:app --reload`
2. open http://localhost:8000/ page works fine, the handler outputs a template, the template contains a url_for function that loads a `toto` route
3. you create a `NoRouteMatchFoundException`, editing the `home_router.py` by making a typo in the name of the handler like: `@get("/toto", name="oto")`
4. reload the page, you get the 500 error, you indeed look for the toto route and it doesnt exist
5. you fix the bug in your app reverting to `@get("/toto", name="toto")`
6. the reload kicks in but stalls closing the database in the lifespan handler

What make mes think it is a bug in Litestar is:
1. every other error I have encountered in Litestar doesnt lead to that reload stalling, and I faced many misconfiguration on mmy side refactoring a big app, this one triggers 100% of the time
2. an "equivalent" FastAPI app doesnt trigger the same behaviour, reload works fine after a 500

Obviously it could be an error in my lifespan handler, I dont think it is because of 2) but FastAPI is definitly less strict so it could be that.

This is a very annoying DX experience but not life-threathening :)

### URL to code causing the issue

https://github.com/euri10/bug_reload_litestar

### Litestar Version

2.0.0b2

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/1984">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1984/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1984/pledge.svg">
</picture>
</a>

**Comment by euri10** [comment]
some update as I fixed it but I think this is a litestar bug nonetheless or thre's something I dont understand :)

the fix is to `return conn` instead of `yield conn` here: 

https://github.com/euri10/bug_reload_litestar/blob/4ea33ec75315b5df70fbdf21a81e634a015112b9/bug_reload_litestar/utils/dependencies.py#L13

it is as if litestar would not "finish" resolving the dependency, I mean processing what is after the yield, if caught in a 500 

Thus effectlively the context manager that aquires the connection is not closed and on a reload that triggers the lifespan cleaning part, then I cant close the db

**Comment by provinzkraut** [comment]
Hi, so this is not really a bug, but expected behaviour. 
The issue is that the generator "hangs" because of an unhandled exception. This can be mitigated by wrapping the `yield` in a `try/finally`:

It is explained in the section [Dependencies with `yield` > Handling exceptions](https://docs.litestar.dev/2/usage/dependency-injection.html#handling-exceptions):

> You should always wrap yield in a try/finally block, regardless of whether you want to handle exceptions, to ensure that the cleanup code is run even when exceptions occurred

Here is a minimal example to reproduce this behaviour:

```python
from unittest.mock import MagicMock

from litestar import get
from litestar.testing import create_test_client

mock = MagicMock()

def some_dependency() -> str:
    mock()
    yield "something"
    mock()


@get("/", dependencies={"some": some_dependency})
async def handler(some: str) -> str:
    raise ValueError()


with create_test_client(handler) as client:
    client.get("/")
    assert mock.call_count == 2
``` 

which can be fixed by adding a `try/finally` block:

```python
from unittest.mock import MagicMock

from litestar import get
from litestar.testing import create_test_client

mock = MagicMock()

def some_dependency() -> str:
    mock()
    try:
        yield "something"
    finally:
        mock()


@get("/", dependencies={"some": some_dependency})
async def handler(some: str) -> str:
    raise ValueError()


with create_test_client(handler) as client:
    client.get("/")
    assert mock.call_count == 2
``` 

And for what it's worth, an equivalent FastAPI application behaves the same way:

```python
from unittest.mock import MagicMock

from litestar import get
from litestar.testing import create_test_client

mock = MagicMock()


def some_dependency() -> str:
    mock()
    yield "something"
    mock()


@get("/", dependencies={"some": some_dependency})
async def handler(some: str) -> str:
    raise ValueError()


with create_test_client(handler) as client:
    client.get("/")
    assert mock.call_count == 2
```

<hr>

As for the bad DX, I think handling exceptions in a way that prevent would result in a worse DX in most cases, since it makes explicitly handling exceptions way more complicated.

**Comment by euri10** [comment]
OOo I should rtfm better, thanks tons for this, make total sense :)
