### ISSUE TITLE
Docs: Prometheus integration

### ISSUE THREAD

**Issue by provinzkraut** [litestar-org/litestar#1991]
### Summary

The prometheus integration added in #1872 is currently undocumented. Both prose and reference docs are missing. 

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/1991">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/1991/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/1991/pledge.svg">
</picture>
</a>

**Comment by JacobCoffee** [comment]
Also #1882
