### ISSUE TITLE
Enhancement: allow setting individual optional DTO fields

### ISSUE THREAD

**Issue by LonelyVikingMichael** [litestar-org/litestar#2005]
### Summary

I'd like to be able to mark individual DTO fields as optional while other remain required. This is helpful where more nuance is required than `DTOConfig.partial` can provide.

An `optional` keyword argument on `DTOConfig` seems like the right approach.

### Basic Example

```python
class User(DeclarativeBase):
    email: Mapped[str] = mapped_column(String(320), nullable=False, unique=True)
    password_hash: Mapped[str] = mapped_column(String(1024))
    is_active: Mapped[bool] = mapped_column(Boolean(), nullable=False, default=False)
    is_verified: Mapped[bool] = mapped_column(Boolean(), nullable=False, default=False)


class UserReadDTO(SQLAlchemyDTO[User]):
	"""DTO with optional `is_active` and `is_verified` fields."""
	config = DTOConfig(optional={"is_active", "is_verified"})
```

### Drawbacks and Impact

I'm not sure how much benefit there would be to the community at large - this would be particularly helpful to `litestar-users`

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2005">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2005/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2005/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
Does this do what you want?

https://docs.litestar.dev/2/usage/dto/1-dto-factory.html#marking-fields

**Comment by peterschutt** [comment]
A self contained, minimal example that demonstrates your issue would be helpful.

> I'd like to be able to mark individual DTO fields as optional

"optional" as in field type is to be made a union with `None`, or not required to be submitted in the client payload?

What if a user isn't privileged, but in the api docs the `is_verified` parameter is documented as an optional parameter, isn't this leaking abstraction to them?

As for the idea of granular setting of `partial`, I think it makes sense. What about making `DTOConfig.partial` accept either a bool, or `set[str]` where the latter would be a set of field names to be made partial fields?
