### ISSUE TITLE
Enhancement: set debug=True in create_test_client by default

### ISSUE THREAD

**Issue by Goldziher** [litestar-org/litestar#2010]
We should set debug True in the test helpers. 

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2010">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2010/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2010/pledge.svg">
</picture>
</a>

**Comment by peterschutt** [comment]
100% - I've had this thought many times myself.
