### ISSUE TITLE
Bug: serialization on multipart form

### ISSUE THREAD

**Issue by euri10** [litestar-org/litestar#2019]
### Description

I get a 400 on a multipart form where I think it should work ok given the payload I'm passing,

the handler is:
```
@dataclass
class AddProductForm:
    name: str
    description: str
    image_path: UploadFile
    subcategory: int
    shipping_options: int | list[int]
    price_row_1: float
    amount_row_1: int
    price_row_2: float | None = None
    amount_row_2: int | None = None
    price_row_3: float | None = None
    amount_row_3: int | None = None
    price_row_4: float | None = None
    amount_row_4: int | None = None
    price_row_5: float | None = None
    amount_row_5: int | None = None

@post("/add_product", name="add_product_post")
async def add_product_post(
    request: Request,
    conn: BuildPgConnection,
    app_settings: AppSettings,
    data: Annotated[AddProductForm, Body(media_type=RequestEncodingType.MULTI_PART)],
) -> Template:
```

if payload is
```
name: world
description: dewqdwq
image_path: (binary)
subcategory: 7
shipping_options: 1
shipping_options: 1797
amount_row_1: 1
price_row_1: 125.1
amount_row_2: 
price_row_2: 
amount_row_3: 
price_row_3: 
amount_row_4: 
price_row_4: 
amount_row_5: 
price_row_5: 
``` 
I get a ` {"status_code":400,"detail":"Validation failed for POST http://localhost:9000/products/add_product","extra":[{"message":"Expected int | null, got str","key":"amount_row_2","source":"body"}]}` so it sees the null passed as an empty string

if payload is:
```
name: 1
description: dewqdwq
image_path: (binary)
subcategory: 7
shipping_options: 1
shipping_options: 1797
amount_row_1: 1
price_row_1: 125.1
amount_row_2: 1
price_row_2: 109.0
amount_row_3: 1
price_row_3: 12.9
amount_row_4: 1
price_row_4: 12.8
amount_row_5: 1
price_row_5: 12.5
``` 
I get the same 400 this time because it complains name is not a str

`{"status_code":400,"detail":"Validation failed for POST http://localhost:9000/products/add_product","extra":[{"message":"Expected `str`, got `int`","key":"name","source":"body"}]}`

### MCVE

```python
# Your MCVE code here
```

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Litestar Version

 litestar (2.0.0beta2 dc8790e) this is post https://github.com/litestar-org/litestar/pull/2001 fix

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2019">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2019/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2019/pledge.svg">
</picture>
</a>

**Comment by Goldziher** [comment]
Hi @euri10,

I need to see the actual multipart request you are sending. Please submit the entire form data in serialized Form, including the boundary parts. If you're using a browser, you can get that from the network tab of the developer console.

**Comment by euri10** [comment]
oh sorry,
here's one for the first issue with None:
```
------WebKitFormBoundaryBjhqT8WAQXalgkfy
Content-Disposition: form-data; name="name"

name
------WebKitFormBoundaryBjhqT8WAQXalgkfy
Content-Disposition: form-data; name="description"

description
------WebKitFormBoundaryBjhqT8WAQXalgkfy
Content-Disposition: form-data; name="image_path"; filename="banner-light.svg"
Content-Type: image/svg+xml


------WebKitFormBoundaryBjhqT8WAQXalgkfy
Content-Disposition: form-data; name="subcategory"

1
------WebKitFormBoundaryBjhqT8WAQXalgkfy
Content-Disposition: form-data; name="shipping_options"

1
------WebKitFormBoundaryBjhqT8WAQXalgkfy
Content-Disposition: form-data; name="amount_row_1"

1
------WebKitFormBoundaryBjhqT8WAQXalgkfy
Content-Disposition: form-data; name="price_row_1"

100.0
------WebKitFormBoundaryBjhqT8WAQXalgkfy
Content-Disposition: form-data; name="amount_row_2"


------WebKitFormBoundaryBjhqT8WAQXalgkfy
Content-Disposition: form-data; name="price_row_2"


------WebKitFormBoundaryBjhqT8WAQXalgkfy
Content-Disposition: form-data; name="amount_row_3"


------WebKitFormBoundaryBjhqT8WAQXalgkfy
Content-Disposition: form-data; name="price_row_3"


------WebKitFormBoundaryBjhqT8WAQXalgkfy
Content-Disposition: form-data; name="amount_row_4"


------WebKitFormBoundaryBjhqT8WAQXalgkfy
Content-Disposition: form-data; name="price_row_4"


------WebKitFormBoundaryBjhqT8WAQXalgkfy
Content-Disposition: form-data; name="amount_row_5"


------WebKitFormBoundaryBjhqT8WAQXalgkfy
Content-Disposition: form-data; name="price_row_5"


------WebKitFormBoundaryBjhqT8WAQXalgkfy--
```

here's the second for the issue str/int in the name field:
```
------WebKitFormBoundarycxbRxk0HGu9C0xZD
Content-Disposition: form-data; name="name"

1
------WebKitFormBoundarycxbRxk0HGu9C0xZD
Content-Disposition: form-data; name="description"

description
------WebKitFormBoundarycxbRxk0HGu9C0xZD
Content-Disposition: form-data; name="image_path"; filename="banner-light.svg"
Content-Type: image/svg+xml


------WebKitFormBoundarycxbRxk0HGu9C0xZD
Content-Disposition: form-data; name="subcategory"

1
------WebKitFormBoundarycxbRxk0HGu9C0xZD
Content-Disposition: form-data; name="shipping_options"

1
------WebKitFormBoundarycxbRxk0HGu9C0xZD
Content-Disposition: form-data; name="amount_row_1"

1
------WebKitFormBoundarycxbRxk0HGu9C0xZD
Content-Disposition: form-data; name="price_row_1"

100.0
------WebKitFormBoundarycxbRxk0HGu9C0xZD
Content-Disposition: form-data; name="amount_row_2"

2
------WebKitFormBoundarycxbRxk0HGu9C0xZD
Content-Disposition: form-data; name="price_row_2"

100.0
------WebKitFormBoundarycxbRxk0HGu9C0xZD
Content-Disposition: form-data; name="amount_row_3"

3
------WebKitFormBoundarycxbRxk0HGu9C0xZD
Content-Disposition: form-data; name="price_row_3"

100.0
------WebKitFormBoundarycxbRxk0HGu9C0xZD
Content-Disposition: form-data; name="amount_row_4"

4
------WebKitFormBoundarycxbRxk0HGu9C0xZD
Content-Disposition: form-data; name="price_row_4"

100.0
------WebKitFormBoundarycxbRxk0HGu9C0xZD
Content-Disposition: form-data; name="amount_row_5"

5
------WebKitFormBoundarycxbRxk0HGu9C0xZD
Content-Disposition: form-data; name="price_row_5"

100.0
------WebKitFormBoundarycxbRxk0HGu9C0xZD--
```

also I briefly looked at tests and if I get it correctly, only pydantic forms are tested using this form, attrs or dataclass are not: https://github.com/litestar-org/litestar/blob/dc8790e63f0e90f1650042558a9be620bf4b1eae/tests/unit/test_kwargs/__init__.py#L4-L8

**Comment by Goldziher** [comment]
Ok, I see the issue. It seems that we relied on empty strings being evaluated as None values.

**Comment by Goldziher** [comment]
The `None` value is fixed in a PR. As for sending a single value list - this is not possible i'm afraid. 

We cannot know from the multipart data whether what you are sending is a single value list or a simple primitive, that is - unless you are sending an encoded array as json, in which case you are simply sending a string - `"[1,2,3,4]"`. 

But given the multipart protocol, we cannot know what a single value is in fact a list. The solution is to type the value as a single value or list (union type), which will work.
