### ISSUE TITLE
Bug: serialization of list items in forms when the list has a single element leads to a 400

### ISSUE THREAD

**Issue by euri10** [litestar-org/litestar#2028]
### Description

real-life situation is the following:

1. I have a form with a select, that has the `multiple` attribute
2. user can either select one or more entries, the resulting payload will be `li=1` in case he chooses one element, `li=1&li=2&li=3` if he chooses more
2.1. if he chooses more than one entry then validation works as intended, see tests 1 and 2 from the parametrization above
2.2. if he chooses only one entry, then a 400 occurs, which I think is incorrect, I should retrieve `[1]` in the handler

the following tests depicts I think the above, when I pass only one integer while the form is declared to expect `list[int]`.

[`main...euri10:forms?expand=1`#diff-13fb84aa44](https://github.com/litestar-org/litestar/compare/main...euri10:forms?expand=1#diff-13fb84aa44ecfcf0011c55c2df5e679f39b5f1aee9bafb28d01e7cdf6f21e99eR15-R61)

### MCVE

```python
# Your MCVE code here
```

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Litestar Version

2.0.0beta3

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2028">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2028/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2028/pledge.svg">
</picture>
</a>

**Comment by Goldziher** [comment]
So, this is not a bug par se. We cannot know from the form data whether its a list or not given the serialization format of multipart. Thus - single elements are not assumed to be a list. You can bypass this in one of two ways:

1. you can send serialized json arrays as values: `"[1,2,3,4]”` and we will deserialize this into a json list.
2. you can type you handler to receive a single or list: `str | list[str]` etc. This will also work.
