### ISSUE TITLE
Refactor: Reduce Cognitive Complexity

### ISSUE THREAD

**Issue by Goldziher** [litestar-org/litestar#203]
Sonar complains about several functions having too high "cognitive complexity", see --> https://sonarcloud.io/project/issues?resolved=false&severities=CRITICAL&id=starlite-api_starlite. It would be nice to refactor these to be both clearer and simpler - probably by splitting them into functions, or refactoring them into classes, using functional composition etc. 

This is a good issue for those who like to contribute - because it will accept multiple small PRs. If you work on this, please make sure to have unit tests in place to ensure implementation is not broken. Also please ensure that coverage remains at 100% for the affected code. 

<a href="https://polar.sh/litestar-org/litestar/issues/203">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/203/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/203/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
> Fixed in #501

Not really. That was one PR that addressed this, but as you can see from the top comment and the provided link therewithin, there are still 19 open reports from SonarCloud regarding this.
