### ISSUE TITLE
Bug: ModuleNotFoundError: No module named 'rich' when installing Litestar for first time

### ISSUE THREAD

**Issue by Faolain** [litestar-org/litestar#2037]
### Description

Starting a fresh app using the instructions on https://docs.litestar.dev/2/ after having installed some dependencies prior (not many) I receive the following error after trying to run `litestar run`

```
❯ litestar run
Traceback (most recent call last):
  File "/Users/user/Desktop/test-api-v2/.venv/bin/litestar", line 5, in <module>
    from litestar.__main__ import run_cli
  File "/Users/user/Desktop/test-api-v2/.venv/lib/python3.11/site-packages/litestar/__main__.py", line 1, in <module>
    from litestar.cli.main import litestar_group  # pragma: no cover
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/user/Desktop/test-api-v2/.venv/lib/python3.11/site-packages/litestar/cli/__init__.py", line 4, in <module>
    from .main import litestar_group
  File "/Users/user/Desktop/test-api-v2/.venv/lib/python3.11/site-packages/litestar/cli/main.py", line 7, in <module>
    from ._utils import RICH_CLICK_INSTALLED, LitestarEnv, LitestarExtensionGroup
  File "/Users/user/Desktop/test-api-v2/.venv/lib/python3.11/site-packages/litestar/cli/_utils.py", line 14, in <module>
    from rich import get_console
ModuleNotFoundError: No module named 'rich'
```

### MCVE

```python
from litestar import Litestar, get


@get("/")
async def index() -> str:
    return "Hello World"


@get("/books/{book_id:int}")
async def get_book(book_id: int):
    return {"book_id": book_id}


app = Litestar([index, get_book])
```

### Steps to reproduce

```bash
Follow example from https://docs.litestar.dev/2/ 

❯ poetry add litestar
Using version ^2.0.0b4 for litestar

❯ poetry add "litestar[pydantic]"
Using version ^2.0.0b4 for litestar

❯ litestar run
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Logs

```bash
❯ poetry add litestar
Using version ^2.0.0b4 for litestar

Updating dependencies
Resolving dependencies... Downloading https://files.pythonhosted.org/packages/4d/cd/3b3fd9a85c1861f84a22573093fef6a3cf9312b4443d83fa75b0f690a535/fast_query_parsers-
Resolving dependencies... Downloading https://files.pythonhosted.org/packages/4d/cd/3b3fd9a85c1861f84a22573093fef6a3cf9312b4443d83fa75b0f690a535/fast_query_parsers-
Resolving dependencies... (2.7s)

Package operations: 15 installs, 0 updates, 0 removals

  • Installing idna (3.4)
  • Installing six (1.16.0)
  • Installing sniffio (1.3.0)
  • Installing anyio (3.7.1)
  • Installing certifi (2023.5.7)
  • Installing h11 (0.14.0)
  • Installing python-dateutil (2.8.2)
  • Installing faker (19.2.0)
  • Installing httpcore (0.17.3)
  • Installing fast-query-parsers (1.0.2)
  • Installing httpx (0.24.1)
  • Installing msgspec (0.17.0)
  • Installing multidict (6.0.4)
  • Installing polyfactory (2.6.3)
  • Installing litestar (2.0.0b4)

❯ poetry add "litestar[pydantic]"
Using version ^2.0.0b4 for litestar

Updating dependencies
Resolving dependencies... (0.6s)

Package operations: 3 installs, 0 updates, 0 removals

  • Installing dnspython (2.4.0)
  • Installing email-validator (2.0.0.post2)
  • Installing pydantic-extra-types (2.0.0)

# In case relevent pyproject.toml

[tool.poetry.dependencies]
python = "^3.11"
mypy = "^1.4.1"
pytest-cov = "^4.1.0"
pydantic = "^2.0.3"
pre-commit = "^3.3.3"
litestar = {extras = ["pydantic"], version = "^2.0.0b4"}

[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
ruff = "^0.0.278"
mypy = "^1.4.1"

[tool.poetry.group.test.dependencies]
ruff = "^0.0.278"
mypy = "^1.4.1"
pytest = "^7.4.0"

[tool.black]
line-length = 88

[tool.ruff]
line-length = 88
unfixable = ["B", "SIM", "TRY", "RUF", "F401", "F841"]
ignore = ["E712"]
select = ["F", "E", "W", "I001"]

[tool.mypy]
plugins = ["pydantic.mypy"]

follow_imports = "silent"
warn_redundant_casts = true
disallow_any_generics = true
no_implicit_reexport = true

disallow_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = true
warn_unused_ignores = true
show_error_codes = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

```

### Litestar Version

2.0.0b4
python==3.11.4 using pyenv

### Platform

- [ ] Linux
- [X] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2037">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2037/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2037/pledge.svg">
</picture>
</a>

**Comment by cofin** [comment]
Can you install with the console option? 

it should be `poetry add litestar[cli, pydantic]`.   This should add those dependencies for you.  

However, the CLI should be optional, so I'll look into what is causing that.

**Comment by cofin** [comment]
We probably need to make it a bit more clear that the `litestar` command is considered an optional component.  Here's the existing [documentation](https://docs.litestar.dev/2/usage/cli.html) on it, but maybe we can make this a bit more prominent somewhere?

**Comment by Faolain** [comment]
Ah that did it thanks @cofin! Sorry about that, standard would've taken care of it apologies!

**Comment by JacobCoffee** [comment]
Maybe we should advertise litestar[standard] as the default?
here:
![image](https://github.com/litestar-org/litestar/assets/45884264/3ff34307-9352-4e2d-a7e8-d35559419709)

**Comment by JacobCoffee** [comment]
Maybe instead of adding even more admonitions, we can just move the already existing one out of the collapsed bit.

![image](https://github.com/litestar-org/litestar/assets/45884264/4e0b3a89-9145-43b0-a03d-7fa6fffb5ffd)

**Comment by JacobCoffee** [comment]
@Faolain what do you think? https://github.com/litestar-org/litestar/pull/2041 contains the 2nd above layout, if that would make more sense to you and newcomers that stumble into the docs wondering how to install with a working cli (and uvicorn, etc) to get up and going faster.

**Comment by provinzkraut** [comment]
> but maybe we can make this a bit more prominent somewhere?

I'm actually not sure how much more prominent we can make it? :grimacing: 

![Screenshot from 2023-07-22 09-19-49](https://github.com/litestar-org/litestar/assets/25355197/fbdbf80d-dd37-473d-b7c2-1a862acca52d)

**Comment by provinzkraut** [comment]
> Maybe we should advertise litestar[standard] as the default?

I don't think we should, since it will contain a whole bunch of stuff most will never use :shrug:

**Comment by Faolain** [comment]
> @Faolain what do you think? #2041 contains the 2nd above layout, if that would make more sense to you and newcomers that stumble into the docs wondering how to install with a working cli (and uvicorn, etc) to get up and going faster.

Love it!
