### ISSUE TITLE
Bug: 400 error on checkbox

### ISSUE THREAD

**Issue by euri10** [litestar-org/litestar#2043]
### Description

the below works fine with a pydantic form but not with a dataclass,

if the checkbox is checked, then the payload here would be `enable_2fa=on` which pydantic casts to a bool

with the dataclass I get `{"status_code":400,"detail":"Validation failed for POST http://0.0.0.0:9000/users/me/add_2fa","extra":[{"message":"Expected `bool | null`, got `str`","key":"enable_2fa","source":"body"}]}`

### MCVE

```python
# @dataclass
# class Add2FAForm:
#     enable_2fa: bool | None = None

class Add2FAForm(BaseModel):
    enable_2fa: bool | None = None


@post("/me/add_2fa", name="add_2fa")
async def add_2fa(
        request: Request,
        conn: BuildPgConnection,
        data: Annotated[Add2FAForm, Body(media_type=RequestEncodingType.URL_ENCODED)],
```

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Litestar Version

litestar = "^2.0.0b4"

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2043">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2043/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2043/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
Not a bug but intentional. Treating `on` as a bool is Pydantic specific behaviour. 

Litestar does not aim to abstract away all differences in serialisation/validation behaviour of the various supported libraries (msgspec/attrs/Pydantic), since that would make supporting them in the first place a bit pointless.
