### ISSUE TITLE
Enhancement: Extend SQLAlchemy Plugin to include Alembic

### ISSUE THREAD

**Issue by cofin** [litestar-org/litestar#2055]
### Summary

It would be great if we could automatically configure Alembic with the SQLA plugin.

To do this, we'd need to be able to specify/customize:
- The alembic version table name
- The path for migrations
- Default migration make template
- Default alembic `env.py` (or altenative implementation)
- Expose alembic commands as a `db` CLI command.

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2055">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2055/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2055/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
This is being tracked externally in [advanced-alchemy](https://github.com/jolt-org/advanced-alchemy/)
