### ISSUE TITLE
Bug: `operation_id` cannot be set if a handler has multiple paths defined

### ISSUE THREAD

**Issue by floxay** [litestar-org/litestar#2075]
### Description

Schema generation fails when `operation_id` is set on a handler with multiple paths:

```
ImproperlyConfiguredException on GET /schema
500: operation_ids must be unique, please ensure the value of 'operation_id' is either not set or unique for TestOperation
```

### MCVE

```python
from litestar import Litestar, get

@get(
    path=[
        "/foo",
        "/bar",
    ],
    operation_id="TestOperation",
)
def test_handler() -> str:
    return "OK"

app = Litestar(route_handlers=[test_handler], debug=True)

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, port=5000)
```

### Litestar Version

2.0.0beta4

### Platform

- [ ] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2075">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2075/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2075/pledge.svg">
</picture>
</a>

**Comment by Goldziher** [comment]
So, issue here is that each path has to have a unique operation_id. 

Have you tried using a callable instead for operation_id?

**Comment by floxay** [comment]
No, I have not.

The typing indicated it's a `str | None` so I just expected that it will be handled and made unique by some internal logic (prefixing with handler path index or name, or similar) by default as nothing seemed to indicate otherwise that handlers with multiple paths cannot have `operation_id` as a simple string.

**Comment by Goldziher** [comment]
ok, lemme check this out - we should support a callable.

**Comment by Goldziher** [comment]
Ok, this is technically not a bug. You can pass an `operation_id_creator` function to handle this on the global config. We will now allow setting such a callable also locally on the route handler.
