### ISSUE TITLE
Bug: Can not serve static file in / path

### ISSUE THREAD

**Issue by saltcable** [litestar-org/litestar#2119]
### Description

Can not serve static file in / path when serving a home page there.

Structure:
├───root
├───root/robots.txt
└───code.py

### MCVE

```python
from pathlib import Path

from litestar import Litestar
from litestar import get, Router, Controller
from litestar.static_files import StaticFilesConfig


class PageController(Controller):
    @get(name='index')
    async def index(self) -> str:
        return 'index'


app = Litestar(
    route_handlers=[Router(path='/', route_handlers=[PageController])],
    static_files_config=[StaticFilesConfig(path=f"/", directories=[Path(__file__).with_name('root')], name='root')],
)
```

### Steps to reproduce

```bash
1. Go to 'http://127.0.0.1:XXXX/robots.txt'
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Logs

```bash
INFO:     127.0.0.1:51696 - "GET /robots.txt HTTP/1.1" 404 Not Found
```

### Litestar Version

litestar==2.0.0b4

### Platform

- [ ] Linux
- [ ] Mac
- [X] Windows
- [ ] Other (Please specify in the description above)

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2119">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2119/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2119/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
A simpler way to reproduce this:

```python
from pathlib import Path
from secrets import token_hex

from litestar import get, Litestar
from litestar.static_files.config import StaticFilesConfig
from litestar.testing import create_test_client


@get("/")
async def index() -> str:
    return "index"


file = Path() / token_hex()
file.touch()

with create_test_client(
    Litestar([index], static_files_config=[StaticFilesConfig(path="/", directories=[file.parent])])
) as client:
    assert client.get(f"/{file}").status_code == 200
```

**Comment by provinzkraut** [comment]
I think this might be a limitation with out current design of the static files application.

@Goldziher can you take a look at this if you have the time?

**Comment by Goldziher** [comment]
> I think this might be a limitation with out current design of the static files application.
> 
> @Goldziher can you take a look at this if you have the time?

Sure
