### ISSUE TITLE
Bug: Handle dialect that doesn't support JSON type

### ISSUE THREAD

**Issue by thiagozf** [litestar-org/litestar#2137]
### Description

I'm using a custom dialect that doesn't support JSON types. As you can see [here](https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/engine/create.py#L680), SQLAlchemy throws a `TypeError` when it receives invalid arguments on `create_engine`.

Litestar anticipates this error can happen, but it handles the wrong exception type (`ValueError` instead of `TypeError`).

https://github.com/litestar-org/litestar/blob/9f98636d8a2d3c22ce260b37a1543eee9e74bbc8/litestar/contrib/sqlalchemy/plugins/init/config/common.py#L187-L193

### MCVE

```python
# Your MCVE code here
```

### Steps to reproduce

```bash
1. Install a dialect that doesn't support JSON
2. Setup the SQLAlchemy plugin to use that dialect 
3. Start the Litestar app
```

### Logs

```bash
Using Litestar app from env: 'app.main:app'
...
INFO:     Started server process [55936]
INFO:     Waiting for application startup.
ERROR:    Traceback (most recent call last):
  File "<dev>/.venv/lib/python3.11/site-packages/litestar/app.py", line 541, in lifespan
    await self._call_lifespan_hook(hook)
  File "<dev>/.venv/lib/python3.11/site-packages/litestar/app.py", line 514, in _call_lifespan_hook
    ret = hook(self) if inspect.signature(hook).parameters else hook()  # type: ignore
          ^^^^^^^^^^
  File "<dev>/.venv/lib/python3.11/site-packages/litestar/contrib/sqlalchemy/plugins/init/config/common.py", line 252, in update_app_state
    app.state.update(self.create_app_state_items())
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<dev>/.venv/lib/python3.11/site-packages/litestar/contrib/sqlalchemy/plugins/init/config/common.py", line 242, in create_app_state_items
    self.engine_app_state_key: self.create_engine(),
                               ^^^^^^^^^^^^^^^^^^^^
  File "<dev>/.venv/lib/python3.11/site-packages/litestar/contrib/sqlalchemy/plugins/init/config/common.py", line 188, in create_engine
    self.engine_instance = self.create_engine_callable(self.connection_string, **engine_config)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "<dev>/.venv/lib/python3.11/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^
  File "<dev>/.venv/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 680, in create_engine
    raise TypeError(
TypeError: Invalid argument(s) 'json_deserializer','json_serializer' sent to create_engine(), using configuration BigQueryDialect/QueuePool/Engine.  Please check that the keyword arguments are appropriate for this combination of components.
```

### Litestar Version

2.0.0rc1

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

**Comment by cofin** [comment]
What DB engine are you using here?

**Comment by thiagozf** [comment]
@cofin I'm using Google BigQuery and a forked version of [`sqlalchemy-bigquery`](https://github.com/googleapis/python-bigquery-sqlalchemy) to support SQLAlchemy>=2

**Comment by cofin** [comment]
> @cofin I'm using Google BigQuery and a forked version of [`sqlalchemy-bigquery`](https://github.com/googleapis/python-bigquery-sqlalchemy) to support SQLAlchemy>=2

Cool!  Is the fork public? I'd like to add in official tests for BQ when it supports 2.0. 

Also, I'll address the exception handling you reported.

**Comment by thiagozf** [comment]
@cofin Unfortunately it is not public 😢  Also, I've submitted a PR that should fix the issue.
