### ISSUE TITLE
Enhancement: make 302 the default status_code for Redirect

### ISSUE THREAD

**Issue by sfermigier** [litestar-org/litestar#2138]
### Summary

I wish `Redirect()` would have a default status_code of 302. This is, I believe, the most common use case.

### Basic Example

```
Redirect(url)
```
instead of
```
Redirect(url, status_code=HTTP_302_FOUND)
```

### Drawbacks and Impact

No impact on existing code.

Some people may use 302 by default when they actually meant to use something else.

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2138">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2138/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2138/pledge.svg">
</picture>
</a>

**Comment by Goldziher** [comment]
That makes sense
