### ISSUE TITLE
Bug: Using `structlog.dev.ConsoleRenderer` causes `TypeError: can only concatenate str (not "bytes") to str`

### ISSUE THREAD

**Issue by sykloid** [litestar-org/litestar#2151]
### Description

Adding an instance of `structlog.dev.ConsoleRenderer` to the `processors` parameter of a `StructLoggingConfig` causes an exception which doesn't appear if said processor is not present (the correct message is logged as JSON to stdout).

I've included one instance of the exception traceback but the exception is thrown multiple times, I believe this is because `log_exceptions="always"` causes a subsequent log of the first exception, which causes another log, etc.

### MCVE

```python
# Almost verbatim from https://docs.litestar.dev/2/usage/logging.html#using-structlog

from litestar import Litestar, Request, get
from litestar.logging import StructLoggingConfig
import structlog


@get("/")
async def my_router_handler(request: Request) -> None:
    request.logger.info("inside a request")
    return None


# Only change to base example, added two parameters to config.
logging_config = StructLoggingConfig(processors=[structlog.dev.ConsoleRenderer()], log_exceptions="always")

app = Litestar(route_handlers=[my_router_handler], logging_config=logging_config)
```

### Steps to reproduce

```bash
1. `litestar run`
2. `GET /`
```

### Logs

```bash
Traceback (most recent call last):
  File "/home/sykloid/src/scratch/litestar_test/.venv/lib/python3.11/site-packages/litestar/middleware/exceptions/middleware.py", line 159, in __call__
    await self.app(scope, receive, send)
  File "/home/sykloid/src/scratch/litestar_test/.venv/lib/python3.11/site-packages/litestar/routes/http.py", line 79, in handle
    response = await self._get_response_for_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sykloid/src/scratch/litestar_test/.venv/lib/python3.11/site-packages/litestar/routes/http.py", line 131, in _get_response_for_request
    response = await self._call_handler_function(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sykloid/src/scratch/litestar_test/.venv/lib/python3.11/site-packages/litestar/routes/http.py", line 160, in _call_handler_function
    response_data, cleanup_group = await self._get_response_data(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sykloid/src/scratch/litestar_test/.venv/lib/python3.11/site-packages/litestar/routes/http.py", line 208, in _get_response_data
    data = await route_handler.fn.value(**parsed_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sykloid/src/scratch/litestar_test/src/litestar_test/structlog_example.py", line 8, in my_router_handler
    request.logger.info("inside a request")
  File "/home/sykloid/src/scratch/litestar_test/.venv/lib/python3.11/site-packages/structlog/_log_levels.py", line 161, in meth
    return self._proxy_to_logger(name, event, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sykloid/src/scratch/litestar_test/.venv/lib/python3.11/site-packages/structlog/_base.py", line 205, in _proxy_to_logger
    return getattr(self._logger, method_name)(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sykloid/src/scratch/litestar_test/.venv/lib/python3.11/site-packages/structlog/_output.py", line 320, in msg
    until_not_interrupted(self._write, message + b"\n")
                                       ~~~~~~~~^~~~~~~
TypeError: can only concatenate str (not "bytes") to str
```

### Litestar Version

2.0.0rc1

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2151">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2151/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2151/pledge.svg">
</picture>
</a>

**Comment by sykloid** [comment]
I did a bunch more digging because I was bored, and found that I was able to replicate the issue with the regular `structlog.processors.JSONRenderer()`, if I left out the `serializer=default_json_serializer` parameter.

Is there a way to perform that serialization as a processor without rendering to string, so that a subsequent `ConsoleRenderer` can be used?

**Comment by provinzkraut** [comment]
@JacobCoffee can you take a look at this?

**Comment by Goldziher** [comment]
> I did a bunch more digging because I was bored, and found that I was able to replicate the issue with the regular `structlog.processors.JSONRenderer()`, if I left out the `serializer=default_json_serializer` parameter.
> 
> Is there a way to perform that serialization as a processor without rendering to string, so that a subsequent `ConsoleRenderer` can be used?

Dk you want to take this over?

**Comment by lsanpablo** [comment]
I'm not sure there's anything to do for this issue as these errors come from structlog itself. It seems like litestar's `StructLoggingConfig` provides reasonable defaults, and if a user wants to change the processors, they should change the `logger_factory` to one that's compatible with their selected processors. In this case `structlog.PrintLoggerFactory` works well.
OP's error replicated in structlog:
![replicated](https://github.com/litestar-org/litestar/assets/7145688/89fde7d9-709e-4b7e-8011-94a36a14340e)

Workaround:
![workaround](https://github.com/litestar-org/litestar/assets/7145688/842f3762-06c2-4898-9683-bfad4e32082e)

Workaround in OP's sample app
<img width="1227" alt="workaround_app" src="https://github.com/litestar-org/litestar/assets/7145688/e8c40dc2-88ee-40c2-aeb3-62d776eb280e">

**Comment by cesarmg1980** [comment]
given the above response from @lsanpablo can this still be considered as a bug?

**Comment by JacobCoffee** [comment]
I'm not sure, for now users can easily override that default logger factory with the one that works.

https://github.com/litestar-org/litestar/blob/770cfd8b37ed0d41ec46a2f1daaceecbf5f20dda/litestar/logging/config.py#L277 `BytesLoggerFactory` is expecting only bytes, changing it to `PrintLoggerFactory` fixes it but is seems to be breaking until 3.x. Maybe we can add a default processor to convert str/bytes to the expected output format?
@litestar-org/members thoughts?

**Comment by guacs** [comment]
> I'm not sure, for now users can easily override that default logger factory with the one that works.
> 
> https://github.com/litestar-org/litestar/blob/770cfd8b37ed0d41ec46a2f1daaceecbf5f20dda/litestar/logging/config.py#L277
> 
> `BytesLoggerFactory` is expecting only bytes, changing it to `PrintLoggerFactory` fixes it but is seems to be breaking until 3.x. Maybe we can add a default processor to convert str/bytes to the expected output format?
> @litestar-org/members thoughts?

I agree with @cesarmg1980. I don't think this is a bug. If the user is modifying the processors, then I think they are also responsible for updating any other config values that may be needed (`logger_factory` in this case). Maybe this specific case could be documented, since using `ConsoleRenderer` during development is common.

**Comment by PashaWNN** [comment]
It's still reproduced in 2.16.0

My config:
```python
def drop_healthcheck_logs(_, __, event_dict):
    if 'healthcheck' in event_dict.get('path', ''):
        raise structlog.DropEvent
    return event_dict


def get_litestar_app() -> Litestar:
    litestar_app = Litestar(
        route_handlers=[handle_cdek_webhook_view, healthcheck_view],
        dependencies={'cdek_client': CdekClient},
        on_startup=[ensure_webhook],
        plugins=[
            StructlogPlugin(
                config=StructlogConfig(
                    structlog_logging_config=StructLoggingConfig(
                        processors=[drop_healthcheck_logs] + default_structlog_processors()
                    )
                )
            )
        ],
    )
    return litestar_app
```
