### ISSUE TITLE
Bug: beanie.PydanticObjectId cannot be a path parameter anymore

### ISSUE THREAD

**Issue by gsakkis** [litestar-org/litestar#2158]
### Description

I tried upgrading from v2.0.0beta2 to the latest main and found that using a `beanie.PydanticObjectId` as path parameter raises validation error. Using git bisect I traced it down to b32088f6.

### MCVE

```python
from beanie import PydanticObjectId
from litestar import Litestar, get


@get("/test/{id:str}")
async def test(id: PydanticObjectId) -> dict[str, PydanticObjectId]:
    return {"id": id}


app = Litestar(route_handlers=[test], type_encoders={PydanticObjectId: str})
```

### Steps to reproduce

Right before b32088f6 (66700b7b):
```bash
curl -s 'localhost:8000/test/64d6088586da7ecbfe53340f' | jq .
{
  "id": "64d6088586da7ecbfe53340f"
}
```

At b32088f6:
```bash
curl -s 'localhost:8000/test/64d6088586da7ecbfe53340f' | jq .
{
  "status_code": 400,
  "detail": "Validation failed for GET http://localhost:8000/test/64d6088586da7ecbfe53340f",
  "extra": [
    {
      "message": "Unsupported type: <class 'str'>",
      "key": "id"
    }
  ]
}
```
```


### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Litestar Version

b32088f6

### Platform

- [ ] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2158">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2158/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2158/pledge.svg">
</picture>
</a>

**Comment by Goldziher** [comment]
Hi, have you tried defining a type decoder for the beanie type?

**Comment by gsakkis** [comment]
No, how? I don't see a `type_decoders` parameter. 

Also why I have to do something extra? The beanie type validates strings already:
```py
In [1]: from beanie import PydanticObjectId

In [2]: PydanticObjectId("64d6088586da7ecbfe53340f")
Out[2]: ObjectId('64d6088586da7ecbfe53340f')

In [3]: PydanticObjectId("123")
...
InvalidId: '123' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string
```

**Comment by Goldziher** [comment]
> No, how? I don't see a `type_decoders` parameter. 
> 
> Also why I have to do something extra? The beanie type validates strings already:
> ```py
> In [1]: from beanie import PydanticObjectId
> 
> In [2]: PydanticObjectId("64d6088586da7ecbfe53340f")
> Out[2]: ObjectId('64d6088586da7ecbfe53340f')
> 
> In [3]: PydanticObjectId("123")
> ...
> InvalidId: '123' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string
> ```

Msgspec doesn't know how to handle this type. 

There is a `type_decoders` and `type_encoders` kwargs on all levels of the app.

**Comment by Goldziher** [comment]
- You need encoders for request and decoders for marshaling json

**Comment by gsakkis** [comment]
Ah I was at the breaking commit, `type_decoders` was added later. I'll dig in the code as there are no docs for it afaict.

**Comment by provinzkraut** [comment]
>  I'll dig in the code as there are no docs for it afaict.

Yeah, we need to add those. We're lacking docs for a lot of serialisation intricacies in general.

**Comment by gsakkis** [comment]
This seems to do the trick:
```py
app = Litestar(
    route_handlers=[test],
    type_encoders={PydanticObjectId: str},
    type_decoders=[
        (
            lambda target_type: issubclass(target_type, PydanticObjectId),
            lambda target_type, value: target_type.validate(value),
        )
    ],
)
```

Wondering if it would be possible to support automatically all [Pydantic custom data types with `__get_validators__`](https://docs.pydantic.dev/1.10/usage/types/#classes-with-__get_validators__) and/or the equivalent for Pydantic v2.

**Comment by provinzkraut** [comment]
> Wondering if it would be possible to support automatically all [Pydantic custom data types with `__get_validators__`](https://docs.pydantic.dev/1.10/usage/types/#classes-with-__get_validators__) and/or the equivalent for Pydantic v2.

Should be. We'd just need to add logic for those to the [Pydantic plugin](https://github.com/litestar-org/litestar/blob/48e0f074b2b34e4516c31fdf25e0f8d541817aec/litestar/contrib/pydantic/pydantic_init_plugin.py#L73).

**Comment by gsakkis** [comment]
Thanks, closing this.
