### ISSUE TITLE
Enhancement: Making litestar compatible with pyinstaller

### ISSUE THREAD

**Issue by Vuizur** [litestar-org/litestar#2172]
### Summary

I am currently trying to compile a litestar server to an .exe file. For this I am using pyinstaller, but it does currently not work.

For illustration, I slightly modified the hello-world-example and added pyinstaller: https://github.com/Vuizur/litestar-hello-world.

app.py is now:

```python
"""Minimal Litestar application."""
from asyncio import sleep
from typing import Any

from litestar import Litestar, get
import uvicorn


@get("/async")
async def async_hello_world() -> dict[str, Any]:
    """Route Handler that outputs hello world."""
    await sleep(0.1)
    return {"hello": "world"}


@get("/sync", sync_to_thread=False)
def sync_hello_world() -> dict[str, Any]:
    """Route Handler that outputs hello world."""
    return {"hello": "world"}


app = Litestar(route_handlers=[sync_hello_world, async_hello_world])

if __name__ == "__main__":
    uvicorn.run(app)
```

This works from Python, but when I compile the exe with `pyinstaller app.py` and try to run it, I get the following error:

```
Traceback (most recent call last):
  File "logging\config.py", line 390, in resolve
AttributeError: module 'litestar.logging' has no attribute 'standard'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "logging\config.py", line 392, in resolve
ModuleNotFoundError: No module named 'litestar.logging.standard'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "logging\config.py", line 565, in configure
  File "logging\config.py", line 723, in configure_handler
  File "logging\config.py", line 399, in resolve
  File "logging\config.py", line 392, in resolve
ValueError: Cannot resolve 'litestar.logging.standard.QueueListenerHandler': No module named 'litestar.logging.standard'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 22, in <module>
  File "litestar\app.py", line 435, in __init__
  File "litestar\logging\config.py", line 229, in configure
  File "logging\config.py", line 810, in dictConfig
  File "logging\config.py", line 572, in configure
ValueError: Unable to configure handler 'queue_listener'
[19004] Failed to execute script 'app' due to unhandled exception!
```

This can be fixed by creating `hook-litestar.py` and pasting the following code:
```python
from PyInstaller.utils.hooks import collect_submodules
hiddenimports = collect_submodules('litestar.logging')
```
and then running `pyinstaller --additional-hooks-dir=. app.py`

However, it would be pretty cool if litestar distributed these hooks itself. I don't know the exact steps to do this, but this page describes it: https://pyinstaller.org/en/stable/hooks.html# 

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2172">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2172/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2172/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
+1 for a separate package

**Comment by Vuizur** [comment]
The package https://github.com/iancleary/pyinstaller-fastapi is something like an example project. As far as I can understand it is pretty trivial what it is doing, basically adding 
```
if __name__ == "__main__":
    uvicorn.run(app)
```
to app.py. It does define a hook, but that one seems to be obsolete and has been added directly to pyinstaller-hooks-contrib. 

So I think the best thing seems to add the hook I gave to https://github.com/pyinstaller/pyinstaller-hooks-contrib. I could look into it...

**Comment by JacobCoffee** [comment]
That sounds like a cool addition to our external packages! 😄 Let us know if you need anything in particular, I am going to close this.  When you get it working you can put up a PR to https://github.com/litestar-org/awesome-litestar/ so that we can have it public.

**Comment by Vuizur** [comment]
I added the hook to pyinstaller, so now it works out of the box: https://github.com/pyinstaller/pyinstaller-hooks-contrib/pull/625. You only need 
```python 
if __name__ == "__main__":
    uvicorn.run(app)
```
now.

**Comment by cofin** [comment]
+1 to this.  Very cool!
