### ISSUE TITLE
Bug: pydantic validations aren't being handled by DTOs

### ISSUE THREAD

**Issue by aorith** [litestar-org/litestar#2190]
### Description

In the documentation of Litestar we have:

> When a value fails pydantic validation, the result will be a ValidationException with the extra key set to the pydantic validation errors. Thus, this data will be made available for the API consumers by default.

But when combined with DTO's in a post request, if a pydantic validation fails the exception is not handled and the client receives an InternalServerError (500) instead of a BadRequest (400):

```
    __pydantic_self__.__pydantic_validator__.validate_python(data, self_instance=__pydantic_self__)
pydantic_core._pydantic_core.ValidationError: 1 validation error for User
name
  String should have at most 2 characters [type=string_too_long, input_value='abc', input_type=str]
    For further information visit https://errors.pydantic.dev/2.2/v/string_too_long

Status code: 500
```

If the validation isn't handled by pydantic (or at least it isn't handled **first** by pydantic) it works, for example an Enum validation returns a proper 400 status code because `msgspec` catches it first:

```python
from enum import Enum

class NameEnum(str, Enum):
    a = "A"
    b = "B"

# (replace the User class of the example with this)
class User(BaseModel):
    name: NameEnum
```

Output for incorrect Enum:

```
  File ".../.venv/lib64/python3.11/site-packages/litestar/serialization/msgspec_hooks.py", line 191, in decode_json
    raise SerializationException(str(msgspec_error)) from msgspec_error
litestar.exceptions.base_exceptions.SerializationException: Invalid enum value 'abc' - at `$.name`


...

  File ".../.venv/lib64/python3.11/site-packages/litestar/routes/http.py", line 186, in _get_response_data
    raise ClientException(str(e)) from e
litestar.exceptions.http_exceptions.ClientException: 400: Invalid enum value 'abc' - at `$.name`
```

### MCVE

```python
from litestar import Litestar, post
from litestar.contrib.pydantic import PydanticDTO
from litestar.testing import TestClient
from pydantic import BaseModel, Field


class User(BaseModel):
    name: str = Field(max_length=2)


UserDTO = PydanticDTO[User]


@post("/user", dto=UserDTO, sync_to_thread=False)
def create_user(data: User) -> User:
    return data


with TestClient(Litestar([create_user], debug=True)) as client:
    response = client.post("/user", json={"name": "abc"})
    print(response.text)
    print(f"Status code: {response.status_code}")
    assert response.status_code == 201
```

### Steps to reproduce

```bash
1. Execute the MCVE
```

### Litestar Version

2.0.0rc1

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2190">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2190/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2190/pledge.svg">
</picture>
</a>

**Comment by guacs** [comment]
If no one else is looking into this, could someone assign this to me please?
