### ISSUE TITLE
Docs: Broken link for Flask Docs

### ISSUE THREAD

**Issue by wideltann** [litestar-org/litestar#2206]
### Description

The link to the static file docs is incorrect in the "Note" at this link [https://docs.litestar.dev/2/migration/flask.html#static-files](https://docs.litestar.dev/2/migration/flask.html#static-files).

It should redirect to [https://docs.litestar.dev/2/usage/static-files.html#static-files](https://docs.litestar.dev/2/usage/static-files.html#static-files).

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2206">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2206/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2206/pledge.svg">
</picture>
</a>

**Comment by JacobCoffee** [comment]
Thanks! Would you like to provide a PR?

**Comment by wideltann** [comment]
Sure can!

**Comment by wideltann** [comment]
Sorry this slipped off my radar, will get this sorted out tomorrow!

**Comment by ctrl-Felix** [comment]
I believe this has been fixed in 384fce6ba1ad7f5e390845973a1c3fedc880336e and can be closed
