### ISSUE TITLE
Refactor: remove `app` parameter from `Response.to_asgi_response`

### ISSUE THREAD

**Issue by provinzkraut** [litestar-org/litestar#2217]
The parameter `app` of `Response.to_asgi_response` is unused and redundant because it will always be the same as `request.app`.

It should be deprecated and marked for removal in the next major version.

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2217">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2217/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2217/pledge.svg">
</picture>
</a>

**Comment by wevonosky** [comment]
@Goldziher would love to pick this up as my first contribution. The nature of the change isn't clear to me, should this issue just be creating a deprecation warning about the app parameter of the `to_asgi_response` or should it go ahead and remove it?

**Comment by provinzkraut** [comment]
This change is going to be happen in two stages:

1. Now: Add a deprecation warning for the parameter
2. In version 3: Remove the parameter

**Comment by wevonosky** [comment]
Thanks, one last question...we want to notify users that providing app will be deprecated in that function and that app will be inferred from `request`....but `request` isn't used in that method either. Feels like we should warn about removing them both yeah?

**Comment by provinzkraut** [comment]
> but `request` isn't used in that method either.

It's currently not, but `app` is used, and we'll need to use `request` to get `app`, so it *will* be used after this change.
