### ISSUE TITLE
Infrastructure: replace poetry

### ISSUE THREAD

**Issue by Goldziher** [litestar-org/litestar#2219]
### Summary

Following multiple discussions and given some repeated issues with poetry we decided to switch from poetry to using PDM + Hatchling

The tasks are as follow:

1. replace poetry with PDM for dependency management. This includes the configuration in pyproject, the logic in the github actions, and the contributions guidelines.
2. replace poetry with Hatchling for releasing litestar. This includes the configuration in pyproject, the contributions guidelines and the release github action. 

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2219">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2219/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2219/pledge.svg">
</picture>
</a>

**Comment by cofin** [comment]
I think we should start with the foundation that @JacobCoffee has [here](https://github.com/JacobCoffee/niapi/blob/main/pyproject.toml)

**Comment by benjamin-kirkbride** [comment]
Does PDM necessitate using PDM to contribute in the same way that Poetry does, or is it possible to just `pip install -e ".[dev]"` (or similar) to start hacking?

**Comment by JacobCoffee** [comment]
I know that you can do `pip install -e .`.. without `requirements.txt` file, I am not 100% sure on passing the optional extras though.. I didn't think Poetry was able to do this either? @provinzkraut @cofin

**Comment by provinzkraut** [comment]
Afaik there's no standard for these "dev dependencies" (yet), so pip won't be able to install them.

**Comment by benjamin-kirkbride** [comment]
There is a standard for it, but you are correct that Poetry doesn't (or at least didn't) use it.

https://packaging.python.org/en/latest/specifications/declaring-project-metadata/?highlight=optional-dependencies#dependencies-optional-dependencies

**Comment by benjamin-kirkbride** [comment]
Here is an example of it in use: https://github.com/pythonarcade/arcade/blob/development/pyproject.toml#L39

**Comment by JacobCoffee** [comment]
This is true for optional package dependencies, but PDM manages them outside of the scope of the standard as well, similar to poetry

https://pdm.fming.dev/latest/usage/dependency/#add-development-only-dependencies
```toml
[tool.pdm.dev-dependencies]
lint = [
    "flake8",
    "black"
]
test = ["pytest", "pytest-cov"]
doc = ["mkdocs"]
```

**Comment by benjamin-kirkbride** [comment]
@JacobCoffee it seems like it actually is possible with PDM: https://pdm.fming.dev/latest/usage/dependency/#add-dependencies:~:text=optional%20groups%20in-,optional%2Ddependencies,-%2C%20even%20before%20the

**Comment by nandoflorestan** [comment]
What is the main reason to move away from poetry?  This issue does not say.

**Comment by JacobCoffee** [comment]
I believe performance issues (dependency resolution time) and bugs with developmental dependency installs were to of the key reasons.
