### ISSUE TITLE
Bug: Calling exists() with filters doesn't work SQLAlchemy contrib

### ISSUE THREAD

**Issue by nielsvanhooy** [litestar-org/litestar#2221]
### Description

Hi There.

i was testing something out and came across something of which i think is unintended.

in the file litestar/contrib/sqlalchemy/repository/_async.py  specifically the function exists()

the function eventually calls self.count method which accepts filters.
however the function exists() doesn't accept *args ( or *filters in this case). (this is the same for the sync variant).
I tested it out with overriding  this function and the behaviour that i was expecting seems to work then with filters.

signature of the function count() that exists() calls
```py
    async def count(
        self,
        *filters: FilterTypes,
        statement: Select[tuple[ModelT]] | StatementLambdaElement | None = None,
        **kwargs: Any,
    ) -> int:
```

original code:
```py
    async def exists(self, **kwargs: Any) -> bool:
        """Return true if the object specified by ``kwargs`` exists.

        Args:
            **kwargs: Identifier of the instance to be retrieved.

        Returns:
            True if the instance was found.  False if not found..

        """
        existing = await self.count(**kwargs)
        return existing > 0
```

overrided and working
```py
    async def exists(self, *filters: FilterTypes, **kwargs: Any) -> bool:
        """Return true if the object specified by ``kwargs`` exists.

        Args:
            *filters: Types for specific filtering operations.
            **kwargs: Identifier of the instance to be retrieved.

        Returns:
            True if the instance was found.  False if not found..

        """
        existing = await self.count(*filters, **kwargs)
        return existing > 0
```

just wanted to know if was a bug/oversight for this functionality so that i can open a pull request.

### MCVE

```python
# Your MCVE code here
```

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Litestar Version

2.0

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2221">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2221/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2221/pledge.svg">
</picture>
</a>

**Comment by cofin** [comment]
Thanks for reporting.  A fix is incoming for this.
