### ISSUE TITLE
Can't use Msgspec Struct in handler arguments as request body

### ISSUE THREAD

**Issue by FHU-yezi** [litestar-org/litestar#2249]
I want to use Msgspec for both request and response, like this:

```python
from litestar import Litestar, Response, post
from msgspec import Struct


class TestRequest(Struct):
    number: int


class TestResponse(Struct):
    result: int


@post("/test")
async def post_test_handler(data: TestRequest) -> Response:
    return Response(TestResponse(result=data.number))


app = Litestar([post_test_handler])
```

and this command:

```shell
uvicorn main:app --reload
```

but I got the error below:

```
{
	"status_code": 400,
	"detail": "Validation failed for POST http://localhost:6666/test",
	"extra": [
		{
			"message": "Expected `object`, got `null`",
			"key": "data",
			"source": "body"
		}
	]
}
```

So I read the doc again, it said:

> The type of data an be any supported type, including
> - [dataclasses](https://docs.python.org/3/library/dataclasses.html#dataclasses.dataclass)
> - [TypedDicts](https://docs.python.org/3/library/typing.html#typing.TypedDict)
> - Pydantic models
> - Arbitrary stdlib types
> - Typed supported via [plugins](https://docs.litestar.dev/2/usage/plugins.html)

[Requests - Litestar Framework](https://docs.litestar.dev/2/usage/requests.html#request-body)

Seems that Litestar does not support Msgspec for request body?

I searched Issues and found this: #1929 

Changed code:

```python
from litestar import Litestar, Response, post
from litestar.dto.msgspec_dto import MsgspecDTO
from msgspec import Struct


class TestRequest(Struct):
    number: int


class TestResponse(Struct):
    result: int


@post("/test", dto=MsgspecDTO[TestRequest])
async def post_test_handler(data: TestRequest) -> Response:
    return Response(TestResponse(result=data.number))


app = Litestar([post_test_handler])
```

but new error occured:

```
{
	"status_code": 400,
	"detail": "Input data was truncated"
}
```

No further info I can found about this error message.

Maybe I can write a plugin and convert Msgspec Struct to DTO, but the part about this in the doc: [Plugins - Litestar Framework](https://docs.litestar.dev/2/usage/plugins.html#serializationpluginprotocol) is too complex that I don't know how to do this.

My expected behavior is:

1. When I use the code in the first code block, it should work and return `{"result": <number>}`.
2. When I know how to write the plugin and set it up in the Litestar app class, the code should work, same as 1.
3. With some edit, code block 2 can work and return the correct response.

Environment:

- OS: Manjaro Linux (Arch Based), with kernel 6.5.0-1
- Python: 3.11.3
- Litestar: 2.0.1
- Msgspec: 0.18.2
- Uvicorn: 0.23.2 with Cython 3.11.3

**Comment by Alc-Alc** [comment]
I do not believe this is an issue. The 400 response status indicated you have not sent the required fields in your POST request. Can you how you are making the request?

**Comment by FHU-yezi** [comment]
I use Insomnia ( an API manage tool like Postman ) to send the request.

I can make sure that this error is not belong to my mistake because:

1. I change the post decorator to get, and directly put the arguments in handler function, then use Insomnia to send request, everything is OK.
2. Use cURL to send request lead to the same issue, the commend is shown below.

```shell
curl -X POST "http://localhost:8000/test" -d "{'number': 2}"
```

**Comment by Alc-Alc** [comment]
I am on the same version and `curl -X POST "http://localhost:8000/test" -d '{"number": 2}'` gives me `{"result":2}`. I am using the same code you posted at the beginning.

```python
from litestar import Litestar, Response, post
from msgspec import Struct


class TestRequest(Struct):
    number: int


class TestResponse(Struct):
    result: int


@post("/test")
async def post_test_handler(data: TestRequest) -> Response:
    return Response(TestResponse(result=data.number))


app = Litestar([post_test_handler])
```

**Comment by FHU-yezi** [comment]
I can get the same correct result on my Ubuntu server, will try again once I have time, maybe a couple of hours later.

Thanks for your quickly reply.

**Comment by FHU-yezi** [comment]
Finally i got the correct answer, the problem maybe is my shell, which is zsh treat " and ' as different syntax element, so one of my cURL commend lead to error.

We should also change our doc to show that Msgspec are also supported to define a request body, as same as dataclasses, TypeDicts and Pydantic Models.

If someone is interest in this doc improvment, a new issue may be created.

Thanks all the team member and other guys who helped me to solve the problem, Happy Coding :)

**Comment by FHU-yezi** [comment]
Finally i got the correct answer, the problem maybe is my shell, which is zsh treat " and ' as different syntax elements, so one of my cURL commend leads to error.

We should also change our doc to show that Msgspec is also supported to define a request body, as same as dataclasses, TypeDicts and Pydantic Models.

If someone is interest in this doc improvment, a new issue may be created.

Thanks all the team member and other guys who helped me to solve the problem, Happy Coding :)
