### ISSUE TITLE
Bug: Incorrectly serialized examples in OpenAPI schema

### ISSUE THREAD

**Issue by floxay** [litestar-org/litestar#2272]
### Description

The provided example values are serialized incorrectly into the OpenAPI schema.
![image](https://github.com/litestar-org/litestar/assets/57007485/609155d3-a026-40c8-8816-019af7bab381)

The issue seem to be that due to inheritance simply the [`BaseSchemaObject.to_schema()` method is called for `Example` instances during the schema serialization](https://github.com/litestar-org/litestar/blob/3b3ed502de26bb945857fa8b94af45afdde7e075/litestar/openapi/spec/base.py#L22-L23), because of this all of the fields of [`Example`](https://github.com/litestar-org/litestar/blob/3b3ed502de26bb945857fa8b94af45afdde7e075/litestar/openapi/spec/example.py#L9-L33) ends up being serialized under the example "section" instead of just the value of the [`Example.value`](https://github.com/litestar-org/litestar/blob/3b3ed502de26bb945857fa8b94af45afdde7e075/litestar/openapi/spec/example.py#L20-L25) field.

### URL to code causing the issue

https://github.com/litestar-org/litestar/blob/3b3ed502de26bb945857fa8b94af45afdde7e075/litestar/openapi/spec/base.py#L22-L23

### MCVE

```python
from typing import Annotated
from msgspec import Struct, Meta
from litestar import Litestar, post


class TestBody(Struct):
    field1: Annotated[str, Meta(examples=["the answer"])]
    field2: Annotated[int, Meta(examples=[42])]


@post(sync_to_thread=False)
def test(data: TestBody) -> None:
    ...


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app=Litestar(route_handlers=[test]), port=8080)
```

### Steps to reproduce

```bash
1. Run the MCVE
2. Open any of the auto-generated docs (redoc, swagger, elements)
3. See the request or schema example (depending on docs)
```

### Litestar Version

2.0.1

### Platform

- [ ] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2272">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2272/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2272/pledge.svg">
</picture>
</a>

**Comment by abdulhaq-e** [comment]
Hello

Sorry that I don't have much experience with OpenAPI yet. I would like to clarify that the correct serialization according to the OpenAPI specs is:

```json
{
    "field1": "the answer",
    "field2": 42
}
```

Is that correct?

**Comment by Goldziher** [comment]
> Hello
> 
> Sorry that I don't have much experience with OpenAPI yet. I would like to clarify that the correct serialization according to the OpenAPI specs is:
> 
> ```json
> {
>     "field1": "the answer",
>     "field2": 42
> }
> ```
> 
> Is that correct?

you can see the openapi spec: https://spec.openapis.org/oas/latest.html#requestBodyObject

**Comment by Goldziher** [comment]
I am actually not certain this bug report is correct- https://spec.openapis.org/oas/latest.html#exampleObject. We need a reproduction of this with openapi 3.1 schema that fails an up to date validator.

**Comment by floxay** [comment]
Yes, this is a little bit confusing but I believe this is incorrect:
- the "Try it out" feature fails on both Swagger and Spotlight Elements, which is not really suprising as it tries to send the above JSON which is obviously incorrect.
<details>
<summary>Images of the error (click to expand)</summary>

![image](https://github.com/litestar-org/litestar/assets/57007485/1133bddc-2486-47ee-bbe7-530261681d18)
![image](https://github.com/litestar-org/litestar/assets/57007485/26ca6232-df4e-4ab8-954a-b3d168825854)
</details>

- the above links to the OpenAPI specification refer to Example Objects and examples in the Request Body, however this issue is I believe related to examples in Schemas Objects (https://spec.openapis.org/oas/latest.html#schema-object) as the generated JSON looks like this:

![image](https://github.com/litestar-org/litestar/assets/57007485/8d7ad7bc-8b8e-4f3c-a488-f7c8454c457f)

**Comment by floxay** [comment]
Based on "Edit 2": https://github.com/litestar-org/litestar/compare/main...floxay:litestar:exp/openapi-example-serialization
Seems to work but unsure about the pydantic v2 json_schema_extra callable.

**Comment by Goldziher** [comment]
there should be a field called `examples`: [...], I think. So this is a bug. 

PR with a fix and proper tests is highly welcome.

**Comment by Goldziher** [comment]
@floxay do you want to take this over?

**Comment by floxay** [comment]
Sure, I think I can do it later today.

**Comment by floxay** [comment]
Unfortunately I still have no clue how to resolve the [`JsonSchemaExtraCallable`](https://github.com/pydantic/pydantic/blob/ed009ba0fa908b06fc2d3735b633885c4795096c/pydantic/config.py#L20-L23) in Pydantic's [`ConfigDict.json_schema_extra`](https://github.com/pydantic/pydantic/blob/ed009ba0fa908b06fc2d3735b633885c4795096c/pydantic/config.py#L115-L116).

Additionally, while I were correcting some tests I've also noticed that the `examples` field of OpenAPI [`Parameter Objects`](https://spec.openapis.org/oas/v3.1.0#fixed-fields-9) is supposed to be a `string` to `Example Object | Reference Object` mapping, meaning the list [`litestar.Parameter`](https://github.com/litestar-org/litestar/blob/main/litestar/params.py#L164-L172) takes is somewhat problematic as example names cannot be provided to build the map.
Plus, currently these examples provided as `Example` objects are serialized into ParamObj.schema.examples rather than ParamObj.examples:
- ParamObj.schema is a Schema Object, "examples" here is a list of raw example values, values supplied here ***will not*** show up in Swagger for Parameter Objects (*meanwhile a single example value under the deprecated "example" field would, somewhat weird...*)
- ParamObj.examples is the above mentioned map which allows Example Object, values supplied here ***will*** show up in Swagger for Parameter Objects

Due to the above `tests/unit/test_openapi/test_parameters.py::test_create_parameters` still fails in #2299
