### ISSUE TITLE
Docs: Marketing Site 404's

### ISSUE THREAD

**Issue by benjamin-kirkbride** [litestar-org/litestar#2273]
### Summary

The following URLs found on the front of the marketing site (https://litestar.dev/) 404:
- https://docs.litestar.dev/2/usage/the-litestar-app.html
- https://docs.litestar.dev/2/usage/contrib/sqlalchemy/index.html
- https://docs.litestar.dev/2/usage/route-handlers.html

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2273">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2273/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2273/pledge.svg">
</picture>
</a>

**Comment by abdulhaq-e** [comment]
Thanks, this will be fixed after merging: https://github.com/litestar-org/litestar.dev/pull/16
