### ISSUE TITLE
Docs: examples for accessing template engine instance don't run

### ISSUE THREAD

**Issue by wevonosky** [litestar-org/litestar#2274]
### Description

There are two examples in the docs [here](https://github.com/litestar-org/litestar/blob/main/docs/examples/templating/engine_instance_jinja.py#L4) and [here](https://github.com/litestar-org/litestar/blob/main/docs/examples/templating/engine_instance_mako.py#L4) which show how to access the template engine given construction from `TemplateConfig`. These examples are missing a required keyword argument `directory` into `TemplateConfig` and won't run as is. 

### URL to code causing the issue

https://github.com/litestar-org/litestar/blob/main/docs/examples/templating/engine_instance_mako.py#L4

### MCVE

```python
from litestar.contrib.jinja import JinjaTemplateEngine
from litestar.template.config import TemplateConfig

template_config = TemplateConfig(engine=JinjaTemplateEngine)
```

### Steps to reproduce

```bash
1. Go to `docs/examples/templating/engine_instance_jinja.py`
2. Attempt to run the code
```

### Litestar Version

2.0.0

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2274">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2274/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2274/pledge.svg">
</picture>
</a>

**Comment by Goldziher** [comment]
PR is welcome.

**Comment by wevonosky** [comment]
Looks like this was addressed in [2250](https://github.com/litestar-org/litestar/pull/2250)
