### ISSUE TITLE
Docs: Make Async Note More Clear

### ISSUE THREAD

**Issue by benjamin-kirkbride** [litestar-org/litestar#2275]
### Summary

On the page: https://docs.litestar.dev/2/topics/sync-vs-async.html

There is a note which states:

> Since “blocking” is about the flow of execution, one might think of await as blocking as well; the execution will not proceed past it until the awaitable has been resolved, which fits the definition of the term. However, since at the same time other parts of the program (more precisely, other parts currently waiting at an await) are allowed to proceed, this is not considered blocking and usually referred to as “waiting”.

Should it instead say "more precisely, other parts **which are not** currently waiting at an await"?

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2275">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2275/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2275/pledge.svg">
</picture>
</a>

**Comment by Goldziher** [comment]
pr welcome

**Comment by Goldziher** [comment]
also @benjamin-kirkbride - feel free to start a PR for such things without an issue.

**Comment by provinzkraut** [comment]
> Should it instead say "more precisely, other parts which are not currently waiting at an await"?

Not really. Maybe the whole thing needs to be reworded if this can be easily misunderstood.
What this is trying to say is that when something reaches an `await`, that task may be temporarily suspended, and another task, which had been suspended previously at an `await` may be resumed and run until the next `await`.

**Comment by benjamin-kirkbride** [comment]
@Goldziher I'm happy to create PR's for changes, but I wasn't entirely sure that I was correct about this one, and as @provinzkraut pointed out it seems like perhaps the phrasing needs to be reworked.

If I am not sure about a change, should I make an issue or a PR which the discussion then takes place on??

**Comment by provinzkraut** [comment]
> If I am not sure about a change, should I make an issue or a PR which the discussion then takes place on?

I think in this case it's fine if you just open a PR with your suggestion for a fix (=
