### ISSUE TITLE
Bug: Calling repository list() with basic select statement doesn't work as expected SQLAlchemy contrib

### ISSUE THREAD

**Issue by nielsvanhooy** [litestar-org/litestar#2281]
### Description

Bug: Calling repository list() with basic select statement doesn't work SQLAlchemy contrib

Hi there.

i came across an bug within the SQLAlchemy contrib.

i was making a simple select statement 

```py
statement = select(User.name, User.last_name)
```
then i would call the list() function in file: contrib/sqlalchemy/repository/_async.py line 796.

the expected result would have been

```py
[('test_name', 'test_last_name'), ('test_name_two', 'test_last_name_two')]
```
however since the function list() works with .scalars() this would return:

```py
['test_name', 'test_name_two']
```

by using scalars(), SQLAlchemy returns a different "results" object that only iterates over the first value of each row. if the query would have returned multiple values per row, then the additional values in each row are discarded.

i have created an PR for this. 
i did ran into some typing problems there but ill revert to that in the PR.

### Litestar Version

main

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2281">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2281/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2281/pledge.svg">
</picture>
</a>

**Comment by cofin** [comment]
@nielsvanhooy, the repository is mainly focused on using the ORM pieces of SQLAlchemy.  I think the example above is a core statement. That said, it would be helpful to have something like this work.

Out of curiosity, if you change your statement to the following, what happens?
```python
statement = select(User).options(load_only(User.name, User.last_name))
```

I'll look into other options as well.
