### ISSUE TITLE
Bug: serializer not working with misleading message 

### ISSUE THREAD

**Issue by 0xSwego** [litestar-org/litestar#2288]
### Description

I had some problems with a serializer not working, and displaying an error message I couldn't decipher.

The issue was a SQLAlchemy relationship that was defined using a string type instead of the type itself:
`conditions: Mapped[list["AlertTemplateCondition"]] = relationship(back_populates="alert_template")`

When I was trying to serialize this object and its children, this error was raised:
```
Traceback (most recent call last):
  File "/home/0xSwego/projects/litestar-backend-template/.venv/lib/python3.10/site-packages/litestar/serialization/msgspec_hooks.py", line 141, in encode_json
    return msgspec.json.encode(value, enc_hook=serializer) if serializer else _msgspec_json_encoder.encode(value)
  File "/home/0xSwego/projects/litestar-backend-template/.venv/lib/python3.10/site-packages/litestar/serialization/msgspec_hooks.py", line 88, in default_serializer
    raise TypeError(f"Unsupported type: {type(value)!r}")
TypeError: Unsupported type: <class 'app.domain.alerts.models.AlertTemplateCondition'>
```

Removing the quotes from the type fixed the issue:
`conditions: Mapped[list[AlertTemplateCondition]] = relationship(back_populates="alert_template")`

It'd be great if the right serializer was found even if the type is written in quotes.

### MCVE

Models:

```py
class AlertTemplate(orm.DatabaseModel):
    __tablename__ = "alert_templates"  # type: ignore[assignment]
    
    conditions: Mapped[list["AlertTemplateCondition"]] = relationship(back_populates="alert_template")

class AlertTemplateCondition(orm.DatabaseModel, orm.AuditColumns):
    __tablename__ = "alert_template_conditions"  # type: ignore[assignment]

    alert_template_id: Mapped[UUID] = mapped_column(ForeignKey("alert_templates.id"))
    alert_template: Mapped[AlertTemplate] = relationship()
```

DTOs:
```py
class AlertTemplateDTO(SQLAlchemyDTO[AlertTemplate]):
    config = dto.config(max_nested_depth=1)

class AlertTemplateConditionDTO(SQLAlchemyDTO[AlertTemplateCondition]):
    config = dto.config(max_nested_depth=0)
```

Controller:
```py
class AlertTemplatesController(Controller):
    """Handles the interactions within the AlertTemplate objects."""

    dependencies = {"alert_template_service": provide_alert_template_service}
    return_dto = AlertTemplateDTO

    @get(
        operation_id="ListAlertTemplates",
        name="alert_templates:list",
        summary="List Alert Templates",
        path=urls.ALERT_TEMPLATES_LIST,
    )
    async def list_alert_templates(
        self,
        alert_template_service: AlertTemplateService,
    ) -> OffsetPagination[AlertTemplate]:
        """List all alert templates"""
        results = await alert_template_service.list()
        return alert_template_service.to_dto(results)
```

### Litestar Version

2.0.1

### Platform

- [X] Linux
- [ ] Mac
- [X] Windows
- [ ] Other (Please specify in the description above)

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2288">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2288/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2288/pledge.svg">
</picture>
</a>

**Comment by guacs** [comment]
Could you provide a minimal reproduction of the bug?

**Comment by 0xSwego** [comment]
@guacs sure! I have taken the litestar-fullstack repo and added the code that is causing the problem:
https://github.com/0xSwego/litestar-fullstack/tree/master

I've also added a test that fails due to the error. Running `pytest tests/integration/test_alerts.py` will trigger it

**Comment by guacs** [comment]
@0xSwego I'm having some trouble reproducing this. Could you provide a minimal example with a minimal self-contained application (not the litestar-fullstack one)?

**Comment by provinzkraut** [comment]
@0xSwego any updates on this?

**Comment by 0xSwego** [comment]
@guacs I wouldn't know where to start from and it would take me a huge amount of time. If the issue cannot be reproduced because you have troubles with the code, I can close it.

**Comment by guacs** [comment]
> @guacs I wouldn't know where to start from and it would take me a huge amount of time. If the issue cannot be reproduced because you have troubles with the code, I can close it.

Let me try once more to reproduce this. If I'm not able to, then we can close it.

**Comment by 0xSwego** [comment]
@guacs you should be able to set up the whole project with the `make install` command (Unix friendly, unfortunately. I am on Windows and use WSL)

**Comment by provinzkraut** [comment]
@guacs any updates?

**Comment by guacs** [comment]
I'm closing this since I haven't been able to create an MCVE for this. If anyone faces this issue and can provide an MCVE, please feel free to reopen the issue.
