### ISSUE TITLE
Enhancement: Allow for class attribute / controller level dependency injection

### ISSUE THREAD

**Issue by ccrvlh** [litestar-org/litestar#2303]
### Summary

It's a fair use case to have a set of routes (class-based controller) that share the same dependency.
This is useful if in every route you want to access to headers, host or other request level information.

Currently, it seems the way of doing this would be to define the `dependencies` dictionary at the controller level, and manually annotate the handler with the dependency, in a controller with 5, 10, 15 routes it less than ideal.

Having a controller-level dependency definition allow you to access the dependency using `self.my_custom_dep`, which would give access to the dependency without the need to annotate every route.

### Basic Example

```python
class MyController(Controller):
    host_context: str = Provide(get_host_context)

    @get("/")
    def get_handler(self):
        self.host_context # you would have access to the host_context without having to declare it within the handler
        ... 
```

### Drawbacks and Impact

Dependency injection is already super flexible and can handle multiple levels of injection. But it's error prone, since it's mostly dependent on string manipulation (the dictionary keys), and very verbose (having to accept the same argument multiple times).

The obvious drawback is adding yet another way of handling dependency injection, and there would be a few issues to handle like: (1) at what level should this be injected, (2) handling `async` and `sync` dependencies, or dependencies on `async` and `sync` routes, (3) potentially implicit behavior since the handler would be resolving something without having the explicit annotation.

I do feel the pros outweight the cons, since it's clear enough that is a dependency because of the `Provide` (which btw it's great naming when compared to other frameworks), and it's predictable enough in the sense that if you're within a class, it makes se to be able to access the class attributes.

### Unresolved questions

How to implement. IIRC (it's been a while since I had this setup), `fastapi-utils` implemented this with the `cbv`. I _think_ this is the snippet that actually injects the dependencies (crediting [the project](https://fastapi-utils.davidmontague.xyz/), and the [snippet](https://github.com/dmontagu/fastapi-utils/blob/master/fastapi_utils/cbv.py#L56-L89)):

```python
def _init_cbv(cls: Type[Any]) -> None:
    """
    Idempotently modifies the provided `cls`, performing the following modifications:
    * The `__init__` function is updated to set any class-annotated dependencies as instance attributes
    * The `__signature__` attribute is updated to indicate to FastAPI what arguments should be passed to the initializer
    """
    if getattr(cls, CBV_CLASS_KEY, False):  # pragma: no cover
        return  # Already initialized
    old_init: Callable[..., Any] = cls.__init__
    old_signature = inspect.signature(old_init)
    old_parameters = list(old_signature.parameters.values())[1:]  # drop `self` parameter
    new_parameters = [
        x
        for x in old_parameters
        if x.kind not in (inspect.Parameter.VAR_POSITIONAL, inspect.Parameter.VAR_KEYWORD)
    ]
    dependency_names: List[str] = []
    for name, hint in get_type_hints(cls).items():
        if is_classvar(hint):
            continue
        parameter_kwargs = {"default": getattr(cls, name, Ellipsis)}
        dependency_names.append(name)
        new_parameters.append(
            inspect.Parameter(
                name=name, kind=inspect.Parameter.KEYWORD_ONLY, annotation=hint, **parameter_kwargs
            )
        )
    new_signature = old_signature.replace(parameters=new_parameters)

    def new_init(self: Any, *args: Any, **kwargs: Any) -> None:
        for dep_name in dependency_names:
            dep_value = kwargs.pop(dep_name)
            setattr(self, dep_name, dep_value)
        old_init(self, *args, **kwargs)

    setattr(cls, "__signature__", new_signature)
    setattr(cls, "__init__", new_init)
    setattr(cls, CBV_CLASS_KEY, True)
```

For Litestar, I'm confess I haven't spend much time yet looking into the codebase, but it would probably need some trickery to make the controller read the subclass attributes and then register the dependencies as if they were being registered in the dict, and when a handler is sitting within that subclass, the app would have to inject it without having the type hint.

Edit:

#### Practical implementation ideas

Playing around a bit it should be possible to extract those dependencies like:

```python
def extract_controler_dependencies(controller: Type[Controller]) -> dict[str, Provide]:
    dependencies = {}
    for i in inspect.classify_class_attrs(controller):
        if isinstance(i.object, Provide):
            dependencies.update({i.name: i.object})
    return dependencies
```

I left it as `Type[Controller]` because the `Router` seems to use the class directly instead of an instance, right? While the `Provide` should be an instance.

So if this extraction happened within the `register` method of the the `app`, which will call the `resolve_dependencies` on the `BaseRouteHandler`, it should be possible to add those dependencies to the `layer.dependencies`.

At last, for the routes, it would be possible to get the routes for a controller with `MyController().get_route_handlers()`, and the last bit would be identifying that a specific dependency should be injected in the controller routes. And maybe injecting the dependency on the`on_registration` or `resolve_before_request` methods of the `RouteHandler`.

Anyways... just some ideas.

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2303">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2303/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2303/pledge.svg">
</picture>
</a>

**Comment by ccrvlh** [comment]
I went on to try to understand the logic, and I got to this so far:

```python

    def resolve_dependencies(self) -> dict[str, Provide]:
        """Return all dependencies correlating to handler function's kwargs that exist in the handler's scope."""
        if self._resolved_dependencies is Empty:
            self._resolved_dependencies = {}

            for layer in self.ownership_layers:

                ## BRUTE FORCE METHOD ==================

                controller_dependencies = {}
                for attr in dir(layer):
                    layer_attr = getattr(layer, attr, None)
                    if not layer_attr:
                        continue
                    if isinstance(layer_attr, Provide):
                        controller_dependencies.update({attr: layer_attr})
                    continue

                layer_dependencies = layer.dependencies or {}
                if not layer_dependencies:
                    layer.dependencies = {}

                for k, v in controller_dependencies.items():
                    if k not in layer_dependencies:
                        layer.dependencies[k] = v

                ## END ==================

                for key, provider in layer_dependencies.items():
                    ...
```
The idea was to check for Controller attributes that have an instance of `Provide` as values and inject that into the dependency map, the second step would be to resolve the dependency even without it being declared on the handler's parameters, so that a `self.my_dependency` would be resolved.

It's not possible to import `Controller` from the `BaseRouter` (circular dependency), so I went with the "brute force" method, and checked the layer for attributes that have instances of `Provide` as value. I can see the dependency, but couldn't make it resolve - it doesn't go to the `parameter_model.dependency_batches`. So I imagine it's because it doesn't have `kwargs` here:

```python
        if parameter_model.has_kwargs and route_handler.signature_model:
            kwargs = parameter_model.to_kwargs(connection=request)
```

So I tried changing this to `or` (trying it to force it to resolve even with a handler without kwargs). But even still, the `parameter_model` doesn't have `dependency_batches`, which makes me think this is happening when parsing the handler's signature, maybe? At the end of the day all I could get was the `Provide` instance within the route, without being resolved.

Anyways. I was just curious on how it could work, it seems it would be possible by (1) manually adding the dependency the handler's signature (it seems that's the way the dependency gets injected and resolved?) or (2) creating a method that injects "controller level global dependencies". I'll way for some feedback on whether this is something worth pursuing and if so, what would be appropriate design.

**Comment by provinzkraut** [comment]
There are 2 main issues with this:

- Dependency resolution is tied to requests
- Controller instances are not tied to requests, and instead created only once

This makes injecting dynamic things into controller unsafe and impractical. So unfortunately, the feature that you're asking for is not compatible with the fundamental design of controllers.

<hr>

> But it's error prone, since it's mostly dependent on string manipulation (the dictionary keys)

I'm not sure what errors you're talking about. Could you elaborate?

>  and very verbose (having to accept the same argument multiple times).

I'd argue that it's not so much verbose as explicit.

<hr>

This is something that has come up more than once now, and I think the key here is to understand that controllers *are not views*. They might look like views on the surface, but functionally, they have little in common with how a view typically works. Controllers in Litestar are merely a neatly grouped collection of route handlers. They're conceptionally equivalent of doing the same thing on a module level and functionally (almost) equivalent of just adding the handlers + settings to a router.

I'd say this is on us though, because the documentation doesn't really go into detail about the function of controllers in an application, aside from explaining some basics of what you can do with them.

<hr>

The right question to ask here I think would be "Should Litestar have views?", which is something that has also been discussed in #2257.

**Comment by ccrvlh** [comment]
> I'm not sure what errors you're talking about. Could you elaborate?

I mean dictionary keys are strings, so you lose autocomplete from the IDE as you would have when declaring a class attribute and accessing it with `self.my_dependency`. You always have to make sure the dictionary key is exactly the same as the parameter you declared on your route handler. I mean, this is fine, but I do think the class-level dependency provides a better (and cleaner) DX.

> I'd argue that it's not so much verbose as explicit.

Definitely, bad wording on my part. I usually prefer things to be explicit, but I think the `Provide` name is so clear, that I prefer avoiding declaring the same parameter multiple times.

> and I think the key here is to understand that controllers are not views

I see controllers exactly how you described them: a collection of route handlers. A collection of route handlers that share the same dependency, could have a class level attribute that is being provided for every route within that controller, so I think the behavior makes sense, even if they are not `views` as described. As I understand, this word is being used to described the HDA-like behavior, as the link on the description. I actually don't use views at all (and to be honest, never did), and mostly develop raw APIs.

> This makes injecting dynamic things into controller unsafe and impractical. So unfortunately, the feature that you're asking for is not compatible with the fundamental design of controllers.

I had the impression that the logic would be something like (1) gather all dependencies and track their parent (eg. the controller) (2) when calling a route handler that is child of a controller with a defined dependency, inject. I definitely don't know enough about the architecture to add to this, but I think this is the most relevant aspect to consider, if it's incompatible with the architecture, that's totally fine. It's not the case that the framework lacks options to use dependencies anyways.

**Comment by peterschutt** [comment]
I wonder if something could be done with contextvars? Each request has its own async context and if we put an `@property` on the controller for each dependency, and set the contextvar when the deps are resolved and inside the property function `return dependency_ctx_var.get(default)`.

Just thinking out loud, so there might be some fundamental reason this won't work, but it feels like a potential way around the "controller instance shared across requests" issue.
