### ISSUE TITLE
Enhancement: Make `litestar` CLI part of the base package

### ISSUE THREAD

**Issue by JacobCoffee** [litestar-org/litestar#2318]
### Summary

Move the CLI dependencies into the core package

### Basic Example

`pip install litestar` should include the Litestar CLI

`pip install litestar[standard]` should continue to do the same thing (base + uvicorn, etc.)

### Drawbacks and Impact

- Heavier package with click-rich (click + rich) installed

###

Flask, Django, etc. do this; It makes sense for us. Relevant Discord forum post:
https://discord.com/channels/919193495116337154/1152738535397404752

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2318">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2318/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2318/pledge.svg">
</picture>
</a>

**Comment by lsanpablo** [comment]
I can look into this.
