### ISSUE TITLE
Docs: Incorrect code snippet in Signature Namespace docs

### ISSUE THREAD

**Issue by peterschutt** [litestar-org/litestar#2320]
### Summary

In the [Signature Namespace](https://docs.litestar.dev/latest/usage/routing/handlers.html#signature-namespace) page of the docs.

![image](https://github.com/litestar-org/litestar/assets/20659309/1ef4ef5e-3382-44a4-a0e7-214a1e1fe437)

I think this snippet should be highlighting a `from domain import Model  # noqa` line.

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2320">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2320/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2320/pledge.svg">
</picture>
</a>

**Comment by Alc-Alc** [comment]
It exists here 

https://github.com/litestar-org/litestar/blob/737a45a60e416ff1d96ce1e75b0b97b8f0247d5c/docs/usage/routing/handlers.rst?plain=1#L562-L570

I believe there is some sphinx directive or some hook that is removing these unused imports. Probably it must be `noqa: F401` not `noqa: TC002`?

**Comment by peterschutt** [comment]
`TC002` is from `flake8-type-checking` and is `Move third-party import into a type-checking block`. Looks like this is `TCH002` in ruff.

The rule suggests to move the import into an `if TYPE_CHECKING:` block if it is only used for type hints in the module.
