### ISSUE TITLE
Enhancement: Self-signed certificate generation for CLI

### ISSUE THREAD

**Issue by geeshta** [litestar-org/litestar#2335]
### Summary

This is along the lines what Flask (actually Werkzeug) and Django-extensions have. A new CLI option (or two) would be added to the `run` command
- `--ssl-certfile` to specify the location of the certificate
- `--ssl-keyfile` to specify the location of the keyfile
- If only one of them is provided, the second file is assumed to be in the same directory
- If the files are not found, they are automatically generated

The logic is taken from [`runserver_plus` in Django Extensions](https://django-extensions.readthedocs.io/en/latest/runserver_plus.html#ssl) and the names are taken from [Uvicorn](https://www.uvicorn.org/settings/#https)

The paths would be then forwarded to Uvicorn.

It would require the `cryptography` extras (which are already used for client sessions) and the `cryptography` module would be used to generate the self-signed certificates. 

[HERE](https://github.com/pallets/werkzeug/blob/main/src/werkzeug/serving.py#L540) is how Werkzeug handles the cert generation and [HERE](https://github.com/django-extensions/django-extensions/blob/main/django_extensions/management/commands/runserver_plus.py#L404) is how Django-Extensions handles the logic.

It is only meant to be used for development purposes on a HTTPS connection of course and would only generate a self-signed certificate.

### Basic Example

`litestar run --ssl-certfile=cert/server.crt`  - looks for `server.key` inside of the `cert/` directory
`litestar run --ssl-keyfile=cert/server.key` - looks for `server.crt` inside of the `cert/` directory
`litestar run --ssl-cerfile=cert/server.crt --ssl-keyfile=security/keys/server.key`
- if both files exist, use them
- otherwise generate new ones using `cryptography`
- if `cryptography` extras are not installed, terminate and inform user

### Unresolved questions

The exact logic and option names are open for discussion.

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2335">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2335/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2335/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
I like this idea, but I want to make on additional suggestion.

Even though we don't recommend it, I know people use this to deploy their apps, and we might want to "officially" support that option in the future. The presence of cert flags implies they might be used to deploy proper certs, so having them autogenerate certs if they're missing by default could lead to some serious issues. 

To prevent this, we could add an additional flag `--generate-dev-certs` (or a better name) that enables this explicitly.

**Comment by peterschutt** [comment]
> I like this idea, but I want to make on additional suggestion.
> 
> Even though we don't recommend it, I know people use this to deploy their apps, and we might want to "officially" support that option in the future. The presence of cert flags implies they might be used to deploy proper certs, so having them autogenerate certs if they're missing by default could lead to some serious issues.
> 
> To prevent this, we could add an additional flag `--generate-dev-certs` (or a better name) that enables this explicitly.
> 
> @litestar-org/maintainers?

Yeah - erring on the side of caution sounds reasonable to me.

**Comment by cofin** [comment]
I'd imagine there are few non-dev scenarios where having a self-signed cert might also be desirable (although I can't think of one right now).  I do agree that it needs to an extra flag to do this.

I can't think of anything better than `--generate-dev-certs` or `--generate-self-signed-certs` either, so no strong opinions on that one.

**Comment by provinzkraut** [comment]
How about something like [trustme](https://github.com/python-trio/trustme) instead?

**Comment by cofin** [comment]
> How about something like [trustme](https://github.com/python-trio/trustme) instead?

I like this approach as well.  @geeshta can you elaborate on your specific use case for self-signed certs?  Is it specifically for local development with SSL enabled?  Integration with `trustme` may be the easiest way to bake this functionality in.

**Comment by geeshta** [comment]
> > How about something like [trustme](https://github.com/python-trio/trustme) instead?
> 
> I like this approach as well.  @geeshta can you elaborate on your specific use case for self-signed certs?  Is it specifically for local development with SSL enabled?  Integration with `trustme` may be the easiest way to bake this functionality in.

Yeah it's just to enable serving with HTTPS during development (I use some client side JavaScript that requires HTTPS).

I haven't heard about trustme before but I really like how django-extensions handles that.

**Comment by geeshta** [comment]
I personally never needed the certificate to be actually signed by a CA as trustme provides though and saw that Werkzeug uses `cryptography` to generate self-signed certs.
