### ISSUE TITLE
Bug: typing error passing list of context managers to `lifespan` app parameter

### ISSUE THREAD

**Issue by peterschutt** [litestar-org/litestar#2348]
### Description

Passing a list of pre-constructed async context managers to `lifespan` parameter causes:

```
app.py:20: error: Argument "lifespan" to "Litestar" has incompatible type "list[AioCtxMgr]"; expected "list[Callable[[Litestar], AbstractAsyncContextManager[Any]] | AbstractAsyncContextManager[Any]] | None"  [arg-type]
app.py:20: note: "List" is invariant -- see https://mypy.readthedocs.io/en/stable/common_issues.html#variance
app.py:20: note: Consider using "Sequence" instead, which is covariant
```

### MCVE

```python
from __future__ import annotations

from typing import Any

from litestar import Litestar


class AioCtxMgr:
    """A dummy context manager."""

    async def __aenter__(self) -> None:
        pass

    async def __aexit__(self, *args: Any) -> None:
        pass


ctx_mgrs = [AioCtxMgr()]
Litestar(route_handlers=[], lifespan=ctx_mgrs)

Litestar(route_handlers=[], lifespan=[AioCtxMgr()])  # OK
```

### Steps to reproduce

```bash
Run mypy on MCVE code.
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Litestar Version

2.0.1final0

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2348">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2348/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2348/pledge.svg">
</picture>
</a>

**Comment by peterschutt** [comment]
Can this be typed with `OptionalSequence`?

**Comment by provinzkraut** [comment]
> Can this be typed with `OptionalSequence`?

I don't why not :+1:
