### ISSUE TITLE
Bug: schema not respecting alias generator or alias on field

### ISSUE THREAD

**Issue by rseeley** [litestar-org/litestar#2373]
### Description

When using a Pydantic model with an alias generator function, like camel case, or a field with an alias, and using `model_dump(by_alias=True)` in `type_encoders` for `BaseModel`, the schema doesn't show the aliased key format. It'll still use snake case, matching the class attributes. This seems to be a regression from `2.0.0alpha7` (currently testing this on `2.1.1`).

### URL to code causing the issue

https://github.com/rseeley/litestar-mcves/blob/mcve/camel-schema/app.py

### Steps to reproduce

```bash
1. Clone repo above
2. Run installation/run steps in the README
3. Create a Pydantic model with either an alias generator or aliased Field (or both, as in the GH reproduction)
4. Go to `/async` to see that the alias is returning properly in actual responses
5. Go to `/schema` to see that the keys are snake case
```

### Litestar Version

2.1.1

### Platform

- [ ] Linux
- [X] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2373">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2373/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2373/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
@guacs @gsakkis can you look into this?

**Comment by guacs** [comment]
> @guacs @gsakkis can you look into this?

I can look into it.

**Comment by guacs** [comment]
This is due to the changes in #2150. I think the solution is to make this configurable by adding `request_prefer_alias` and `response_prefer_alias` options to the `OpenAPIConfig` and use that to determine what value to set for `prefer_alias` in `SchemaCreator`.
