### ISSUE TITLE
Docs: errors in the SQLAlchemy Repository Tutorial

### ISSUE THREAD

**Issue by sfermigier** [litestar-org/litestar#2374]
### Summary

Running the examples in the SQLAlchemy Repository Tutorial give the following error:

```
    |   File "toto.py", line 144, in on_startup
    |     async with sqlalchemy_config.create_engine().begin() as conn:
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    | AttributeError: 'SQLAlchemyAsyncConfig' object has no attribute 'create_engine'
```

I suspect the API has changed.

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2374">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2374/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2374/pledge.svg">
</picture>
</a>

**Comment by lsanpablo** [comment]
I actually ran into this a few days ago when starting a new app. I can update the docs.

FWIW, the following worked for me:
```
async def on_startup() -> None:
    """Initializes the database."""
    async with sqlalchemy_config.get_engine().begin() as conn:
        await conn.run_sync(UUIDBase.metadata.create_all)
```
