### ISSUE TITLE
Docs: order of lifespan ctx exit and on_shutdown hooks

### ISSUE THREAD

**Issue by peterschutt** [litestar-org/litestar#2403]
### Summary

From a quick glance at the docs, it doesn't appear that we explicitly document the order that `__aexit__` methods on the `lifespan` context managers are called, relative to the registered `on_shutdown` hooks. This ordering might be important, especially that it prevents an `on_shutdown` hook from interacting with a resource that is managed by the lifespan context, e.g., a db engine, or redis connection or similar.

Take this app, for ex:

```py
app = Litestar(lifespan=[ctx_a, ctx_b], on_shutdown=[hook_a, hook_b])
```

On shutdown, the order of calls is:
1. `ctx_b.__aexit__()`
2. `ctx_a.__aexit__()`
3. `hook_a`
4. `hook_b`

So, on shutdown, context managers are exited in reverse order (which is natural behavior of the exit stack), and before shutdown hooks. Then, shutdown hooks are called in registered order.

We should also add tests to lock this behavior in, as FWICT (checked here: https://github.com/litestar-org/litestar/blob/main/tests/unit/test_asgi_router.py), we have tests that they are all called on shutdown, but nothing that tests for explicit order.

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2403">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2403/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2403/pledge.svg">
</picture>
</a>

**Comment by orgarten** [comment]
I assume the docs would go [here](https://docs.litestar.dev/latest/usage/applications.html)? 

I can add a paragraph to the Startup/Shutdown section and then give the tests a try.

**Comment by peterschutt** [comment]
That would be great @orgarten, cheers!

> I assume the docs would go [here](https://docs.litestar.dev/latest/usage/applications.html)?

Yep, around that area. You could add an admonition to each of the sections about lifespan context, and shutdown hooks that demonstrates their place in the sequence, or add a new section following that talks about the sequencing.. or something else that you think is better! 

We probably should include the calls to `on_startup` hooks and entering the lifespan contexts as well.

Shall I assign the issue to you?

**Comment by orgarten** [comment]
Yes, go ahead an assign me @peterschutt. It's probably gonna take a couple of days though.

I will see what works best in my opinion. Once the content is there, the format should be a quick change anyway.

**Comment by orgarten** [comment]
Ok, I added a section inside the documentation of the app regarding the order. 

I would implement the tests insider `tests/unit/test_app.py` unless there are any objections with a suggestion of a better place :)
