### ISSUE TITLE
Docs: Request headers missing from usage section. 

### ISSUE THREAD

**Issue by EliasEriksson** [litestar-org/litestar#2408]
### Summary

There seams to be no example to how to acquire the request headers in a route handler under the usage section of the documentation. What seams to exit is the [API reference of the connection object](https://docs.litestar.dev/latest/reference/connection.html#litestar.connection.ASGIConnection.headers). 

Maybe there should be some section about it under the [Request usage](https://docs.litestar.dev/latest/usage/requests.html) section since there is a section about response headers in the [Responses usage](https://docs.litestar.dev/latest/usage/responses.html) section?

---

## Funding
* If you would like to see an issue prioritized, make a pledge towards it!
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/litestar-org/litestar/issues/2408">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2408/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2408/pledge.svg">
</picture>
</a>

**Comment by peterschutt** [comment]
There are examples in the docs for handlers and parameters. E.g:

- https://docs.litestar.dev/latest/usage/routing/handlers.html#reserved-keyword-arguments
- https://docs.litestar.dev/latest/usage/routing/parameters.html#header-and-cookie-parameters

However, I can understand that the Request section would be the logical place to look for this stuff first.

Open to restructure suggestions!

**Comment by EliasEriksson** [comment]
I see. I did not find that in the docs when I was looking for it but someone in the discord channel pointed me to your [first link](https://docs.litestar.dev/latest/usage/routing/handlers.html#reserved-keyword-arguments) and this [discussion](https://github.com/orgs/litestar-org/discussions/2286) showing the information in the [second link](https://docs.litestar.dev/latest/usage/routing/parameters.html#header-and-cookie-parameters). 

When I was first looking for the information it was hard to find but knowing what I know now it makes sense for it to be here it is.
