### ISSUE TITLE
Enhancement: Support Pydantic 1 and 2 within the same app

### ISSUE THREAD

**Issue by provinzkraut** [litestar-org/litestar#2419]
### Summary

Since Pydantic 2 contains Pydantic 1, we should support Pydantic 1 and 2 within the same application so users can make use of Pydantic's backwards compatibility layer. 

We already have everything we need for this in the Pydantic plugin, it just need to be split up.
This could also simplify testing, since we could test v1 and v2 within the same environment.

**Comment by peterschutt** [comment]
> This could also simplify testing, since we could test v1 and v2 within the same environment.

This would be nice!

Would this mean we would have to constrain to pydantic>=2? Or we would support v1 in either case that v1 and v2 is installed, and only v2 if v2 installed?

**Comment by provinzkraut** [comment]
The latter. I did some testing with this a while ago and it seemed to work just fine.

**Comment by peterschutt** [comment]
> only v2 if v2 installed?

Should read "only v1 if v1 installed"

**Comment by provinzkraut** [comment]
> > only v2 if v2 installed?
> 
> Should read "only v1 if v1 installed"

That's actually how I read it :upside_down_face: 

So yes, the plan is to support v1 if v1 is installed, and v1 + v2 if v2 is installed.

**Comment by geeshta** [comment]
@provinzkraut this should be closed because of #2487 no?

**Comment by JacobCoffee** [comment]
Closed in 2487
