### ISSUE TITLE
Bug: Logging test gives key error in ``python@3.12``

### ISSUE THREAD

**Issue by JacobCoffee** [litestar-org/litestar#2451]
Should circle back and resolve this - I'm not sure what this is testing TBH, but in 3.12 it raises a key error b/c it is expecting there to be a handler called `"cfg://handlers.console"` in `cfg://handlers`

_Originally posted by @peterschutt in https://github.com/litestar-org/litestar/pull/2396#discussion_r1359753145_
            

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh Litestar dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2451">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2451/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2451/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
This has been solved in #3185.
