### ISSUE TITLE
Docs: `template_engine` documented but not actually used

### ISSUE THREAD

**Issue by guacs** [litestar-org/litestar#2454]
### Summary

In the `Template` response, there's a `template_engine` parameter that is taken as per the docstrings as seen [here](https://github.com/litestar-org/litestar/blob/2385b32b52a786634bcef6059900165123f31705/litestar/response/template.py#L59) (it's also there in the reference documentation). Was this meant to be removed or should support for giving a custom engine class on instantiation of the response be allowed?

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh Litestar dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2454">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2454/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2454/pledge.svg">
</picture>
</a>

**Comment by peterschutt** [comment]
It was removed in favor of retrieving it from the application as part of the PR that created the ASGI response variants. That PR was merged somewhat abruptly, so not surprising there are some rough edges around that stuff.

Should be safe to remove the docstring for it.
