### ISSUE TITLE
Bug: Litestar Logging in Python3.12: Unable to configure handler 'queue_listener'

### ISSUE THREAD

**Issue by ddxv** [litestar-org/litestar#2469]
### Description

Using the logging example from:
https://docs.litestar.dev/2/usage/logging.html
```python
from litestar import Litestar, Request, get
from litestar.logging import LoggingConfig


@get("/")
def my_router_handler(request: Request) -> None:
    request.logger.info("inside a request")
    return None


logging_config = LoggingConfig(
    loggers={
        "my_app": {
            "level": "INFO",
            "handlers": ["queue_listener"],
        }
    }
)

app = Litestar(route_handlers=[my_router_handler], logging_config=logging_config)

```

Saving the above in app.py and running with `litestar run` causes the following error:

```
/home/james/testproj/app.py:5: LitestarWarning: Use of a synchronous callable <function my_router_handler at 0x7f197e854fe0> without setting sync_to_thread is discouraged since synchronous callables can block the main thread if they perform blocking operations. If the callable is guaranteed to be non-blocking, you can set sync_to_thread=False to skip this warning, or set the environmentvariable LITESTAR_WARN_IMPLICIT_SYNC_TO_THREAD=0 to disable warnings of this type entirely.
  @get("/")
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/logging/config.py", line 581, in configure
    handler = self.configure_handler(handlers[name])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/logging/config.py", line 786, in configure_handler
    raise ValueError('No handlers specified for a QueueHandler')
ValueError: No handlers specified for a QueueHandler

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/james/testproj/.virtualenv/bin/litestar", line 8, in <module>
    sys.exit(run_cli())
             ^^^^^^^^^
  File "/home/james/testproj/.virtualenv/lib/python3.12/site-packages/litestar/__main__.py", line 6, in run_cli
    litestar_group()
  File "/home/james/testproj/.virtualenv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/james/testproj/.virtualenv/lib/python3.12/site-packages/rich_click/rich_command.py", line 125, in main
    with self.make_context(prog_name, args, **extra) as ctx:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/james/testproj/.virtualenv/lib/python3.12/site-packages/litestar/cli/_utils.py", line 242, in make_context
    self._prepare(ctx)
  File "/home/james/testproj/.virtualenv/lib/python3.12/site-packages/litestar/cli/_utils.py", line 224, in _prepare
    env = ctx.obj = LitestarEnv.from_env(ctx.params.get("app_path"), ctx.params.get("app_dir"))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/james/testproj/.virtualenv/lib/python3.12/site-packages/litestar/cli/_utils.py", line 122, in from_env
    loaded_app = _autodiscover_app(cwd)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/james/testproj/.virtualenv/lib/python3.12/site-packages/litestar/cli/_utils.py", line 332, in _autodiscover_app
    module = importlib.import_module(import_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/home/james/testproj/app.py", line 20, in <module>
    app = Litestar(route_handlers=[my_router_handler], logging_config=logging_config)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/james/testproj/.virtualenv/lib/python3.12/site-packages/litestar/app.py", line 445, in __init__
    self.get_logger = self.logging_config.configure()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/james/testproj/.virtualenv/lib/python3.12/site-packages/litestar/logging/config.py", line 229, in configure
    config.dictConfig(values)
  File "/usr/local/lib/python3.12/logging/config.py", line 912, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/local/lib/python3.12/logging/config.py", line 588, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'queue_listener'
```

I'm not sure what is causing this issue, but could be related to #2451

### Litestar Version

2.2.1

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh Litestar dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2469">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2469/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2469/pledge.svg">
</picture>
</a>

**Comment by ddxv** [comment]
Ah, a few things I learned since posting this. First I saw that Python3.12 doesn't appear to be officially supported yet, so this 'bug' might just be unnecessary and can be closed if it's already something being covered.

Second, I realized that I originally thought this was due to my projects logging, but I'm actually able to recreate it with a pure `hello_world` example project that doesn't attempt to use `queue_listener`.  

For example:
```
from litestar import Litestar, get


@get("/")
async def index() -> str:
    return "Hello, world!"


@get("/books/{book_id:int}")
async def get_book(book_id: int) -> dict[str, int]:
    return {"book_id": book_id}


app = Litestar([index, get_book])
```

Throws essentially the same error `Unable to configure handler 'queue_listener'` as I guess this is originating from within litestar itself.

**Comment by peterschutt** [comment]
3.12 support was completed in https://github.com/litestar-org/litestar/pull/2396 - this has not made it to a release yet, but I would be interested to know if your problem still exists if you install Litestar from GH main.

**Comment by peterschutt** [comment]
For background: [some stuff changed in 3.12 in the way queue listeners/handlers are configured](https://docs.python.org/3/library/logging.config.html#configuring-queuehandler-and-queuelistener)

**Comment by ddxv** [comment]
@peterschutt Thanks for the quick reply. Indeed, trying the above examples with the current GitHub main resolves the `ValueError` for `queue_listener`, but there is a warning in the logging example:

`/home/james/testproj/app.py:5: LitestarWarning: Use of a synchronous callable <function my_router_handler at 0x7f371ca84b80> without setting sync_to_thread is discouraged since synchronous callables can block the main thread if they perform blocking operations. If the callable is guaranteed to be non-blocking, you can set sync_to_thread=False to skip this warning, or set the environmentvariable LITESTAR_WARN_IMPLICIT_SYNC_TO_THREAD=0 to disable warnings of this type entirely.`

And it seems that the 'inside a request' message is not displayed in the terminal when hitting the end point:
```python
@get("/")
def my_router_handler(request: Request) -> None:
    request.logger.info("inside a request")
    return None
```

Anyways, the original issue seems to have been resolved. Let me know if you think the above warrants a separate issue and if you'd like to close this one.

**Comment by peterschutt** [comment]
That's an expected warning.

Using a sync handler can be a bit of a foot-gun. If the handler is quick, and won't block the event loop `sync_to_thread=False` is by far the more efficient way to to. This means the handler is called inside the asyncio task that is handling the request, just like any other function. However, if a sync handler blocks at all, e.g., has to make a request to a database via a sync API, then `sync_to_thread=True` is likely to be a better choice, which means the handler gets called in a separate thread and won't block the event loop.

Unnecessarily running sync handlers in threads is expensive. Not running sync handlers in threads when they block the event loop is no good. So, we chose to warn when a sync handler is defined without explicitly setting the `sync_to_thread` flag.

```py
@get("/", sync_to_thread=False)  # this should silence that warning.
def my_router_handler(request: Request) -> None:
    request.logger.info("inside a request")
    return None
```
