### ISSUE TITLE
Bug: logging AttributeError: 'str' object has no attribute 'handle'

### ISSUE THREAD

**Issue by euri10** [litestar-org/litestar#2477]
### Description

I get this error using a slightly modified mvce that comes from the docs (just changed the handler to be async)

```
❯ uvicorn l:app
INFO:     Started server process [269081]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:35226 - "GET / HTTP/1.1" 200 OK
Exception in thread Thread-1 (_monitor):
Traceback (most recent call last):
  File "/home/lotso/.asdf/installs/python/3.11.6/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/home/lotso/.asdf/installs/python/3.11.6/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lotso/.asdf/installs/python/3.11.6/lib/python3.11/logging/handlers.py", line 1584, in _monitor
    self.handle(record)
  File "/home/lotso/.asdf/installs/python/3.11.6/lib/python3.11/logging/handlers.py", line 1565, in handle
    handler.handle(record)
    ^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'handle'
INFO:     127.0.0.1:35226 - "GET / HTTP/1.1" 200 OK
```

### MCVE

```python
from litestar import Litestar, Request, get
from litestar.logging import LoggingConfig


@get("/")
async def my_router_handler(request: Request) -> None:
    request.logger.info("inside a request")
    return None


logging_config = LoggingConfig(
    loggers={
        "my_app": {
            "level": "INFO",
            "handlers": ["queue_listener"],
        }
    }
)

app = Litestar(route_handlers=[my_router_handler], logging_config=logging_config)
```

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Litestar Version

`  • Installing litestar (2.2.1 7c3d24f)`

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh Litestar dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2477">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2477/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2477/pledge.svg">
</picture>
</a>

**Comment by euri10** [comment]
2.2.0 doesnt exhibit the traceback, there might have been a regression somewhere

**Comment by peterschutt** [comment]
What py version?

**Comment by euri10** [comment]
it's 3.11.6
I also have the bug on same litestar git version but without using LoggingConfig

**Comment by euri10** [comment]
I think this is the culprit:
https://github.com/litestar-org/litestar/blob/7c3d24f9b70731df372b29bff9eb5cf359055b3a/litestar/logging/config.py#L43

**Comment by peterschutt** [comment]
I think that might just need to be added under an `if >= 3.12.0` guard if that is the case. There have been changes to the way queue handlers/listeners are configured in 3.12 (https://docs.python.org/3/library/logging.config.html#configuring-queuehandler-and-queuelistener).

The thing is, that change hasn't made it into a release yet - you are installing from main?

**Comment by euri10** [comment]
> I think that might just need to be added under an `if >= 3.12.0` guard if that is the case. There have been changes to the way queue handlers/listeners are configured in 3.12 ([docs.python.org/3/library/logging.config.html#configuring-queuehandler-and-queuelistener](https://docs.python.org/3/library/logging.config.html#configuring-queuehandler-and-queuelistener)).
> 
> The thing is, that change hasn't made it into a release yet - you are installing from main?

yes I installed from main
however I still dont get how without even importing anyting from litestar.logging makes me have the traceback

**Comment by peterschutt** [comment]
Can you try pointing to https://github.com/litestar-org/litestar/tree/2477-logging-attribute-error and see how that goes.. 

>  however I still dont get how without even importing anyting from litestar.logging makes me have the traceback

Looking at your config in the OP, well, you pass in the logger that you want, so I feel the same, why should the queue listener/handler have anything to do with anything. But then, look at `LoggingConfig.__post_init__()`: https://github.com/litestar-org/litestar/blob/50ee00a7839f489f01c331a118d37dd215e977b2/litestar/logging/config.py#L198-L206

The queue listener is added to the logging config irrespective of the passed in config.

TBH, I find the logging part of litestar a little hard to wrap my head around..

**Comment by peterschutt** [comment]
>  however I still dont get how without even importing anyting from litestar.logging makes me have the traceback

if you import `from litestar import Litestar`, then you are importing from `litestar.logging`: https://github.com/litestar-org/litestar/blob/7c3d24f9b70731df372b29bff9eb5cf359055b3a/litestar/app.py#L28

**Comment by euri10** [comment]
> Can you try pointing to [`2477-logging-attribute-error`](https://github.com/litestar-org/litestar/tree/2477-logging-attribute-error?rgh-link-date=2023-10-20T10%3A36%3A44Z) and see how that goes..


yup that solves it,
