### ISSUE TITLE
Enhancement: Allow passing a list as the template context

### ISSUE THREAD

**Issue by geeshta** [litestar-org/litestar#2481]
### Summary

I find myself often constructing the `context` for a template as a dict where the keys are the same as the variable names, e.g.
```python
context = {
    "form": form,
    "movies": movies,
    # etc
}
```
I usually name the variables the same in the template and the handler code. It would be nice if I can just pass a list of variables and the conversion to dict would be handled automatically in a similar way #2422 did this for signature types.

### Basic Example

```py
@get("/movies")
async def get_movies(movie_service: MovieService) -> Template:
    form = MovieForm()
    movies = await movie_service.get_movies()
    return Template("movie_list.html.j2", context=[form, movies])
```

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh Litestar dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2481">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2481/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2481/pledge.svg">
</picture>
</a>

**Comment by peterschutt** [comment]
I can see the parallel in utility to #2422, however there is a key difference in that it is dealing with types, this is dealing with local variables, and I don't know of a good way to get the name of the variable from the variable itself. 

I.e., to be given a list such as `[form, movies]`, and be able to construct a mapping of `{"form": form, "movies": movies}`, we need to find the names of the variables from the variables themselves.

Here's a helper function that you could use:

```py
def get_local_context(*names: str, local_ns: dict[str, Any] | None = None) -> dict[str, Any]:
    if local_ns is None:
        local_ns = inspect.currentframe().f_back.f_locals
    return {name: local_ns[name] for name in names}

@get("/movies")
async def get_movies(movie_service: MovieService) -> Template:
    form = MovieForm()
    movies = await movie_service.get_movies()
    return Template("movie_list.html.j2", context=get_local_context("form", "movies")
```

Building the dict literal yourself will be quite a bit more performant, however:

```python-console
>>> def without_inspect():
...   form = object()
...   movies = object()
...   return {"form": form, "movies": movies}
... 
>>> def with_inspect():
...   form = object()
...   movies = object()
...   return get_local_context("form", "movies")
... 
>>> def with_pass_locals():
...   form = object()
...   movies = object()
...   return get_local_context("form", "movies", local_ns=locals())
...
>>> import timeit
>>> timeit.timeit("without_inspect()", globals=globals())
0.20843668799989246
>>> timeit.timeit("with_inspect()", globals=globals())
0.8220364069998141
>>> timeit.timeit("with_pass_locals()", globals=globals())
0.6310827120000795
```

**Comment by geeshta** [comment]
Thanks a lot for the analysis, @peterschutt !
