### ISSUE TITLE
Enhancement: Ignore cache when the cached response is an error

### ISSUE THREAD

**Issue by Kumzy** [litestar-org/litestar#2501]
### Summary

Hello,

Following a thread on discord and the suggestion from @Alc-Alc 

When cache is enabled on the controller, it caches errors. So if we fix the issue and start again the app, the response sent by Litestar is still the error and not the correct answer.

```python
@get(
        operation_id="ListCustomer",
        name="customers:list",
        summary="List Customers",
        description="Retrieve the customers.",
        path=urls.CUSTOMER_LIST,
        cache=60,
    )
```

@Alc-Alc suggests the following:  adding `no_cache_on_exception` on `ResponseCacheConfig` (or any relevant place)

Thank you

### Basic Example

1. Create a route with cache=60
2. Create an error that route
3. Get the route through the appropriate method (GET)
4. Fix the issue and query the route again, the error is returned
5. (optional) if we set the cache to 0, the correct response is returned

### Drawbacks and Impact

Adding a new property/config
Documentation needed

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh Litestar dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2501">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2501/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2501/pledge.svg">
</picture>
</a>

**Comment by peterschutt** [comment]
In #2537 I've made an attempt at a solution for this. Feedback appreciated.

The PR adds the ability to define a predicate callable that can discriminate whether a response should be cached, or not.

E.g., 

```py
def should_cache(scope: HTTPScope, status_code: int) -> bool:
    return custom_logic_to_control_response_caching()

app = Litestar(..., response_cache_config=ResponseCacheConfig(..., do_cache_predicate=should_cache))
```

At this point, the default predicate is:

```py
def default_do_cache_predicate(scope: HTTPScope, status_code: int) -> bool:
    """Given a status code, returns a boolean indicating whether the response should be cached.

    Args:
        scope: ASGI scope.
        status_code: status code of the response.

    Returns:
        A boolean indicating whether the response should be cached.
    """
    if scope["method"] != "GET":
        return False

    return HTTP_200_OK <= status_code < HTTP_300_MULTIPLE_CHOICES or status_code in (
        HTTP_301_MOVED_PERMANENTLY,
        HTTP_308_PERMANENT_REDIRECT,
    )
```
That logic is open to discussion, i.e., maybe we should not cache 201s and others - but if someone has `cache=True` on a POST route at the moment, then we are caching that as far as I can tell.. so trying to walk a line between reasonable, and not breaking.
