### ISSUE TITLE
Bug: Dependency injection and annotated query parameter

### ISSUE THREAD

**Issue by gsakkis** [litestar-org/litestar#2517]
### Description

Dependency injection doesn't play well annotated query parameters:
1. The OpenAPI schema lists both the query parameter and the dependency parameter, even when the latter is declared explicitly as a `Dependency` with default value, in which case "[Litestar knows to exclude it from the docs](https://docs.litestar.dev/latest/usage/dependency-injection.html#exclude-dependencies-with-default-values-from-openapi-docs)".
2. Even worse, the query parameter key is not deterministic: sometimes it picks the formal parameter name, sometimes the one given as "query" in the `Parameter` annotation. This took me a while to figure out as (I think) it manifests when restarting the server; it seems deterministic as long as the server is not restarted. 

### MCVE

```python
from dataclasses import dataclass
from typing import Annotated

from litestar import Litestar, get
from litestar.di import Provide
from litestar.params import Parameter, Dependency


@dataclass
class User:
    name: str


async def retrieve_db_user(user_name: str | None) -> User:
    return User(name=user_name)


@get(path="/", dependencies={"user_obj": Provide(retrieve_db_user)})
async def get_user(
    user_name: Annotated[str | None, Parameter(query="user")],
    user_obj: Annotated[User, Dependency(default=None)]
) -> User:
    return user_obj


app = Litestar([get_user])
```

### Steps to reproduce

1. Check http://localhost:8000/schema: both `user` and `user_name` show up as query parameters.
2. Run `curl -w '\n' 'localhost:8000?user=xxx'`, restart the server, repeat this a couple of times. Sometimes the response is `{"name":"xxx"}`, the rest it is `{"name":null}`.

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Litestar Version

Litestar 2.2.1
Python 3.10.12

### Platform

- [ ] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

**Comment by peterschutt** [comment]
> 1. The OpenAPI schema lists both the query parameter and the dependency parameter, even when the latter is declared explicitly as a `Dependency` with default value, in which case "[Litestar knows to exclude it from the docs](https://docs.litestar.dev/latest/usage/dependency-injection.html#exclude-dependencies-with-default-values-from-openapi-docs)".

I doesn't look like it is listing the dependency parameter as that is called `user_obj`. It is listing `user_name` and `user`, if it was listing the dependency one of those would be `user_obj`, right?

![image](https://github.com/litestar-org/litestar/assets/20659309/bf4cdd4d-0a12-4f97-9b26-82111c019feb)

**Comment by peterschutt** [comment]
> 2\. Run `curl -w '\n' 'localhost:8000?user=xxx'`, restart the server, repeat this a couple of times. Sometimes the response is `{"name":"xxx"}`, the rest it is `{"name":null}`.

Confirmed this. I had to restart a few times, but eventually I got `{"name": null}` returned, and without restarting the server in that case if I requested `?user_name?=abc` then it would response `{"name": "abc"}`.

I hoped that setting `PYTHONHASHSEED` to a constant might make it reproducible, but unfortunately not. It feels like some sort of dict ordering issue..

**Comment by peterschutt** [comment]
In the example, you actually do have two query params declared. 1. for the dependency, called `user_name` and one for the route handler called `user` and you are seeing both in the openapi docs, because they are both declared.

This refactor simplifies the example, and makes docs and query param behave as expected.

```py
from dataclasses import dataclass
from typing import Annotated

from litestar import Litestar, get
from litestar.di import Provide
from litestar.params import Parameter, Dependency


@dataclass
class User:
    name: str


async def retrieve_db_user(user_name: Annotated[str | None, Parameter(query="user")]) -> User:
    return User(name=user_name)


@get(path="/", dependencies={"user_obj": Provide(retrieve_db_user)})
async def get_user(user_obj: User) -> User:
    return user_obj


app = Litestar([get_user])
```

Also this is probably even better:

```py
from dataclasses import dataclass

from litestar import Litestar, get
from litestar.di import Provide
from litestar.params import Parameter


@dataclass
class User:
    name: str


async def retrieve_db_user(user_name: str | None) -> User:
    return User(name=user_name)


@get(path="/", dependencies={"user_obj": Provide(retrieve_db_user)})
async def get_user(user_obj: User, user_name: str | None) -> User:  # <-- multiple injections of user_name in this example
    return user_obj


app = Litestar([get_user], parameters={"user_name": Parameter(query="user")})  # <-- defined the parameter on a higher layer
```

So I'm just not sure that the original pattern in this issue is defined behavior. Its certainly not a pattern that we'd encourage which I imagine is why this hasn't come up before now.

@litestar-org/maintainers should we support the OP pattern in this example where the query parameter is declared in both the dependency signature and the handler signature, but the parameter only declared on one of them? I have a feeling there is still a bug here, but more subtle than this example lets on.

**Comment by gsakkis** [comment]
> In the example, you actually do have two query params declared. 1. for the dependency, called user_name and one for the route handler called user and you are seeing both in the openapi docs, because they are both declared.

I guess my understanding of the DI mechanics was wrong. 

How I thought it works:
1. There is one query parameter, the one defined in the route handler, called "user" externally.
2. This query parameter is validated against its annotation (`str | None`).
3. The validated value is passed to the `retrieve_db_user` dependency as `user_name`.
4. The returned value is bound to `user_obj`

What apparently seems to be happening is that the parameters of the dependency are literally injected in the signature of the route handler. So the effective signature is something like:
```async def get_user(user: str | None, user_name: str | None) -> User```
or in different order:
```async def get_user(*, user_name: str | None, user: str | None) -> User```
This would explain the generated openapi schema and potentially the observed ambiguity in the binding.

> `app = Litestar([get_user], parameters={"user_name": Parameter(query="user")})  # <-- defined the parameter on a higher layer`

I like this parameter definition, though ideally not at the app layer. Is there a better way to have such a definition shared only between a single route handler and a dependency?

**Comment by peterschutt** [comment]
> I like this parameter definition, though ideally not at the app layer. Is there a better way to have such a definition shared only between a single route handler and a dependency?

Yes, you can achieve same using a controller or router, e.g.,:

```py
from dataclasses import dataclass

from litestar import Litestar, Router, get
from litestar.params import Parameter


@dataclass
class User:
    name: str


async def retrieve_db_user(user_name: str | None) -> User:
    return User(name=user_name)


@get(path="/")
async def get_user(user_obj: User, user_name: str | None) -> User:
    return user_obj

router = Router(
    route_handlers=[get_user],
    dependencies={"user_obj": retrieve_db_user},  # you don't have to wrap dependencies in `Provide`
    parameters={"user_name": Parameter(query="user"),
)

app = Litestar([router]) 
```

**Comment by peterschutt** [comment]
I don't think there's anything to action here.
