### ISSUE TITLE
Enhancement: refactor openapi controller

### ISSUE THREAD

**Issue by peterschutt** [litestar-org/litestar#2541]
### Summary

Refactor `OpenAPIController` into a suite of plugins that can be individually added to the application in order to serve a UI of choice for the project.

Currently, every app that configures openapi will have access to redoc, swagger, stoplight elements and rapidoc UIs. This is unnecessary, and the controller is beginning to become bloated.

### Basic Example

```py
app = Litestar(..., plugins=[ReDocUIPlugin()])
```

### Drawbacks and Impact

To implement this in a non-breaking way, we'll need to preserve the current behavior of having all UIs available if there is an OpenAPIConfig object defined and no plugin defined. However, this will give us a path to deprecating current behavior to prefer the plugin-based approach in 3.0.

### Unresolved questions

How should we identify that a plugin for an openapi UI has been registered on the app so as not to register the OpenAPIController (or equivalent)?

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh Litestar dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2541">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2541/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2541/pledge.svg">
</picture>
</a>

**Comment by orgarten** [comment]
What exactly would this entail? The OpenAPI controller in `openapi/controller.py` would have to be split up for the different UIs. 

The plugins would follow the [InitPluginProtocol](https://docs.litestar.dev/2/usage/plugins.html#initpluginprotocol) or is there anything else to it?

Anyway, I can give this a try but might need some help along the way. If this is urgent, someone else should probably take the lead here, though.

**Comment by peterschutt** [comment]
From the `OpenAPIConfig` object:
- [ ] we will still need to respect the `enabled_endpoints` config and `root_schema_site` configs. I think we should deprecate these and ignore them if one of the framework plugins is explicitly defined.
- [ ] respect the `path` config

Compared to the current controller:

- [ ] I'm thinking of using a router for this version
- [ ] `get_schema_from_request()` will be replaced with DI
- [ ] `should_serve_endpoint()` will be redundant as the `enabled_endpoints` config will be obsolete and doc frameworks will be opt-in via a plugin system.
- [ ] `favicon` will be maintained
- [ ] we'll only add the json/yaml routes respecting the `enabled_endpoints` config
- [ ] the root site handler will be registered to both the `/` and `/name` paths
- [ ] plugins will provide a callback that receives the schema object and the json serialized schema and should return the bytes that will form the body of the response.
- [ ] will need a way for plugins to optionally be able to add extra handers, such as the swagger oauth2 redirect handler we have on the controller.
- [ ] the `_get_schema_as_json()` will be dumped and replace by DI (we can use DI caching also)
