### ISSUE TITLE
Bug: Optionally typed parameters do not render in OpenAPI docs properly

### ISSUE THREAD

**Issue by JacobCoffee** [litestar-org/litestar#2546]
### Description

When using an arbitrary enum as a type (or `Literal` assumedly), it generates a dropdown in the OpenAPI docs.

```py
environment: Environment = Parameter(
        title="Environment",
        description="The environment to filter by.",
        default=None,
        required=False,
    ),
```

but hitting this endpoint gives a validation error:

```py
 File ".venv/lib/python3.10/site-packages/litestar/_signature/model.py", line 190, in parse_values_from_connection_kwargs
    return convert(kwargs, cls, strict=False, dec_hook=deserializer, str_keys=True).to_dict()
msgspec.ValidationError: Expected `str`, got `null` - at `$.environment`
```

This makes sense, but the fix of adding ` | None` moves the dropdown field to just a plain textfield.

### MCVE

```python
from enum import StrEnum
from litestar import Litestar, get
from litestar.params import Parameter

class Environment(StrEnum):
    DEVELOPMENT = "dev"
    TEST = "test"
    QA = "qa"

@get(path="/")
async def test(
    environment: Environment
    | None = Parameter(
        title="Environment",
        description="The environment to filter by.",
        default=None,
        required=False,
    ),
) -> None:
    return None

app = Litestar([test])
```

### Steps to reproduce

```bash
1. Write mcve.py
2. Browse to OpenAPI schema
3. Observe dropdown fields
4. Execute on the test route
5. See error
6. Apply fix `Environment | None`
7. Reload OpenAPI schema
8. See no dropdown, just text field
9. Execute on the test route
10. See it work, but be deeply saddened that there is no longer a dropdown box and contemplate deleting your entire application.
```

### Screenshots
`: Environment`
<img width="394" alt="image" src="https://github.com/litestar-org/litestar/assets/45884264/44d1e28b-f765-4d52-ae88-e78a80c1db27">

`: Environment | None`
<img width="505" alt="image" src="https://github.com/litestar-org/litestar/assets/45884264/cdb662af-ecb4-445a-88a8-6a153691eb0b">

### Litestar Version

2.x

### Platform

- [ ] Linux
- [ ] Mac
- [ ] Windows
- [X] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh Litestar dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2546">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2546/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2546/pledge.svg">
</picture>
</a>

**Comment by JacobCoffee** [comment]
Without looking, this is probably expected behavior.. but it sucks

**Comment by peterschutt** [comment]
```py
    environment: Environment
    | None = Parameter(
```
"rough fmt" amiright?
