### ISSUE TITLE
Bug: `litestar.datastructures.MultiDict.copy` returns `multidict._multidict.MultiDict` instance.

### ISSUE THREAD

**Issue by nilsso** [litestar-org/litestar#2549]
### Description

Seems the object returned by `litestar.datastructures.MultiDict.copy` is actually a `multidict._multidict.MultiDict` instance.
```py
from litestar.datastructures import MultiDict

a = MultiDict()
b = a.copy()
print(type(a))
# litestar.datastructures.multi_dicts.MultiDict
print(type(b))
# multidict._multidict.MultiDict
```
Is this intentional?

### MCVE

```python
See description.
```

### Litestar Version

2.2.1

### Platform

- [ ] Linux
- [X] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh Litestar dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2549">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2549/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2549/pledge.svg">
</picture>
</a>

**Comment by JacobCoffee** [comment]
@litestar-org/members curious on this.

@Alc-Alc did we hit this yesterday in our OIDC testing?

**Comment by peterschutt** [comment]
I don't think this is anything we are doing:

```python-console
>>> from multidict import MultiDict
>>> class MyMD(MultiDict): ...
... 
>>> my_md = MyMD()
>>> my_md_copy = my_md.copy()
>>> type(my_md)
<class '__main__.MyMD'>
>>> type(my_md_copy)
<class 'multidict._multidict.MultiDict'>
>>> 
```
It seems that `MultiDict.copy()` doesn't support sub-classes.

**Comment by provinzkraut** [comment]
Opened an issue here: https://github.com/aio-libs/multidict/issues/901

**Comment by webknjaz** [comment]
This is how inheritance works, typically:
```pycon
>>> class MyDict(dict): ...
... 
>>> my_dict = MyDict()
>>> my_dict_copy = my_dict.copy()
>>> type(my_dict)
<class '__main__.MyDict'>
>>> type(my_dict_copy)
<class 'dict'>
```
If you want a custom class, make override the method.

**Comment by provinzkraut** [comment]
Since it seems like this won't be fixed upstream, I've implemented a fix on our side here: https://github.com/litestar-org/litestar/pull/3009
