### ISSUE TITLE
Docs: Code example provided in docs doesn't work without installing additional dependencies

### ISSUE THREAD

**Issue by AgarwalPragy** [litestar-org/litestar#2557]
### Summary

https://docs.litestar.dev/2/tutorials/sqlalchemy/index.html

Code in the given doc doesn't work without also installing `aiosqlite` and `greenlet`

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh Litestar dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2557">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2557/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2557/pledge.svg">
</picture>
</a>

**Comment by peterschutt** [comment]
Thanks for this report - we will definitely need to add aiosqlite to the required install. I don't think we should have to add greenlet, as it is one of sqlalchemy's core dependencies:

https://github.com/sqlalchemy/sqlalchemy/blob/6ba7499cdef168c9b8def2f160d3a2f09fc83218/setup.cfg#L40
