### ISSUE TITLE
Enhancement: Flash Message Framework

### ISSUE THREAD

**Issue by JacobCoffee** [litestar-org/litestar#2560]
### Summary

Add official support for a flash message framework to show one-time/temporary/stateful messages through our middleware, or something.

### Basic Example

- https://docs.djangoproject.com/en/4.2/ref/contrib/messages/
- https://flask.palletsprojects.com/en/3.0.x/patterns/flashing/
- https://github.com/orgs/litestar-org/discussions/1454
- (Reopen of) https://github.com/litestar-org/litestar/issues/1455
- https://discord.com/channels/919193495116337154/1144752656410222645/1144752656410222645

### Drawbacks and Impact

Currently we can do this using the `request` state but a straightforward, documented way to do this would be nice.

### Unresolved questions

It should probably be a plugin.

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh Litestar dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2560">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2560/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2560/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
I think it's okay to push here!

**Comment by JacobCoffee** [comment]
This didn't make it into 2.7, moving to 2.8
