### ISSUE TITLE
Optimizing Redis Cache for API Requests: Preventing Empty Cache on Options Requests Handling

### ISSUE THREAD

**Issue by ysnbyzli** [litestar-org/litestar#2573]
### Description

We cache incoming GET requests to our API using RedisStore. However, the data is stored as empty based on the Options request that comes along with the GET request. In the following code, an additional condition should be added to the "if" statement, like and `scope["method"] != HttpMethod.OPTIONS`, to prevent handling Options in this case, ensuring that the value of my Redis key is not empty.

```py
if message["type"] == "http.response.body" and not message["more_body"] and scope["method"] != HttpMethod.OPTIONS.value:
    key = (route_handler.cache_key_builder or self.config.key_builder)(Request(scope))
    await store.set(key, encode_msgpack(messages), expires_in=expires_in)
```

### URL to code causing the issue

https://github.com/litestar-org/litestar/blob/0f3e507eb6d2c388fc57a83021fda429615e8286/litestar/middleware/response_cache.py#L45

### MCVE

```python
from litestar import get
from litestar.testing import create_test_client

@get(cache=10)
async def something() -> str:
    return 'text'

with create_test_client([something]) as client:
    assert client.get('').text == 'text'
    assert client.get('').text == 'text'
    client.options('')
    assert client.get('').text == 'text'
```
RESULT(204):
```
\x92\x83\xa4type\xb3http.response.start\xa6status\xcc\xcc\xa7headers\x94\x92\xc4\x16access-control-max-age\xc4\x03600\x92\xc4\x1baccess-control-allow-origin\xc4\x01*\x92\xc4\x1caccess-control-allow-methods\xc4,DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT\x92\xc4\x1caccess-control-allow-headers\xc4RAccept, Accept-Language, Content-Language, Content-Type, authorization, x-timezone\x83\xa4type\xb2http.response.body\xa4body\xc4\x00\xa9more_body\xc2"
```

### Steps to reproduce

```bash
1. Create a redis store
2. Add `Cache=Ture` to any get request
3. Send Options request
4. Check redis value by key
```

### Litestar Version

2.2.1

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh Litestar dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2573">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2573/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2573/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
I think this would be closed by #2537?

**Comment by cemrehancavdar** [comment]
Sure it will, but disabling options to get cached should be default behavior i hope.
OPTIONS gets cached before GET and get returns empty response, so it might be better disabled without user to write a predicate? @provinzkraut

**Comment by provinzkraut** [comment]
@cemrehancavdar There seems to be a different bug causing this behaviour. @Alc-Alc described this in #2588. The overwriting of the cache shouldn't happen in any case, no matter what method is used.
