### ISSUE TITLE
Bug: File upload example doesn't work with Swagger

### ISSUE THREAD

**Issue by AgarwalPragy** [litestar-org/litestar#2628]
### Summary

The examples demonstrating file uploads in the docs don't work well with Swagger.

[Example from docs](https://docs.litestar.dev/2/usage/requests.html#file-uploads)
```py
from typing import Annotated

from litestar import Litestar, MediaType, post
from litestar.datastructures import UploadFile
from litestar.enums import RequestEncodingType
from litestar.params import Body


@post(path="/", media_type=MediaType.TEXT)
async def handle_file_upload(
    data: Annotated[UploadFile, Body(media_type=RequestEncodingType.MULTI_PART)],
) -> str:
    content = await data.read()
    filename = data.filename
    return f"{filename}, {content.decode()}"


app = Litestar(route_handlers=[handle_file_upload])
```

# Result
http://127.0.0.1:8000/schema/swagger#/default/HandleFileUpload
<img width="1401" alt="image" src="https://github.com/litestar-org/litestar/assets/7423639/b5b2b4e2-55c0-4edd-9c3d-f6a1561e3519">

# Expected
![image](https://static1.smartbear.co/swagger/media/images/swagger-ui-file-upload.png)

https://swagger.io/docs/specification/2-0/file-upload/

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh Litestar dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2628">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2628/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2628/pledge.svg">
</picture>
</a>

**Comment by AgarwalPragy** [comment]
Additionally, the file upload seems not to be working - have I configured things incorrectly?

```py
from typing import Annotated

from litestar import Litestar, post
from litestar import get
from litestar.datastructures import UploadFile
from litestar.enums import MediaType
from litestar.enums import RequestEncodingType
from litestar.params import Body


@get(path="/upload", media_type=MediaType.HTML)
def file_upload_form() -> str:
    return """
    <html>
        <body>
            <form action="/upload" enctype="multipart/form-data" method="post">
                <input type="file" accept="image/png, image/jpeg" />
                <input type="submit" value="Submit">
            </form>
        </body>
    </html>
    """


@post(path="/upload")
async def handle_file_upload(
        data: Annotated[UploadFile, Body(media_type=RequestEncodingType.MULTI_PART)],
) -> str:
    return "success"


app = Litestar(route_handlers=[handle_file_upload, file_upload_form])
```

produces the following error

```json
{
  "status_code": 400,
  "detail": "Validation failed for POST http://127.0.0.1:8000/upload",
  "extra": [
    {
      "message": "Unsupported type: <class 'dict'>",
      "key": "data",
      "source": "body"
    }
  ]
}
```

**Comment by vkuznetsovgn** [comment]
Hey guys, any progress on this one?

**Comment by marxide** [comment]
Hi! I'm not sure if this is a bug, but should this also work for `Optional[UploadFile]`? When I annotate a field with that, the Swagger UI shows a string input with an adjacent "send empty value" checkbox. I was expecting to see a file input with the checkbox.
