### ISSUE TITLE
Bug: Schema downloads don't work for `yml/yaml`

### ISSUE THREAD

**Issue by JacobCoffee** [litestar-org/litestar#2634]
### Description

When hitting `/schema/openapi.json` I get the full file, but when hitting `/schema/openapi.yml` or `/schema/openapi.yaml` the file is zero bytes.

Some of my production applications on 2.x do not have this issue, but the latest .yml changes may have broken this?
https://github.com/litestar-org/litestar/pull/2411

### URL to code causing the issue

https://github.com/litestar-org/litestar-hello-world/

### Steps to reproduce

```bash
1. Go to /schema/openapi.yaml
2. See error
```

### Litestar Version

2.2.x

### Platform

- [ ] Linux
- [ ] Mac
- [ ] Windows
- [X] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh Litestar dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2634">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2634/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2634/pledge.svg">
</picture>
</a>

**Comment by JacobCoffee** [comment]
@Alc-Alc says that it is working in later versions. Updating to 2.2.3 fixed things.
`2.2.1 -> 2.3.2`

**Comment by dkubatin** [comment]
I'm having the same problem.

litestar version: `2.5.3`
