### ISSUE TITLE
Bug: Schema generation partially broken since litestar version 2.3.0

### ISSUE THREAD

**Issue by euthuppan** [litestar-org/litestar#2635]
### Description

2.2.1 is my last working version of litestar. 

Before:
<img width="467" alt="image" src="https://github.com/litestar-org/litestar/assets/85191795/dc9594b1-4b09-4607-9061-dcd65bf0a09f">

After:
I first get this `internal server error` when i first try to go to my Swagger URL

<img width="436" alt="image" src="https://github.com/litestar-org/litestar/assets/85191795/90112884-907e-4ee0-a14c-a92c338ef761">

And then when i refresh once more, it goes to my swagger page, but only 2/3 of it.

<img width="217" alt="image" src="https://github.com/litestar-org/litestar/assets/85191795/74f16208-e80a-46de-b580-3dd566e0f14b">

With no changes in my code, the problems just start at version 2.3.0 and beyond. Just wanted to bring attention to this, as I will now be sticking to litestar 2.2.1 until this is resolved.

### MCVE

```python
How my app code looks like when passing in my controllers:

app = Litestar(
    route_handlers=[
        read_root,
        refresh_templates,
        LinuxPXEController,
        WindowsPXEController,
        ESXiPXEController
    ],
 ...
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Litestar Version

2.3.0

### Platform

- [X] Linux
- [X] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh Litestar dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2635">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2635/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2635/pledge.svg">
</picture>
</a>

**Comment by cofin** [comment]
@euthuppan could you please enable `debug` mode on the application and let us know if that gives you additional output?

```python
app = Litestar(
    **debug=True,**
    route_handlers=[
        read_root,
        refresh_templates,
        LinuxPXEController,
        WindowsPXEController,
        ESXiPXEController
    ],
    ```

**Comment by timwedde** [comment]
I've also started running into this issue with v2.3, find a screenshot of the error in debug mode below:
![Screenshot 2023-11-09 at 11 39 54](https://github.com/litestar-org/litestar/assets/20231751/6eb6b953-781c-4f86-8d96-a947ff92128c)


This also happens for ReDoc and Elements, so it's consistent across all OpenAPI renderers.

**Comment by provinzkraut** [comment]
@timwedde @euthuppan could one of you provide an MCVE that reproduces this?

**Comment by timwedde** [comment]
Took me a little while to track this down, but here you go:
```py
# pip install pydantic==2.4.2 litestar==2.3.2

from litestar import Litestar, get
from pydantic import BaseModel


class SubModel(BaseModel):
    fail: dict = {}  # fails
    # fail: dict = Field(default={})  # fails
    # fail: dict = Field(default_factory=dict)  # works


class Model(BaseModel):
    id: int
    submodel: SubModel


@get("/")
async def mcve() -> Model:
    return Model(id=1, submodel=SubModel())


app = Litestar(
    debug=True,
    route_handlers=[mcve],
)
```

Seems that this may now be semi-intended behavior since the `default_factory` approach is likely the objectively correct one anyway, but it does somewhat smell like a breaking change in a minor version update. For reference, this does work properly on Litestar versions before 2.3.x, with the same pydantic version.

**Comment by Alc-Alc** [comment]
So things seems to have broken on 46ea14bf045f1804e0a1623407ec525179acbfb4 (#2553) for the MCVE above (`fail: dict = {}`). Bisected all the way from a7fe0f306e541253351fb1ad373bf6ff590eef9a (v2.2.0) to 0c6a57f8454838572aa6eaffd89123c778d638df (current main)

**Comment by Alc-Alc** [comment]
So change this https://github.com/litestar-org/litestar/blob/0c6a57f8454838572aa6eaffd89123c778d638df/litestar/contrib/pydantic/utils.py#L164-L165

```py
def is_pydantic_undefined(value: Any) -> bool:
    return any(v is value for v in PYDANTIC_UNDEFINED_SENTINELS)
```

so that it is the same as this?

https://github.com/litestar-org/litestar/blob/0c6a57f8454838572aa6eaffd89123c778d638df/litestar/utils/predicates.py#L314-L323

**Comment by provinzkraut** [comment]
Thanks for the effort @Alc-Alc! The proposed change looks good to me, do you want to implement it (and add a test case to reproduce)?

**Comment by provinzkraut** [comment]
Also thanks @timwedde for the great mcve! This is really helpful! :)
