### ISSUE TITLE
Docs: Clarify wording around thread safety in MemoryStore documentation

### ISSUE THREAD

**Issue by jdglaser** [litestar-org/litestar#2651]
### Summary

The `MemoryStore` class has the following description in the API reference:

> In memory, thread-safe, asynchronous key/value store.

This can be slightly misleading, as the actual implementation of `MemoryStore` uses `anyio.Lock` which, by design, is [not thread safe](https://anyio.readthedocs.io/en/stable/synchronization.html):

> Note AnyIO primitives are not thread-safe, therefore they should not be used directly from worker threads. Use [run_sync()](https://anyio.readthedocs.io/en/stable/api.html#anyio.from_thread.run_sync) for that.

A better phrase might be "atomic", since what the `MemoryStore` really guarantees is that that multi-step operations (such as get and renew) either succeed fully or fail, and won't be stuck in an in-between state.

Additionally, it might be worth calling out in the docs under the `Stores` section that `MemoryStore` (or any in memory data structure for that matter) should not be used when enabling multiple worker processes, or at least it shouldn't be used for interprocess communication. In those cases, it usually makes sense to use some non-memory store (e.g. Redis).

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh Litestar dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2651">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2651/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2651/pledge.svg">
</picture>
</a>

**Comment by JacobCoffee** [comment]
Would you like to open a PR wit this change?

**Comment by jdglaser** [comment]
> Would you like to open a PR wit this change?

Sure! I can work on getting a PR for it out there soon.
