### ISSUE TITLE
Bug: Routes with duplicate parameter names are not shown in OpenAPI rendering

### ISSUE THREAD

**Issue by ThirVondukr** [litestar-org/litestar#2662]
### Description

OpenAPI schema fails to generate if there's 2 parameters present with identical name, route is subsequently removed from OpenAPI schema.

### MCVE

```python
from typing import Annotated

from litestar import Litestar, post
from litestar.params import Parameter


@post("/test")
async def route(
    name: Annotated[str | None, Parameter(cookie="name")] = None,
    name_header: Annotated[str | None, Parameter(header="name")] = None,
) -> str:
    return name or name_header or ""


app = Litestar(
    route_handlers=[route],
)
```

### Steps to reproduce

```bash
1. Launch uvicorn server `uvicorn app:app`
2. Go to http://127.0.0.1:8000/schema/swagger
3. See error
```

### Logs

```bash
$ uvicorn app:app
INFO:     Started server process [8376]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:54807 - "GET /schema/swagger HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:54807 - "GET /schema/swagger HTTP/1.1" 200 OK
```

### Litestar Version

2.3.2

### Platform

- [ ] Linux
- [ ] Mac
- [X] Windows
- [ ] Other (Please specify in the description above)

**Comment by Alc-Alc** [comment]
Changed the title to be more descriptive of the actual issue. The routes continue to work, it's just that they are not shown on any OpenAPI renderers (swagger, elements etc) after the first load which raises the following exception (not attaching the stack trace).

`500: OpenAPI schema generation for handler `app.route` detected multiple parameters named 'name' with different types.`

**Comment by ThirVondukr** [comment]
I should have originally attached stacktrace, but I'm fairly new to litestar and didn't know how to configure debug/logging options 🙂

**Comment by Alc-Alc** [comment]
> I should have originally attached stacktrace, but I'm fairly new to litestar and didn't know how to configure debug/logging options 🙂

No worries 🙂 I just do `app = Litestar(route_handlers=[route], debug=True)` and run the app.


> Also on first request `openapi.json` returns status code 500 🤔

This is not limited to your issue per se, most issues in the schema generation exhibit the same behavior, it sort of gets "cached" which is why you only see the error on the first try and the "non erroneous" schema from the second.

**Comment by peterschutt** [comment]
I've opened #2788 to address this, it would now only be an error to have two openapi params declared in the same place (i.e., two dependencies that both declare a "name" header with different constraints).

I've got a slightly modified MCVE:

```py
from __future__ import annotations

from typing import Dict, Optional

from typing_extensions import Annotated

from litestar import Litestar, post
from litestar.params import Parameter


@post("/test")
async def route(
    name_cookie: Annotated[Optional[str], Parameter(cookie="name", description="name via cookie")] = None,
    name_header: Annotated[Optional[str], Parameter(header="name", description="name via header")] = None,
) -> Dict[str, str]:
    return {"name_cookie": name_cookie or "", "name_header": name_header or ""}


app = Litestar(route_handlers=[route], debug=True)
```

And that renders:

![image](https://github.com/litestar-org/litestar/assets/20659309/df9d95d0-aa3b-4d48-b749-dbb92f8aa9b9)

So I suppose that satisfies this particular issue, however, when I try the route out:

![image](https://github.com/litestar-org/litestar/assets/20659309/8180309c-62ab-4007-8f92-2c4615ba10f3)

Notice that I don't get a value for the cookie name. It doesn't seem to make any difference if I send the header name or not, the cookie name doesn't come through. Was this ever working for you @ThirVondukr?
