### ISSUE TITLE
Bug: SSE not showing up in browser if not explicitly ending AsyncGenerator content with newline

### ISSUE THREAD

**Issue by macabrus** [litestar-org/litestar#2678]
### Description

I am using Litestar on the backend, HTMX + Jinja2 for templating.
I have following code:
```python

@get(path="/progress", sync_to_thread=False)
def handle_updates() -> ServerSentEvent:
    """This route pushes finish/progress events to the client."""

    async def result_notifier() -> AsyncGenerator[str, None]:
        # keep state per client, re-render template fragment
        ctx = {
            "progress": None,
            "tasks": (tasks := TASKS),
        }
        for i in itertools.count(1):
            html = f'<h1>{i}</h1>\n'   # this \n missing was the problem!!!
            yield html
            await asyncio.sleep(1)

    return ServerSentEvent(result_notifier())
```
and following event receiver in HTMX:

```html
<div id="queue-status" hx-ext="sse" sse-connect="/progress" >
    <div sse-swap="message"></div>
</div>
```
also tried `curl`ing:
```shell
curl http://localhost:8000/progress
data: <h1>1</h1>
data: <h1>2</h1>
...

curl http://localhost:8000/progress
data: <h1>1</h1>

data: <h1>2</h1>

data: <h1>3</h1>

data: <h1>4</h1>
...
```

My issue is that i didn't explicitly end events with '\n' so browser was forever buffering them and not showing in event stream console (neither Safari nor Chrome). As I've learned, SSE should **explicitly** end in '\n\n' to prevent buffering behavior! Is this expected behaviour? It wasn't obvious for me at all and I suggest this to be in the docs.

### Logs

```bash
server logs do not contain errors, client side behavior is odd.
```

### Litestar Version

latest

### Platform

- [ ] Linux
- [X] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh Litestar dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2678">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2678/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2678/pledge.svg">
</picture>
</a>

**Comment by JacobCoffee** [comment]
I think we could document this better in https://docs.litestar.dev/latest/usage/responses.html#server-sent-event-responses and also include a link to the living standard for it (https://html.spec.whatwg.org/multipage/server-sent-events.html)

**Comment by provinzkraut** [comment]
I think we *should* consider this a bug. It's very unintuitive and can be easily fixed by appending the newline if it's not already there :shrug:

**Comment by provinzkraut** [comment]
Now that I think about this, it might be better if simply were to add a parameter that could configure this. Something like `disable_client_buffering`?

**Comment by provinzkraut** [comment]
@euri10 Iiuc your PR #2888 would fix this one as well, right?

**Comment by euri10** [comment]
> @euri10 Iiuc your PR #2888 would fix this one as well, right?

yes i think so :)
