### ISSUE TITLE
Enhancement: Allow creating templates from strings

### ISSUE THREAD

**Issue by 3tilley** [litestar-org/litestar#2687]
### Summary

Especially when using HTMX, there are lots of little html partials that need to be returned. I could set these all up in a Jinja templates but it's a layer of indirection I don't particularly want to deal with - particularly with HTMX's focus on locality. It would be easier to just do something like `Template.from_str(...)`.

The alternative would be to use something like `yattag` or `airium`, which I'll probably try. If this is the best way to do it maybe `litestar` could suggest one of them as part of being "opinionated".

### Basic Example
````python
@get("/foo")
def my_route() -> Reswap:
    table = f"""
        <table>
        {% for item in items %}
        <TR>
           <TD class="c1"><IMG src="favicon.ico"></TD>
           <TD class="c2">{{item.date}}</TD>
           <TD class="c3">{{item.id}}</TD>
           <TD class="c4"><SPAN>{{item.position}}</SPAN></TD>
           <TD class="c5"><SPAN>{{item.status}}</SPAN></TD>
        {% endfor %}
        </table>
        </TR>
      """
    return Template.from_str(table, context=get_items())
````

### Drawbacks and Impact

I guess there other ways of doing this, perhaps with a custom template engine? I can't see any other way in which it would have much impact

**Comment by JacobCoffee** [comment]
Hi @3tilley, please check the dev docs on this. It should be released soon.

https://docs.litestar.dev/dev/usage/templating.html#template-files-vs-strings

**Comment by 3tilley** [comment]
This is awesome! Thanks for turning this around so quickly!
