### ISSUE TITLE
Bug: Dependency Injection:``"NameError: name 'Callable' is not defined"

### ISSUE THREAD

**Issue by aedify-swi** [litestar-org/litestar#2695]
### Description

Hello!

I encountered a bug / a severe misunderstanding on my end when using litestar's DI.

I am trying to inject a [svcs](https://svcs.hynek.me/en/stable/) Container via litestar's DI. (We were using litestar DI previously, but as our workflow runners use svcs and we're now unifying all the dependencies in one place.) Unfortunately, this leads to a wonderful 500 I cannot resolve: `NameError: name 'Callable' is not defined`.

Some additional observations:
 - Injecting the `registry` with type annotation `svcs.Registry` fails too, typing it as `Any` works
 - Injecting the `container` with type annotation `svcs.Container` or `Any` always fails
 - Injecting everything as `Any` works (even in the Provide).
 - Injecting everything as `Any` but the container in the handler as `svcs.Container` results in a `NameError: name 'AbstractContextManager' is not defined`

### MCVE

```python
from collections.abc import AsyncGenerator
from typing import Any
from uuid import UUID

import litestar
import msgspec
import svcs
import uvicorn
from litestar.di import Provide
from litestar.exceptions import NotFoundException
from litestar.params import Dependency


class Result(msgspec.Struct):
    field: str


class Req(msgspec.Struct):
    field: str


@litestar.post("/test")
async def test(
    data: Req,
    container: svcs.Container = Dependency(),
) -> Result:
    if data.field is not None:
        await container.aget(UUID)
        return Result(field="test")
    raise NotFoundException


registry = svcs.Registry()
registry.register_value(UUID, UUID(int=0))


async def provide_container(
    registry: svcs.Registry
) -> AsyncGenerator[svcs.Container, None]:
    async with svcs.Container(registry) as container:
        yield container


app = litestar.Litestar(
    route_handlers=[test],
    debug=True,
    dependencies={
        "registry": Provide(lambda: registry, sync_to_thread=False),
        "container": Provide(provide_container),
    },
)

uvicorn.run(app)
```

### Steps to reproduce

```bash
1. Run the MCVE
```

### Logs

```bash
INFO:     Started server process [832654]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
ERROR - 2023-11-17 08:47:01,314 - litestar - config - exception raised on http connection to route /test

Traceback (most recent call last):
  File "/home/user/test/.venv/lib/python3.11/site-packages/litestar/middleware/exceptions/middleware.py", line 191, in __call__
    await self.app(scope, receive, send)
  File "/home/user/test/.venv/lib/python3.11/site-packages/litestar/routes/http.py", line 81, in handle
    response = await self._get_response_for_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/test/.venv/lib/python3.11/site-packages/litestar/routes/http.py", line 133, in _get_response_for_request
    return await self._call_handler_function(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/test/.venv/lib/python3.11/site-packages/litestar/routes/http.py", line 153, in _call_handler_function
    response_data, cleanup_group = await self._get_response_data(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/test/.venv/lib/python3.11/site-packages/litestar/routes/http.py", line 185, in _get_response_data
    cleanup_group = await parameter_model.resolve_dependencies(request, kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/test/.venv/lib/python3.11/site-packages/litestar/_kwargs/kwargs_model.py", line 391, in resolve_dependencies
    await resolve_dependency(next(iter(batch)), connection, kwargs, cleanup_group)
  File "/home/user/test/.venv/lib/python3.11/site-packages/litestar/_kwargs/dependencies.py", line 62, in resolve_dependency
    signature_model.parse_values_from_connection_kwargs(connection=connection, **kwargs)
  File "/home/user/test/.venv/lib/python3.11/site-packages/litestar/_signature/model.py", line 190, in parse_values_from_connection_kwargs
    return convert(kwargs, cls, strict=False, dec_hook=deserializer, str_keys=True).to_dict()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/test/.venv/lib/python3.11/site-packages/msgspec/_utils.py", line 209, in get_dataclass_info
    hints = get_class_annotations(obj)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/test/.venv/lib/python3.11/site-packages/msgspec/_utils.py", line 131, in get_class_annotations
    value = typing._eval_type(value, cls_locals, cls_globals)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.11.0/lib/python3.11/typing.py", line 378, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.11.0/lib/python3.11/typing.py", line 871, in _evaluate
    eval(self.__forward_code__, globalns, localns),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'Callable' is not defined
Traceback (most recent call last):
  File "/home/user/test/.venv/lib/python3.11/site-packages/litestar/middleware/exceptions/middleware.py", line 191, in __call__
    await self.app(scope, receive, send)
  File "/home/user/test/.venv/lib/python3.11/site-packages/litestar/routes/http.py", line 81, in handle
    response = await self._get_response_for_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/test/.venv/lib/python3.11/site-packages/litestar/routes/http.py", line 133, in _get_response_for_request
    return await self._call_handler_function(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/test/.venv/lib/python3.11/site-packages/litestar/routes/http.py", line 153, in _call_handler_function
    response_data, cleanup_group = await self._get_response_data(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/test/.venv/lib/python3.11/site-packages/litestar/routes/http.py", line 185, in _get_response_data
    cleanup_group = await parameter_model.resolve_dependencies(request, kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/test/.venv/lib/python3.11/site-packages/litestar/_kwargs/kwargs_model.py", line 391, in resolve_dependencies
    await resolve_dependency(next(iter(batch)), connection, kwargs, cleanup_group)
  File "/home/user/test/.venv/lib/python3.11/site-packages/litestar/_kwargs/dependencies.py", line 62, in resolve_dependency
    signature_model.parse_values_from_connection_kwargs(connection=connection, **kwargs)
  File "/home/user/test/.venv/lib/python3.11/site-packages/litestar/_signature/model.py", line 190, in parse_values_from_connection_kwargs
    return convert(kwargs, cls, strict=False, dec_hook=deserializer, str_keys=True).to_dict()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/test/.venv/lib/python3.11/site-packages/msgspec/_utils.py", line 209, in get_dataclass_info
    hints = get_class_annotations(obj)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/test/.venv/lib/python3.11/site-packages/msgspec/_utils.py", line 131, in get_class_annotations
    value = typing._eval_type(value, cls_locals, cls_globals)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.11.0/lib/python3.11/typing.py", line 378, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.pyenv/versions/3.11.0/lib/python3.11/typing.py", line 871, in _evaluate
    eval(self.__forward_code__, globalns, localns),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'Callable' is not defined
INFO:     127.0.0.1:52232 - "POST /test HTTP/1.1" 500 Internal Server Error
```

### Litestar Version

2.3.2

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh Litestar dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2695">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2695/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2695/pledge.svg">
</picture>
</a>

**Comment by peterschutt** [comment]
Thanks for the report and MCVE @aedify-swi.

I've reproduced with a slightly slimmed down version:

```py
from collections.abc import AsyncGenerator
from typing import Callable
from uuid import UUID

import litestar
import svcs
import uvicorn
from litestar.di import Provide
from litestar.params import Dependency


@litestar.get("/")
async def handle(
    container: svcs.Container = Dependency(skip_validation=True),
) -> None:
    pass


registry = svcs.Registry()
registry.register_value(UUID, UUID(int=0))


async def provide_container(
    registry: svcs.Registry
) -> AsyncGenerator[svcs.Container, None]:
    async with svcs.Container(registry) as container:
        yield container


app = litestar.Litestar(
    route_handlers=[handle],
    debug=True,
    dependencies={
        "registry": Provide(lambda: registry, sync_to_thread=False),
        "container": Provide(provide_container),
    },
    signature_types=[Callable]
)

if __name__ == "__main__":
    uvicorn.run(app)
```

I'll take a closer look over the next day or two to see what is really up here, but you can get going with the following:

```py
async def provide_container(
    registry: svcs.Registry = Dependency(skip_validation=True)  # <-- add this
) -> AsyncGenerator[svcs.Container, None]:
    async with svcs.Container(registry) as container:
        yield container
```

**Comment by peterschutt** [comment]
I don't think the OP is something that can be fixed here. The issue is that in `svcs` they've been overwriting the `__module__` attribute of their types in `svcs.__init__`:

```py
# Make nicer public names.
__locals = locals()
for __name in __all__:
    if not __name.startswith("__") and not __name.islower():
        __locals[__name].__module__ = "svcs"
del __locals
del __name  # pyright: ignore[reportUnboundVariable]
```
Which means the correct global namespace cannot be determined for the `svcs.*` types, and so when msgspec tries to resolve the annotations on `Registry` it cannot because it doesn't have `Callable` in the namespace of types to use for the resolution.

Good news is this was removed in a PR yesterday: https://github.com/hynek/svcs/pull/53

**Comment by guacs** [comment]
@aedify-swi just to note one more thing. Even with the fix in `svcs`, you'll still have to do `Dependency(skip_validation=True)` since `svcs.Registry` and `svcs.Container` have some union types that `msgpsec` (the library we use for handling the validation) does not support.

**Comment by peterschutt** [comment]
As time goes on, the more I think that `skip_validation=True` should be the default for dependencies.

**Comment by guacs** [comment]
> As time goes on, the more I think that `skip_validation=True` should be the default for dependencies.

Yeah I think that makes a lot of sense, but unfortunately that would be a breaking change :/

**Comment by peterschutt** [comment]
> > As time goes on, the more I think that `skip_validation=True` should be the default for dependencies.
> 
> Yeah I think that makes a lot of sense, but unfortunately that would be a breaking change :/

we could make it an experimental feature for 2.x?

**Comment by guacs** [comment]
I don't think it should be experimental but a future flag or something. I think there was some conversation regarding this in one of the other issues.

**Comment by peterschutt** [comment]
Well i say experimental, because I think it should be, at least at first.

There is a safety net that validating the dependencies via the signature model brings us - that is, if a user incorrectly annotates the type of a dependency in the handler signature it gets picked up eventually via msgspec, and is propagated as a 500 error on request. Without this, we most likely still end up with a 500 error, but that would rely on some logic inside the handler to interact with the injected value in a type-incompatible manner. Worst case would be that the annotated type shares some common api with the injected instance, and the route doesn't fail but the user is not operating on the object they think they are.

**Comment by guacs** [comment]
> Well i say experimental, because I think it should be, at least at first.
> 
> There is a safety net that validating the dependencies via the signature model brings us - that is, if a user incorrectly annotates the type of a dependency in the handler signature it gets picked up eventually via msgspec, and is propagated as a 500 error on request. Without this, we most likely still end up with a 500 error, but that would rely on some logic inside the handler to interact with the injected value in a type-incompatible manner. Worst case would be that the annotated type shares some common api with the injected instance, and the route doesn't fail but the user is not operating on the object they think they are.

That makes sense. So, would this experimental flag become a future flag at some point? If so, what would that process be like?

**Comment by peterschutt** [comment]
> So, would this experimental flag become a future flag at some point?

If the experiment was successful, I suppose yes.

> If so, what would that process be like?

Probably the flag would be moved/added to future flags and made default on the next major version bump.

**Comment by guacs** [comment]
> Probably the flag would be moved/added to future flags and made default on the next major version bump.

The "moved/added" is where I was confused. If it's moved, then the existing code that used it in experimental flags wouldn't work as expected until they move the flag into feature flags. If it's added, then in the code we have to check in both experimental and feature flags which doesn't feel right to me.

I think it's important that we create a documented process for how the experimental/feature flags work before introducing them.
