### ISSUE TITLE
Docs: Rate limit middleware docs typo

### ISSUE THREAD

**Issue by JacobCoffee** [litestar-org/litestar#2697]
### Summary

https://docs.litestar.dev/latest/usage/middleware/builtin-middleware.html#rate-limit-middleware

This last sentence seems to be punctuated when it shouldn't have, or missing additional details.
<img width="912" alt="image" src="https://github.com/litestar-org/litestar/assets/45884264/8bb592ec-fd0b-4cf6-9dab-4d5eb94e3bf6">

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh Litestar dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2697">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2697/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2697/pledge.svg">
</picture>
</a>

**Comment by cesarmg1980** [comment]
@all-contributors please add @cesarmg1980 for contributions

**Comment by cesarmg1980** [comment]
@all_contributors please add @cesarmg1980 for doc

**Comment by cesarmg1980** [comment]
maybe this issue can be closed?
