### ISSUE TITLE
Bug(Docs): 'Redirect' object is not callable

### ISSUE THREAD

**Issue by hunterjsb** [litestar-org/litestar#2709]
### Description

Creating middleware according to the [the documentation](https://github.com/litestar-org/litestar/blob/main/docs/usage/middleware/creating-middleware.rst#responding-using-the-middlewareprotocol) raises a `TypeError` : `'Redirect' object is not callable`

### MCVE

```python
app = Litestar(middleware=[RedirectMiddleware])  # as defined below
```

### Steps to reproduce

Add the following middleware to your application:
```py
class RedirectMiddleware(MiddlewareProtocol):
    def __init__(self, app: ASGIApp) -> None:
        super().__init__(app)
        self.app = app

    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None:
        if Request(scope).session is None:
            response = Redirect(path="/login")
            await response(scope, receive, send)
        else:
            await self.app(scope, receive, send)
```

### Litestar Version

2.3.2

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh Litestar dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2709">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2709/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2709/pledge.svg">
</picture>
</a>

**Comment by hunterjsb** [comment]
I believe the docs should use `litestar.responses.redirect.ASGIRedirectResponse` instead of `litestar.responses.Redirect`

**Comment by provinzkraut** [comment]
Thanks for reporting this!

> I believe the docs should use `litestar.responses.redirect.ASGIRedirectResponse` instead of `litestar.responses.Redirect`

That would be the proper fix, yes. Do you want to submit a PR for this? :)

**Comment by hunterjsb** [comment]
Just did! #2710
