### ISSUE TITLE
Bug: incorrect message in ValidationException when multiple errors occured

### ISSUE THREAD

**Issue by aldem** [litestar-org/litestar#2714]
### Description

When there is more than one validation issue detected, the message describing the problem for each parameter is the same.

In my case, I have rules as `a > 5` and `b < 5` but I get:

```json
{
    "status_code": 400,
    "detail": "Validation failed for GET http://127.0.0.1:8000/?a=0&b=9",
    "extra": [
        {
            "message": "Expected `int` <= 4",
            "key": "a",
            "source": "query"
        },
        {
            "message": "Expected `int` <= 4",
            "key": "b",
            "source": "query"
        }
    ]
}
```

Single error (if only one parameter is invalid) is correctly displaying the message.

### MCVE

```python
from litestar import Litestar, get, Response
from litestar.params import Parameter
from typing import Annotated

@get("/")
async def default(
        a: Annotated[int, Parameter(gt=5)],
        b: Annotated[int, Parameter(lt=5)],
) -> Response:
    return Response(content=f'{a} {b}\n')

app = Litestar(route_handlers=[default])
```

### Steps to reproduce

```bash
Run the app and access the URL `http://127.0.0.1:8000/?a=0&b=9`.
```

### Litestar Version

Litestar 2.3.2 on Python 3.11.2

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh Litestar dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2714">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2714/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2714/pledge.svg">
</picture>
</a>

**Comment by peterschutt** [comment]
Thanks for reporting this@aldem and appreciate the MCVE!
