### ISSUE TITLE
Bug: Renaming in DTOs with nested fields will rename all occurrences.

### ISSUE THREAD

**Issue by simon-lund** [litestar-org/litestar#2721]
### Description

In the example below, we have two models: 'Chat' and 'Message', each with an 'id' field. We also define a ResponseDTO for the Chat model, using DTOConfig to rename its 'id' field to 'chat_id'. 

The intention is to only rename the 'id' of the Chat model. However, this configuration unexpectedly renames the 'id' field in the nested Message objects as well. As a result, the response output is 

`{"chat_id":"1","messages":[{"chat_id":"1","created_at":"1","user_id":"1"}]}`, 

where both Chat and Message 'id' fields are affected, contrary to the intended behavior.

### MCVE

```python
from typing_extensions import List
from litestar import get, Litestar
from pydantic import BaseModel
from litestar.dto import DTOConfig
from litestar.contrib.pydantic import PydanticDTO

class Message(BaseModel):
    id: str
    created_at: str
    user_id: str

class Chat(BaseModel):
    id: str
    messages: List[Message]

class ResponseDTO(PydanticDTO[Chat]):
    config = DTOConfig(rename_fields={"id": "chat_id"})

@get(return_dto=ResponseDTO)
async def get_chat() -> Chat:
    return Chat(id="1", messages=[Message(id="1", created_at="1", user_id="1")])

app = Litestar([get_chat])
```

### Steps to reproduce

```bash
1. Start Litestar
2. Make API call `curl localhost:8000`
3. Observe :bug:
```

### Litestar Version

2.2.1

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh Litestar dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2721">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2721/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2721/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
@peterschutt Haven't really investigated yet, but it happens on both the regular and the codegen backend
