### ISSUE TITLE
Enhancement: Support nested renaming in DTOs

### ISSUE THREAD

**Issue by simon-lund** [litestar-org/litestar#2722]
### Summary

Similar to nested exclusion, I would like to be able to rename nested fields in a DTO.

Links for nested exclusion tutorial:
https://docs.litestar.dev/2/tutorials/dto-tutorial/02-nested-exclude.html
https://docs.litestar.dev/2/tutorials/dto-tutorial/03-nested-collection-exclude.html

Expected behavior:
```bash
> curl localhost:8000
{"id":"1","messages":[{"id":"1", "userName":"1"}]}
```

### Basic Example

```python
from typing import Annotated

from litestar import get, Litestar
from litestar.contrib.pydantic import PydanticDTO
from litestar.dto import DTOConfig
from pydantic import BaseModel


class Message(BaseModel):
    id: str
    user_id: str
    ...


class Chat(BaseModel):
    id: str
    messages: list[Message]
    ...


dto_config = DTOConfig(rename_fields={"messages.0.user_id": "userName"})
ChatDTO = PydanticDTO[Annotated[Chat, dto_config]]


@get(return_dto=ChatDTO)
def get_chat() -> Chat:
    return Chat(id="1", messages=[Message(id="1", user_id="1")])


app = Litestar([get_chat])

```

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh Litestar dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2722">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2722/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2722/pledge.svg">
</picture>
</a>

**Comment by peterschutt** [comment]
Closed by #2764
