### ISSUE TITLE
Bug: multiple connection objects can cause the app to hang

### ISSUE THREAD

**Issue by peterschutt** [litestar-org/litestar#2727]
### Description

If multiple request objects are created before the first one calls one of the cached data access methods, e.g., `Request.json()` et. al, then the 2nd one to attempt to access the data will cause the request to block on `receive()` for a 2nd time, waiting for message that will never come.

The reason is that we only check whether the data has been cached upon instantiation of the connection objects, not when the connection object attempts to access the request data.

### MCVE

```python
from typing import Dict

from litestar import Litestar, Request, post
from litestar.types.asgi_types import ASGIApp, Message, Receive, Scope, Send


def some_middleware(app: ASGIApp) -> ASGIApp:
    async def middleware(scope: Scope, receive: Receive, send: Send) -> None:
        request = Request(scope, receive, send)

        async def wrapped_send(message: Message) -> None:
            await request.json()
            # do something with data
            await send(message)

        await app(scope, receive, wrapped_send)

    return middleware


@post(middleware=[some_middleware])
async def root(request: Request) -> Dict[str, str]:
    return request.json()


app = Litestar(route_handlers=[root], debug=True)
```

### Steps to reproduce

```bash
1. run the above application
2. make any POST request to `/`
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Litestar Version

main

### Platform

- [X] Linux
- [X] Mac
- [X] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh Litestar dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2727">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2727/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2727/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
What if we simply made the connection objects singletons? I.e. modify the `__new__` method to cache the object in the scope upon instantiation, and reuse that instance for subsequent instantiations?

**Comment by peterschutt** [comment]
> What if we simply made the connection objects singletons? I.e. modify the `__new__` method to cache the object in the scope upon instantiation, and reuse that instance for subsequent instantiations?
> 
> 
> 
> 

Caching a connection in scope is the direction I was heading too (see https://github.com/litestar-org/litestar/pull/2718) - leveraging `__new__()` to abstract this is an interesting idea and definitely worth a look!

**Comment by provinzkraut** [comment]
> Caching a connection in scope is the direction I was heading too (see #2718) - leveraging `__new__()` to abstract this is an interesting idea and definitely worth a look!

Will have to think about potential side effects and edge cases a bit, but wouldn’t this allow us to greatly simplify the whole process? If we cache the connection objects themselves, we wouldn’t need to do cache the individual parts (urls, headers, cookies) in the scope anymore.

The only problem I see there is that since everything *inherits* from the base connection, of you create a `Request`, the cached things won’t be reused. We could change this by switching from inheritance to compositions and make the underlying connection an instance attribute rather than a base class but that would be breaking.

**Comment by peterschutt** [comment]
I've elected to fix the current behavior by moving the initial scope cache checks from within `__init__()` to inside the access methods, as it is a pretty simple fix this way, and more aligned with how we usually configure these sort of `self._object_cache_attribute`s (that is, setting them to empty and populating them on first access).
