### ISSUE TITLE
Bug: Optional query parameters not generating correctly in openapi json

### ISSUE THREAD

**Issue by WilliamStam** [litestar-org/litestar#2730]
### Description

when using an optional query parameter as a parameter in the route handler it incorrectly defines the type. it doesnt pick up the None in it and set required instead it adds None as a "oneOf" 

```
async def checking_optional_query_params(
        self,
        opt1: Optional[str] = None,
        opt2: str = None,
        opt3: Annotated[str | None, Parameter(query="opt3")] = None,
        opt4: Annotated[str, Parameter(query="opt4")] = None,
    ) -> dict:
```

results in 

```
"parameters": [
    {
        "name": "opt1",
        "in": "query",
        "schema": {
            "oneOf": [
                {
                    "type": "null"
                },
                {
                    "type": "string"
                }
            ]
        },
        "required": false,
        "deprecated": false,
        "allowEmptyValue": false,
        "allowReserved": false
    },
    {
        "name": "opt2",
        "in": "query",
        "schema": {
            "type": "string"
        },
        "required": true,
        "deprecated": false,
        "allowEmptyValue": false,
        "allowReserved": false
    },
    {
        "name": "opt3",
        "in": "query",
        "schema": {
            "oneOf": [
                {
                    "type": "null"
                },
                {
                    "type": "string"
                }
            ]
        },
        "required": false,
        "deprecated": false,
        "allowEmptyValue": false,
        "allowReserved": false
    },
    {
        "name": "opt4",
        "in": "query",
        "schema": {
            "type": "string"
        },
        "required": true,
        "deprecated": false,
        "allowEmptyValue": false,
        "allowReserved": false
    }
],
```

shouldnt they all be:

```
{
    "name": "opt2",
    "in": "query",
    "schema": {
        "type": "string"
    },
    "required": false,
    "deprecated": false,
    "allowEmptyValue": true,
    "allowReserved": false
},
```

### MCVE

```python
from typing import Annotated, Optional

from litestar import Controller, Litestar, get
from litestar.openapi import OpenAPIConfig
from litestar.params import Parameter


class RouteController(Controller):
    @get("")
    async def checking_optional_query_params(
        self,
        opt1: Optional[str] = None,
        opt2: str = None,
        opt3: Annotated[str | None, Parameter(query="opt3")] = None,
        opt4: Annotated[str, Parameter(query="opt4")] = None,
    ) -> dict:
        return {
            "opt1": opt1,
            "opt2": opt2,
            "opt3": opt3,
            "opt4": opt4,
        }


app = Litestar(
    debug=True,
    route_handlers=[
        RouteController
    ],
    openapi_config=OpenAPIConfig(
        title="TestAPI",
        version="1.0.0",
        security=[],
    )
)
```

### Steps to reproduce

```bash
save the above as `test.py`
run it with `uvicorn test:app`
go to `http://127.0.0.1:8000/schema/rapidoc`
view `http://127.0.0.1:8000/schema/openapi.json`
```

### Screenshots

"![Rapidoc](https://i.imgur.com/QMj3Msm.png)"

### Litestar Version

litestar==2.3.2
pydantic==2.5.1
uvicorn==0.24.0.post1

### Platform

- [ ] Linux
- [ ] Mac
- [X] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh Litestar dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2730">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2730/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2730/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
This is actually correct. If you say `Optional[str]`, it's just a shorthand for `Union[str, None]`, meaning the field can be either a `str`, or `None`. This is exactly what is generated for the OpenAPI schema. Whether or not this is then required is defined by the default value. If you have a default, it's not required. If you don't have a default, it is required. What would you expect the value of a parameter to be if it's not required and doesn't have a default?
