### ISSUE TITLE
Bug: OpenAPI schema generation fails when using pydantic alias

### ISSUE THREAD

**Issue by LonelyVikingMichael** [litestar-org/litestar#2731]
### Description

I thought my issue was the same as #2471, but it turns out to be different.

Defining any alias on a pydantic field for a single schema seems to lead OpenAPI generation to believe that it is working with two schemas (which is technically correct if we allow population by field name as well?)

### MCVE

```python
from litestar import Litestar, post
from litestar.testing import TestClient
from pydantic.v1 import BaseModel, Field


class Address(BaseModel):
    line_one: str = Field(alias="lineOne")


@post()
async def test_handler(data: Address) -> Address:
    return data


app = Litestar(route_handlers=[test_handler], debug=True)


with TestClient(app=app) as client:
    response = client.get(
        "/schema/swagger",
    )
    assert response.is_success
```

### Steps to reproduce

```bash
1. Execute the MCVE
```

### Logs

```bash
litestar.exceptions.http_exceptions.ImproperlyConfiguredException: 500: Two different schemas with the title Address have been defined.

first: {"properties":{"lineOne":{"type":"string"}},"type":"object","required":["lineOne"],"title":"Address"}
second: {"properties":{"line_one":{"type":"string"}},"type":"object","required":["line_one"],"title":"Address"}

To fix this issue, either rename the base classes from which these titles are derived or manuallyset a 'title' kwarg in the route handler.
```

### Litestar Version

2.3.2

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh Litestar dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2731">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2731/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2731/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
I can't seem to reproduce this on `main` and `v2.3.2`. What Litestar and Pydantic version are you using?

**Comment by LonelyVikingMichael** [comment]
This is with Litestar v2.3.2 and Pydantic v2.5.x

But using a `pydantic.v1.BaseModel`

**Comment by provinzkraut** [comment]
That’s the configuration I tried as well. Can you maybe provide a dump of your env, e.g. if you’re using poetry `poetry export` or

**Comment by odiseo0** [comment]
I believe I'm experimenting the same issue or a different one but it's related to Pydantic I'm usign the Pydantic plugin for the aliases as well. `litestar==2.3.2` and `pydantic==2.5.1`

**Comment by chris-telemetry** [comment]
I was able to reproduce using `litestar==2.3.2` and `pydantic==2.5.1`.

I can confirm that this is the same issue as the one raised in #2471. It's not reproducible on `main` for that reason.

Looking at the full trace:

```
...
line 651, in process_schema_result
    raise ImproperlyConfiguredException(
litestar.exceptions.http_exceptions.ImproperlyConfiguredException: 500: Two different schemas with the title Address have been defined.

first: {"properties":{"lineOne":{"type":"string"}},"type":"object","required":["lineOne"],"title":"Address"}
second: {"properties":{"line_one":{"type":"string"}},"type":"object","required":["line_one"],"title":"Address"}
```

Makes it clear as that exception was removed in #2475. There's no longer a check at all for duplicate schema titles.

I'd imagine this will be resolved in the next release, whenever that may be.

**Comment by cofin** [comment]
@LonelyVikingMichael Can you try adding in the Pydantic Plugin and set it to `prefer_alias`?  [This may solve your problem](https://github.com/cofin/litestar-fullstack/blob/main/src/app/domain/plugins.py#L8)

**Comment by LonelyVikingMichael** [comment]
> @LonelyVikingMichael Can you try adding in the Pydantic Plugin and set it to `prefer_alias`? [This may solve your problem](https://github.com/cofin/litestar-fullstack/blob/main/src/app/domain/plugins.py#L8)

That did it, thank you very much
