### ISSUE TITLE
bug: 2.4 changes schema key names

### ISSUE THREAD

**Issue by ssenior45** [litestar-org/litestar#2804]
### Summary

There was a change in this PR (https://github.com/litestar-org/litestar/commit/219355c0e322fab41c921c56ca97d356b7ef868b#diff-6cdcc2ab6bdeda3d72588f3b65db0c437f7ba9cad43892829e75c4d701f9e658R659-R661) that updated the way schema keys are generated for the OpenAPI schema.

Where we originally had something like `UserAccount` as the model name, we know have `app_domain_accounts_UserAccount` or something similar.

### Basic Example

MCVE

```python
import json

from litestar import Litestar, get
from litestar.testing import TestClient
from pydantic import BaseModel


class SampleOne(BaseModel):
    property_one: str


class SampleTwo(BaseModel):
    __module__ = ""
    property_one: str


@get("/one")
async def test_handler_one() -> SampleOne:
    return SampleOne(property_one="test")


@get("/two")
async def test_handler_two() -> SampleTwo:
    return SampleTwo(property_one="test")


app = Litestar(route_handlers=[test_handler_one, test_handler_two], debug=True)

with TestClient(app=app) as client:
    response = client.get("/schema/openapi.json")
    print(json.dumps(response.json()["components"]["schemas"], indent=2))
```

This outputs:

```
{
  "main_SampleOne": {
    "properties": {
      "property_one": {
        "type": "string"
      }
    },
    "type": "object",
    "required": [
      "property_one"
    ],
    "title": "SampleOne"
  },
  "SampleTwo": {
    "properties": {
      "property_one": {
        "type": "string"
      }
    },
    "type": "object",
    "required": [
      "property_one"
    ],
    "title": "SampleTwo"
  }
}INFO - 2023-11-29 18:43:59,780 - httpx - _client - HTTP Request: GET http://testserver.local/schema/openapi.json "HTTP/1.1 200 OK"
```

Notice that for the `SampleOne` model the generated schema key name is `main_SampleOne`.

After reviewing the PR as far as I can understand it you are now making use of class metadata to get name of the model, whereas previously you were using the schema title field.

The only workaround I've been able to come up with can be seen in the the `SampleTwo` model where I set `__module__ = ""`. This allows me to get only the class name as the schema key as can be seen in the output.

### Drawbacks and Impact

This is a breaking change for us as we use an OpenAPI typescript generator from the generated `openapi.json`
and the named types are now different than what it expects.

### Unresolved questions

1. Is there any other way to define the model name other than the workaround presented here
2. If you take on this feature request then the implementation details are up to you but perhaps this could be achieved with a new dunder method on the class and if it's there, use it otherwise use the `__module__.__name__`

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh Litestar dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2804">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2804/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2804/pledge.svg">
</picture>
</a>

**Comment by peterschutt** [comment]
> I think we should consider this a bug fix

Agree

> My suggestion would be that we revert to the original behaviour and hide the new one behind a feature flag. The change itself is fairly straightforward, and it's mostly our tests that would need to be adjust to test for both versions of this.

Maybe we can have our cake and eat it too by using the complex naming only if there is a collision detected. So, where we would have raised an error before 2.4, we would only then introduce the complex naming. That would mean that any pre-2.4 code should still continue to work as planned, and only new code that leverages 2.4's feature to support same-named-types will notice any difference in the generated schema.

And then, I think we should also consider making the complex naming only long enough, i.e, if two colliding types have full names like "a.b.c.Model" and "a.b.d.Model" then "c_Model" and "d_Model" would be sufficient.

**Comment by peterschutt** [comment]
> > I think we should consider this a bug fix
> 
> Agree
> 
> > My suggestion would be that we revert to the original behaviour and hide the new one behind a feature flag. The change itself is fairly straightforward, and it's mostly our tests that would need to be adjust to test for both versions of this.
> 
> Maybe we can have our cake and eat it too by using the complex naming only if there is a collision detected. So, where we would have raised an error before 2.4, we would only then introduce the complex naming. That would mean that any pre-2.4 code should still continue to work without change, and only new code that leverages 2.4's feature to support same-named-types will notice any difference in the generated schema.
> 
> And then, I think we should also consider making the complex naming only long enough, i.e, if two colliding types have full names like "a.b.c.Model" and "a.b.d.Model" then "c_Model" and "d_Model" would be sufficient.

After looking at the problem closer, one issue to overcome to achieve my solution is that we add the schemas and build references route by route, operation by operation. So, this means that at the time any single schema is being added, we don't yet know about all of the schemas in order to determine the minimum unique key name. One way I can overcome this is to keep the current behavior of adding the full path keys, and then post-process at the end, trimming down the keys to the minimum required length to remain unique. Will also need to take care of the case where a route is added after the openapi schema has been generated.

To handle this extra layer of processing and state tracking I'm building a suite of factory functions for our openapi generation, which also has the benefit of tidying up the passing around of state between all of the functions in the `_openapi` namespace. This is being done in #2805, which I'll prob try to get merged before attempting to specifically address this issue, as even if we decide to go with the feature flag approach, I think that refactoring stands on its own merits.

**Comment by ssenior45** [comment]
Thanks for the comments.

In the interim, before the proposed solution makes it into a release, any comments on the workaround I am using? Is it safe to continue with it or is there are better way to workaround it you can think of?

**Comment by peterschutt** [comment]
> Thanks for the comments.
> 
> In the interim, before the proposed solution makes it into a release, any comments on the workaround I am using? Is it safe to continue with it or is there are better way to workaround it you can think of?

Is the workaround that you are overriding the `__module__` attribute? 

There's a good chance that will introduce issues if you are using `from __future__ import annotations` in your code, as that module attribute is required to get the namespace to resolve the type annotations within.

If you aren't doing that and it doesn't break anything else for  you then sure, but we wouldn't want to encourage that as anything more than a temporary workaround.
