### ISSUE TITLE
Enhancement: allow `CompressionMiddleware` to use custom implementations of `CompressionFacade` 

### ISSUE THREAD

**Issue by guacs** [litestar-org/litestar#2842]
### Summary

With the current implementation of compression, it's limited to whatever is supported by Litestar i.e. `gzip` and `brotli`. If others want to use a different compression, they have to create a middleware of their own for handling that, but that results in issues if they are also caching the response. The caching of the compressed responses is handled properly when using the built in `CompressionMiddleware`, but if users are implementing their own they'll have to handle it properly as well. For example, see [here](https://discord.com/channels/919193495116337154/1175435198918303764).

To work around this and allow users to use a different compression (one that is supported out of the box), I'm proposing that we allow the passing of a type that implements the `CompressionFacade` to the `CompressionConfig`. Then the middleware would use this to get the compressed body as well as the value for the `Content-Encoding` header. Essentially, the `CompressionFacade` would become a `CompressionProtocol` (though we might have to keep the same name in order to maintain compatibility). 

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh Litestar dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2842">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2842/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2842/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
Implemented in #2952. This will be included in the 2.6.0 release.
