### ISSUE TITLE
Enhancement: Add `Scalar` API documentation

### ISSUE THREAD

**Issue by JacobCoffee** [litestar-org/litestar#2846]
### Summary

- https://scalar.com/swagger-editor
<img width="1489" alt="image" src="https://github.com/litestar-org/litestar/assets/45884264/425fe3c8-3adc-41a0-9cf9-cb714665824e">

### Basic Example

- Swagger
- ReDoc
- RapiDoc
- Stoplight Elements
- **Scalar**

### Drawbacks and Impact

This will need to be refactored into a plugin once we do that for the rest of them.

**Comment by peterschutt** [comment]
I've got refactoring of the openapi controller on my radar - would you be happy for this to wait until that is done?

**Comment by JacobCoffee** [comment]
@peterschutt welp i refreshed my page and you commented 😅 i am happy to decline my pr though

**Comment by peterschutt** [comment]
The way I envisage the new approach, is that the openapi UI frameworks that you want to use will be configurable via the openapi config object. For backward compatibility, the default value for that config option will have to be every UI framework that we have released on the current openapi controller. My preference would be to wait until that is done, and then we can write a "plugin".

I don't think these things will be actual litestar plugins, but just openapi frontend plugins. They'll have a `render(openapi_config: OpenapiConfig, openapi_json: dict[str, Any]) -> bytes:` method and have to declare the path they are to be served under.. smth like that anyway.

**Comment by Alc-Alc** [comment]
Closed in #2906
