### ISSUE TITLE
Enhancement: Support OpenAPI examples defined in Structs, Pydantic models and dataclasses

### ISSUE THREAD

**Issue by bogdanteleaga** [litestar-org/litestar#2849]
### Description

Examples provided on json parameter fields do not get rendered in the Swagger UI.

The `/schema/openapi.json` does get generated similarly to https://github.com/litestar-org/litestar/pull/2660, but it seems this does not result in the examples being actually rendered in the Swagger UI.

I included examples for defining the classes with any of pydantic, msgspec and dataclass.

### MCVE

```python
from litestar import post, Litestar
from typing import Annotated
from msgspec import Struct, Meta


class Lookup(Struct):
    id: Annotated[str, Meta(examples=["example-1", "example-2"])]

#class Lookup(BaseModel):
#    id: Annotated[str, Field(json_schema_extra={"example": "example-1"})

#@dataclass
#class Lookup:
#    id: Annotated[str, Parameter(examples=[Example(value="example-1"), Example(value="example-2")])


@post(path="/lookup")
async def lookup(lookup: Lookup) -> Lookup:
    return Lookup(id=lookup.id)


app = Litestar(route_handlers=[lookup])
```

### Steps to reproduce

```bash
1. Go to `http://127.0.0.1:8000/schema/swagger`
2. Click on `/lookup`
3. Scroll down to examples
4. They are missing
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Litestar Version

2.4.2

### Platform

- [ ] Linux
- [X] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh Litestar dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2849">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2849/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2849/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
Hey @bogdanteleaga, I've re-labelled this as an enhancement, since it's not really a bug; Declaring examples this way is simply not supported at the moment, but it's a reasonable feature to add.

**Comment by bogdanteleaga** [comment]
If I remember correctly this used to work before the rename. Maybe that came with a bigger change than expected, but that's the main reason I considered it to be a bug.

Looking at the other issue I still don't see an answer to the initial question: there is no way currently to set examples for the request body?

**Comment by provinzkraut** [comment]
> Looking at the other issue I still don't see an answer to the initial question: there is no way currently to set examples for the request body?

Sure, you can. You'll simply have to write it out explicitly:

```python
from litestar import post, Litestar
from typing import Annotated

from litestar.openapi.spec import Example
from litestar.params import BodyKwarg
from dataclasses import dataclass


@dataclass
class Foo:
    bar: str


@post("/")
async def handler(
    data: Annotated[
        Foo,
        BodyKwarg(
            examples=[
                Example(summary="This is how to use the body", value="some string")
            ]
        ),
    ]
) -> None:
    pass
```

**Comment by tuukkamustonen** [comment]
@bogdanteleaga You can set e.g. `value={"attr": 1, "another": 2}`, and you can give a list of examples for the different variations.

**Comment by bogdanteleaga** [comment]
So the example above rewritten like this
```python
@dataclass
class Foo:
    foo: str
    bar: str


@post("/")
async def handler(
    data: Annotated[
        Foo,
        BodyKwarg(
            examples=[
                Example(
                    summary="This is how to use the body",
                    value={"foo": "a", "bar": "b"},
                )
            ]
        ),
    ]
) -> None:
    pass
```

Results in this within the swagger UI
```
{
  "foo": "string",
  "bar": "string"
}
```
