### ISSUE TITLE
Bug: Investigate CI failures

### ISSUE THREAD

**Issue by JacobCoffee** [litestar-org/litestar#2853]
### Description

PDM lock file change
bunch of docs warnings

### URL to code causing the issue

https://github.com/litestar-org/litestar/actions/runs/7131606153/job/19420476513

### Litestar Version

2.4.3

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2853">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2853/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2853/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
Not just release, happens on regular doc builds as well.

**Comment by peterschutt** [comment]
> related #2726

I'm not sure how related these two are - this one looks like we should be running `pdm sync` in the CI step, not `pdm install`:

> [pdm sync](https://pdm-project.org/latest/reference/cli/#sync) installs packages from the lock file.
    [pdm update](https://pdm-project.org/latest/reference/cli/#update) will update the lock file, then sync.
    [pdm install](https://pdm-project.org/latest/reference/cli/#install) will check the project file for changes, update the lock file if needed, then sync.

We don't ever want the lock file to be updated in this context, so should be using pdm sync, right?
