### ISSUE TITLE
Testing: Problems with docker-compose in tests

### ISSUE THREAD

**Issue by ashm-tech** [litestar-org/litestar#2944]
### Description

Hello!

I had a problem running the tests due to the fact that docker-compose is called as if from the command line in the tests. 

Therefore, I want to suggest that you rewrite these tests using the official docker SDK for python, so that in the future users will have fewer errors related to docker and docker-composer

If you agree and allow me to make such a change to the tests, then I will update the tests by the end of the week

### MCVE

```python
# Your MCVE code here
```

### Steps to reproduce

```bash
1. Go to 'litestar'
2. Run `make test` or `make test-all` or `pytest`
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Logs

```bash
https://drive.google.com/file/d/1gH37wLFYPTXtnLZmrUY8EhnAg6JONDHX/view?usp=sharing
```

### Litestar Version

2.4.5

### Platform

- [X] Linux
- [ ] Mac
- [X] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2944">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2944/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2944/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
> I had a problem running the tests due to the fact that docker-compose is called as if from the command line in the tests.

What exactly is the problem?

**Comment by ashm-tech** [comment]
> > I had a problem running the tests due to the fact that docker-compose is called as if from the command line in the tests.
> 
> What exactly is the problem?

The problem is that in the subprocess parameters for launching docker-compose, the very name docker-compose is passed with an error (like this ['docker', 'compose'], instead of ['docker-compose']) therefore, the system perceives the command in such a way that we want to launch docker with a flag that a simple one does not have docker, and only docker-compose has it.

Here is an example of an error that repeats itself in all failed tests:
```
subprocess.CalledProcessError: Command '['docker', 'compose', '--file=/home/ashm/oss/litestar/tests/docker-compose.yml', '--project-name=litestar_pytest-master', 'up', '-d', 'redis']' returned non-zero exit status 125.
```

I suggest fixing this error by using a special SDK for working with docker and docker-compose so that problems with it no longer arise

**Comment by provinzkraut** [comment]
> the system perceives the command in such a way that we want to launch docker with a flag that a simple one does not have docker, and only docker-compose has it.

`docker-compose` is the command used by the legacy compose version. Compose v2 is integrated with docker itself, and the correct command for it is `docker compose`.

https://docs.docker.com/compose/migrate/#what-are-the-differences-between-compose-v1-and-compose-v2

> Update scripts to use Compose V2 by replacing the hyphen (-) with a space, using `docker compose` instead of `docker-compose`.

We don't want to support an outdated version of docker just for testing and I don't think there's much to be gained from using the SDK except for a bit more added complexity.
