### ISSUE TITLE
Bug: Logs and Stack traces are not visible OOTB in Python3.12

### ISSUE THREAD

**Issue by Alc-Alc** [litestar-org/litestar#2954]
### Description

Logging (on routes) and also stack trace (when using `litestar.testing.create_test_client` in debug mode) don't appear to be printed on the terminal when executed in Python 3.12. Running the minimal example in Python 3.8,  I can see contents of the "Logs" section in my terminal; both a `WARNING` and an `ERROR` log, along with a stack trace. However, neither is visible when run on Python 3.12. There is one workaround (that I am aware of) shared by @cofin in the Discord server but (IMO) these functionalities should simply "just work".

> @cofin's example modified to suit the example code (the actual MCVE is under the MCVE section)
This at least makes one of the log ("WARNING" log) show up on 3.12, but no "ERROR" log and stack trace.

```python
import logging
from litestar import get, Request
from litestar.logging.config import LoggingConfig
from litestar.testing import create_test_client


@get()
async def evil_route(request: Request) -> str:
    request.logger.warning("you can't see me")
    1 / 0
    return "so, you will never catch me"


with create_test_client(
    [evil_route],
    logging_config=LoggingConfig(
        root={"level": logging.getLevelName(logging.INFO), "handlers": ["console"]},
        formatters={
            "standard": {
                "format": "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
            }
        },
    ),
) as client:
    response = client.get("")
    assert response.status_code == 500
```

PS: This may probably be a duplicate issue, so feel free to close as one.

### MCVE

```python
from litestar import get, Request
from litestar.testing import create_test_client

@get()
async def evil_route(request: Request) -> str:
    request.logger.warning("you can't see me")
    1 / 0
    return "so, you will never catch me"

with create_test_client([evil_route]) as client:
    response = client.get("")
    assert response.status_code == 500
```

### Steps to reproduce

```bash
1. Save as "some_python_file.py"
2. Run `python some_python_file.py`
4. See error (actually you can't :p that is the error)
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Logs

```bash
WARNING - ,-555869153 - root - http - you can't see me
ERROR - ,-555869152 - litestar - middleware - exception raised on http connection to route /

Traceback (most recent call last):
  File "litestar/litestar/middleware/exceptions/middleware.py", line 192, in __call__
    await self.app(scope, receive, send)
  File "litestar/litestar/routes/http.py", line 82, in handle
    response = await self._get_response_for_request(
  File "litestar/litestar/routes/http.py", line 134, in _get_response_for_request
    return await self._call_handler_function(
  File "litestar/litestar/routes/http.py", line 154, in _call_handler_function
    response_data, cleanup_group = await self._get_response_data(
  File "litestar/litestar/routes/http.py", line 207, in _get_response_data
    data = await route_handler.fn(**parsed_kwargs)
  File "litestar/app.py", line 7, in evil_route
    1 / 0
ZeroDivisionError: division by zero
Traceback (most recent call last):
  File "litestar/litestar/middleware/exceptions/middleware.py", line 192, in __call__
    await self.app(scope, receive, send)
  File "litestar/litestar/routes/http.py", line 82, in handle
    response = await self._get_response_for_request(
  File "litestar/litestar/routes/http.py", line 134, in _get_response_for_request
    return await self._call_handler_function(
  File "litestar/litestar/routes/http.py", line 154, in _call_handler_function
    response_data, cleanup_group = await self._get_response_data(
  File "litestar/litestar/routes/http.py", line 207, in _get_response_data
    data = await route_handler.fn(**parsed_kwargs)
  File "litestar/app.py", line 7, in evil_route
    1 / 0
ZeroDivisionError: division by zero
```

### Litestar Version

804f0151fc9b03e81f6cb6cbb38a9dfd395ead79 (main as of issue creation)

### Platform

- [] Linux
- [X] Mac (sorry, I forgot I had to check this)
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2954">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2954/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2954/pledge.svg">
</picture>
</a>

**Comment by FergusMok** [comment]
Hi @Alc-Alc I've tried reproducing using the MCVE on `804f015`, but I'm still somehow able to get the entirety of the logs. I've tried using Python 3.12.0 and 3.12.1. 
```
(.venv) ➜  litestar git:(v2.5.0) ✗ python -V
Python 3.12.1
(.venv) ➜  litestar git:(v2.5.0) ✗ python some_python_file.py
WARNING - �3
g�U,-144329509 - root - http - you can't see me
ERROR - �3
g�U,-144329507 - litestar - middleware - exception raised on http connection to route /

Traceback (most recent call last):
...
```

**Comment by Alc-Alc** [comment]
> Hi @Alc-Alc I've tried reproducing using the MCVE on `804f015`, but I'm still somehow able to get the entirety of the logs. I've tried using Python 3.12.0 and 3.12.1.
> 
> ```
> (.venv) ➜  litestar git:(v2.5.0) ✗ python -V
> Python 3.12.1
> (.venv) ➜  litestar git:(v2.5.0) ✗ python some_python_file.py
> WARNING - �3
> g�U,-144329509 - root - http - you can't see me
> ERROR - �3
> g�U,-144329507 - litestar - middleware - exception raised on http connection to route /
> 
> Traceback (most recent call last):
> ...
> ```

@FergusMok thanks for checking, I created a new venv and did `pip install git+https://github.com/litestar-org/litestar.git@804f0151fc9b03e81f6cb6cbb38a9dfd395ead79` and I can still observe the same issue I have described (no logs, nothing). I am 3.12.0

**Comment by euri10** [comment]
on 3.12.1
```
❯ python a.py
2024-01-11 09:39:41,301 - root - WARNING - you can't see me                                                                                                                                               3.12.1 at  09:39:37
2024-01-11 09:39:41,304 - httpx - INFO - HTTP Request: GET http://testserver.local "HTTP/1.1 500 Internal Server Error"
```

**Comment by Alc-Alc** [comment]
FWIW, I am on a Mac (edited the issue description, my apologies)

**Comment by jderrien** [comment]
The problem seems to be with the `queue_listener` handler. Using the `console` one works.

Tested with Python 3.12.2. Former Python 3.12 versions won't work due to https://github.com/python/cpython/issues/111615.

I'm not familiar with the queue handlers, but I'll try to dig a little bit more.

**Comment by Alc-Alc** [comment]
> The problem seems to be with the `queue_listener` handler. Using the `console` one works.
> 
> Tested with Python 3.12.2. Former Python 3.12 versions won't work due to [python/cpython#111615](https://github.com/python/cpython/issues/111615).
> 
> I'm not familiar with the queue handlers, but I'll try to dig a little bit more.

thanks for taking a look at this, it does work with `console` as shown in the "workaround" code of the issue description

**Comment by teddybee** [comment]
I still has the same problem, I can't see any logger.info logs.
logging_config is the same as OP`s
Python 3.11 
Litestar 2.7.1

**Comment by provinzkraut** [comment]
@JacobCoffee?

**Comment by jderrien** [comment]
@provinzkraut I'm happy to help here, in particular if I broke something

@teddybee I double checked and it seems it works as expected for me:

```shell
$ python --version
Python 3.11.8
$ pip freeze | grep litestar
litestar==2.7.1
```

```python
import logging
from litestar import get, Litestar, Request

logger = logging.getLogger()


@get("/")
async def root(request: Request) -> dict:
    logger.info("Root endpoint called, info log (logger)")
    request.logger.info("Root endpoint called, info log (request.logger)")
    return {"Hello": "World"}


@get("/evil")
async def evil_route(request: Request) -> str:
    request.logger.warning("Evil route called, warning log")
    1 / 0
    return "won't return"


app = Litestar(route_handlers=[root, evil_route])
```

Running the app with `litestar run`, and calling the endpoints:
```
$ litestar run
Using Litestar app from app:app
Starting server process ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
┌──────────────────────────────┬──────────────────────┐
│ Litestar version             │ 2.7.1                │
│ Debug mode                   │ Disabled             │
│ Python Debugger on exception │ Disabled             │
│ CORS                         │ Disabled             │
│ CSRF                         │ Disabled             │
│ OpenAPI                      │ Enabled path=/schema │
│ Compression                  │ Disabled             │
└──────────────────────────────┴──────────────────────┘
INFO:     Started server process [97446]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:57318 - "GET / HTTP/1.1" 200 OK
INFO - 2024-03-30 10:32:18,173 - root - app - Root endpoint called, info log (logger)
INFO - 2024-03-30 10:32:18,173 - root - app - Root endpoint called, info log (request.logger)
INFO:     127.0.0.1:57319 - "GET /evil HTTP/1.1" 500 Internal Server Error
WARNING - 2024-03-30 10:32:21,347 - root - app - Evil route called, warning log
```

```
$ curl -s http://127.0.0.1:8000/ | jq
{
  "Hello": "World"
}
$ curl -s http://127.0.0.1:8000/evil | jq
{
  "status_code": 500,
  "detail": "Internal Server Error"
}
```

Note: the stacktrace is logged when running `litestar run --debug`

You might want to send a MCVE showing your issue. Thanks!

**Comment by teddybee** [comment]
At me, info and debug are not working, warning and critical are working.
I use it in a Controller class.

**Comment by jderrien** [comment]
> If that matters, picologging is installed as a dependency.

It might be the problem. If `picologging` is installed, Litestar will use it by default.
The code you posted refers to the standard `logging` module. You might be mixing both libs.

Maybe try something like this:
```python
logging_config = LoggingConfig(
    root={"level": "DEBUG", "handlers": ["console"]},
    formatters={
        "standard": {"format": "%(asctime)s - %(name)s - %(levelname)s - %(message)s"}
    },
)

def get_logger(mod_name: str) -> picologging.Logger:
    logger = picologging.getLogger(mod_name)
    return logger
```

I don't think your issue is related to this one, you might want to open a new issue.
