### ISSUE TITLE
Bug: Description not set for UUID based path parameters in OpenAPI

### ISSUE THREAD

**Issue by Alc-Alc** [litestar-org/litestar#2967]
### Description

The value set in `Parameter(description="UUID ID")` is not used for the actual description in the OpenAPI schema if the path parameter is of type `UUID`. I did some digging and found out this is due to the presence of the following code. https://github.com/litestar-org/litestar/blob/44809182b1b62a8da5b7c5bec3b22987581779d5/litestar/_openapi/schema_generation/schema.py#L525-L532

Since description for UUID is already set https://github.com/litestar-org/litestar/blob/44809182b1b62a8da5b7c5bec3b22987581779d5/litestar/_openapi/schema_generation/schema.py#L120 the code above makes it so that description from the user defined `Parameter` is not set again.

#### Proposed Fix 1 (Breaking / debatably breaking?)
Remove "description" in https://github.com/litestar-org/litestar/blob/44809182b1b62a8da5b7c5bec3b22987581779d5/litestar/_openapi/schema_generation/schema.py#L120 such that it appears like so
```suggestion py
UUID: Schema(type=OpenAPIType.STRING, format=OpenAPIFormat.UUID)
```
#### Proposed Fix 2 (Special Casing until next major release then replace with Proposed Fix 1)
Change https://github.com/litestar-org/litestar/blob/44809182b1b62a8da5b7c5bec3b22987581779d5/litestar/_openapi/schema_generation/schema.py#L531 such that it appears like so
```suggestion py
if schema_key == "description" or getattr(schema, schema_key, None) is None:
```

@peterschutt suggested special casing with comments explaining the behavior would be ideal. Thoughts?

### MCVE

```python
from uuid import UUID
from typing_extensions import Annotated
from litestar.params import Parameter
from litestar import get
from litestar.testing import create_test_client

@get("str/{id:str}")
async def str_path(id: Annotated[str, Parameter(description="String ID")]) -> str:
    return id

@get("uuid/{id:uuid}")
async def uuid_path(id: Annotated[UUID, Parameter(description="UUID ID")]) -> UUID:
    return id

with create_test_client([str_path, uuid_path]) as client:
    # correct, currently passes, should pass
    assert client.app.openapi_schema.paths["/str/{id}"].get.parameters[0].description == "String ID"

    # wrong, currently passes, should fail
    assert client.app.openapi_schema.paths["/uuid/{id}"].get.parameters[0].description == "Any UUID string"

    # expected, currently fails, should pass
    assert client.app.openapi_schema.paths["/uuid/{id}"].get.parameters[0].description == "UUID ID"
```

### Steps to reproduce

```bash
1. Save as "mcve.py"
2. Run `python mcve.py`
3. Second assert that currently passes, should fail.
4. Third assert that currently fails, should pass.
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Litestar Version

cc45c1132584210250dd725595612c9c95c4bf68 (main as of issue creation)

### Platform

- [ ] Linux
- [X] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2967">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2967/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2967/pledge.svg">
</picture>
</a>

**Comment by peterschutt** [comment]
> Proposed Fix 1 (Breaking / debatably breaking?)

If we treat this as a bug and include the fix in a patch release, removing the default description will cause schema generation to change behavior between patch releases - this is why I'm in favor of option 2.

**Comment by provinzkraut** [comment]
@Alc-Alc would you want to go ahead and implement a fix for this?
