### ISSUE TITLE
Pydantic DTOs with IPvAnyAddress fail at validation

### ISSUE THREAD

**Issue by FranzForstmayr** [litestar-org/litestar#2974]
### Description

Validation fails if using a `IPvAnyAddress` field in pydantic DTO.

### MCVE

```python
from litestar import Litestar, post
from litestar.contrib.pydantic import PydanticDTO
from litestar.dto import DTOData
from pydantic import BaseModel, IPvAnyAddress
from litestar.openapi.config import OpenAPIConfig


class Foo(BaseModel):
    ip: IPvAnyAddress


FooDTO = PydanticDTO[Foo]


@post("/foo", dto=FooDTO)
async def foo_handler(data: DTOData[Foo]) -> Foo:
    return data.create_instance()


config = OpenAPIConfig(
    title="Test",
    version="0.1",
    use_handler_docstrings=True,
    root_schema_site="swagger",
)
"""OpenAPI config for app.  See OpenAPISettings for configuration."""


app = Litestar([foo_handler], openapi_config=config)
```

### Steps to reproduce

```bash
`litestar run`

curl -X 'POST' \
>   'http://localhost:8000/foo' \
>   -H 'accept: application/json' \
>   -H 'Content-Type: application/json' \
>   -d '{
>   "ip": "198.51.100.42"
> }'
```

Can also get reproduced in Swagger UI.

### Logs

```bash
{"status_code":400,"detail":"Unsupported type: <class 'str'> - at `$.ip`"}
```

### Litestar Version

2.5.0

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2974">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2974/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2974/pledge.svg">
</picture>
</a>

**Comment by peterschutt** [comment]
I believe this is the same issue as this: https://github.com/litestar-org/litestar/issues/2334

**Comment by provinzkraut** [comment]
I agree with @peterschutt's assessment. Closing this as a duplicate. Let's try to get #2491 finished up.
