### ISSUE TITLE
Enhancement: Allow async `key_builder` function for request caching

### ISSUE THREAD

**Issue by casabre** [litestar-org/litestar#2977]
### Summary

I am having the need to create custom keys also for the JSON content of "POST" calls. Since I have to deserialize the body of the request, I cannot easily retrieve the JSON content in a synchronized function.

Thus, I am needing a check against `iscoroutine` in order to call it the async way or the sync way.

### Basic Example

Simple key builder with json content

```
async def key_builder(request: Request[typing.Any, typing.Any, typing.Any]) -> str:
    """Custom key builder."""
    key = default_cache_key_builder(request=request)
    if request.method == "POST":
        post_params = list((await request.json()).items())
        post_params.sort(key=lambda x: x[0])
        key = key + urlencode(post_params, doseq=True)
    return key
```

### Drawbacks and Impact

I am seeing no impact right now because the legacy way is still support and the coroutine check should be neglectable performance-wise.

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2977">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2977/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2977/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
@casabre, as @peterschutt explained in [this comment](https://github.com/litestar-org/litestar/pull/2978#discussion_r1449604958), having the `key_builder` function won't work as you don't have access to `request.json()` to receive data in the key builder function. Personally I think we should *not* allow making this function async precisely to avoid cases like these. Key builders should be able to work from from the static information given on the request without needing to refer to the request body (and caching `POST` request like this is questionable anyway IMO). 

I suggest you work with other resource indicators (such as ETags) instead to achieve similar results.


@litestar-org/maintainers for thoughts

**Comment by casabre** [comment]
@provinzkraut, @peterschutt, thanks for you feedback and I understand the constraints here. 

Maybe let me explain my use case. I am having more complex query parameters (many and also nested) that I chose to use a post call to retrieve my data. I know that I could have used the query parameter too but there are many parameters and the nested structure of some makes it pretty inconvenient. 

I was using aiocache before and there it was possible. I migrated to litestar because I am seeing a lot benefits due to community, features and also a build in caching system in order to get rid off the outdated aiocache package.

Ok, that was my motivation for this issue and the PR because I was not seeing the constraints beforehand and during my e2e testing, it was working... I guess mostly due to the returned json data.

Is there a way forward to support use cases like this? Could we extract the key string at the route handler and forward it somehow to the response cache middleware?

**Comment by provinzkraut** [comment]
> I am having more complex query parameters (many and also nested) that I chose to use a post call to retrieve my data. I know that I could have used the query parameter too but there are many parameters and the nested structure of some makes it pretty inconvenient.

What if you were to send the query parameters as JSON? Then you could still use a`GET` request and wouldn't have to rely on any of these workarounds.

**Comment by casabre** [comment]
Thanks for your recommendation. I believe that works but I am more concerned about the final, total URL length. Furthermore, the PR was the lower hanging fruit for me compared to all the additional refactoring. But I will try a quick refactoring.

One more question. Is there already a middleware available which could try to deserialize the JSON content rather than doing it in every route implementation?

**Comment by provinzkraut** [comment]
> Is there already a middleware available which could try to deserialize the JSON content rather than doing it in every route implementation?

Can you explain what you mean by "doing it in every route implementation"?

Generally speaking, middlewares are not meant to handle things like deserialisation; As they are ASGI applications, they should be constrained to operate on that level to ensure interoperability (i.e. they should work on the scope and maybe deal with the raw body bytes if absolutely necessary).

**Comment by provinzkraut** [comment]
Closing this for now for the reasons stated [here](https://github.com/litestar-org/litestar/issues/2977#issuecomment-1890725169).

@casabre please let me know if we can help you solve your problems in other ways.
