### ISSUE TITLE
Bug: using `Struct` or `BaseModel` as dependency callable raises exception

### ISSUE THREAD

**Issue by guacs** [litestar-org/litestar#2979]
### Description

When using a `Struct` or `BaseModel` (pydantic) type as the callable for dependencies (@provinzkraut thanks for the [idea](https://discord.com/channels/919193495116337154/1131595764045459496/1193144136837120090)!), it results in an `ImproperlyConfiguredException` claiming that it's not type hinted even though it is. 

It works only with `dataclasses`.

### MCVE

```python
from typing import Optional

from msgspec import Struct

from litestar import Litestar, get


class UserFilterQuery(Struct):
    first_or_last_name_contains: Optional[str] = None
    is_active: bool = True


@get("/users", dependencies={"filter_": UserFilterQuery})
async def users_retrieve(filter_: UserFilterQuery) -> None:
    pass


app = Litestar([users_retrieve])
```

### Steps to reproduce

```bash
1. Run the MCVE
```

### Logs

```bash
Traceback (most recent call last):
  File "/home/guacs/open-source/litestar/litestar/typing.py", line 597, in from_parameter
    annotation = fn_type_hints[parameter.name]
                 ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'first_or_last_name_contains'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/guacs/open-source/litestar/_app.py", line 18, in <module>
    app = Litestar([users_retrieve])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guacs/open-source/litestar/litestar/app.py", line 453, in __init__
    self.register(route_handler)
  File "/home/guacs/open-source/litestar/litestar/app.py", line 618, in register
    route_handler.on_registration(self)
  File "/home/guacs/open-source/litestar/litestar/handlers/http_handlers/base.py", line 532, in on_registration
    super().on_registration(app)
  File "/home/guacs/open-source/litestar/litestar/handlers/base.py", line 524, in on_registration
    self.resolve_dependencies()
  File "/home/guacs/open-source/litestar/litestar/handlers/base.py", line 357, in resolve_dependencies
    provider.parsed_fn_signature = ParsedSignature.from_fn(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guacs/open-source/litestar/litestar/utils/signature.py", line 219, in from_fn
    return cls.from_signature(signature, fn_type_hints)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/guacs/open-source/litestar/litestar/utils/signature.py", line 233, in from_signature
    parameters = tuple(
                 ^^^^^^
  File "/home/guacs/open-source/litestar/litestar/utils/signature.py", line 234, in <genexpr>
    FieldDefinition.from_parameter(parameter=parameter, fn_type_hints=fn_type_hints)
  File "/home/guacs/open-source/litestar/litestar/typing.py", line 599, in from_parameter
    raise ImproperlyConfiguredException(
litestar.exceptions.http_exceptions.ImproperlyConfiguredException: 500: 'first_or_last_name_contains' does not have a type annotation. If it should receive any value, use 'Any'.
```

### Litestar Version

HEAD (main)

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2979">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2979/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2979/pledge.svg">
</picture>
</a>

**Comment by guacs** [comment]
The issue is in [this](https://github.com/litestar-org/litestar/blob/915e4a9baa78c1b8411edf7fc47cc52fffc9ad30/litestar/utils/signature.py#L151-L152) line. Due to it setting the function as the `__init__` of the class, we don't get any type hints. This is because the msgspec generated `__init__` has no type hints. The same is the case for pydantic models though in that case the type hints aren't empty but is instead `{"data": Any, "return": NoneType}` which is obviously incorrect.

Using the class directly instead of `__init__` method of the class solves the issue for these types, but then it'll fail for the classes that are not of this type since in those cases getting the type hints of `__init__` is the right behavior.

**Comment by peterschutt** [comment]
Pydantic types their `__init__` methods like:

```py
__init__(__pydantic_self__, **data: 'Any') -> 'None'
```

Msgspec types their `__init__` methods like:

```py
__init__(self, /, *args, **kwargs)
```

We could always merge the annotations from the class and the `__init__` method where the dependency is a class, however there is an issue with priority.

Say I have a pydantic model like:

```py
class DepClass(BaseModel):
    data: int | None = None
```

B/c pydantic annotates it's `__init__` signature, inspecting its types will return `{"data": Any, "return": None}`, where `data` isn't the annotation of our model attribute, it is the annotation of pydantic's `__init__(..., **data: Any)` argument.

So, for this case we would have to prioritize the class annotations over the `__init__` annotations.

However, for a regular python class, something like this is possible:

```py
class DepClass:
    data: int

    def __init__(self, data: Literal["abc", "def"]) -> None:
        self.data = 1 if data == "abc" else 2
```

In this case, we'd need to prioritize the `__init__` arg type over the class type.

Therefore, I think the correct approach would be to offload parsing of annotations to plugins where the type is a class and a plugin supported type.

**Comment by guacs** [comment]
That makes sense to me. Only default to `__init__` if none of the plugins know how to get the type hints for the given class. I have a doubt regarding the implementation: would we have to create a new plugin for this?

**Comment by provinzkraut** [comment]
> would we have to create a new plugin for this?

I think we can leverage the existing ones as they're already capable of extracting the type information from the type.

**Comment by peterschutt** [comment]
Is this another instance of needing to add a new non-protocol plugin base type if we have to add a new method for this?

**Comment by provinzkraut** [comment]
> Is this another instance of needing to add a new non-protocol plugin base type if we have to add a new method for this?

Yeah. We should really work on migration all plugins to `ABC`s. It’s just way more flexible. 

Or are you suggesting we don’t do that and find another way to keep working with protocols?

**Comment by peterschutt** [comment]
> Or are you suggesting we don’t do that and find another way to keep working with protocols?

Not at all.

> Yeah. We should really work on migration all plugins to ABCs. It’s just way more flexible.

Yeah, this has been a learning experience for me with protocols. Seems they are only good for simple things like typing a function parameter that expects a thing to have a particular method. The lack of default implementations makes ABCs far superior to an API that is expected to evolve.
