### ISSUE TITLE
Docs: Wrong title for `concurrency` reference docs

### ISSUE THREAD

**Issue by redmer** [litestar-org/litestar#2987]
### Summary

https://github.com/litestar-org/litestar/blame/7c4dd4bfceea7361ee76815550bfbf6cf185c5b8/docs/reference/concurrency.rst#L1

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/2987">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/2987/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/2987/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
Title is `cli` but should be `concurrency`

**Comment by provinzkraut** [comment]
@redmer PRs are welcome :)

**Comment by PossiblePanda** [comment]
Created a PR to fix :)
