### ISSUE TITLE
Docs: Document SSE

### ISSUE THREAD

**Issue by provinzkraut** [litestar-org/litestar#3011]
### Summary

The SSE documentation is currently lacking:

- Docs for `ServerSentEventMessage`
- Sending messages a dicts

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3011">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3011/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3011/pledge.svg">
</picture>
</a>

**Comment by peterschutt** [comment]
Any suggestions here @euri10?

**Comment by euri10** [comment]
ok just reading the current docs here:

https://docs.litestar.dev/latest/usage/responses.html#server-sent-event-responses

I think everything @provinzkraut mentions is currently in the docs:

ServerSentEventMessage is mentionned, the dict option as well

now I see room for improvment I'd say in the example given; it currently only yield a str and we "should" maybe yield a ServerSentEventMessage and show it that way with all the other possibilities we test,

if agree I can tweak the example, does that make sense to you >?
