### ISSUE TITLE
Enhancement: Pass the caught exception to `exception_logging_handler` for more flexible logging decision

### ISSUE THREAD

**Issue by tuukkamustonen** [litestar-org/litestar#3019]
### Summary

Pass `Exception` instance to `LogConfig.exception_logging_handler` callable, like for exception handlers.

This would allow to judge if / how to log exception based on exception type:

- `HTTPException` (at least 4XX ones) - log as INFO, without stacktrace. These are client errors, and expected to happen every now and then. Absolutely no need to log them as ERROR and with stacktrace.
- Some `Timeout` error - log as WARNING, as it's bound to happen every now and then, but it's not a bug, really
- Any other `Exception` - log as ERROR with stacktrace, as yes it looks like a bug as it slipped in.

Currently, the `exception_logging_handler` is passed pre-formatted stacktrace, so it cannot judge what the exception actually was. But it would make a lot of sense to just pass the caught exception, instead of the stacktrace, and let the function decide when and how to represent the exception.

As a workaround, it's possible to grab the exception via `sys.exc_info()` (I believe). But it would be "cleaner" if the exception was passed in, and one wouldn't have to do that. It would also signal the developer that it's actually okay to determine logic based on exception type, now you have to kinda think outside the box.

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3019">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3019/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3019/pledge.svg">
</picture>
</a>

**Comment by tuukkamustonen** [comment]
Discovered https://docs.litestar.dev/2/usage/applications.html#after-exception and there, the callable is passed the `Exception` instance:

```py
async def after_exception_handler(exc: Exception, scope: "Scope") -> None:
```

What's the use case for having separate `after_exception_handler` and `exception_logging_handler`?

**Comment by provinzkraut** [comment]
If you want to customise your logging to such a degree, using the `after_exception_handler` is the right approach; Litestar's built-in exception logging config is meant to provide sensible default and a degree of customisation out of the box. I don't think this warrants a breaking change (introducing a new parameter), considering logging as a whole is going to change in 3.0, where we're looking to simplify the setup in general and remove a lot of the configuration in favour of a leaner interface and moving more towards just using stdlib logging config, which will be tracked in #2858. Feel free to comment your ideas on there as well.

@cofin maybe you have some thoughts on this as well, but I'm closing this for now.
