### ISSUE TITLE
Docs: Warn about using `TYPE_CHECKING` for injected types

### ISSUE THREAD

**Issue by tuukkamustonen** [litestar-org/litestar#3033]
### Summary

Typically, annotation-only imports may be skipped during runtime (for perf gains) with `if TYPE_CHECKING` blocks.

There are even linters to enforce this, ie. nag when an annotation-only import is done without `TYPE_CHECKING` block. There's https://github.com/snok/flake8-type-checking and a matching [ruff rule](https://docs.astral.sh/ruff/rules/typing-only-first-party-import/).

Moving the import to `if TYPE_CHECKING` block will raise error, as Litestar DI needs the type information:

```py
# app.py

from litestar import Litestar, get
from litestar.di import Provide
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from service import Service


@get()
async def hello(service: Service) -> None:
    pass


app = Litestar(
    route_handlers=[hello],
    dependencies={"service": Provide(Service, sync_to_thread=False)}
)

# service.py

class Service:
    pass
```

```console
❯ python app.py
Traceback (most recent call last):
  File "/home/musttu/Projects/api/api/app.py", line 18, in <module>
    dependencies={"service": Provide(Service, sync_to_thread=False)}
NameError: name 'Service' is not defined
```

I didn't see any mention of this caveat in the documentation - should be added.

---

Also, is there some trick to configure the linters to _not_ nag in these cases (Litestar DI), but do in others?

It seems that `flake8-type-checking` [supports FastAPI](https://github.com/snok/flake8-type-checking/issues/52) but [apparently not Litestar](https://github.com/snok/flake8-type-checking/issues?q=is%3Aissue+is%3Aopen+litestar). `ruff`probably doesn't have any special tricks for either(?)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3033">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3033/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3033/pledge.svg">
</picture>
</a>

**Comment by floxay** [comment]
It seems it is mentioned under [Usage > Routing > Route Handlers > Signature namespace](https://docs.litestar.dev/latest/usage/routing/handlers.html#signature-namespace)

**Comment by tuukkamustonen** [comment]
Fair enough, it's there and there's even a workaround 🥳

Could be linked to from DI page, too. At least I expected to find it there 🤔

**Comment by peterschutt** [comment]
> Could be linked to from DI page, too? At least I expected to find it there 🤔

Any improvements to the docs are warmly welcomed!
