### ISSUE TITLE
Bug: uvicorn>=0.26 introduces a breaking change with --root-path and path parameter

### ISSUE THREAD

**Issue by smithk86** [litestar-org/litestar#3041]
### Description

Once Uvicorn is upgraded to v0.26 or beyond, any `path` parameters type gets the value of --root-path prepended to them.

### MCVE

```python
from pathlib import Path

from litestar import Litestar
from litestar.handlers import get

@get(path=["/", "/{path:path}"], sync_to_thread=False)
def pathfinder(path: Path | None) -> str:
    return f"path: {path}"

app = Litestar(route_handlers=[pathfinder], debug=True)
```

### Steps to reproduce

```bash
Uvicorn <0.26:
1. uvicorn mcve:app --root-path /test
2. curl http://localhost:8000/myPath -> "path: /myPath"

Uvicorn >=0.26:
1. uvicorn mcve:app --root-path /test
2. curl http://localhost:8000/myPath -> "path: /test/myPath"
```

### Litestar Version

2.5.2

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3041">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3041/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3041/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
Related to #2998.
