### ISSUE TITLE
Bug: OpenAPI schema is missing `model_config` configs from Pydantic models (e.g. `json_schema_extra`)

### ISSUE THREAD

**Issue by tuukkamustonen** [litestar-org/litestar#3054]
### Description

The generated OpenAPI schema is missing configs set via `model_config` in Pydantic models, when Pydantic model is used as response (and probably when used as request body).

The `title`, `json_schema_extra` (and other configs) should be copied over to the schema.

### MCVE

```python
import uvicorn
from litestar import Litestar, get
from litestar.openapi import ResponseSpec
from pydantic import BaseModel, ConfigDict


class Payload(BaseModel):
    model_config = ConfigDict(
        title="Some label",
        json_schema_extra={
            "examples": [
                {
                    "field": "VALUE1"
                },
                {
                    "field": "VALUE2"
                }
            ],
            "not": {
                "type": "integer"
            }
        }
    )

    field: str


@get(
    responses={
        200: ResponseSpec(Payload, generate_examples=False)
    }
)
async def hello() -> Payload:
    pass


app = Litestar(
    route_handlers=[hello],
)


uvicorn.run(app)
```

### Steps to reproduce

Run it.

Inspect the generated schema:

```json
{
  "info": {
    "title": "Litestar API",
    "version": "1.0.0"
  },
  "openapi": "3.1.0",
  "servers": [
    {
      "url": "/"
    }
  ],
  "paths": {
    "/": {
      "get": {
        "summary": "Hello",
        "operationId": "Hello",
        "responses": {
          "200": {
            "description": "Additional response",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Payload"
                }
              }
            }
          }
        },
        "deprecated": false
      }
    }
  },
  "components": {
    "schemas": {
      "Payload": {
        <--------- "title" should be here
        "properties": {
          "field": {
            "type": "string"
          }
        },
        "type": "object",
        "required": [
          "field"
        ],
        "title": "Payload"
        <------- "examples" should be here
        <------- "not" should be here
      }
    }
  }
}
```

### Related

- It's possible to provide OpenAPI examples for input args via `Parameter(examples=[...])` but how can you do the same for response body? `ResponseSpec` doesn't provide `examples` field, only `generate_examples` flag...
- How can you generate examples for request body? There's no `generate_examples` flag for `Parameter`?

### Litestar Version

2.5.1

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3054">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3054/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3054/pledge.svg">
</picture>
</a>

**Comment by tuukkamustonen** [comment]
Quite similar to https://github.com/litestar-org/litestar/issues/2849

**Comment by provinzkraut** [comment]
Litestar does not use Pydantic to generate the OpenAPI schema. Pydantic's OpenAPI schema generation works very differently to Litestar's and there's not supposed to be this kind of interoperability. The reason is simply that we want to remain independent of the modelling library (e.g. Pydantic, msgspec, attrs, dataclasses), and therefore only consider the information these libraries provide to us. Metadata available on the fields for example is considered, but we don't take into account special logic of these individual libraries like these.

If you want your schema to be generated by Pydantic according to Pydantic's logic, you can use Pydantic directly and include the schemas it generates via the `OpenAPIConfig` object.

**Comment by kayprogrammer** [comment]
> If you want your schema to be generated by Pydantic according to Pydantic's logic, you can use Pydantic directly and include the schemas it generates via the `OpenAPIConfig` object.

How do we do this please?

**Comment by Keating950** [comment]
> Litestar does not use Pydantic to generate the OpenAPI schema. Pydantic's OpenAPI schema generation works very differently to Litestar's and there's not supposed to be this kind of interoperability. The reason is simply that we want to remain independent of the modelling library (e.g. Pydantic, msgspec, attrs, dataclasses), and therefore only consider the information these libraries provide to us. Metadata available on the fields for example is considered, but we don't take into account special logic of these individual libraries like these.
> 
> If you want your schema to be generated by Pydantic according to Pydantic's logic, you can use Pydantic directly and include the schemas it generates via the `OpenAPIConfig` object.

In thatcase, I wonder if the [docs on OpenAPI schema generation](https://docs.litestar.dev/2/usage/openapi/schema_generation.html#customizing-pydantic-model-schemas) should be updated, in particular the sentence "You can customize the OpenAPI schemas generated for pydantic models by following the guidelines in the Pydantic docs."
