### ISSUE TITLE
Bug: Response examples are not generated even with `generate_examples=True`

### ISSUE THREAD

**Issue by tuukkamustonen** [litestar-org/litestar#3058]
### Description

It's unclear how to enable/disable the example the example generation for responses.

Is it by default on or not? `Parameter` defaults to `generate_examples=True` but no examples appear by default.

Yet in a larger app I do get examples, but I don't seem to understand how to reproduce the same on a MCVE.

(Is there a mention about this in docs?)

### MCVE

```python
import json

from litestar import Litestar, post
from litestar.openapi import ResponseSpec
from pydantic import BaseModel


class Response(BaseModel):
    text: str
    num: int


@post("/", responses={201: ResponseSpec(Response, generate_examples=True)})
def endpoint() -> Response:
    return Response(text="hello", num=1)


app = Litestar(route_handlers=[endpoint])

print(json.dumps(app.openapi_schema.to_schema(), indent=4))


The schema:

```json
    "components": {
        "schemas": {
            "Response": {
                "properties": {
                    "text": {
                        "type": "string"
                    },
                    "num": {
                        "type": "integer"
                    }
                },
                "type": "object",
                "required": [
                    "num",
                    "text"
                ],
                "title": "Response"
            }
        }
    }
```

No `"examples"` there.
```


### Steps to reproduce

```bash
1. `python app.py`
2. See the schema
```

### Litestar Version

2.5.1

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3058">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3058/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3058/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
You need to set `create_examples=True` on the application itself; It is off by default. 

```python
from litestar import Litestar
from litestar.openapi import OpenAPIConfig

app = Litestar(
    openapi_config=OpenAPIConfig(
        create_examples=True,
        title="OpenAPI",
        version="1.0.0",
    ),
)
```

**Comment by tuukkamustonen** [comment]
Thanks. Just couldn't find it, docs don't mention it (one more thing to add there...)

Though, I have an actual application (ie. not MCVE) that I'm converting, and it doesn't have `create_examples=True` set, yet it generates those examples. So, there must be bug/glitch in there somewhere.

I will debug more (probably tomorrow) and report back.

**Comment by tuukkamustonen** [comment]
@provinzkraut Okay, traced it out. This one's actually quite funny. I had annotated `dict[str, Any]` and not as `Response` (temporarily, for laziness) as the return type of the endpoint, like:

```py
from typing import Any

import uvicorn
from litestar import Litestar, post
from litestar.openapi import ResponseSpec
from pydantic import BaseModel


class Response(BaseModel):
    text: str
    num: int


@post("/", responses={201: ResponseSpec(Response, generate_examples=True)})
async def endpoint() -> dict[str, Any]:  # <---- HERE
    return {"text": "hello", "num": 1}


app = Litestar(
    route_handlers=[endpoint],
)

uvicorn.run(app)
```

This leads to Litestar generating examples, when if the return type is annotated with the Pydantic model, it does not (as `create_examples=False`).

The usage here is wrong (annotating a different type than in `@post(responses=...)`). However, I think the validation could be stricter, perhaps so that this would rather raise, then proceed with unexpected(?) behavior. What do you think?

**Comment by provinzkraut** [comment]
Just to confirm, this only happens when you include a `ResponseSpec`?

**Comment by tuukkamustonen** [comment]
Yes.

With `dict[str, Any]` and _without_ `ResponseSpec` the whole component is missing from the schema:

```json
{
  "info": {
    "title": "Litestar API",
    "version": "1.0.0"
  },
  "openapi": "3.1.0",
  "servers": [
    {
      "url": "/"
    }
  ],
  "paths": {
    "/": {
      "post": {
        "summary": "Endpoint",
        "operationId": "Endpoint",
        "responses": {
          "201": {
            "description": "Document created, URL follows",
            "headers": {},
            "content": {
              "application/json": {
                "schema": {
                  "additionalProperties": {},
                  "type": "object"
                }
              }
            }
          }
        },
        "deprecated": false
      }
    }
  },
  "components": {
    "schemas": {}
  }
}
```
