### ISSUE TITLE
Bug: `null` type OpenAPI response generated for ResponseSpec(None) / 204

### ISSUE THREAD

**Issue by tuukkamustonen** [litestar-org/litestar#3069]
### Description

Attempting to document (empty) error response description something like:

```py
    responses={
        204: ResponseSpec(None, description="Data successfully wiped")
    }
```

`None` is the required `data_container` argument.

This leads to:

```json
        "responses": {
          "204": {
            "description": "Data successfully wiped",
            "content": {
              "application/json": {
                "schema": {
                  "type": "null",
                  "examples": {
                    "nonetype-example-1": {
                      "description": "Example  value"
                    }
                  }
                }
              }
            }
          }
```

It:

- Generates `content`, which should rather be missing
- Generates example withing the `content`, even though `create_examples` was not enabled (false by default). This is likely related with https://github.com/litestar-org/litestar/issues/3058#issuecomment-1924015790

The `content` should not be there. https://swagger.io/docs/specification/describing-responses/:

> **Response Body**
> Some responses, such as `204 No Content`, have no body. To indicate the response body is empty, do not specify a content for the response:
> 
>       responses:
>         '204':
>           description: The resource was deleted successfully.

If `None` is incorrect value to pass here, what would be the right one, to adjust the 204 response?

### MCVE

```python
import uvicorn
from litestar import Litestar, delete
from litestar.openapi import ResponseSpec


@delete(
    responses={
        204: ResponseSpec(None, description="Data successfully deleted")
    }
)
async def delete_user_data() -> None:
    pass


app = Litestar(
    route_handlers=[delete_user_data],
)

uvicorn.run(app)
```

### Steps to reproduce

```bash
curl http://localhost:8000/schema/openapi.json
```

```json
{
  "info": {
    "title": "Litestar API",
    "version": "1.0.0"
  },
  "openapi": "3.1.0",
  "servers": [
    {
      "url": "/"
    }
  ],
  "paths": {
    "/": {
      "delete": {
        "summary": "DeleteUserData",
        "operationId": "DeleteUserData",
        "responses": {
          "204": {
            "description": "Data successfully deleted",
            "content": {  # <--------- this shouldn't be here
              "application/json": {
                "schema": {
                  "type": "null",
                  "examples": {
                    "nonetype-example-1": {
                      "description": "Example  value"
                    }
                  }
                }
              }
            }
          }
        },
        "deprecated": false
      }
    }
  },
  "components": {
    "schemas": {}
  }
}
```

### Litestar Version

2.5.1

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3069">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3069/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3069/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
Seems like a reasonable assessment. Would you be interested in submitting a fix for this?

**Comment by tuukkamustonen** [comment]
Yeah, I can try have a look in the coming week.
