### ISSUE TITLE
Bug: Sync `after_exception` handler prints `NoneType: None` when logging stacktrace

### ISSUE THREAD

**Issue by tuukkamustonen** [litestar-org/litestar#3071]
### Description

Defining a _sync_ [after_exception](https://docs.litestar.dev/latest/usage/applications.html#after-exception) and logging there with stacktrace doesn't show stacktrace.

### MCVE

```python
import logging

from litestar import Litestar, get
from litestar.testing import TestClient
from litestar.types import Scope


@get()
def endpoint() -> None:
    raise Exception("TESTING")


def exc_handler(exc: Exception, scope: Scope) -> None:
    logging.getLogger().exception(exc)


app = Litestar(
    route_handlers=[endpoint],
    after_exception=[exc_handler],
    logging_config=None,  # silence the default logging
)

with TestClient(app) as client:
    client.get("/")
```

Prints:

```
TESTING
NoneType: None
```

Change `exc_handler` to `async def` and it's as expected:

```
TESTING
Traceback (most recent call last):
  File "/home/musttu/.cache/pypoetry/virtualenvs/myproject-nodyA2ll-py3.10/lib/python3.10/site-packages/litestar/middleware/exceptions/middleware.py", line 192, in __call__
    await self.app(scope, receive, send)
  File "/home/musttu/.cache/pypoetry/virtualenvs/myproject-nodyA2ll-py3.10/lib/python3.10/site-packages/litestar/routes/http.py", line 82, in handle
    response = await self._get_response_for_request(
  File "/home/musttu/.cache/pypoetry/virtualenvs/myproject-nodyA2ll-py3.10/lib/python3.10/site-packages/litestar/routes/http.py", line 134, in _get_response_for_request
    return await self._call_handler_function(
  File "/home/musttu/.cache/pypoetry/virtualenvs/myproject-nodyA2ll-py3.10/lib/python3.10/site-packages/litestar/routes/http.py", line 154, in _call_handler_function
    response_data, cleanup_group = await self._get_response_data(
  File "/home/musttu/.cache/pypoetry/virtualenvs/myproject-nodyA2ll-py3.10/lib/python3.10/site-packages/litestar/routes/http.py", line 207, in _get_response_data
    data = await route_handler.fn(**parsed_kwargs)
  File "/home/musttu/Projects/api/api/app.py", line 10, in endpoint
    raise Exception("TESTING")
Exception: TESTING
```

### Litestar Version

2.5.1

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3069">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3069/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3069/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
This is an interesting case. I'm not 100% sure what's going on, but the behaviour you're seeing is consistent with what you get when you call `logger.exception()` while not currently handling an exception. This suggests that it's not receiving the proper exception context, but I'm not sure why that is.

**Comment by provinzkraut** [comment]
> Why does it spawn a new thread, though? As a safeguard to prevent blocking the loop if people end up doing IO there?

Yes

> Did I understand right that:
> 
>     * Sync `after_exception` is spawned into a thread
> 
>     * Sync exception handlers are not?

Correct

> Normally, if you don't need to do async IO you might as well just define the function as sync. There's shouldn't be harm/side-effect in that. But here, if `after_exception` is automatically executed in a thread, the side effect is that you lose a bit RAM, perf, the stacktrace and probably a few more things that you wouldn't expect.

Also correct, yes

> But I think whatever the approach, harmonization would do good here - establish a rule and follow that, it seems to be a bit mixed.

Agreed. There's no consistency here (and in a few other places). These are mostly leftovers from the Starlette integration and we should aim for a path that unifies behaviour here.

> With dependencies and handler declaration, you have to explicitly pass `sync_to_thread=True`. If DI was supported also for these callables I guess it would look like...
> 
> ```python
> Litestar(
>     after_exception=[Provide(my_after_exception, sync_to_thread=True)],
>     exception_handlers={
>         Exception: Provide(my_exception_handler, sync_to_thread=True),
>     }
> ```

That interface doesn't really make a lot of sense since `Provide` is a wrapper that allows something ti be injected as a dependency.

> But yeah, I think _not_ running the sync in thread by default and just documenting that could work.

I think that's not a good idea since it would deviate from the current behaviour in other places even more. IMO if we offer to pass a sync *or* async function, we should always allow `sync_to_thread`.

> (Then, if you want to go fancy, provide a decorator that will run the sync method in thread so people don't have to do inline `run_in_executor` 🤷🏻‍♂️)

That already exists, it's just not part of the public API:
```python
from litestar.utils.sync import ensure_async_callable

@ensure_async_callable
def some_sync_func() -> None:
  ...
```

we could think about making this available publicly though.

**Comment by provinzkraut** [comment]
Closing this as per https://github.com/litestar-org/litestar/issues/3071#issuecomment-1942122092.

@tuukkamustonen If you want, feel free to open a PR to add the clarification to the docs!

**Comment by tuukkamustonen** [comment]
> That interface doesn't really make a lot of sense since Provide is a wrapper that allows something ti be injected as a dependency.

That's why I wrote "If DI was supported also for these callables" though (yes, current it's not).

> I think that's not a good idea since it would deviate from the current behaviour in other places even more.

Something to consider for 3.0 at least. Harmonization even if it would break something.

> IMO if we offer to pass a sync _or_ async function, we should always allow `sync_to_thread`.

Allow or force? If allow, how would you configure that?

> That already exists, it's just not part of the public API
> we could think about making this available publicly though

Though if `sync_to_thread` is/was the default, then there would be no use. If it wasn't, then yes.

**Comment by provinzkraut** [comment]
> Something to consider for 3.0 at least. Harmonization even if it would break something.

Yeah, definitely. We could maybe try to collect those on an issue and then decide what the best way to go about them is.

> Allow or force? If allow, how would you configure that?

Not sure I follow. So far it's never forced. `sync_to_thread` defaults to `None`, but you get a warning if you leave it unset with a sync callable. IMO it makes sense that it has the same behaviour everywhere.

> Though if `sync_to_thread` is/was the default, then there would be no use. If it wasn't, then yes.

I don't think `sync_to_thread=True` should be the default if we introduce it to other places. It should behave the same as it does now.

**Comment by tuukkamustonen** [comment]
I mean you wrote:

> IMO if we offer to pass a sync or async function, we should always allow `sync_to_thread`.

I mean if you _allow_ `sync_to_thread`, ie. for exception handlers or after_exception, how would you define that?

Yes, I agree that `sync_to_thread` should be disabled by default. But when I suggested that earlier you wrote:

> I think that's not a good idea since it would deviate from the current behaviour

Thus the confusion. But maybe I misinterpreted something.

Harmonization in 3.0 is the key 👍🏻

**Comment by provinzkraut** [comment]
> I mean you wrote:
> 
> > IMO if we offer to pass a sync or async function, we should always allow `sync_to_thread`.
> 
> I mean if you _allow_ `sync_to_thread`, ie. for exception handlers or after_exception, how would you define that?

Sorry. What I meant was: We should allow passing `sync_to_thread`, i.e. make `sync_to_thread` available as a parameter to pass. Not that we should default it to `sync_to_thread=True`.

**Comment by tuukkamustonen** [comment]
Yeah, and one more question here would be that _how_ did you intend `sync_to_thread` to be passed (for exception handlers, after exception, et al)?

**Comment by provinzkraut** [comment]
> Yeah, and one more question here would be that _how_ did you intend `sync_to_thread` to be passed (for exception handlers, after exception, et al)?

I think we could a decorator as you suggested + emit a warning if a non-wrapped, sync callable is passed.
