### ISSUE TITLE
Documentation Style Overhaul

### ISSUE THREAD

**Issue by JacobCoffee** [litestar-org/litestar#3078]
Overhaul styling for documentation in 3.x (Can be earlier, but makes sense for big changes).
This would actually be done in the org-level repo to be reflected across all projects.

Some options in order of my preference

- https://github.com/lepture/shibuya 🥇 
- https://github.com/pradyunsg/lutra (very alpha, not ready yet) 🥈 
- https://github.com/withastro/starlight (almost for the lols of starlite -> litestar -> litestar + starlight) 🥉 

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3078">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3078/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3078/pledge.svg">
</picture>
</a>

**Comment by guacs** [comment]
I didn't really like the purple background for the code blocks in dark mode in Shibuya. I liked the starlight theme :)

**Comment by lepture** [comment]
@guacs you can use other colors too:

https://shibuya.lepture.com/customisation/colors/

**Comment by JacobCoffee** [comment]
@guacs also advanced alchemy uses these, but the latest shibuya moved to a different coloring so it has the default right now.

https://docs.advanced-alchemy.jolt.rs/latest/

but it had custom brand colors for all the things :D

**Comment by guacs** [comment]
> @guacs you can use other colors too:
> 
> https://shibuya.lepture.com/customisation/colors/

Oh that's great. I should have RTFM :D

**Comment by Alc-Alc** [comment]
This is the closest I can find, so I will drop this here, not sure if there is a different issue for "better docs".

> A better documentation, I started a new project about 2 months ago and wanted to try litestar instead of FastAPI.
I found the documentation messy and frustrating to read so i gave up and went back to FastAPI.
This what made flask, FastAPI etc... so appealing, the examples and documentation is amazing.

**Comment by JacobCoffee** [comment]
I dont think these are in line wit the goal of the documentation *style*, they deserve maybe their own project with some sub-issues. This is resolved in https://github.com/litestar-org/litestar/pull/3324
