### ISSUE TITLE
Request to Package litestar for Conda Distribution

### ISSUE THREAD

**Issue by aretrace** [litestar-org/litestar#3086]
### Summary

Hello,

I am writing to request the packaging and release of litestar for Conda distribution. I believe that making litestar available through Conda Forge would significantly benefit the Conda community, especially those who rely on Conda / Mamba for managing their Python environments.

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3086">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3086/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3086/pledge.svg">
</picture>
</a>

**Comment by JacobCoffee** [comment]
+1 but I am not familiar with the Conda packaging process. Unless someone else it we will have to do some research.

I see Pydantic also packages via Conda Forge so we may be able to see how their CI/publishing is set up.

**Comment by JacobCoffee** [comment]
Hi, just an update: I've found these:

- https://github.com/conda-forge/staged-recipes/pull/25131
- https://github.com/conda-forge/starlite-feedstock/issues/47

Would they satisfy this issues requirements?

**Comment by thewchan** [comment]
@JacobCoffee I believe is the on-going effort to bring Litestar over to Conda https://github.com/conda-forge/staged-recipes/pull/25131

**Comment by JacobCoffee** [comment]
This is done now in https://github.com/conda-forge/staged-recipes/pull/25131 I believe.
