### ISSUE TITLE
Bug: session middleware cookies always include segment number

### ISSUE THREAD

**Issue by betaprior** [litestar-org/litestar#3090]
### Description

The docstring of [litestar.middleware.session.client_side.CookieBackendConfig](https://github.com/litestar-org/litestar/blob/04a9501d719c26ff4ef8451d216707a1b72a1c77/litestar/middleware/session/client_side.py#L209) suggests that key for the cookie inside the header is of the form `session=<data>`, unless the cookie is over 4KB in which case it's split into segments named e.g. `session-0=<data-0>`, etc.  

However, even when the cookie is under 4KB, the segment number is present in the key, i.e. it's impossible to specify that the key be named `session` -- it will always turn into `session-0`.  The reason for this is that 
 `litestar.middleware.session.client_side.ClientSideSessionBackend._create_session_cookies` returns the result of the list comprehension which includes `[Cookie(..., key=f"{self.config.key}-{i}", ...) for i, datum in enumerate(data)]`.

### Litestar Version

2.6.0

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3090">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3090/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3090/pledge.svg">
</picture>
</a>

**Comment by guacs** [comment]
@betaprior since you seem to have figured out the issue, would you like to raise a PR with a fix?
