### ISSUE TITLE
Docs: Minor inconsistencies in description and example for "Applications" chapter

### ISSUE THREAD

**Issue by aranvir** [litestar-org/litestar#3110]
### Summary

These are small inconsistencies I spotted while reading this chapter. 

Using `state` as kwarg for `on_startup` and `on_shutdown`:
- Link: https://docs.litestar.dev/latest/usage/applications.html#using-application-state
- Paragraph: "As seen in the examples for the [on_startup](https://docs.litestar.dev/latest/usage/applications.html#before-after-startup) / [on_shutdown](https://docs.litestar.dev/latest/usage/applications.html#before-after-shutdown) , callables passed to these hooks can receive an optional kwarg called state, which is the application’s state object."
- Problem: The examples at the top of the chapter do not use the `state` kwargs argument. Instead they use `app` and then fetch the state from that object .
- Suggested solution: Since use of `state` as reserved kwarg is documented [elsewhere](https://docs.litestar.dev/latest/usage/routing/handlers.html#reserved-keyword-arguments), I assume the example file just needs an update.

The `after_exception` hook:
- Link: https://docs.litestar.dev/latest/usage/applications.html#after-exception
- Paragraph: "The after_exception hook takes a [sync or async callable](https://docs.litestar.dev/latest/reference/types.html#litestar.types.AfterExceptionHookHandler) that is called with three arguments: the exception that occurred, the ASGI scope of the request or websocket connection, and the application state."
- Problem: Documentation states that 3 arguments need to be passed, example only uses 2 arguments: `exc` and `scope`
- Suggested solution: Again, I assume the example is just outdated.

The `before_send` hook:
- Link: https://docs.litestar.dev/latest/usage/applications.html#before-send
- Paragraph: "The hook receives the message instance and the application state."
- Problem: The example receives scope instead of state
- Suggested solution: Not sure if this is even a problem or just fuzzy wording. But since the sections before referred to the kwarg `state` I think this should be made more consistent by either using `state` instead of `scope` in the example or to update the description to use `scope` instead of `state`.

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3110">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3110/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3110/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
Thanks for the report @aranvir!

The examples are actually correct in all of those cases and it's the documentation that's wrong. This has changed in 2.0 and it seems that the docs haven't been updated (the examples are actually ran and tested, that's why they're correct).

Would you want to open a PR to fix those issues?

**Comment by aranvir** [comment]
Yes, can do!

For my understanding: Is `state` then still a valid kwarg for these cases (e.g., on_startup hooks)? Or only for Router Handlers which is why it is documented [there](https://docs.litestar.dev/latest/usage/routing/handlers.html#reserved-keyword-arguments).

**Comment by provinzkraut** [comment]
> For my understanding: Is `state` then still a valid kwarg for these cases (e.g., on_startup hooks)? Or only for Router Handlers which is why it is documented [there](https://docs.litestar.dev/latest/usage/routing/handlers.html#reserved-keyword-arguments).

No, it's not valid there anymore. It used to be that you could pass different signatures, but that functionality has been removed. The `state` arg you mention is only available as part of the dependency injection, so in route handlers or injected dependency callables.
