### ISSUE TITLE
Bug: SerializationException on partial DTO for nested Pydantic model with custom type

### ISSUE THREAD

**Issue by gsakkis** [litestar-org/litestar#3192]
### Description

This is somewhat complicated to describe and reduce to a (not so) minimal CVE. It involves:
- A custom type (`CustomID`)
- A Pydantic-aware wrapper of the custom type using `__get_pydantic_core_schema__` (`PydanticCustomID`)
- A Pydantic model with a field of `PydanticCustomID` type (`Question`)
- Another Pydantic model with a `list[Question]` field (`Form`)
- Two `Form` DTOs: a full and a partial.
- Two PUT route handlers that use the DTOs

What happens:
- With valid input, both handlers work fine.
- With a missing nested field, the full DTO handler works as expected: returns HTTP 400 "Object missing required field `text` - at `$.questions[0]`".
- With a missing nested field, the partial DTO returns a 500 (`SerializationException: Unsupported type: <class 'app.PydanticCustomID'>`).

### MCVE

```python
from litestar import Litestar, put
from litestar.contrib.pydantic import PydanticDTO
from litestar.dto import DTOData, DTOConfig
from pydantic import BaseModel
from pydantic_core import core_schema


class CustomID:
    def __init__(self, value: str) -> None:
        self.value = value


class PydanticCustomID(CustomID):
    @classmethod
    def __get_pydantic_core_schema__(cls, source_type, handler):
        return core_schema.no_info_plain_validator_function(PydanticCustomID)


class Question(BaseModel):
    id: PydanticCustomID
    text: str


class Form(BaseModel):
    questions: list[Question]


class FullFormDTO(PydanticDTO[Form]):
    config = DTOConfig(partial=False)


class PartialFormDTO(PydanticDTO[Form]):
    config = DTOConfig(partial=True)


@put("/full", dto=FullFormDTO)
async def update_full(data: DTOData[Form]) -> str:
    return "ok"


@put("/partial", dto=PartialFormDTO)
async def update_partial(data: DTOData[Form]) -> str:
    return "ok"


app = Litestar(
    route_handlers=[update_full, update_partial],
    type_decoders=[
        (
            lambda target_type: target_type is PydanticCustomID,
            lambda target_type, value: PydanticCustomID(value),
        )
    ],
)
```

### Steps to reproduce

```bash
$ http -b PUT http://127.0.0.1:8000/full questions:='[{"id": "123", "text": "foo"}]'
ok

$ http -b PUT http://127.0.0.1:8000/partial questions:='[{"id": "123", "text": "foo"}]'
ok

$ http -b PUT http://127.0.0.1:8000/full questions:='[{"id": "123"}]'
{
    "detail": "Object missing required field `text` - at `$.questions[0]`",
    "status_code": 400
}

$ http -b PUT http://127.0.0.1:8000/partial questions:='[{"id": "123"}]'
{
    "details": "Traceback (most recent call last): (...) litestar.exceptions.base_exceptions.SerializationException: Unsupported type: <class 'app.PydanticCustomID'>\n",
    "status_code": 500
}
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Litestar Version

2.6.1

### Platform

- [ ] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3192">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3192/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3192/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
This is a bug but not exactly the one reported here :)

The difference between the partial and non-partial is expected; In one case the missing field is caught early by the DTO because it is defined there as required. In the other case where all fields can potentially be missing, Pydantic is reporting the exception, so you're getting an error message from Pydantic as well. Since the Pydantic error message includes, by default, a reference to the object in question, this is also included in the error response, which Litestar is trying to serlialise here. Since you are using a custom type but are not telling Litestar about how to serialise it, the exception is thrown. You'd need to add e.g. `type_encoders={PydanticCustomID: lambda c: c.value}` to your app for this to work properly.

That being said, there's also a bug where we don't use the `type_encoders` properly inside a plain text exception response. I'm cooking up a PR for this at the moment.
