### ISSUE TITLE
Feature: Allow layered `Parameter` definitions for Path Parameters

### ISSUE THREAD

**Issue by tuukkamustonen** [litestar-org/litestar#3197]
### Description

`Controller.parameters` does not allow to "pre-declare" path arguments

### MCVE

```python
from __future__ import annotations

import json

from litestar import get, Controller
from litestar.app import Litestar
from litestar.params import Parameter


class UserController(Controller):
    path = "/users/{path_item:str}"
    parameters = {
        "path_item": Parameter(description="Lorem ipsum"),  # this breaks it
        "query_item": Parameter(description="Lorem ipsum"),
        "header_item": Parameter(header="header-item", description="Lorem ipsum"),
        "cookie_item": Parameter(cookie="cookie_item", description="Lorem ipsum"),
    }

    @get()
    async def get(self, path_item: str, query_item: str, header_item: str, cookie_item: str) -> str:
        return "hello"


app = Litestar(
    [UserController],
    debug=True,
)

print(json.dumps(app.openapi_schema.to_schema(), indent=4))
```

### Steps to reproduce

Above leads to:

```
Traceback (most recent call last):
  File "/home/mtvx/Projects/myproject/api/litestar_testapp.py", line 24, in <module>
    app = Litestar(
  File "/home/mtvx/.cache/pypoetry/virtualenvs/oura-1LPe1lTf-py3.10/lib/python3.10/site-packages/litestar/app.py", line 470, in __init__
    self.register(route_handler)
  File "/home/mtvx/.cache/pypoetry/virtualenvs/oura-1LPe1lTf-py3.10/lib/python3.10/site-packages/litestar/app.py", line 657, in register
    route.create_handler_map()
  File "/home/mtvx/.cache/pypoetry/virtualenvs/oura-1LPe1lTf-py3.10/lib/python3.10/site-packages/litestar/routes/http.py", line 99, in create_handler_map
    kwargs_model = self.create_handler_kwargs_model(route_handler=route_handler)
  File "/home/mtvx/.cache/pypoetry/virtualenvs/oura-1LPe1lTf-py3.10/lib/python3.10/site-packages/litestar/routes/base.py", line 135, in create_handler_kwargs_model
    return KwargsModel.create_for_signature_model(
  File "/home/mtvx/.cache/pypoetry/virtualenvs/oura-1LPe1lTf-py3.10/lib/python3.10/site-packages/litestar/_kwargs/kwargs_model.py", line 282, in create_for_signature_model
    cls._validate_raw_kwargs(
  File "/home/mtvx/.cache/pypoetry/virtualenvs/oura-1LPe1lTf-py3.10/lib/python3.10/site-packages/litestar/_kwargs/kwargs_model.py", line 466, in _validate_raw_kwargs
    raise ImproperlyConfiguredException(
litestar.exceptions.http_exceptions.ImproperlyConfiguredException: 500: Kwarg resolution ambiguity detected for the following keys: p, a, t, h, _, i, t, e, m. Make sure to use distinct keys for your dependencies, path parameters and aliased parameters.
```

If you comment out the `path_item` from `parameters`, then it works (but "Lorem ipsum" is not set for the path item).

### Litestar Version

2.7.0

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3197">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3197/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3197/pledge.svg">
</picture>
</a>

**Comment by peterschutt** [comment]
Thanks for reporting, could you include the full traceback please?

**Comment by tuukkamustonen** [comment]
Added to the description.

**Comment by guacs** [comment]
Aah we're not ignoring `ParameterKwarg` for path parameters that are included in the layered parameters [here](https://github.com/litestar-org/litestar/blob/ef9dbb7a0cc4c7031dbf9a7bff02719d8a65a008/litestar/_kwargs/kwargs_model.py#L450-L457).

Also, it seems there's a small error in the error message since it's displaying each letter instead of all the duplicate names.

**Comment by peterschutt** [comment]
This is [documented behavior](https://docs.litestar.dev/latest/usage/routing/parameters.html#layered-parameters):

![image](https://github.com/litestar-org/litestar/assets/20659309/dc5b4941-f45d-436e-a10f-3f0926efdff6)

**Comment by tuukkamustonen** [comment]
Aww crap, indeed I didn't see that 🙈

> Also, it seems there's a small error in the error message since it's displaying each letter instead of all the duplicate names.

Yeah, maybe the error message could be polished if not anything else.

Does it still stand that it would be complicated to implement this, or have things changed...?

**Comment by provinzkraut** [comment]
I'm thinking if we should even allow this. I can't think of a good use case for this actually. Since you can, due to their nature, only define paths locally, it makes sense that their parameters should be declared as close as possible as well.

**Comment by guacs** [comment]
> I'm thinking if we should even allow this. I can't think of a good use case for this actually. Since you can, due to their nature, only define paths locally, it makes sense that their parameters should be declared as close as possible as well.
> 
> @litestar-org/maintainers?

I don't think this is something we should support either. As shown [here](https://github.com/litestar-org/litestar/pull/3223#issuecomment-2008546856), there would be some ambiguity and while we can deal with it, there would still be room for a lot of confusion.
