### ISSUE TITLE
Bug: Type Checker throws "Return type, "TestClient[Unknown]", is partially unknown" error message

### ISSUE THREAD

**Issue by Jarmos-san** [litestar-org/litestar#3229]
### Description

We use [pyright](https://microsoft.github.io/pyright) to perform a customary type-check on our source and complains about missing return types on our test cases.

### MCVE

```python
# add the following lines of code in a main.py file

import pytest
from litestar import Litestar
from litestar.status_codes import HTTP_200_OK
from litestar.testing import TestClient

@get()
async def ping(self) -> dict[str, str]:
    return {"health": "OK"}

app = Litestar(route_handlers=[ping])

@pytest.fixture(scope="class")
def test_client(self) -> TestClient:
    return TestClient(app=app)

def test_health_check_returns_status_200_ok(self, test_client: TestClient) -> None:
    with test_client as client:
        response = client.get("/health-check")
        assert response.status_code == HTTP_200_OK
```

### Steps to reproduce

1. Copy the contents of the MVCE shared above to a `main.py` file.
2. Install the dependencies - `pytest`, `litestar` and `pyright`.
3. Activate the virtual environment and invoke the `pyright main.py` command.
4. And then `pyright` will throw an error related to the return type of `TestClient`.

### Logs

```console
/home/<...>/core/tests/routes/test_routes.py
  /home/<...>/core/tests/routes/test_routes.py:16:16 - error: Return type, "TestClient[Unknown]", is partially unknown (reportUnknownVariableType)
  /home/<...>/core/tests/routes/test_routes.py:20:29 - error: Type of "client" is partially unknown
    Type of "client" is "TestClient[Unknown]" (reportUnknownVariableType)
  /home/<...>/core/tests/routes/test_routes.py:27:29 - error: Type of "client" is partially unknown
    Type of "client" is "TestClient[Unknown]" (reportUnknownVariableType)
3 errors, 0 warnings, 0 informations
```

### Litestar Version

v2.5.4

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3229">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3229/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3229/pledge.svg">
</picture>
</a>

**Comment by Alc-Alc** [comment]
I do not think this is a bug

`TestClient[Litestar]` is the proper way, can you check that?

**Comment by Jarmos-san** [comment]
Yeah, `TestClient[Litestar]` is indeed the way to go about it. Thanks for the solution!
