### ISSUE TITLE
Enhancement: Support for dictionaries with Pydantic models as value, e.g. dict[str, PydanticClass]

### ISSUE THREAD

**Issue by ErikvdVen** [litestar-org/litestar#3233]
### Summary

As mentioned on the Discord channel, below code will result in a Pydantic validation error. If I turn households into lists (as well as in the defaults dict as in the HousHolds class) it all works!! But using dict[str, HouseHold] as typehint, does not work out.

As a maintainer `g...` pointed out: This is something we just don't handle in polyfactory currently. When given a dictionary for households, then it's assumed that the value you've given is what should be used. That means we end up not creating instances of HouseHold, but just pass in the raw dictionary and pydantic complains.

Currently we do support Sequence[SomeModel, but no other type is supported. I think supporting things like Mapping[str, SomeModel] is going to be somewhat complex though I'm not a 100% sure.

The code:
```
from pydantic import Field, BaseModel
from uuid import UUID, uuid4
from typing_extensions import TypedDict
from typing import Union
from datetime import date, datetime

from polyfactory.factories.pydantic_factory import ModelFactory
from polyfactory.factories import TypedDictFactory

class RelativeDict(TypedDict):
    household_id:str
    familymember_id:str

class FamilyMember(BaseModel):
    familymember_id: str
    name: str
    hobbies: list[str]
    age: Union[float, int]
    birthday: Union[datetime, date]
    relatives: list[RelativeDict]

class HouseHold(BaseModel):
    household_id: str
    name: str
    familymembers: list[FamilyMember]

class HouseHolds(BaseModel):
    id: UUID = Field(default_factory=uuid4)
    households: dict[str, HouseHold]

class RelativeDictFactory(TypedDictFactory[RelativeDict]):
    ...

class FamilyMemberFactory(ModelFactory[FamilyMember]):
    relatives = list[RelativeDictFactory]

class HouseHoldFactory(ModelFactory[HouseHold]):
    familymembers = list[FamilyMemberFactory]

class HouseHoldsFactory(ModelFactory[HouseHolds]):
    ...

defaults = {
    "households": {
        "beck": {
            "household_id": "beck", 
            "name": "Family Beck", 
            "familymembers": [
                {
                    "familymember_id": "linda",
                    "relatives": [
                        {
                            "household_id": "grant",
                            "familymember_id": "dad"
                        }
                    ]
                }, 
                {"familymember_id": "erik"}
            ]
        }
        ,"grant":{
            "household_id": "grant", 
            "name": "Family Grant", 
            "familymembers": [
                {"familymember_id": "dad"}, 
                {"familymember_id": "mother"}
            ]
        }
    }
}

test = HouseHoldsFactory.build(**defaults)
print(test)
```

Just running the build method without any defaults works, but as you can see, the `relatives` key of the `FamilyMember` class should only contain a Household id and a Familymember id that exist (ie. an id of a Household that contains a Familymember wiht a certain id). So there are dependencies, that's the reason of this whole dictionary. 

It does saves us from having to provide all the other fields, as in practice these classes could contain a ton of extra fields, which don't have dependencies, so Polyfactory could easily fake those for us.

### Basic Example

Maintainer `g...` provided a basic solution for now:
```
defaults = {
    "households": {
        "beck": HouseHold(...)
        ,"grant": HouseHold(...)
}
```
So that should work out or I could override the build method, was his suggestion. 

What I think would be ideal is:

```
class HouseHoldsFactory(ModelFactory[HouseHolds]):
    households: dict[str, HouseHoldFactory]
```

So the `ModelFactory` knows when it hits the key households, it actually knows how to handle that object (the keys should be a string and the values should be parsed with that `HouseHoldFactory` class).

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3233">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3233/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3233/pledge.svg">
</picture>
</a>

**Comment by guacs** [comment]
@ErikvdVen I think I may have not been clear. I think this is something we could potentially implement, so I don't think this issue should be closed.

**Comment by peterschutt** [comment]
Is this supposed to be a polyfactory issue @guacs?

**Comment by guacs** [comment]
Yeah you're right. That's why he closed it. I got it confused :D

**Comment by ErikvdVen** [comment]
> Is this supposed to be a polyfactory issue @guacs?

Haha exactly. I clicked the button on discord to open an issue but found out to late that this wasn't the polyfactory repo, so that's why I closed it and opened the same ticket over there.

**Comment by JacobCoffee** [comment]
Transfer button works as well! :)

<img width="461" alt="image" src="https://github.com/litestar-org/litestar/assets/45884264/49f397dc-2508-4fa2-b1d9-fa92d355d136">

**Comment by guacs** [comment]
> Transfer button works as well! :)
> 
> <img alt="image" width="461" src="https://private-user-images.githubusercontent.com/45884264/316267411-49f397dc-2508-4fa2-b1d9-fa92d355d136.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyNDYxMjcsIm5iZiI6MTcxMTI0NTgyNywicGF0aCI6Ii80NTg4NDI2NC8zMTYyNjc0MTEtNDlmMzk3ZGMtMjUwOC00ZmEyLWIxZDktZmE5MmQzNTVkMTM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDAyMDM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzODFlMjZjMDc3ODdhYzJhODNhNzc0YjMxOTI5Yzk0MWI4MTA1NWQ2YWVhMDI0YjMyMWJhZDhiMGExZmFhMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.syLFw8Y7z3iyOPTqy2L4eT0JeL7xKhmdwKhlb4srJAo">

Oh I didn't know you could do this. That's cool.
