### ISSUE TITLE
Bug: advanced-alchemy's `wrap_sqlalchemy_exception()` has moved

### ISSUE THREAD

**Issue by ubernostrum** [litestar-org/litestar#3238]
### Description

Currently, `litestar.contrib.sqlalchemy._util` [imports `wrap_sqlalchemy_exception()` from `advanced_alchemy.repository.util`](https://github.com/litestar-org/litestar/blob/e763cea5e8a259695a2827c5ac3e568832c2445d/litestar/contrib/sqlalchemy/repository/_util.py#L3), but that function [has moved](https://github.com/jolt-org/advanced-alchemy/commit/3364b6e45fa9f79d7cb5d0194ef4d232e3fdf9dc) to `advanced_alchemy.exceptions` as of advanced-alchemy 0.8.0, released this week.

One fix might be to attempt to import first from the new location, and if `ImportError` is raised catch it and fall back to importing from the old location.

Longer-term (3.0) I'd suggest just not attempting to import  it, as Litestar appears to make no use of this function and only imports it to re-export it in the `__all__` of `litestar.contrib.sqlalchemy.repository`.

### MCVE

```python
>>> from importlib.metadata import version
>>> print(version("advanced_alchemy"))
0.8.0
>>> from litestar.contrib.sqlalchemy.repository import SQLAlchemyAsyncRepository
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/james/.pyenv/versions/3.12.0/envs/litestar-aa-bug/lib/python3.12/site-packages/litestar/contrib/sqlalchemy/repository/__init__.py", line 3, in <module>
    from ._util import wrap_sqlalchemy_exception
  File "/Users/james/.pyenv/versions/3.12.0/envs/litestar-aa-bug/lib/python3.12/site-packages/litestar/contrib/sqlalchemy/repository/_util.py", line 3, in <module>
    from advanced_alchemy.repository._util import get_instrumented_attr, wrap_sqlalchemy_exception
ImportError: cannot import name 'wrap_sqlalchemy_exception' from 'advanced_alchemy.repository._util' (/Users/james/.pyenv/versions/3.12.0/envs/litestar-aa-bug/lib/python3.12/site-packages/advanced_alchemy/repository/_util.py)
```

### Steps to reproduce

1. `python -m pip install "litestar[sqlalchemy]"`
2. Verify advanced-alchemy installed version >= 0.8.0
3. Attempt to import either the sync or async repository through `litestar.contrib.sqlalchemy.repository`
4. Receive `ImportError`

### Litestar Version

2.7.0

### Platform

- [X] Linux
- [X] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3238">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3238/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3238/pledge.svg">
</picture>
</a>

**Comment by peterschutt** [comment]
We still have `pdm.lock` pointing to v0.7.4 which is why this isn't showing up in our CI.

Given the tight coupling that we still have between litestar and AA I think we should be testing releases on the AA side against the litestar codebase. I.e., in the AA release pipeline have a step that clones litestar, installs deps, install latest AA over the top and then run the litestar test suite to ensure that a release in AA doesn't have a downstream incompatibility with litestar.  WDYT @cofin?

**Comment by peterschutt** [comment]
Fixed upstream - thanks for reporting @ubernostrum
