### ISSUE TITLE
Enhancement: Add plugin for grafana loki

### ISSUE THREAD

**Issue by aranvir** [litestar-org/litestar#3249]
### Summary

[Grafana Loki](https://grafana.com/docs/loki/latest/) is a compact log aggregator. Logs of different sources (files, streams, etc.) are ingested by a client (e.g., [Grafana Promtail](https://grafana.com/docs/loki/latest/send-data/promtail/)) and pushed to the Loki API. The logs are indexed by labels, not content. Loki stores the data as chunks on the local file system or an S3 bucket. The stored data can be visualized via Grafana or pulled from the Loki API for use in a different application.

I played around with this as a weekend project to look for a simpler alternative to the ELK stack. There are already multiple agent solutions to ingest logs from k8s pods or docker compose services but I wanted to learn more about how the API works and how I can use it for custom logging of timeseries data.

My question is whether this would be desirable to add it to the litestar library as a `contrib` package. Since the client would not add any new dependencies it would be just another "nice to have".

### Basic Example

I wrote a Loki client that can manage a queue to send messages concurrently to the main workflow (to not block the route handler). It also offers a method to send a message immediately instead of queueing it. I wrote a minimal litestar demo that showcases its use. I also appended my docker compose file that I used to set up a Grafana and Grafana loki instance.

Note: I use loguru here for convenvience, it is not essential to the client.

**Loki Client**
```python
import asyncio
import copy
from datetime import datetime
import time
import threading
from dataclasses import dataclass, field, InitVar
from contextlib import asynccontextmanager

import httpx
from loguru import logger
from litestar import Litestar
from litestar.config.app import AppConfig
from litestar.di import Provide
from litestar.plugins import InitPluginProtocol


@dataclass
class LokiValue:
    """Container for a timestamped log line."""
    time_value: InitVar[int | datetime]
    line: str
    time_ns: str = field(init=False)

    def __post_init__(self, time_value: int | datetime):
        if isinstance(time_value, int):
            self.time_ns = str(time_value)
        else:
            self.time_ns = str(time_value.timestamp() * 1e9)

    def loki_format(self) -> list[str]:
        data = [self.time_ns, self.line]
        return data

    @classmethod
    def timestamped_line(cls, line: str):
        return cls(
            time_value=time.time_ns(),
            line=line,
        )


@dataclass
class LokiMessage:
    """Container for a full Loki message including labels and one or more values"""
    labels: dict[str, str]
    values: list[LokiValue]

    def as_payload(self):
        data = {
            "streams": [{
                "stream": self.labels,
                "values": [v.loki_format() for v in self.values]
            }]
        }
        return data


@dataclass
class LokiMessageTemplate:
    """Convenience class to pre-define a set of labels and use it to create Loki messages ad-hoc
    without needing to set the labels again and again.
    """
    labels: dict[str, str]

    def to_message(self, values: list[LokiValue]) -> LokiMessage:
        return LokiMessage(
            labels=self.labels,
            values=values
        )

    def timestamped_message(self, line: str, extra_labels: dict[str, str] = None):
        value = LokiValue.timestamped_line(line)
        if extra_labels:
            labels = copy.copy(self.labels)
            labels.update(extra_labels)
            return LokiMessage(
                labels=labels,
                values=[value]
            )
        else:
            return self.to_message([value])


class LokiQueueHandler:
    def __init__(
            self,
            address: str = "http://localhost:3100",
            *,
            extra_labels: dict | None = None,
    ):
        """Async loki client that pushes messages from a queue or sends a message immediately on request."""
        self._address = address
        self._endpoint = "/loki/api/v1/push"
        self._full_address = self._address + self._endpoint
        self._headers = {'Content-type': 'application/json'}
        self._extra_labels = extra_labels
        self._queue: asyncio.Queue[LokiMessage] = asyncio.Queue()
        self._queue_run = threading.Event()
        self._queue_run.set()

    def put_nowait(self, msg: LokiMessage):
        """Place a message in the message queue that will be sent in the near future."""
        self._queue.put_nowait(msg)
        logger.debug("Message put in queue")

    async def write(self, msg: LokiMessage):
        """Send a message immediately."""
        await self._send_message(msg)

    async def _send_message(self, msg: LokiMessage):
        """Send a message to the loki endpoint. Bypasses the queue."""
        async with httpx.AsyncClient(base_url=self._address, headers=self._headers) as client:
            r = await client.post(url=self._endpoint, json=msg.as_payload())
            logger.info(f"message sent. {r}. {r.text}")

    async def handle_queue(self):
        """While event is set, fetch items from the queue and then them to the Loki endpoint."""
        logger.info("Queue started")
        while self._queue_run.wait(0):
            try:
                msg = self._queue.get_nowait()
            except asyncio.QueueEmpty:
                await asyncio.sleep(1)
            else:
                logger.info("Received message from queue")
                await self._send_message(msg)
        logger.info("Queue ended.")


class LokiQueuePlugin(LokiQueueHandler, InitPluginProtocol):
    """Registers a lifespan that runs the Loki queue. Adds a dependency to the app so that any route handler
    can send messages to loki or put them in the queue."""

    @asynccontextmanager
    async def lifespan(self, _: Litestar):
        task = asyncio.create_task(self.handle_queue())
        yield
        self._queue_run.clear()
        try:
            await task
        except Exception:
            pass

    def get_handle(self):
        return self

    def on_app_init(self, app_config: AppConfig) -> AppConfig:
        app_config.dependencies["loki"] = Provide(self.get_handle, sync_to_thread=True)
        app_config.lifespan.append(self.lifespan)
        return app_config


```

**Litestar App**
```python
from litestar import Litestar, get

from loki_queue import LokiQueuePlugin, LokiMessageTemplate

loki_plugin = LokiQueuePlugin()
template = LokiMessageTemplate(
    {"app": "litestar_demo"}
)


@get("/")
async def home(loki: LokiQueuePlugin) -> str:
    message = template.timestamped_message("Hello World")
    loki.put_nowait(message)
    return "Loki message triggered."


@get("/user/{user:str}")
async def home_user(user: str, loki: LokiQueuePlugin) -> str:
    message = template.timestamped_message(f"Hello {user}", extra_labels={"user": user})
    loki.put_nowait(message)
    return f"Loki message triggered by user {user}."


app = Litestar(
    route_handlers=[
        home,
        home_user
    ],
    plugins=[loki_plugin]
)

```

**docker-compose.yml**
```yaml
version: "2"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

  loki:
    image: grafana/loki
    container_name: loki
    restart: unless-stopped
    volumes:
      - ./config/loki_config.yaml:/etc/loki/local-config.yaml
      - loki-storage:/loki
    ports:
      - '3100:3100'
    command: -config.file=/etc/loki/local-config.yaml

volumes:
  grafana-storage: {}
  loki-storage: {}
```

### Drawbacks and Impact

I just started learning about Grafana Loki, so I'm not 100% sure if this is the best use of it. Maybe it's better just to log and ingest everything. On the other hand, while it seems easy to get a basic setup running, even with one of the other agents, it might take longer to understand all the different configuration details and options.

Using this plugin as a starter seems way simpler to me, since it's more "what you see is what you get".

### Unresolved questions

The example provided is my first iteration and can use some improvement. E.g., it's probably better to use Pydantic instead of dataclass for input validation. Loki is quite strict on the formatting, so passing a timestamp as an integer insted of a string will not fly.

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3249">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3249/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3249/pledge.svg">
</picture>
</a>

**Comment by peterschutt** [comment]
Hey thanks for this! How have you found the experience of working with the plugin system? Anything you'd like to see added or any pain points?

I'd encourage you to publish this as your own plugin library and we can promote it in our Discord showcase and add it to https://github.com/litestar-org/awesome-litestar. If over time there proves to be enough interest - we can consider to move the project into the org if necessary in order to assist with maintenance, but lets get there first.

Let us know either here or in discord if you stand up a repository for the plugin. Cheers!

**Comment by peterschutt** [comment]
Reopened as I just saw the discord discussion suggesting to open this issue - take the above comment as my opinion on the matter :)

**Comment by aranvir** [comment]
> Hey thanks for this! How have you found the experience of working with the plugin system? Anything you'd like to see added or any pain points?
> 
> I'd encourage you to publish this as your own plugin library and we can promote it in our Discord showcase and add it to https://github.com/litestar-org/awesome-litestar. If over time there proves to be enough interest - we can consider to move the project into the org if necessary in order to assist with maintenance, but lets get there first.
> 
> Let us know either here or in discord if you stand up a repository for the plugin. Cheers!

Hi @peterschutt, after playing around with litestar for a while now, I found it very easy and straightforward to set up a plugin like this. So, no complaints so far ;)

When I have time, I'll set up a seaparate repo for this plugin to make it easily available to others. Is it okay to name it something like `litestar-plugin-loki` or is there a certain naming schema you'd like people to follow?

**Comment by peterschutt** [comment]
I'll close this, but let us know once you have the repo up!
