### ISSUE TITLE
bug(docs): stale reference to pydantic signature models

### ISSUE THREAD

**Issue by peterschutt** [litestar-org/litestar#3259]
https://github.com/litestar-org/litestar/blob/4b7d77ea9cfd5860e1ab61a7259062c66e2465ec/docs/usage/routing/parameters.rst?plain=1#L51

I don't think it matters how this coercion occurs for the purposes of the docs - we'd just be better off noting that it does occur and leave it at that.

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3259">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3259/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3259/pledge.svg">
</picture>
</a>

**Comment by peterschutt** [comment]
Similar reference in here: https://docs.litestar.dev/latest/usage/routing/parameters.html#type-coercion

**Comment by JacobCoffee** [comment]
Things like this are cleaned up in https://github.com/litestar-org/litestar/pull/3212, i can add it to my list
