### ISSUE TITLE
Bug: default not generated for query parameter in openapi spec.

### ISSUE THREAD

**Issue by globglarb** [litestar-org/litestar#3278]
### Description

Hi,

The default of a query parameter is not properly generated when creating the openapi specification. See MVCE down below.

The generated specification looks like this:

```json
...
"paths": {
    "/query_default": {
      "get": {
        "summary": "QueryDefault",
        "operationId": "QueryDefaultQueryDefault",
        "parameters": [
          {
            "name": "foo",
            "in": "query",
            "schema": {
              "type": "integer"
            },
            "required": false,
            "deprecated": false,
            "allowEmptyValue": false,
            "allowReserved": false
          }
        ],
...
```
where the default is missing in the schema property.

### MCVE

```python
@get(path="query_default")
def query_default(foo: int = 12) -> None:
    return

app = Litestar(route_handlers=[query_default])
```

### Litestar Version

Version 2.7.1

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3278">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3278/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3278/pledge.svg">
</picture>
</a>

**Comment by JacobCoffee** [comment]
Could you confirm that this is also true in 2.7.0?

**Comment by globglarb** [comment]
Same result with fixed version 2.7.0
```toml
dependencies = [
    "litestar[standard]==2.7.0"
]
```

**Comment by JacobCoffee** [comment]
Thanks!

**Comment by guacs** [comment]
I don't think this is a bug. The [specification](https://spec.openapis.org/oas/latest.html#parameter-object) doesn't have a field to indicate a default value for parameters.

**Comment by guacs** [comment]
Sorry about that. I was completely wrong. While it's correct that the parameter object as per the spec doesn't allow for defaults, it does allow for a `schema` which *can* have a default value. 

Us not parsing the default properly is a bug.

**Comment by globglarb** [comment]
Thanks for the workaround. I added the working schema snippet for completeness
```json
...
 "paths": {
    "/query_default": {
      "get": {
        "summary": "QueryDefault",
        "operationId": "QueryDefaultQueryDefault",
        "parameters": [
          {
            "name": "foo",
            "in": "query",
            "schema": {
              "type": "integer",
              "default": 12
            },
            "required": false,
            "deprecated": false,
            "allowEmptyValue": false,
            "allowReserved": false
          }
        ],
...
```
