### ISSUE TITLE
Docs: Create an example of utilizing GraphQL with Litestar via Strawberry

### ISSUE THREAD

**Issue by JacobCoffee** [litestar-org/litestar#3317]
Maybe an example app(with integrated input validation) or a suggestion would be useful in the docs. 
Thank you, I will try it soon.

_Originally posted by @teddybee in https://github.com/litestar-org/litestar/discussions/605#discussioncomment-8381807_

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3317">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3317/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3317/pledge.svg">
</picture>
</a>

**Comment by aarcex3** [comment]
Hi, I would like to take this one.
What kind of example app should I do?.
_Im a newbie btw, somethings are not very clear to me but I wanna give it a try_  🤓

**Comment by sloria** [comment]
i think it'd still be useful to mention graphql support within the litestar docs itself. someone who is evaluating litestar as a framework underlying a multi-protocol (REST, GraphQL, etc) web app would be pleased to find a "blessed" solution within the docs.

even just the initial code sample in https://strawberry.rocks/docs/integrations/litestar and a link to the strawberry docs would suffice IMO
