### ISSUE TITLE
Bug: Remove use of `assert` for pydantic import flow control

### ISSUE THREAD

**Issue by peterschutt** [litestar-org/litestar#3354]
### Description

It was a poor choice to use assertions for the Pydantic import version discrimination refactor in #3347, as they can be optimized away.

We should revert to raising some other exception type where this was applied.

https://github.com/litestar-org/litestar/blob/fe73848ad25961f37109ad4049799a64b856c8d3/litestar/contrib/pydantic/pydantic_dto_factory.py#L26-L37

### MCVE

```python
# Your MCVE code here
```

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Litestar Version

v2.8.2

### Platform

- [ ] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3354">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3354/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3354/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
Why not just raise an `ImportError`?

**Comment by peterschutt** [comment]
> Why not just raise an `ImportError`?

Yeah
