### ISSUE TITLE
Bug: OpenAPI Specs incorrect for Paginated DTO Response

### ISSUE THREAD

**Issue by cofin** [litestar-org/litestar#3367]
### Description

When using a DTO and returned a paginated response type like `OffsetPagination[model_type]`, the resulting open API specs do not include the pagination structure.

Here's an example [without using a DTO from fullstack](https://fullstack.litestar.dev/schema/#tag/user-accounts/get/api/users).

For instance, here is an example of the [fullstack Tags controller.](https://fullstack.litestar.dev/schema/#tag/tags/get/api/tags)  
```json
{
  "schema": {
    "items": {
      "properties": {
        "name": {
          "type": "string"
        },
        "description": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "type": "string"
            }
          ]
        },
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "slug": {
          "type": "string"
        }
      },
      "type": "object",
      "required": [
        "name",
        "slug"
      ],
      "title": "ListTagsTagResponseBody"
    },
    "type": "array"
  }
}
```

### MCVE

```python
# Your MCVE code here
```

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Litestar Version

2.8

### Platform

- [X] Linux
- [X] Mac
- [X] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3367">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3367/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3367/pledge.svg">
</picture>
</a>

**Comment by peterschutt** [comment]
What's the MCVE? A route returning a paginated list of dataclasses with a return dto?

**Comment by peterschutt** [comment]
MCVE:

```py
from dataclasses import dataclass

from litestar import Litestar, get
from litestar.dto import DataclassDTO
from litestar.pagination import ClassicPagination


@dataclass
class Test:
    name: str
    age: int


@get("/without-dto", sync_to_thread=False)
def without_dto() -> ClassicPagination[Test]:
    return ClassicPagination(
        items=[Test("John", 25), Test("Jane", 30)],
        page_size=1,
        current_page=2,
        total_pages=2,
    )


@get("/with-dto", return_dto=DataclassDTO[Test], sync_to_thread=False)
def with_dto() -> ClassicPagination[Test]:
    return ClassicPagination(
        items=[Test("John", 25), Test("Jane", 30)],
        page_size=1,
        current_page=2,
        total_pages=2,
    )


app = Litestar([without_dto, with_dto])
```

![image](https://github.com/litestar-org/litestar/assets/20659309/c1bebf46-095c-4ba9-8d08-2de186b0d57f)

**Comment by peterschutt** [comment]
This is actually a dup of #2929
