### ISSUE TITLE
Bug: Exception not handled correctly

### ISSUE THREAD

**Issue by sorasful** [litestar-org/litestar#3399]
### Description

I noticed that when I tried to raise an HTTPException, instead of returning the dedicated HTTP status code, it was automatically returned as an error 500. 

### MCVE

```python
from litestar import Litestar, get
from litestar.exceptions import HTTPException

@get("/")
def hello_world() -> dict[str, str]:
    """Keeping the tradition alive with hello world."""
    raise HTTPException(410, "Gone")


app = Litestar(route_handlers=[hello_world])
```

### Steps to reproduce

```bash
Just navigate to the / route and notice that we get an 500 error instead of a 410.
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Litestar Version

litestar==2.8.2

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3399">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3399/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3399/pledge.svg">
</picture>
</a>

**Comment by peterschutt** [comment]
Please read the docs for [`HTTPException`](https://docs.litestar.dev/latest/reference/exceptions.html#litestar.exceptions.HTTPException).

The first arugment is `detail`, status has to be provided as a keyword argument:

```py
from typing import Dict

from litestar import Litestar, get
from litestar.exceptions import HTTPException
from litestar.testing import TestClient


@get("/")
def hello_world() -> Dict[str, str]:
    raise HTTPException("Gone", status_code=410)


app = Litestar(route_handlers=[hello_world], debug=True)


def test_app() -> None:
    with TestClient(app=app) as client:
        response = client.get("/")
        assert response.status_code == 410
        assert response.json() == {"detail": "Gone", "status_code": 410}
```
