### ISSUE TITLE
Bug: cant upload one file only if type is list[UploadFile] | None

### ISSUE THREAD

**Issue by euri10** [litestar-org/litestar#3407]
### Description

I though I had the same issue as #2939 but it's slightly different, here is a test case that fails for one file and not for 2 files:
```
@dataclass
 class OFiles:
    file_list: Optional[List[UploadFile]]


@pytest.mark.parametrize("file_count", (1, 2))
def test_upload_multiple_ofiles_in_model(file_count: int) -> None:
    @post("/")
    async def handler(data: OFiles = Body(media_type=RequestEncodingType.MULTI_PART)) -> None:
        assert len(data.file_list) == file_count

        for file in data.file_list:
            assert await file.read() == b"1"

    with create_test_client([handler]) as client:
        files_to_upload = [("file_list", b"1") for _ in range(file_count)]
        response = client.post("/", files=files_to_upload)

        assert response.status_code == HTTP_201_CREATED

```

### MCVE

```python
# Your MCVE code here
```

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Litestar Version

2.8.2final0

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3407">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3407/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3407/pledge.svg">
</picture>
</a>

**Comment by JacobCoffee** [comment]
It also removes the `Upload File` button in OpenAPI schema docs :(

```py
from litestar import Controller, Litestar, post
from litestar.datastructures import UploadFile
from litestar.enums import RequestEncodingType
from litestar.params import Body


class Files(Controller):
    @post(path="/files/upload")
    async def upload_files(
        self,
        data: UploadFile | None = Body(media_type=RequestEncodingType.MULTI_PART),
    ) -> str:
        return data


app = Litestar(route_handlers=[Files])
```

Without `| None`
<img width="805" alt="image" src="https://github.com/litestar-org/litestar/assets/45884264/b6cb0694-aea9-4a82-929c-cdc79fb447fe">

With `| None`

<img width="1454" alt="image" src="https://github.com/litestar-org/litestar/assets/45884264/503e2f27-1319-4820-83bd-40438c66136d">

**Comment by peterschutt** [comment]
> May need to be a separate issue, but `| None` also removes the `Upload File` button in OpenAPI schema docs :(
> 
> ```python
> from litestar import Controller, Litestar, post
> from litestar.datastructures import UploadFile
> from litestar.enums import RequestEncodingType
> from litestar.params import Body
> 
> 
> class Files(Controller):
>     @post(path="/files/upload")
>     async def upload_files(
>         self,
>         data: UploadFile | None = Body(media_type=RequestEncodingType.MULTI_PART),
>     ) -> str:
>         return data
> 
> 
> app = Litestar(route_handlers=[Files])
> ```
> 
> Without `| None` <img alt="image" width="805" src="https://private-user-images.githubusercontent.com/45884264/324127331-b6cb0694-aea9-4a82-929c-cdc79fb447fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NTg3MjYsIm5iZiI6MTcxMzY1ODQyNiwicGF0aCI6Ii80NTg4NDI2NC8zMjQxMjczMzEtYjZjYjA2OTQtYWVhOS00YTgyLTkyOWMtY2RjNzlmYjQ0N2ZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDAwMTM0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NDliZDA4Y2IzMGQwZGMyYjhhZjhlODJiMjA4MzcwM2ZmMjM4NjY4OGI2Nzc4NGJkZmI2MjIzODI0ZmY1M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JJOzLYaGvguoPJLp4Qr3CA1yIX-DUwu1iTtKTiCri-c">
> 
> With `| None`
> <img alt="image" width="1454" src="https://private-user-images.githubusercontent.com/45884264/324127511-503e2f27-1319-4820-83bd-40438c66136d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NTg3MjYsIm5iZiI6MTcxMzY1ODQyNiwicGF0aCI6Ii80NTg4NDI2NC8zMjQxMjc1MTEtNTAzZTJmMjctMTMxOS00ODIwLTgzYmQtNDA0MzhjNjYxMzZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDAwMTM0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkYWJlNThhNDg1MGM5NzE1MzUzM2JjMTBmOWM5OWZkMzE1MjRmYzhiYzQ4ODUwYjZkYTY5OTQ2ZDM4MWFmZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aE_hRg6w-egU0vTAyF2hUiLgYKsGhJ_QlDBp6ACRhJI">

Yeah, I think should be separate. Opened #3411.
