### ISSUE TITLE
Bug: ResponseHeaders results in invalid OpenAPI schema

### ISSUE THREAD

**Issue by mands** [litestar-org/litestar#3416]
### Description

Use of `response_headers` on the Litestar object seems to result in invalid OpenAPI 3.1 schema generation.

The Header object on the response is invalid aiui according to the spec (see https://spec.openapis.org/oas/v3.1.0#header-object) and fails validation when using `redocly lint`, as it includes the `name` and `in` fields.

The schema is as follows,

```json
{
    "info": {
        "title": "Litestar API",
        "version": "1.0.0"
    },
    "openapi": "3.1.0",
    "servers": [
        {
            "url": "/"
        }
    ],
    "paths": {
        "/": {
            "get": {
                "summary": "HelloWorld1",
                "operationId": "HelloWorld1",
                "responses": {
                    "200": {
                        "description": "Request fulfilled, document follows",
                        "headers": {
                            "X-Version": {
                                "schema": {
                                    "type": "string"
                                },
                                "name": "X-Version",
                                "in": "header",
                                "description": "Test",
                                "required": false,
                                "deprecated": false,
                                "allowEmptyValue": false,
                                "allowReserved": false
                            }
                        }
                    }
                },
                "deprecated": false
            }
        }
    },
    "components": {
        "schemas": {}
    }
}
```

### MCVE

```python
from litestar import Litestar, Request, get
from litestar.datastructures import ResponseHeader

@get("/")
async def hello_world1(request: Request) -> None:
    request.logger.info("inside request")
    return None

app1 = Litestar(
    route_handlers=[hello_world1],
    response_headers=[ResponseHeader(name="X-Version", value="ABCD", description="Test")],
)
```

This endpoint works, but the resulting schema fails validation.

```bash
$ litestar schema openapi --output openapi_schema.json
$ npx @redocly/cli lint openapi_schema.json

...
[1] openapi_schema.json:25:33 at #/paths/~1/get/responses/200/headers/X-Version/name

Property `name` is not expected here.

23 |     "type": "string"
24 | },
25 | "name": "X-Version",
26 | "in": "header",
27 | "description": "Test",

Error was generated by the spec rule.


[2] openapi_schema.json:26:33 at #/paths/~1/get/responses/200/headers/X-Version/in

Property `in` is not expected here.

24 | },
25 | "name": "X-Version",
26 | "in": "header",
27 | "description": "Test",
28 | "required": false,
...

```

### Litestar Version

2.8.2, using Python 3.12.2

### Platform

- [ ] Linux
- [X] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3416">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3416/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3416/pledge.svg">
</picture>
</a>

**Comment by peterschutt** [comment]
Thanks for reporting!

We go to a lot of effort to document that these shouldn't be included also:

https://github.com/litestar-org/litestar/blob/a31d1c6347714ae51cc72c08f0333cae414f7f22/litestar/openapi/spec/header.py#L18-L36
