### ISSUE TITLE
Enhancement: Support RSGI Specification (granian)

### ISSUE THREAD

**Issue by gam-phon** [litestar-org/litestar#3423]
### Summary

Here is the [specification](https://github.com/emmett-framework/granian/blob/master/docs/spec/RSGI.md)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3423">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3423/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3423/pledge.svg">
</picture>
</a>

**Comment by JacobCoffee** [comment]
Do you just want to be able to use Granian?

**Comment by gam-phon** [comment]
@JacobCoffee Thanks for your quick response and sharing the plugin.

Actually I am using this command
```
granian --interface asgi app:app
```

I wanted to run it with `--interface rsgi`

Great it will be available in Litestar v3, then please feel free to close this

Thank you

**Comment by gam-phon** [comment]
Thank you for your quick response. I really appreciate it.

**Comment by gam-phon** [comment]
.
