### ISSUE TITLE
Documentation: Self-contained examples in docs

### ISSUE THREAD

**Issue by peterschutt** [litestar-org/litestar#343]
Objective is to ensure that the examples in the docs do not become stale as the library evolves. 

Leveraging `pymdownx.snippets` mkdocs markdown extension allows us to move the examples into their own modules that can be tested alongside the rest of the test suite.

Plan:
- [x] create `examples/` directory
- [x] create `tests/examples/`
- [x] audit and create TODO list of each self contained example in docs
- [ ] transfer all examples to a self-contained module in `examples/` and include a test suite for each in `tests/examples`

For each example in the TODO list:
- [ ] create a module in `examples/` and transfer in the example code
- [ ] create a suite for the module in `tests/examples` that tests the facets of the example that it demonstrates
- [ ] replace the example in the docs with an external reference code block, e.g., 

````md
```py title="Tests a Thing"
--8<-- "examples/test_thing.py"
```
````

<a href="https://polar.sh/litestar-org/litestar/issues/343">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/343/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/343/pledge.svg">
</picture>
</a>

**Comment by Jarmos-san** [comment]
I think this is complete(?) in #1073, @provinzkraut can you clarify. Regardless, I think this issue can be closed because Janek had already implemented the script to run each examples in the documentations during the build process.

**Comment by provinzkraut** [comment]
> I think this issue can be closed because Janek had already implemented the script to run each examples in the documentations during the build process.

You’re mistaken there. Yes, we have a tool to execute run examples and record their results when building the docs but:

1. This is not a replacement for tests. Failures are not reported in the CI / testing process in general 
2. Most examples aren’t yet configured for this
