### ISSUE TITLE
Docs: Update security usage example by moving away from third party library 

### ISSUE THREAD

**Issue by JacobCoffee** [litestar-org/litestar#3443]
We'd have to handle the type coercion that case, but I think better to use either msgspec and `convert()` if we don't want to roll the type parsing ourselves, or dataclasses.

(I only say prefer msgspec over pydantic b/c its available without another dependency).

_Originally posted by @peterschutt in https://github.com/litestar-org/litestar/pull/3344#discussion_r1557281595_
            

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3443">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3443/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3443/pledge.svg">
</picture>
</a>

**Comment by cofin** [comment]
We've recently moved to a new JWT library and there's work on enhancing the JWT components now.  Let's re-open this with a more relevant issue if needed.

**Comment by provinzkraut** [comment]
> We'd have to handle the type coercion that case, but I think better to use either msgspec and convert() if we don't want to roll the type parsing ourselves, or dataclasses.

This has actually been implemented in #3692 :)
