### ISSUE TITLE
Docs: Update security usage examples to use SQLAlchemy v2 `mapped_column`

### ISSUE THREAD

**Issue by JacobCoffee** [litestar-org/litestar#3444]
should we use SQLA 2.x ``mapped_column`` so that we are consistent with the other examples where we use SQLA models?

_Originally posted by @Alc-Alc in https://github.com/litestar-org/litestar/pull/3344#discussion_r1556884991_
            

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3444">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3444/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3444/pledge.svg">
</picture>
</a>

**Comment by Alc-Alc** [comment]
Implemented in #3512
