### ISSUE TITLE
Bug: Litestar instance or factory not found

### ISSUE THREAD

**Issue by glickums** [litestar-org/litestar#3451]
Hi, every time I try to run litestar from vscode I get a "Could not find Litestar instance or factory"

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3451">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3451/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3451/pledge.svg">
</picture>
</a>

**Comment by JacobCoffee** [comment]
Can you provide an MCVE of your project structure? You can see *how* Litestar discovers things in https://docs.litestar.dev/latest/usage/cli.html#autodiscovery, and you error indicates those criteria are not met.
