### ISSUE TITLE
Bug: Multi-body response incompatible with LoggingMiddleware

### ISSUE THREAD

**Issue by keongalvin** [litestar-org/litestar#3477]
### Description

When using `ServerSentEvent` Responses with `StructlogPlugin`, the application errors. 

Preliminary research led me to https://github.com/litestar-org/litestar/blob/main/litestar/middleware/logging.py#L180, where `scope.state._ls_connection_state.log_context` does not have any values during second push of an `ServerSentEventMessage`. 

### MCVE

```python
from asyncio import sleep
from collections.abc import AsyncGenerator

from litestar import Litestar, get
from litestar.plugins.structlog import StructlogPlugin
from litestar.response import ServerSentEvent, ServerSentEventMessage
from litestar.types import SSEData


async def my_generator() -> AsyncGenerator[SSEData, None]:
    count = 0
    while count < 10:
        await sleep(0.01)
        count += 1
        yield ServerSentEventMessage(event="something-with-comment", retry=1000, comment="some comment")


@get(path="/count", sync_to_thread=False)
def sse_handler() -> ServerSentEvent:
    return ServerSentEvent(my_generator())


app = Litestar(route_handlers=[sse_handler],
               plugins=[StructlogPlugin()])
```

### Steps to reproduce

1. Run the server above

```bash
litestar --app main:app run
```

2. Send a request

```bash
 curl localhost:8000/count
```

3. Observe error

### Logs

```bash
File "/.venv/lib/python3.11/site-packages/litestar/middleware/logging.py", line 194, in extract_response_data
     connection_state.log_context.pop(HTTP_RESPONSE_START),
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'http.response.start'
```

### Litestar Version

2.8.3

### Platform

- [ ] Linux
- [X] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3477">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3477/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3477/pledge.svg">
</picture>
</a>

**Comment by peterschutt** [comment]
This generalizes down to a incompatibility between logging middleware and any multi-body response:

```py
from asyncio import sleep
from typing import AsyncGenerator

from litestar import get
from litestar.middleware.logging import LoggingMiddlewareConfig
from litestar.response import Stream
from litestar.testing import create_async_test_client


async def my_generator() -> AsyncGenerator[str, None]:
    count = 0
    while count < 10:
        await sleep(0.01)
        count += 1
        yield f"data: {count}\n"


@get(path="/count", sync_to_thread=False)
def sse_handler() -> Stream:
    return Stream(my_generator())


async def test_app() -> None:
    async with create_async_test_client(sse_handler, middleware=[LoggingMiddlewareConfig().middleware]) as client:
        response = await client.get("/count")
        assert response.status_code == 200
        assert (
            response.text
            == "data: 1\ndata: 2\ndata: 3\ndata: 4\ndata: 5\ndata: 6\ndata: 7\ndata: 8\ndata: 9\ndata: 10\n"
        )
```
