### ISSUE TITLE
Enhancement: Repository pattern interfaces

### ISSUE THREAD

**Issue by fkromer** [litestar-org/litestar#3495]
### Summary

It's common practice to provide generic interfaces for implementing the repository pattern. It makes sense to provide several interfaces for specific types of application designs. CrudRepository is suitable for abstracting persistence of CRUD models. More generic repository interfaces are required for domain driven designs (DDD) involving aggregates, entities (value objects persisted as part of entities). Data abstraction objects (DAOs) can be seen as simple variants of a repository pattern or as an own pattern category ([DAOs vs Repository](https://www.baeldung.com/java-dao-vs-repository#:~:text=DAO%20is%20an%20abstraction%20of,closer%20to%20the%20Domain%20objects)).

Examples:
- [Spring Data Repository](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/package-summary.html) / [usage reference](https://docs.spring.io/spring-data/data-commons/docs/1.6.1.RELEASE/reference/html/repositories.html)

### Drawbacks and Impact

Impacts:
- enables domain driven designs of different complexities

### Unresolved questions

- Should DAO patterns be considered separately from repository patterns?

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3495">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3495/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3495/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
This already exists :)

https://docs.litestar.dev/latest/usage/databases/sqlalchemy/models_and_repository

In fact, there's a whole repository dedicated to this (and more): https://github.com/litestar-org/advanced-alchemy
