### ISSUE TITLE
Bug: Enum OAS issues

### ISSUE THREAD

**Issue by wallseat** [litestar-org/litestar#3518]
### Description

I have two problems with how Enum declared in OAS.

1. When I create 3 different models with same enum, i find, that in always paste in schema As Is. There is not schema declared in components->schemas section of OAS.
It cause a problem with frontend, when they create bindings with code-gen tools. They need to handle this strings directly.
I think it is better to register Enum as objects in schemas and refer to them.

2. When you try to make an Enum field optional, instead of getting oneOf{null, schema{enum{...}} you get enum{..., null}, which is incorrect, i think. Because i'm not realy declared null as value of this enum.
This problem caused by the same logic as above.

I have code to fix it (we use it as monkey-patch in our project), so if we confirm that this is a problem, i'll provide PR.

### MCVE

```python
from enum import StrEnum

from litestar import Litestar, get
from litestar.openapi import OpenAPIConfig
from litestar.openapi.plugins import JsonRenderPlugin
from pydantic import BaseModel, Field


class TestEnum(StrEnum):
    """ "Description!"""

    ONE = "one"
    TWO = "two"


class TestSchemaA(BaseModel):
    enum_field: TestEnum | None = Field(default=None)
    other_filed: int | None = Field(default=None)


class TestSchemaB(BaseModel):
    enum_field: TestEnum
    other_field: int


@get("/a")
async def test_routerA() -> TestSchemaA:
    return TestSchemaA(enum_field=TestEnum.ONE)


@get("/b")
async def test_routerB() -> TestSchemaB:
    return TestSchemaB(enum_field=TestEnum.TWO)


app = Litestar(
    route_handlers=[test_routerA, test_routerB],
    openapi_config=OpenAPIConfig(
        path="/docs",
        title="Test Api",
        version="0.1.0",
        render_plugins=[JsonRenderPlugin()],
    ),
)
```

### Result schema

```
{
  "info": {
    "title": "Test Api",
    "version": "0.1.0"
  },
  "openapi": "3.1.0",
  "servers": [
    {
      "url": "/"
    }
  ],
  "paths": {
    "/a": {
      "get": {
        "summary": "TestRoutera",
        "operationId": "ATestRoutera",
        "responses": {
          "200": {
            "description": "Request fulfilled, document follows",
            "headers": {

            },
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TestSchemaA"
                }
              }
            }
          }
        },
        "deprecated": false
      }
    },
    "/b": {
      "get": {
        "summary": "TestRouterb",
        "operationId": "BTestRouterb",
        "responses": {
          "200": {
            "description": "Request fulfilled, document follows",
            "headers": {

            },
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/TestSchemaB"
                }
              }
            }
          }
        },
        "deprecated": false
      }
    }
  },
  "components": {
    "schemas": {
      "TestSchemaA": {
        "properties": {
          "enum_field": {
            "type": [
              "null",
              "string"
            ],
            "enum": [
              "one",
              "two",
              null]
          },
          "other_filed": {
            "oneOf": [
              {
                "type": "null"
              },
              {
                "type": "integer"
              }
            ]
          }
        },
        "type": "object",
        "required": [],
        "title": "TestSchemaA"
      },
      "TestSchemaB": {
        "properties": {
          "enum_field": {
            "type": "string",
            "enum": [
              "one",
              "two"
            ]
          },
          "other_field": {
            "type": "integer"
          }
        },
        "type": "object",
        "required": [
          "enum_field",
          "other_field"
        ],
        "title": "TestSchemaB"
      }
    }
  }
}
```

### Litestar Version

2.8.2

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3518">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3518/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3518/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
@wallseat Your suggestions sound reasonable, feel free to submit a PR with the proposed changes :)
