### ISSUE TITLE
Enhancement: email service provider integration

### ISSUE THREAD

**Issue by fkromer** [litestar-org/litestar#3520]
### Summary

In the Django world https://github.com/anymail/django-anymail is the kind of de-facto standard for integrating email service providers via a unified API. It would be nice to have an equivalent functionality in Litestar for the fullstack use case.

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3520">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3520/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3520/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
I don't think that this is something that makes sense to have, as there's virtually zero framework integration necessary. Could you elaborate what features that are specific to Litestar would be useful here? The way I see it, there's nothing from preventing a 3rd party ESP library to work inside a Litestar app just like it would anywhere else.

**Comment by provinzkraut** [comment]
I agree that this would be useful, but I still don't see why this unified API has to be Litestar specific?
