### ISSUE TITLE
Patching of click in rich-click via litestar cli breaks Typer cli apps

### ISSUE THREAD

**Issue by scott2b** [litestar-org/litestar#3534]
### Description

I assume this may have similar impact on attempts to use click, but I am using Typer so that is what I have proven out here.

When attempting to use Typer to build cli tools in the general context of building a Litestar application, Typer loses its ability to properly report help messages on commands. This appears to be due to the patching of click in rich-click via litestar/cli/__init__.py. Because of imports in both Litestar and Advanced Alchemy that result in this patching, I am unable to integrate Typer code into a larger platform that includes shared code between command line and web application utilities. I am unsure but would expect similar issues with attempting to use click directly or any other library built on click.

For what it's worth, actual execution of the Typer commands still works from what I have seen, so the commands appear to be getting registered, they just don't show up in the help output.

### MCVE

```python
# examples of imports that break typer's help:
import litestar.cli
from litestar.contrib.sqlalchemy.plugins import AsyncSessionConfig

import typer

app = typer.Typer()

@app.command()
def main(arg1: str = "default1", arg2: int = 0):
    print(f"Running main with arg1={arg1} and arg2={arg2}")

@app.command()
def another(arg1: str = "default1", arg2: int = 0):
    print(f"Running pipeline with arg1={arg1} and arg2={arg2}")

if __name__ == "__main__":
    app()
```

### Steps to reproduce

```bash
1. To run:


pip install typer
pip install litestar

python -m mcve --help

# alternatively:
python mcve.py --help
```

The expectation is that typer will provide command help for `main` and `another` (shown
as a list of commands in the "Commands section) but the help messages do not show.

2. The workaround:

```
pip uninstall rich-click
python -m mcve --help
```

Help messages now show. My working assumption is that the issue is caused by the
patching of click that occurs in rich-click via litestar/cli/__init__.py, which is not executed if rich-click is not installed.

### Litestar Version

2.8.3

### Platform

- [ ] Linux
- [X] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3534">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3534/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3534/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
I agree that we shouldn't just monkey-patch things out of the box.

I'm curious however what your use case is that involves making use of the Litestar CLI and typer simultaneously?

**Comment by scott2b** [comment]
I am not using LItestar CLI, other than my assumption that it is perhaps used for the litestar command itself. I typically use a mix of Typer, argparse, and sometimes Click for building out command line tools such as administrative utilities, backend processing, etc.

It is not so much that I am using them "simultaneously", i.e. Litestar would typically run in its own runtime environment from whatever utilities and processes I have. The issue is more that they share the same code. The ORM code is a particularly strong case in point, although I don't really expect that to be the only conflict. In my case however, it does seem that orm code is directly implicated: I ran into this issue trying to build a typer-based utility and traced the issue's source through interdependencies between Litestar itself and advanced-alchemy. Even if you are not using Litestar CLI directly, indirect imports will cause the patch to happen. At least I have found this to be the case when advanced-alchemy is being used. I have not yet tried to isolate this issue in a codebase that does not utilize advanced-alchemy.

**Comment by scott2b** [comment]
Ok, looking back at the code I provided, and digging through my history of chasing this down, I see the point you are making. I do not have any examples of imports from Litestar proper that cause this problem other than the one above of directly importing litestar.cli. In this sense, I see your point about them being simultaneous.

However, if you install litestar[sqlalchemy] and make just about any import from advanced-alchemy, the issue will show itself. This happens due to a number of interdependent imports within advanced-alchemy that result in the cli module being loaded and the implicit patch executed.

So, yes, depending on your perspective, you might consider this to be more of an advanced-alchemy issue than a Litestar issue. I suppose it comes down to whether or not any other similar implicit imports might happen within Litestar per se, and/or whether general click interoperability is something you see as a priority.
