### ISSUE TITLE
Enhancement: Support configuring Pydantic's `.model_validate(..., strict=True`)

### ISSUE THREAD

**Issue by Anu-cool-007** [litestar-org/litestar#3572]
### Description

Any usage of Strict types has no effect on model validation in Litestar. This is due to the explicit strict=Fasle usage in the pydantic v2's validation method.

### URL to code causing the issue

https://github.com/litestar-org/litestar/blob/65f01ea8ed1162c564b552d637c47dc4220d1cb9/litestar/contrib/pydantic/pydantic_init_plugin.py#L51

### MCVE

```python
from litestar import Litestar, get
from pydantic import BaseModel, StrictBool


class TestModel(BaseModel):
  test_bool: StrictBool


@post("/")
async def test_strict_model(data: TestModel) -> str:
 return "Hello, world!"


app = Litestar([hello_world])
```

### Steps to reproduce

```bash
1. Run the attached MCVE
2. Send a POST req to the server with the following data

{
  "test_bool" : "YES"
}

3. You will receive a success response instead of an error.
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Litestar Version

2.9.0
But this is a day 0 bug with Pydantic v2 support afiak.

### Platform

- [ ] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3572">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3572/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3572/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
Hey @Anu-cool-007, thanks for reporting this! 

Although not really a bug, it makes sense to make this configurable on the Plugin. I've converted it into a feature request :)

**Comment by provinzkraut** [comment]
Hey @Anu-cool-007, I've created #3573, which should address this.

With that, you can do this to get the behaviour you want:

```python
from litestar import Litestar, get
from litestar.contrib.pydantic import PydanticInitPlugin
from pydantic import BaseModel, StrictBool


class TestModel(BaseModel):
  test_bool: StrictBool


@post("/")
async def test_strict_model(data: TestModel) -> str:
 return "Hello, world!"


app = Litestar(
    [hello_world],
    plugins=[PydanticInitPlugin(validate_strict=True)]
)
```
