### ISSUE TITLE
Bug: openapi spec. generation does not respect Response status_code

### ISSUE THREAD

**Issue by TheZwieback** [litestar-org/litestar#3576]
### Description

When changing the status_code in a Response object for a handler the status_code used in generation stays the default one.
Looks like the Response object status_code field is not used in generation of the openapi.json
See screenshot:
<img width="1210" alt="image" src="https://github.com/litestar-org/litestar/assets/29406476/9fbb9549-50ff-4c74-9578-4dbf1fcbe1ea">

### MCVE

```python
from litestar import Litestar, post, Response
from litestar.status_codes import HTTP_200_OK


@post("/test")
async def test() -> Response[dict[str, str]]:
    return Response(
        {"detail": "Test succesfull"},
        status_code=HTTP_200_OK,
    )


app = Litestar(route_handlers=[test])
```

### Steps to reproduce

```bash
1. Start the app
2. Use your favorite openapi renderer
3. Execute the endpoint, returned status is 200, status in rendered openapi is 201.
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Litestar Version

2.9.0

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3576">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3576/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3576/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
@TheZwieback as @Alc-Alc, this is not really a bug. Litestar does not know what you're doing inside your functions, so you'll have to tell it.

You can set the status code on the handler like so

```python

@post("/test", status_code=HTTP_200_OK)
async def test() -> Response[dict[str, str]]:
    return Response(
        {"detail": "Test succesfull"},
        status_code=HTTP_200_OK,
    )
```
which should do what you're looking for.
