### ISSUE TITLE
Docs: bad links in flask migration docs

### ISSUE THREAD

**Issue by JacobCoffee** [litestar-org/litestar#3587]
### Summary

https://docs.litestar.dev/latest/migration/flask.html

<img width="936" alt="image" src="https://github.com/litestar-org/litestar/assets/45884264/e0b452be-8b6e-4b0f-96e1-6c66a81322a3">

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3587">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3587/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3587/pledge.svg">
</picture>
</a>

**Comment by l-armstrong** [comment]
I'm looking to take on this issue. I do have a question. 
Is it that the document should not have something like:`Body <usage/4-request-data/#specifying-a-content-type>`_? 

and should instead render something of the form `request.get_json`, `request.headers`, etc. ?

**Comment by JacobCoffee** [comment]
Those links inside `<...>` have changed or something - So finding where they are supposed to be will just be a bit of digging. like the first one,
```
request.files
Use `UploadFile <usage/4-request-data/#file-uploads>`_
```
Should probably be pointing to https://docs.litestar.dev/2/usage/requests.html#file-uploads which would be something like ```UploadFile <usage/requests/file-uploads>`_``` instead, and the same for the others:
```
request.form
request.form(), prefer `Body <usage/4-request-data/#specifying-a-content-type>`_

request.get_json
request.json(), prefer the `data keyword argument <usage/4-request-data/#request-body>`_
```
