### ISSUE TITLE
Bug: docs website is not up-to-date

### ISSUE THREAD

**Issue by jderrien** [litestar-org/litestar#3600]
### Description

Hello,

It seems the official documentation website is not properly updated on project releases.

https://docs.litestar.dev/2/usage/logging.html (not up-to-date)
https://docs.litestar.dev/main/usage/logging.html (this one is up-to-date)

(It's not a browser caching issue)

### Litestar Version

latest

### Platform

- [ ] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3600">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3600/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3600/pledge.svg">
</picture>
</a>

**Comment by JacobCoffee** [comment]
Thanks for the report! Confused by this since the release docs CI for 2.9.0 and 2.9.1 ran without failure...

**Comment by provinzkraut** [comment]
@JacobCoffee Actually, if you look at the run here, there's some weirdness that's usually not there: https://github.com/litestar-org/litestar/actions/runs/9618212425/job/26531615932#step:7:118

**Comment by JacobCoffee** [comment]
oh :(

**Comment by Alc-Alc** [comment]
I think the new release "fixed" this, @jderrien can you confirm?

**Comment by jderrien** [comment]
@Alc-Alc At least, https://docs.litestar.dev/2/usage/logging.html is up-to-date 👍

**Comment by Alc-Alc** [comment]
Thanks @jderrien.

Closing this, can be reopened if anyone points out a discrepancy.
