### ISSUE TITLE
Enhancement: Allow parameter of type `Iterable` to be processed as  `list`

### ISSUE THREAD

**Issue by rafalkrupinski** [litestar-org/litestar#3631]
### Description

Litestar doesn't think it should process `Iterable` parameter as an array.

The original [discussion](https://discord.com/channels/919193495116337154/1260559977081471058) was about default parameter value, but the problem is actually with how litestar handles `Iterable` itself

### URL to code causing the issue

https://github.com/litestar-org/litestar/blob/8c4c15bb501879dabaecfbf0af541ac571c08cf3/litestar/_kwargs/parameter_definition.py#L67C9-L67C60

### MCVE

```python
@get('/sequence')
async def sequence(foo: Sequence[str]) -> Sequence[str]:
    return foo

@get('/iterable')
async def iterable(foo: Iterable[str]) -> Iterable[str]:
    return foo

app = Litestar(
    route_handlers=(
        sequence,
        iterable,
    )
)
```

### Steps to reproduce

```bash
$ curl  'localhost:8000/sequence?foo=s1&foo=s2'
["s1","s2"]

$ curl 'localhost:8000/iterable?foo=s1&foo=s2'
s2
```

### Litestar Version

2.9.1

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3631">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3631/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3631/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
Other than a theoretical, can you explain what use case this allows that's currently not possible?

Litestar will only ever provide parameters as concrete types, i.e. will always pass a  `list[str]`, never a `Sequence[str]`, so I'm not sure what the benefit of allowing such annotations is, aside from catering to individual style preferences.

I'm asking because it is very much intentional to be restrictive about the typing, so as long as there's no functionality to be gained here, I'm wary of accepting such a feature request.

**Comment by rafalkrupinski** [comment]
Currently Set, Sequence and possibly other types are accepted as parameter types, so it's unintuitive for me as a user, that litestar doesn'tt accept Iterable. The change is for ergonomics.

For example you don't want to do this, even if it worked with litestar, it's a mutable default parameter value.
```py
param: list[str] = []
```

This works but has different semantics and generates different OpenAPI schema, and you need to handle None value manually, and you need another variable or assert to please mypy.

```py
param: list[str]|None=None
```

you can do
```py
param: Sequence[str]=()
```
but currently this fails
```py
param: Iterable[str]=()
```
It's unintuitive that one abstract type works and another doesn't.

**Comment by provinzkraut** [comment]
Thanks for the explanation @rafalkrupinski, that seems reasonable!
