### ISSUE TITLE
Docs: status_code for handlers is incorrect

### ISSUE THREAD

**Issue by ptallada** [litestar-org/litestar#3636]
### Summary

Documentation for handler states: 

* status_code: An http status code for the response. Defaults to ``200`` for mixed method or ``GET``, ``PUT`` and
                ``PATCH``, ``201`` for ``POST`` and ``204`` for ``DELETE``.

However, the code is implemented as:

```python
def get_default_status_code(http_methods: set[Method]) -> int:
    """Return the default status code for a given set of HTTP methods.

    Args:
        http_methods: A set of method strings

    Returns:
        A status code
    """
    if HttpMethod.POST in http_methods:
        return HTTP_201_CREATED
    if HttpMethod.DELETE in http_methods:
        return HTTP_204_NO_CONTENT
    return HTTP_200_OK
```

So a route like the following will return 201 instead of 200, contradicting the documentation.

```python
@route(path="/foo", http_method=[HttpMethod.GET, HttpMethod.POST])
```

Should be something like:

```python
def get_default_status_code(http_methods: set[Method]) -> int:
    """Return the default status code for a given set of HTTP methods.

    Args:
        http_methods: A set of method strings

    Returns:
        A status code
    """
    if len(http_methods) > 1:
        return HTTP_200_OK
    if HttpMethod.POST in http_methods:
        return HTTP_201_CREATED
    if HttpMethod.DELETE in http_methods:
        return HTTP_204_NO_CONTENT
    return HTTP_200_OK
```

Cheers,

Pau.

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3636">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3636/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3636/pledge.svg">
</picture>
</a>

**Comment by FarhanAliRaza** [comment]
Hello, I want to contribute to this issue. Is it a documentation issue? These quotes words are from the basy.py file in http_handlers. I can not understand what the fix will involve.

**Comment by provinzkraut** [comment]
Yes, the documentation is incorrect. The fix would consist of correcting the documentation, such that it accurately reflects the actual behaviour.

**Comment by FarhanAliRaza** [comment]
It would be great help if a link is provided to part of documentation where the change is needed .
I could not found that part of the code .

**Comment by provinzkraut** [comment]
It's in the docstrings of the HTTP route handlers themselves
