### ISSUE TITLE
Enhancement: Get api endpoint description from a docstring

### ISSUE THREAD

**Issue by Rey092** [litestar-org/litestar#3658]
### Summary

Litestar already makes the endpoint 'summary' from the function name. Why not use the endpoint docstring as the description by default if the user did not provide it through the decorator?

### Basic Example

```
@get("/")
async def foo(self) -> str:
    """That does nothing."""
    return "hello world"
```
No description

```
@get("/", description="Only that works")
async def boo(self) -> str:
    """That does nothing."""
    return "hello world"
```
Description 'Only that works'

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3658">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3658/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3658/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
You can already do this by setting [`use_handler_docstrings=True`](https://docs.litestar.dev/latest/reference/openapi/openapi.html#litestar.openapi.OpenAPIConfig.use_handler_docstrings) in the `OpenAPIConfig`.
