### ISSUE TITLE
Bug: OpenTelemetry Middleware Doesn't Capture Exceptions Raised Before Route Handler

### ISSUE THREAD

**Issue by abelkm99** [litestar-org/litestar#3663]
### Description

Recently, I integrated OpenTelemetry into my backend to improve observability. However, I've noticed a specific issue where exceptions raised before the route handler is hit aren't being logged under the current request span. This results in incomplete tracing, making it difficult to capture the full context of request lifecycles, which is crucial for accurate monitoring and debugging.

### MCVE

```python
# Your MCVE code here
```

### Steps to reproduce

```bash
1. Set up a LiteStar application with an OpenTelemetry middleware and another middleware that can raise an exception, such as a JWT middleware.
2. send request to an unknown url by the app.
3. Observe that the request span is not created.
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](https://files.slack.com/files-tmb/T046DJBFEMD-F07HBK3F4TA-38f4387909/image_720.png)"
```

### Logs

```bash
Traceback (most recent call last):
  File "/Users/bella/Documents/python/litestar_backend/.venv/lib/python3.12/site-packages/litestar/_asgi/routing_trie/traversal.py", line 157, in parse_path_to_route
    node, path_parameters, path = traverse_route_map(
                                  ^^^^^^^^^^^^^^^^^^^
  File "/Users/bella/Documents/python/litestar_backend/.venv/lib/python3.12/site-packages/litestar/_asgi/routing_trie/traversal.py", line 54, in traverse_route_map
    raise NotFoundException()
litestar.exceptions.http_exceptions.NotFoundException: 404: Not Found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/bella/Documents/python/litestar_backend/.venv/lib/python3.12/site-packages/litestar/middleware/_internal/exceptions/middleware.py", line 159, in __call__
    await self.app(scope, receive, capture_response_started)
  File "/Users/bella/Documents/python/litestar_backend/.venv/lib/python3.12/site-packages/litestar/_asgi/asgi_router.py", line 90, in __call__
    asgi_app, route_handler, scope["path"], scope["path_params"] = self.handle_routing(
                                                                   ^^^^^^^^^^^^^^^^^^^^
  File "/Users/bella/Documents/python/litestar_backend/.venv/lib/python3.12/site-packages/litestar/_asgi/asgi_router.py", line 112, in handle_routing
    return parse_path_to_route(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/bella/Documents/python/litestar_backend/.venv/lib/python3.12/site-packages/litestar/_asgi/routing_trie/traversal.py", line 174, in parse_path_to_route
    raise NotFoundException() from e
litestar.exceptions.http_exceptions.NotFoundException: 404: Not Found
```

### Litestar Version

litestar 2.10.0

### Platform

- [X] Linux
- [X] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3663">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3663/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3663/pledge.svg">
</picture>
</a>

**Comment by abelkm99** [comment]
### Issue with Exception Handling in Middleware Chain

So, I've been digging into how LiteStar processes requests and handles spans across various middleware layers. Here's a quick rundown of the flow:

1. **Initial ExceptionHandler Middleware**
2. **ASGI Router**
3. **Middleware 1**
4. **Middleware 2**
5. **Middleware n (e.g., JWT Middleware)**
6. **OpenTelemetry Middleware (n+1)**
7. **Second ExceptionHandler Middleware**
8. **HTTP Route Handler**

### Problem

We're running into an issue with OpenTelemetry and how exceptions are logged across this chain.

**Case 1:**  
If something blows up in the route handler, the second `ExceptionHandler Middleware` catches it, and everything is logged correctly within the span. This works as expected.

**Case 2:**  
But if an exception is thrown earlier, like in the `JWT Middleware`, before `OpenTelemetry Middleware` gets involved, there's no span started yet. So, while the exception does get logged, it's not tied to the current request's span in tracing tools like Jaeger or Logfire. This messes with our trace view since the span doesn't capture the full picture of what's happening.

We need to figure out how to make sure exceptions are correctly logged under the appropriate span, even if they happen early in the middleware chain.

I have think we can simply solve this by changing the order to ExceptionHandler -> OtelMiddlware -> ExceptionHandler -> ASGI Router -> .......
I will try to create a PR to solve the issue.

**Comment by abelkm99** [comment]
This issue is resolved on the PR #3689 
Thank you litestart team for the resolving it.

**Comment by provinzkraut** [comment]
Let's keep this open until #3663 is merged :)

**Comment by abelkm99** [comment]
oh Sure I thought it's already merged.
