### ISSUE TITLE
Bug: handler kwargs name affect request validator

### ISSUE THREAD

**Issue by trim21** [litestar-org/litestar#3672]
### Description

I have a handle try to use `body` as handle kwargs, but it failed to decode object, throw a error 

```json
{"status_code":400,"detail":"Validation failed for POST /not-work","extra":[{"message":"Expected `object`, got `bytes`","key":"body"}]}
```

But it works if I don't name it as `body`.

### MCVE

```python
import asyncio
from dataclasses import dataclass
from typing import Annotated, Any

import httpx
from litestar import Litestar, post
from litestar.enums import RequestEncodingType
from litestar.params import Body


@dataclass
class User:
    id: int
    name: str


@post(path="/work", status_code=200)
async def work(
    data: Annotated[User, Body(media_type=RequestEncodingType.URL_ENCODED)],
) -> Any:
    return data


@post(path="/not-work")
async def not_work(
    body: Annotated[User, Body(media_type=RequestEncodingType.URL_ENCODED)],
) -> Any:
    return body


app = Litestar(route_handlers=[work, not_work])


async def main():
    async with httpx.AsyncClient(transport=httpx.ASGITransport(app=app)) as client:
        r = await client.post("http://example.com/work", data={"id": 1, "name": "nn"})
        assert r.status_code == 200

        r = await client.post("http://example.com/not-work", data={"id": 1, "name": "nn"})
        assert r.status_code == 400


asyncio.run(main())
```

### Steps to reproduce

```bash
use litestar 2.10.0 and run code
```

### Litestar Version

2.10.0

### Platform

- [ ] Linux
- [ ] Mac
- [X] Windows
- [X] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3672">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3672/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3672/pledge.svg">
</picture>
</a>

**Comment by Alc-Alc** [comment]
As stated [here](https://docs.litestar.dev/2/usage/requests.html#request-body)

> The body of HTTP requests can be accessed using the special `data` parameter in a handler function.

You must always use the name `data` to access the *validated* requested body (not raw request body).

`body` is also a ["reserved keyword argument"](https://docs.litestar.dev/2/usage/routing/handlers.html#reserved-keyword-arguments).

> the raw request body. Available only for HTTP route handlers

`body` is `bytes`, this is the raw request body. As it's a reserved kwarg, Litestar knows that parameter `body` must be sent `bytes`, but you have annotated it as being a struct `User` and hence this fails the serialization process.

If you want to access raw data (as bytes), use 

```py
@post(path="/not-work")
async def not_work(body: bytes) -> Any:
```

If you want to access the validated form data, use what you already have in the route `work`.

With this context, I do not think this is a bug.

**Comment by trim21** [comment]
thanks

**Comment by trim21** [comment]
as a suggestion, this should throw a error on init time, not as http response

**Comment by Alc-Alc** [comment]
> as a suggestion, this should throw a error on application init time or on router definition time, not as http response

@litestar-org/maintainers wdyt?

**Comment by provinzkraut** [comment]
> > as a suggestion, this should throw a error on application init time or on router definition time, not as http response
> 
> @litestar-org/maintainers wdyt?

Yeah, we should check the annotation at least. We do this with several others aleady
