### ISSUE TITLE
Bug: `request.session` may be Empty but it typed as `dict[str, Any]`

### ISSUE THREAD

**Issue by trim21** [litestar-org/litestar#3676]
### Description

`request.session` is typed as `dict[str, Any]`, but in some case it's `Empty`.

And even worse, `bool(Empty)` is True which means `request.session` is truthy if it's `Empty`.

So a code snippet like this will got suprise:

```python
    if not request.session:
        back_to = "/"
    else:
        back_to = request.session.get("backTo", "/") # goes here if request.session is Empty
```

### MCVE

```python
# Your MCVE code here
```

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Litestar Version

2.10.0

### Platform

- [ ] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3676">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3676/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3676/pledge.svg">
</picture>
</a>

**Comment by cofin** [comment]
I've encountered this as well, but not totally tracked it down.  I usually see it when the session has expired, no longer exists, or on a brand new connection on an open endpoint.

**Comment by cofin** [comment]
@trim21 which session backend are you using?  I have seen it with the Redis backend.

**Comment by trim21** [comment]
> @trim21 which session backend are you using? I have seen it with the Redis backend.

Redis

**Comment by trim21** [comment]
Also I encounter this in a new connection

**Comment by trim21** [comment]
Ok, I know why.

I copy some code from `litestar.security.session_auth.SessionAuthMiddleware`, with `connection.scope["session"] = Empty` . So my own code cause this problem.
