### ISSUE TITLE
Enhancement: Switch to official msgpack media type

### ISSUE THREAD

**Issue by agronholm** [litestar-org/litestar#3727]
### Summary

As of May 2024, msgpack has an officially registered IANA media type: `application/vnd.msgpack`. Litestar should switch to using that in msgpack responses (and accepting it in request bodies), probably in v3.0, as changing the response media type is a breaking change.

Reference: https://www.iana.org/assignments/media-types/application/vnd.msgpack

### Drawbacks and Impact

It would be great to also accept the old media type in requests but only output the new one.

### Unresolved questions

It's not obvious to me how to accept two different media types as msgpack data.

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3727">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3727/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3727/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
Completed in #3732.
