### ISSUE TITLE
Enhancement: after_startup and after_shutdown hook

### ISSUE THREAD

**Issue by m3nowak** [litestar-org/litestar#3730]
### Summary

Issue #2375 mentions, that after_startup and after_shutdown hooks have been removed. However, it is a feature, which I need.
Right now, I'm developing a service for receiving web hooks. After application start, I need to inform remote service, that my server started accepting requests.

### Basic Example

```python
app = Litestar(
    [index],
    after_startup=[lambda: print("Application started up!")]
)
```

### Unresolved questions

My current workaround is running desired function after `asyncio.sleep` together with ASGI server in `asyncio.gather`. Is there a better alternative?

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3730">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3730/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3730/pledge.svg">
</picture>
</a>

**Comment by Alc-Alc** [comment]
Will [lifespan](https://docs.litestar.dev/latest/usage/applications.html#lifespan-context-managers) work for your use case?

**Comment by provinzkraut** [comment]
See discussions in #3598 and #3597.

Closing as duplicate.

@Alc-Alc is correct, using lifespan is the way to go here.
