### ISSUE TITLE
Enhancement: local state for websocket listeners

### ISSUE THREAD

**Issue by olzhasar** [litestar-org/litestar#3764]
### Summary

There seems to be no way to have a state that is unique to a particular websocket connection. Or maybe it's possible, but it's not documented?

### Basic Example

Consider the following example:

```
class Listener(WebsocketListener):
    path = "/ws"

    def on_accept(self, socket: WebSocket, state: State):
        state.user_id = str(uuid.uuid4())

    def on_receive(self, data: str, state: State):
        logger.info("Received: %s", data)
        return state.user_id
```

Here, I expect a different `user_id` for each connection, but it turns out to not be the case:

```
def test_listener(app: Litestar):
    client_1 = TestClient(app)
    client_2 = TestClient(app)

    with (
        client_1.websocket_connect("/ws") as ws_1,
        client_2.websocket_connect("/ws") as ws_2,
    ):
        ws_1.send_text("Hello")
        ws_2.send_text("Hello")

        assert ws_1.receive_text() != ws_2.receive_text()  # FAILS
```

I figured that there is a way to define a custom `Websocket` class which seems to be bound to a particular connection, but if that's the only way, should it be that hard for such a common use case?

UPDATE:
`WebSocketScope` contains it's own state dict, and it's unique to each connection. So my suggestion is to resolve the `state` dependency corresponding to the scope in that case.

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3764">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3764/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3764/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
Since `WebSocket` inherits from `ASGIConnection`, you have access to its `state`, just like with any other connection.

https://docs.litestar.dev/latest/reference/connection.html#litestar.connection.ASGIConnection.state

Using it, your example would look like this:

```python
class Listener(WebsocketListener):
    path = "/ws"

    def on_accept(self, socket: WebSocket):
        socket.state.user_id = str(uuid.uuid4())

    def on_receive(self, data: str):
        logger.info("Received: %s", data)
        return socket.state.user_id
```

**Comment by olzhasar** [comment]
In that case, I would suggest to at least include a similar example to the Websockets section of the documentation.
Tbh, it feels confusing when the state dependency is being resolved, but it's shared between connections.

**Comment by provinzkraut** [comment]
The behaviour of the `state` is documented [here](https://docs.litestar.dev/latest/usage/routing/handlers.html#reserved-keyword-arguments), which describes it as "application state". If there's some place in the documentation that describes it otherwise, let me know where so we can fix that :)

**Comment by olzhasar** [comment]
You might be right, but that wasn't my point.
I just started familiarizing myself with the framework, and didn't have a chance to go through the whole documentation yet.
I was following the example provided [here](https://docs.litestar.dev/latest/usage/websockets.html#class-based-websocket-handling) and ran into an issue.
For me it wasn't clear right away that the `WebsocketListener` is basically just a wrapper around the `Handler` and I should be looking at the handler's documentation. All I'm saying is that a local state that is tied to a connection seems to be a common use case, and a relevant example in the [Websockets section](https://docs.litestar.dev/latest/usage/websockets.html#) would be neat to have.
If you feel like users should figure such things on their own, that's okay with me.
