### ISSUE TITLE
Bug: Inablity to select same value multiple times for a list of Enum parameter in get request

### ISSUE THREAD

**Issue by abhishek-compro** [litestar-org/litestar#3769]
### Description

I want to be able to select the same option multiple times in the array of Enum type but I am unable to do so as shown in the screenshot.

![Screenshot_20240930_223350](https://github.com/user-attachments/assets/d79cc483-486e-498c-a49d-e01b06c228ec)

### MCVE

```python
from enum import Enum

from litestar import Litestar, get

class A(Enum):
    x = "x"
    y = "y"
    z = "z"

@get("/")
def select_multiple_enums(a_list: list[A]) -> list[A]:
    return a_list

app = Litestar(route_handlers=[select_multiple_enums])
```

### Steps to reproduce

```bash
1. Write the above code in a file called `app.py`
2. Run it using `litestar run -dr`
```

### Litestar Version

litestar==2.12.1

### Platform

- [X] Linux
- [ ] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3769">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3769/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3769/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
This is not a bug in Litestar but a limitation of Swagger: https://github.com/swagger-api/swagger-ui/issues/8583
