### ISSUE TITLE
Docs: pypi.org description leading to a 404 error

### ISSUE THREAD

**Issue by romuald** [litestar-org/litestar#3773]
### Summary

Hello

New to using the project, I found out that the pypi home for litlestar currently links to a 404

URL: https://pypi.org/project/litestar/
The "Example Applications" section's first item points to [litestar-pg-redis-docker](https://github.com/litestar-org/litestar-pg-redis-docker), which is currently showing a 404 error

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3773">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3773/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3773/pledge.svg">
</picture>
</a>

**Comment by Alc-Alc** [comment]
Heya @romuald, thanks for the callout. The repo you linked has not updated for a long time and thus is no longer an ideal example that utilizes the full extent of Litestar.

If you are willing, we would accept a PR that removes the reference to this repo.

You can make the change in the following file, which I believe will be reflected in PyPi in the next release🙂.

https://github.com/litestar-org/litestar/blob/4894593fc03a440bfb6b6fb8df8571466afc54b3/README.md?plain=1#L109-L111

In the mean time, if you need a reference repo, [here are few.](https://docs.litestar.dev/latest/#example-applications)
