### ISSUE TITLE
Enhancement: drop 3.8, since it is EOL since 3.13 release

### ISSUE THREAD

**Issue by sobolevn** [litestar-org/litestar#3793]
### Summary

Python 3.8 is EOL: https://devguide.python.org/versions/

Dropping 3.8 will allow us to:
- [ ] Drop python3.8 examples
- [ ] Dropping `List` / `Optional` / etc usage
- [ ] Require one less version in CI

What do others think? 
If you agree, I would like to send a PR :)

**Comment by euri10** [comment]
I remember this : https://discord.com/channels/919193495116337154/919193495690936353/1293567310510162061
Dont remember the specifics though

**Comment by provinzkraut** [comment]
We'll continue supporting 3.8 for a while, since we have users that depend on it, and it's a relatively small effort to do so.
