### ISSUE TITLE
Bug: Missing WebSocket Connection State Validation on Close and Message Send Operations

### ISSUE THREAD

**Issue by ashm-dev** [litestar-org/litestar#3848]
### Description

The current WebSocket implementation in Litestar lacks connection state validation for critical operations. When attempting to close a connection, there is no check to verify if the connection has already been closed. Similarly, when sending messages, the implementation doesn't validate whether the connection is still active before attempting transmission. This can lead to attempts to perform operations on closed connections and potential application errors.

**This is especially noticeable under heavy loads**

### MCVE

```python
# Your MCVE code here
```

### Steps to reproduce

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Litestar Version

latest
v2.12

### Platform

- [X] Linux
- [x] Mac
- [X] Windows
- [X] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3848">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3848/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3848/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
For closing this is true, but for sending we actually check it. https://github.com/litestar-org/litestar/blob/06ce3a058e7c10b511cf342ee5b281c1c4d890d6/litestar/connection/websocket.py#L98

Can you provide an example that allows sending on a closed connection?
