### ISSUE TITLE
Bug: Sentry SDK Integration breaks JWT Authentication

### ISSUE THREAD

**Issue by bpereto** [litestar-org/litestar#3853]
### Description

JWTCookieAuthentication breaks if the sentry integration is used after an exception due to tampered headers.

https://github.com/litestar-org/litestar/blob/f00f87d9efe86544061a82ad9a6fe628f65ec144/litestar/security/jwt/middleware.py#L254

Exception: `AttributeError: 'AnnotatedValue' object has no attribute 'partition'`

The `AnnotatedValue` seems to be `sentry_sdk.utils.AnnotatedValue` (https://github.com/getsentry/sentry-python/blob/200d0cdde8eed2caa89b91db8b17baabe983d2de/sentry_sdk/utils.py#L405).

An exception probably let's sentry tamper the header values which then gets replaced by the "AnnotatedValue" type of sentry. this breaks the token parsing.

### URL to code causing the issue

https://github.com/litestar-org/litestar/blob/f00f87d9efe86544061a82ad9a6fe628f65ec144/litestar/security/jwt/middleware.py#L254

### MCVE

```python
# Your MCVE code here
```

### Steps to reproduce

```bash
1. Enable Sentry Integration
2. Authenticated request to an exception
2. ` await middleware(request.app).authenticate_request(connection=request)`
```

### Screenshots

```bash
"![SCREENSHOT_DESCRIPTION](SCREENSHOT_LINK.png)"
```

### Litestar Version

2.12.1

### Platform

- [ ] Linux
- [X] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3853">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3853/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3853/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
Hey @bpereto, thanks for reporting this! I think this is a bug in the Sentry Litestar integration, not Litestar, as Litestar can't really do anything about how sentry behaves here. You should probably report this over at https://github.com/getsentry/sentry.
