### ISSUE TITLE
Enhancement: avoid circular dependencies on litestar-htmx

### ISSUE THREAD

**Issue by bollwyvl** [litestar-org/litestar#3868]
### Summary

Treat `htmx` as any other optional dependency.

### Basic Example

2.13.0 change of introducing a hard dependency on `litestar-htmx` (which has a hard, but unpinned dependency on `litestar`).

While `pip` can handle this, is troublesome for downstreams (such as https://github.com/conda-forge/litestar-feedstock/pull/11) to bootstrap.

### Drawbacks and Impact

Users will need to use the existing `litestar[htmx]` rather than get `litestar-htmx` "for free". 

### Unresolved questions

`litestar-htmx` has further packaging issues: https://github.com/litestar-org/litestar-htmx/issues/7

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3868">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3868/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3868/pledge.svg">
</picture>
</a>

**Comment by cofin** [comment]
Fixed by https://github.com/litestar-org/litestar-htmx/pull/8

**Comment by cofin** [comment]
We should open a PR and pin litestar to >= 0.4.0 of litestar-htmx.

We can't make it an optional dependency at this point though because this would be considered a breaking change.  It could be a 3.0 consideration though.

**Comment by bollwyvl** [comment]
> We should open a PR and pin litestar to >= 0.4.0 of litestar-htmx.

Doing that at this point would make the situation worse, as there would be no way to bootstrap.

**Comment by bollwyvl** [comment]
(making a `[litestar]` extra that contained the version pin _would_ provide useful metadata, however)

**Comment by bollwyvl** [comment]
> worse

To clarify: the situation would be worse if `litestar-htmx`'s `pyproject.toml` contained a pin with a version. Perhaps that's not what that _pin litestar to >= 0.4.0 of litestar-htmx_ intends

**Comment by cofin** [comment]
I'm fairly certain this doesn't break things, but please feel free to suggest changes on this PR here:
https://github.com/litestar-org/litestar/pull/3884
