### ISSUE TITLE
Bug: create_static_files_router with S3FS crashes due to unsupported fs info key (`mtime`)

### ISSUE THREAD

**Issue by thomastu** [litestar-org/litestar#3899]
### Description

When using S3FS in a static router, [ASGIFileResponse](https://github.com/litestar-org/litestar/blob/f31ef97d6cb725bf9898f55abbb5150b36823f27/litestar/response/file.py#L220) uses the `mtime` attribute on fs_info which is not consistently available across fssspec implementations (See: https://github.com/fsspec/filesystem_spec/issues/526).

### MCVE

```python
# Script Dependencies:
#     litestar
#     s3fs

from s3fs import S3FileSystem
from litestar import Litestar
from litestar.static_files import create_static_files_router

BUCKET_NAME = "some-s3-bucket"

app = Litestar(route_handlers=[
    create_static_files_router(
      path="/", 
      directories=[f"/{BUCKET_NAME}/"],
      html_mode=True,
      file_system=S3FileSystem()
    )
  ]
)
```

### Steps to reproduce

```bash
1. Seed an s3 bucket with an index.html file
2. Run `litestar run`
3. Go to `localhost:8000`
4. See error
```

### Logs

```bash
INFO:     127.0.0.1:50567 - "GET / HTTP/1.1" 500 Internal Server Error
ERROR - 2024-12-12 14:44:08,439 - litestar - config - Uncaught exception (connection_type=http, path=/):
Traceback (most recent call last):
  File ".venv/lib/python3.12/site-packages/litestar/middleware/_internal/exceptions/middleware.py", line 159, in __call__
    await self.app(scope, receive, capture_response_started)
  File ".venv/lib/python3.12/site-packages/litestar/_asgi/asgi_router.py", line 100, in __call__
    await asgi_app(scope, receive, send)
  File ".venv/lib/python3.12/site-packages/litestar/routes/http.py", line 84, in handle
    await response(scope, receive, send)
  File ".venv/lib/python3.12/site-packages/litestar/response/base.py", line 194, in __call__
    await self.start_response(send=send)
  File ".venv/lib/python3.12/site-packages/litestar/response/file.py", line 220, in start_response
    self.headers.setdefault("last-modified", formatdate(fs_info["mtime"], usegmt=True))
                                                        ~~~~~~~^^^^^^^^^
KeyError: 'mtime'
```

### Litestar Version

2.13.0

### Platform

- [ ] Linux
- [X] Mac
- [ ] Windows
- [ ] Other (Please specify in the description above)

---
> [!NOTE]  
> While we are open for sponsoring on [GitHub Sponsors](https://github.com/sponsors/litestar-org/) and 
> [OpenCollective](https://opencollective.com/litestar), we also utilize [Polar.sh](https://polar.sh/) to engage in pledge-based sponsorship.
>
> Check out all issues funded or available for funding [on our Polar.sh dashboard](https://polar.sh/litestar-org)
> * If you would like to see an issue prioritized, make a pledge towards it!
> * We receive the pledge once the issue is completed & verified
> * This, along with engagement in the community, helps us know which features are a priority to our users.

<a href="https://polar.sh/litestar-org/litestar/issues/3899">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/3899/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/3899/pledge.svg">
</picture>
</a>

**Comment by provinzkraut** [comment]
Hmm. Using [this comment](https://github.com/fsspec/filesystem_spec/issues/526#issuecomment-1936188996) as a reference, it seems that support for this varies wildly across different fsspec implementations, so does the key under which the value is provided. I'm not sure it's feasible to patch in special casing for every fsspec FS here. It would be much better if fsspec implemented a unified API to access this. 

We could at least not make it fail in the meantime though.
