### ISSUE TITLE
Bug (docs): Contribution guide not updated

### ISSUE THREAD

**Issue by nightblure** [litestar-org/litestar#3906]
### Description

Hi!

If you go to the documentation page of the [contributor's guide](https://docs.litestar.dev/2/contribution-guide.html), you can see that there is a clearly outdated version containing links to PDM ([move to uv](https://github.com/litestar-org/litestar/pull/3875) and all edits to this section were made 3 weeks ago)

### URL to code causing the issue

https://docs.litestar.dev/2/contribution-guide.html

### MCVE

```python
-
```

### Steps to reproduce

```bash
https://docs.litestar.dev/2/contribution-guide.html
```

### Litestar Version

latest

### Platform

- [X] Linux
- [X] Mac
- [X] Windows
- [ ] Other (Please specify in the description above)

**Comment by JacobCoffee** [comment]
I believe this is due to there not being a release since the `uv` migration. the `2` path for docs is only updated on release whereas `main` [reflects the current state of main](https://docs.litestar.dev/main/contribution-guide.html)
