### ISSUE TITLE
Enhancement: Support async rendering for Jinja2 templates

### ISSUE THREAD

**Issue by jtraub** [litestar-org/litestar#651]
**What's the feature you'd like to ask for.**
Jinja2 supports async rendering. See https://jinja.palletsprojects.com/en/3.0.x/api/#async-support for details.

It would be great if Starlite would add support of this feature allowing to easily port existing async templates and filters

<a href="https://polar.sh/litestar-org/litestar/issues/651">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/651/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/651/pledge.svg">
</picture>
</a>

**Comment by Goldziher** [comment]
@provinzkraut - is this something viable? If not, close this issue?

**Comment by provinzkraut** [comment]
Viable, yes. But it would require #881. I haven't looked deeper into this for quite some time, and it's a low priority feature I'd say. I added it to the [future release](https://github.com/starlite-api/starlite/milestone/3) milestone for now.

**Comment by euri10** [comment]
> **What's the feature you'd like to ask for.** Jinja2 supports async rendering. See [jinja.palletsprojects.com/en/3.0.x/api/#async-support](https://jinja.palletsprojects.com/en/3.0.x/api/#async-support) for details.
> 
> It would be great if Starlite would add support of this feature allowing to easily port existing async templates and filters
> 
> [ ![Fund with Polar](https://camo.githubusercontent.com/3dba0cbc39aa206e899daf2067307760c98ecad3ab30cc89fea77fd8f0971eff/68747470733a2f2f706f6c61722e73682f6170692f6769746875622f6c697465737461722d6f72672f6c697465737461722f6973737565732f3635312f706c656467652e737667) ](https://polar.sh/litestar-org/litestar/issues/651)

this now should be possible after https://github.com/litestar-org/litestar/pull/2195
something along those lines should do the job, not tested though :)
```
environment = Environment(
...
        autoescape=True,
		enable_async=True
    )
template_config = TemplateConfig(
        instance=JinjaTemplateEngine.from_environment(environment)
    )
app = Litestar(
     	...
		...
        template_config=template_config,
    )
```

**Comment by geeshta** [comment]
@euri10 This does only a part of the job 😅 Litestar still calls Template.render() while it should call Template.reder_async()

**Comment by euri10** [comment]
I must admit I have not tested it but from the jinja docs here https://jinja.palletsprojects.com/en/3.0.x/api/#async-support
it says : 

> Sync methods and filters become wrappers around their corresponding async implementations where needed. For example, render invokes async_render, and |map supports async iterables.

so I woould have expected working oob, what is the stacktrace you get ?

**Comment by geeshta** [comment]
```
▼ uvloop/loop.pyx in uvloop.loop.Loop._run at line 518
▼ uvloop/loop.pyx in uvloop.loop.Loop.run_forever at line 1377
▼ uvloop/loop.pyx in uvloop.loop.Loop.run_until_complete at line 1504
▼ uvloop/loop.pyx in uvloop.loop.Loop.run_until_complete at line 1511 
```
