### ISSUE TITLE
Documentation: Add a usage example for "submounting" applications via the `asgi` handler

### ISSUE THREAD

**Issue by provinzkraut** [litestar-org/litestar#675]
A new user asked on our if starlite would support "submounting applications" [like FastAPI does](https://fastapi.tiangolo.com/advanced/sub-applications/). While it is supported via the `asgi` handler, this usage is not apparent to new users / users who aren't too familiar with ASGI conceptually. 

We should add a usage example that demonstrates how to do this.

<a href="https://polar.sh/litestar-org/litestar/issues/675">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/675/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/675/pledge.svg">
</picture>
</a>

**Comment by peterschutt** [comment]
Have a look at https://github.com/piccolo-orm/piccolo_admin/issues/211

**Comment by provinzkraut** [comment]
Oh, I actually never encountered that. Let's defer this then until #681 is resolved.

**Comment by sinisaos** [comment]
@provinzkraut You can use the example from Starlite Piccolo [asgi template](https://github.com/piccolo-orm/piccolo/blob/a61d915f42880dcc0a1245146d7cac2101200af0/piccolo/apps/asgi/commands/templates/app/_starlite_app.py.jinja#L25-L28) which I think is a good example of how to mount a separate asgi application.

**Comment by JacobCoffee** [comment]
This is doable yourself with FastAPI exports this functionality from Starlette, which itself uses https://github.com/abersheeran/a2wsgi.

> @provinzkraut:
 FastAPI exports this functionality from Starlette, which itself uses https://github.com/abersheeran/a2wsgi
You can simply use a2wsgi directly with Litestar (=
The wrapped app can the simply be "mounted" using the asgi route handler:
https://docs.litestar.dev/2/usage/route-handlers.html#asgi-route-handlers

ref: https://discord.com/channels/919193495116337154/1129080604328210473/1129081298238050346

Example:

```py
from litestar import Litestar, asgi
from a2wsgi import WSGIMiddleware
from flask import Flask


flask_app = Flask(__name__)

asgi_flask_app = asgi(path="/", is_mount=True)(
    WSGIMiddleware(flask_app)
)

app = Litestar(route_handler=[asgi_flask_app])
```

**Comment by JacobCoffee** [comment]
Maybe I misunderstood the intent here - We can re-open if we want to add documentation about using a2wsgi into our docs?

**Comment by provinzkraut** [comment]
It was more about showing how to mount existing ASGI apps. Just an example with an explanation really.

**Comment by JacobCoffee** [comment]
Gotcha. my bad 😬
