### ISSUE TITLE
Documentation: Explain DTO basics and relationship between pydantic / DTO / ORM-plugins

### ISSUE THREAD

**Issue by provinzkraut** [litestar-org/litestar#683]
Right now the [documentation on DTOs](https://starlite-api.github.io/starlite/usage/11-data-transfer-objects/) is quite rudimentary, and can be confusing if the reader doesn't already know what a DTO is. Right now, new users unfamiliar with starlite are presented with a few too many options, without a clear explanation when to choose which.

The DTO section should probably lead with a primer answering 

1. What is a DTO?
2.  Why do I need a DTO?

The section goes later on to say

> You can now use it in route handler functions as you would any other pydantic model

but we don't really have a dedicated article about this either. 

Another potentially confusing part I think could be that the SQLAlchemy DTO example functionally does the same as the SQLAlchemyPlugin example. A section about when you'd actually want to return a pydantic model, return a DTO or return a SQLAlchemy-model instance (applies for other supported orms as well) would be great, including examples.

I think the best way to be would to add a new one-stop-shop article on how to return and serialise data, that covers when which method is appropriate, complete with "run as-is" examples.

A third option would be to follow the model of the [SQLAlchemy docs](https://docs.sqlalchemy.org) and have three disctinct categories:

- Tutorials (covering basic usage of all important concepts including examples)
- Reference (covering the usage of all public APIs, including basic examples and technical background)
- API reference

The advantage would be that readers could pick one depending on what they want, so we don't have to "dilute" our documentation which too many tutorial style sections. We could keep the `Usage` and `API Reference`, add a `Tutorials` section and make the  `Usage` section a bit less tutorially in some areas.

Seeing as this attempt to explain the probable sources of confusion for new users is in itself not very clear, I think we can agree that this needs improvement :wink:

**Comment by Alex-CodeLab** [comment]
I think it needs a few more questions answered:
- How is a DTO different from existing data objects (pydantic model, dataclass, etc) 
- When is a DTO not needed
 
(I can't answer these, btw. Personally I think DTOs are an anti-pattern that does not make much sense in Python, but I am curious to see what ppl come up with.)

**Comment by Jarmos-san** [comment]
I've proposed this earlier as well on Discord & I'm commenting this here now for public disclosure.

There's this informative video on YouTube - [What You Need to Know About Your Documentation - Daniele Procida](https://youtu.be/qC1OYK5oqDo) which shares a detailed guideline into writing properly structured technical documentations. The video proposes dividing the entirety of the documentations into four categories:

1. Tutorials, for content to build a small project using Starlite.
2. How-To or Usage Guides to share how the intricate functionalities of Starlite can be used to achieve a particular functionality.
3. Explanation-based articles for thorough & comprehensive explanation on certain topics related to Starlite. These content may or mayn't be best suited for the rest of the sections of the documentations.
4. API Reference for documenting the public Starlite API.

The #1153 PR is based on these concepts to _rewrite_/_restructure_ the "Usage Guidelines" section of the documentations. And I suggest moving all technical (like the content related to DTOs) & other in-depth article-type documentations to a "explanation" category of the documents.

**Comment by peterschutt** [comment]
I think this can be closed @provinzkraut - feel free to re-open though.

**Comment by provinzkraut** [comment]
All good from my end @peterschutt!
