### ISSUE TITLE
Enhancement: Proper support for relationships in SQLAlchemyPlugin

### ISSUE THREAD

**Issue by provinzkraut** [litestar-org/litestar#723]
**What's the feature you'd like to ask for.**
The SQLAlchemyPlugin currently only supports the simplest of relationships, that is: Non-self-referential to-one relationships.
Support for to-many relationships at least would be crucial for this plugin.

**Proposal**

Given these models:
```python
class Pet(Base):
    __tablename__ = "pet"
    id = Column(Integer, primary_key=True)
    name = Column(String)
    owner = relationship("User")
    owner_id = Column(ForeignKey("user.id"))


class User(Base):
    __tablename__ = "user"
    id = Column(Integer, primary_key=True)
    name = Column(String, default="moishe")
    pets = relationship("Pet", uselist=True)
```

The plugin currently generates:

```python
class PetModel(BaseModel):
    id: int
    name: str
    owner: Optional[Owner]

class UserModel(BaseModel):
    id: int
    name: str
    pets: Optional[Any]
```

What we should probably be generating is:

```python
class PetModel(BaseModel):
    id: int
    name: str
    owner_id: int

class UserModel(BaseModel):
    id: int
    name: str
    pets: List[PetModel]
```

**Comment by provinzkraut** [comment]
@peterschutt What are your thoughts on this?

**Comment by peterschutt** [comment]
> @peterschutt What are your thoughts on this?

I agree with everything said here so far. I will get the sqla 2.0 compat PR sorted first, and then look at this if no one else wants to work on it before then.

**Comment by peterschutt** [comment]
Relationships are supported now.
