### ISSUE TITLE
Enhancement: Support customization of  `JinjaTemplateEngine`

### ISSUE THREAD

**Issue by provinzkraut** [litestar-org/litestar#965]
**What's the feature you'd like to ask for.**
The ability to pass a custom `Environment` to `JinjaTemplateEngine`, so it can be configured as needed, e.g. with a different loader than `FileSystemLoader`. As of now this particular example would be difficult to implement since `TemplateEngineProtocol` assumes templates will always be served from a directory.

**Additional context**
Ideally one would be able to call ` JinjaTemplateEngine.from_environment(Environment(...))` to allow for full customization.

<a href="https://polar.sh/litestar-org/litestar/issues/965">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/litestar-org/litestar/issues/965/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/litestar-org/litestar/issues/965/pledge.svg">
</picture>
</a>

**Comment by Goldziher** [comment]
We now allow passing an engine instance to the config, does that not satisfy this?

**Comment by provinzkraut** [comment]
Not really. The example of using a different loader for example still isn't possible since the engine only accepts a directory and no further configuration. 

```python
my_env = Environment(loader=DictLoader(...), keep_trailing_newline=False)
```
You cannot get this into the engine instance.

**Comment by 01EK98** [comment]
I'm gonna hop on and implement this :>
Although I'm embarrassed to say I don't know how to assign the issue to myself 😅

**Comment by provinzkraut** [comment]
> Although I'm embarrassed to say I don't know how to assign the issue to myself sweat_smile

I don't think you can, so did it for you :slightly_smiling_face:

**Comment by provinzkraut** [comment]
This looks like a reasonable approach to me. Do you want to go ahead with the implementation?

**Comment by euri10** [comment]
> This looks like a reasonable approach to me. Do you want to go ahead with the implementation?

sure thing, I'll work on this asap
